// Copyright (c) Tanner Gooding and Contributors. Licensed under the MIT License (MIT). See License.md in the repository root for more information.
//
// Based on the RyuJIT compiler from dotnet/runtime.
// Original source is Copyright (c) .NET Foundation and Contributors. Licensed under the MIT License (MIT).

using System;
using static RyuJitSharp.Emitter.insFormat;

namespace RyuJitSharp;

public partial class Emitter
{
#if TARGET_ARM64
    private static ReadOnlySpan<insFormat> s_instructionFormats => [
#if TARGET_XARCH
#if !TARGET_XARCH
#error Unexpected target type
#endif
#if TARGET_AMD64
#endif
#if TARGET_AMD64
#endif
#if TARGET_AMD64
#endif
#if TARGET_AMD64
#endif
#if TARGET_AMD64
#endif
#if TARGET_AMD64
#endif
#if TARGET_AMD64
#endif
#if TARGET_AMD64
#endif
#if TARGET_AMD64
#endif
#if TARGET_AMD64
#endif
#if TARGET_X86
#endif
#elif TARGET_ARM
#if !TARGET_ARM
#error Unexpected target type
#endif
#if FEATURE_PLI_INSTRUCTION
#endif
#if FEATURE_ITINSTRUCTION
#endif
#elif TARGET_ARM64
#if !TARGET_ARM64
#error Unexpected target type
#endif
        IF_NONE, // invalid
        IF_EN9, // mov
        IF_EN6A, // add
        IF_EN6A, // sub
        IF_EN6B, // ld1
        IF_EN6B, // ld2
        IF_EN6B, // ld3
        IF_EN6B, // ld4
        IF_EN6B, // st1
        IF_EN6B, // st2
        IF_EN6B, // st3
        IF_EN6B, // st4
        IF_EN5A, // ldr
        IF_EN5A, // ldrsw
        IF_EN5B, // fmov
        IF_EN5C, // orr
        IF_EN4A, // ldrb
        IF_EN4A, // ldrh
        IF_EN4A, // ldrsb
        IF_EN4A, // ldrsh
        IF_EN4A, // str
        IF_EN4A, // strb
        IF_EN4A, // strh
        IF_EN4B, // adds
        IF_EN4B, // subs
        IF_EN4C, // cmp
        IF_EN4C, // cmn
        IF_EN4D, // fmul
        IF_EN4D, // fmulx
        IF_EN4E, // and
        IF_EN4E, // eor
        IF_EN4F, // bic
        IF_EN4G, // neg
        IF_EN4H, // cmeq
        IF_EN4H, // cmge
        IF_EN4H, // cmgt
        IF_EN4I, // fcmeq
        IF_EN4I, // fcmge
        IF_EN4I, // fcmgt
        IF_EN4J, // sqshl
        IF_EN4J, // uqshl
        IF_EN4K, // sqdmlal
        IF_EN4K, // sqdmlsl
        IF_EN4K, // sqdmulh
        IF_EN4K, // sqdmull
        IF_EN4K, // sqrdmlah
        IF_EN4K, // sqrdmlsh
        IF_EN4K, // sqrdmulh
        IF_EN3A, // ands
        IF_EN3B, // tst
        IF_EN3C, // orn
        IF_EN3D, // dup
        IF_EN3E, // fmla
        IF_EN3E, // fmls
        IF_EN3F, // fcvtas
        IF_EN3F, // fcvtau
        IF_EN3F, // fcvtms
        IF_EN3F, // fcvtmu
        IF_EN3F, // fcvtns
        IF_EN3F, // fcvtnu
        IF_EN3F, // fcvtps
        IF_EN3F, // fcvtpu
        IF_EN3F, // fcvtzs
        IF_EN3F, // fcvtzu
        IF_EN3G, // scvtf
        IF_EN3G, // ucvtf
        IF_EN3H, // mul
        IF_EN3H, // smull
        IF_EN3H, // umull
        IF_EN3I, // mvn
        IF_EN3J, // ld1_2regs
        IF_EN3J, // ld1_3regs
        IF_EN3J, // ld1_4regs
        IF_EN3J, // st1_2regs
        IF_EN3J, // st1_3regs
        IF_EN3J, // st1_4regs
        IF_EN3J, // ld1r
        IF_EN3J, // ld2r
        IF_EN3J, // ld3r
        IF_EN3J, // ld4r
        IF_EN2A, // negs
        IF_EN2B, // bics
        IF_EN2B, // eon
        IF_EN2C, // lsl
        IF_EN2C, // lsr
        IF_EN2C, // asr
        IF_EN2D, // ror
        IF_EN2E, // ldp
        IF_EN2E, // ldpsw
        IF_EN2E, // stp
        IF_EN2E, // ldnp
        IF_EN2E, // stnp
        IF_EN2F, // ccmp
        IF_EN2F, // ccmn
        IF_EN2H, // ins
        IF_EN2G, // fadd
        IF_EN2G, // fsub
        IF_EN2G, // fdiv
        IF_EN2G, // fmax
        IF_EN2G, // fmaxnm
        IF_EN2G, // fmin
        IF_EN2G, // fminnm
        IF_EN2G, // fabd
        IF_EN2G, // facge
        IF_EN2G, // facgt
        IF_EN2G, // frecps
        IF_EN2G, // frsqrts
        IF_EN2I, // fcmp
        IF_EN2I, // fcmpe
        IF_EN2J, // fabs
        IF_EN2J, // fcmle
        IF_EN2J, // fcmlt
        IF_EN2J, // fcvtxn
        IF_EN2J, // fneg
        IF_EN2J, // frecpe
        IF_EN2J, // frintn
        IF_EN2J, // frintp
        IF_EN2J, // frintm
        IF_EN2J, // frintz
        IF_EN2J, // frinta
        IF_EN2J, // frintx
        IF_EN2J, // frinti
        IF_EN2J, // frsqrte
        IF_EN2J, // fsqrt
        IF_EN2K, // abs
        IF_EN2K, // cmle
        IF_EN2K, // cmlt
        IF_EN2K, // sqabs
        IF_EN2K, // sqneg
        IF_EN2K, // sqxtn
        IF_EN2K, // sqxtun
        IF_EN2K, // suqadd
        IF_EN2K, // usqadd
        IF_EN2K, // uqxtn
        IF_EN2L, // cls
        IF_EN2L, // clz
        IF_EN2L, // rbit
        IF_EN2L, // cnt
        IF_EN2L, // rev16
        IF_EN2L, // rev32
        IF_EN2M, // mla
        IF_EN2M, // mls
        IF_EN2M, // smlal
        IF_EN2M, // smlal2
        IF_EN2M, // smlsl
        IF_EN2M, // smlsl2
        IF_EN2M, // smull2
        IF_EN2M, // sqdmlal2
        IF_EN2M, // sqdmlsl2
        IF_EN2M, // sqdmull2
        IF_EN2M, // sdot
        IF_EN2M, // udot
        IF_EN2M, // umlal
        IF_EN2M, // umlal2
        IF_EN2M, // umlsl
        IF_EN2M, // umlsl2
        IF_EN2M, // umull2
        IF_EN2N, // sshr
        IF_EN2N, // ssra
        IF_EN2N, // srshr
        IF_EN2N, // srsra
        IF_EN2N, // shl
        IF_EN2N, // ushr
        IF_EN2N, // usra
        IF_EN2N, // urshr
        IF_EN2N, // ursra
        IF_EN2N, // sri
        IF_EN2N, // sli
        IF_EN2N, // sqshlu
        IF_EN2N, // sqrshrn
        IF_EN2N, // sqrshrun
        IF_EN2N, // sqshrn
        IF_EN2N, // sqshrun
        IF_EN2N, // uqrshrn
        IF_EN2N, // uqshrn
        IF_EN2O, // cmhi
        IF_EN2O, // cmhs
        IF_EN2O, // cmtst
        IF_EN2O, // sqadd
        IF_EN2O, // sqrshl
        IF_EN2O, // sqsub
        IF_EN2O, // srshl
        IF_EN2O, // sshl
        IF_EN2O, // uqadd
        IF_EN2O, // uqrshl
        IF_EN2O, // uqsub
        IF_EN2O, // urshl
        IF_EN2O, // ushl
        IF_EN2P, // faddp
        IF_EN2P, // fmaxnmp
        IF_EN2P, // fmaxp
        IF_EN2P, // fminnmp
        IF_EN2P, // fminp
        IF_EN2Q, // addp
        IF_LS_2A, // ldar
        IF_LS_2A, // ldarb
        IF_LS_2A, // ldarh
        IF_LS_2A, // ldapr
        IF_LS_2A, // ldaprb
        IF_LS_2A, // ldaprh
        IF_LS_2A, // ldxr
        IF_LS_2A, // ldxrb
        IF_LS_2A, // ldxrh
        IF_LS_2A, // ldaxr
        IF_LS_2A, // ldaxrb
        IF_LS_2A, // ldaxrh
        IF_LS_2C, // ldur
        IF_LS_2C, // ldurb
        IF_LS_2C, // ldurh
        IF_LS_2C, // ldursb
        IF_LS_2C, // ldursh
        IF_LS_2C, // ldursw
        IF_LS_2C, // ldapur
        IF_LS_2C, // ldapurb
        IF_LS_2C, // ldapurh
        IF_LS_2A, // stlr
        IF_LS_2A, // stlrb
        IF_LS_2A, // stlrh
        IF_LS_3D, // stxr
        IF_LS_3D, // stxrb
        IF_LS_3D, // stxrh
        IF_LS_3D, // stlxr
        IF_LS_3D, // stlxrb
        IF_LS_3D, // stlxrh
        IF_LS_2C, // stur
        IF_LS_2C, // sturb
        IF_LS_2C, // sturh
        IF_LS_2C, // stlur
        IF_LS_2C, // stlurb
        IF_LS_2C, // stlurh
        IF_LS_3E, // casb
        IF_LS_3E, // casab
        IF_LS_3E, // casalb
        IF_LS_3E, // caslb
        IF_LS_3E, // cash
        IF_LS_3E, // casah
        IF_LS_3E, // casalh
        IF_LS_3E, // caslh
        IF_LS_3E, // cas
        IF_LS_3E, // casa
        IF_LS_3E, // casal
        IF_LS_3E, // casl
        IF_LS_3E, // ldaddb
        IF_LS_3E, // ldaddab
        IF_LS_3E, // ldaddalb
        IF_LS_3E, // ldaddlb
        IF_LS_3E, // ldaddh
        IF_LS_3E, // ldaddah
        IF_LS_3E, // ldaddalh
        IF_LS_3E, // ldaddlh
        IF_LS_3E, // ldadd
        IF_LS_3E, // ldadda
        IF_LS_3E, // ldaddal
        IF_LS_3E, // ldclral
        IF_LS_3E, // ldsetal
        IF_LS_3E, // ldaddl
        IF_LS_3E, // staddb
        IF_LS_3E, // staddlb
        IF_LS_3E, // staddh
        IF_LS_3E, // staddlh
        IF_LS_3E, // stadd
        IF_LS_3E, // staddl
        IF_LS_3E, // swpb
        IF_LS_3E, // swpab
        IF_LS_3E, // swpalb
        IF_LS_3E, // swplb
        IF_LS_3E, // swph
        IF_LS_3E, // swpah
        IF_LS_3E, // swpalh
        IF_LS_3E, // swplh
        IF_LS_3E, // swp
        IF_LS_3E, // swpa
        IF_LS_3E, // swpal
        IF_LS_3E, // swpl
        IF_DI_1E, // adr
        IF_DI_1E, // adrp
        IF_BI_0A, // b
        IF_BI_0C, // b_tail
        IF_BI_0A, // bl_local
        IF_BI_0C, // bl
        IF_BR_1A, // br
        IF_BR_1B, // br_tail
        IF_BR_1B, // blr
        IF_BR_1A, // ret
        IF_BR_0A, // retaa
        IF_BR_0A, // retab
        IF_BI_0B, // beq
        IF_BI_0B, // bne
        IF_BI_0B, // bhs
        IF_BI_0B, // blo
        IF_BI_0B, // bmi
        IF_BI_0B, // bpl
        IF_BI_0B, // bvs
        IF_BI_0B, // bvc
        IF_BI_0B, // bhi
        IF_BI_0B, // bls
        IF_BI_0B, // bge
        IF_BI_0B, // blt
        IF_BI_0B, // bgt
        IF_BI_0B, // ble
        IF_BI_1A, // cbz
        IF_BI_1A, // cbnz
        IF_BI_1B, // tbz
        IF_BI_1B, // tbnz
        IF_DI_1B, // movk
        IF_DI_1B, // movn
        IF_DI_1B, // movz
        IF_DR_3D, // csel
        IF_DR_3D, // csinc
        IF_DR_3D, // csinv
        IF_DR_3D, // csneg
        IF_DR_2D, // cinc
        IF_DR_2D, // cinv
        IF_DR_2D, // cneg
        IF_DR_1D, // cset
        IF_DR_1D, // csetm
        IF_DV_2P, // aese
        IF_DV_2P, // aesd
        IF_DV_2P, // aesmc
        IF_DV_2P, // aesimc
        IF_DR_2G, // rev
        IF_DV_2M, // rev64
        IF_DR_3A, // adc
        IF_DR_3A, // adcs
        IF_DR_3A, // sbc
        IF_DR_3A, // sbcs
        IF_DR_3A, // udiv
        IF_DR_3A, // sdiv
        IF_DR_3A, // mneg
        IF_DR_4A, // madd
        IF_DR_4A, // msub
        IF_DR_4A, // smaddl
        IF_DR_3A, // smnegl
        IF_DR_4A, // smsubl
        IF_DR_3A, // smulh
        IF_DR_4A, // umaddl
        IF_DR_3A, // umnegl
        IF_DR_4A, // umsubl
        IF_DR_3A, // umulh
        IF_DR_3E, // extr
        IF_DR_3A, // lslv
        IF_DR_3A, // lsrv
        IF_DR_3A, // asrv
        IF_DR_3A, // rorv
        IF_DR_3A, // crc32b
        IF_DR_3A, // crc32h
        IF_DR_3A, // crc32w
        IF_DR_3A, // crc32x
        IF_DR_3A, // crc32cb
        IF_DR_3A, // crc32ch
        IF_DR_3A, // crc32cw
        IF_DR_3A, // crc32cx
        IF_DV_3F, // sha1c
        IF_DV_3F, // sha1m
        IF_DV_3F, // sha1p
        IF_DV_2U, // sha1h
        IF_DV_3F, // sha1su0
        IF_DV_2U, // sha1su1
        IF_DV_3F, // sha256h
        IF_DV_3F, // sha256h2
        IF_DV_2U, // sha256su0
        IF_DV_3F, // sha256su1
        IF_DV_3G, // ext
        IF_DI_2D, // sbfm
        IF_DI_2D, // bfm
        IF_DI_2D, // ubfm
        IF_DI_2D, // sbfiz
        IF_DI_2D, // bfi
        IF_DI_2D, // ubfiz
        IF_DI_2D, // sbfx
        IF_DI_2D, // bfxil
        IF_DI_2D, // ubfx
        IF_DR_2H, // sxtb
        IF_DR_2H, // sxth
        IF_DR_2H, // sxtw
        IF_DR_2H, // uxtb
        IF_DR_2H, // uxth
        IF_PC_0A, // autia1716
        IF_PC_0A, // autiasp
        IF_PC_0A, // autib1716
        IF_PC_0A, // autibsp
        IF_PC_0A, // autibz
        IF_PC_0A, // autiaz
        IF_PC_0A, // pacia1716
        IF_PC_0A, // paciasp
        IF_PC_0A, // pacib1716
        IF_PC_0A, // pacibsp
        IF_PC_0A, // pacibz
        IF_PC_0A, // paciaz
        IF_PC_0A, // xpaclri
        IF_PC_1A, // autiza
        IF_PC_1A, // autizb
        IF_PC_1A, // paciza
        IF_PC_1A, // pacizb
        IF_PC_1A, // xpacd
        IF_PC_1A, // xpaci
        IF_PC_2A, // autia
        IF_PC_2A, // autib
        IF_PC_2A, // pacia
        IF_PC_2A, // pacib
        IF_SN_0A, // nop
        IF_SN_0A, // yield
        IF_SI_0A, // brk
        IF_SI_0B, // dsb
        IF_SI_0B, // dmb
        IF_SI_0B, // isb
        IF_SR_1A, // dczva
        IF_SR_1A, // mrs_tpid0
        IF_DV_2B, // umov
        IF_DV_2B, // smov
        IF_DV_1B, // movi
        IF_DV_1B, // mvni
        IF_DV_2A, // urecpe
        IF_DV_2A, // ursqrte
        IF_DV_3C, // bsl
        IF_DV_3C, // bit
        IF_DV_3C, // bif
        IF_DV_2T, // addv
        IF_DR_2G, // ctz
        IF_DV_2M, // not
        IF_DV_2T, // saddlv
        IF_DV_2T, // smaxv
        IF_DV_2T, // sminv
        IF_DV_2T, // uaddlv
        IF_DV_2T, // umaxv
        IF_DV_2T, // uminv
        IF_DV_2R, // fmaxnmv
        IF_DV_2R, // fmaxv
        IF_DV_2R, // fminnmv
        IF_DV_2R, // fminv
        IF_DV_3A, // uzp1
        IF_DV_3A, // uzp2
        IF_DV_3A, // zip1
        IF_DV_3A, // zip2
        IF_DV_3A, // trn1
        IF_DV_3A, // trn2
        IF_DV_2M, // sqxtn2
        IF_DV_2M, // sqxtun2
        IF_DV_2M, // uqxtn2
        IF_DV_2M, // xtn
        IF_DV_2M, // xtn2
        IF_DV_3D, // fnmul
        IF_DV_4A, // fmadd
        IF_DV_4A, // fmsub
        IF_DV_4A, // fnmadd
        IF_DV_4A, // fnmsub
        IF_DV_2J, // fcvt
        IF_DV_3A, // pmul
        IF_DV_3A, // saba
        IF_DV_3A, // sabd
        IF_DV_3A, // smax
        IF_DV_3A, // smaxp
        IF_DV_3A, // smin
        IF_DV_3A, // sminp
        IF_DV_3A, // uaba
        IF_DV_3A, // uabd
        IF_DV_3A, // umax
        IF_DV_3A, // umaxp
        IF_DV_3A, // umin
        IF_DV_3A, // uminp
        IF_DV_2A, // fcvtl
        IF_DV_2A, // fcvtl2
        IF_DV_2A, // fcvtn
        IF_DV_2A, // fcvtn2
        IF_DV_2A, // fcvtxn2
        IF_DV_2G, // frecpx
        IF_DV_3A, // addhn
        IF_DV_3A, // addhn2
        IF_DV_3A, // pmull
        IF_DV_3A, // pmull2
        IF_DV_3A, // raddhn
        IF_DV_3A, // raddhn2
        IF_DV_3A, // rsubhn
        IF_DV_3A, // rsubhn2
        IF_DV_3A, // sabal
        IF_DV_3A, // sabal2
        IF_DV_3A, // sabdl
        IF_DV_3A, // sabdl2
        IF_DV_2T, // sadalp
        IF_DV_3A, // saddl
        IF_DV_3A, // saddl2
        IF_DV_2T, // saddlp
        IF_DV_3A, // saddw
        IF_DV_3A, // saddw2
        IF_DV_3A, // shadd
        IF_DV_3A, // shsub
        IF_DV_3A, // srhadd
        IF_DV_3A, // ssubl
        IF_DV_3A, // ssubl2
        IF_DV_3A, // ssubw
        IF_DV_3A, // ssubw2
        IF_DV_3A, // subhn
        IF_DV_3A, // subhn2
        IF_DV_3A, // uabal
        IF_DV_3A, // uabal2
        IF_DV_3A, // uabdl
        IF_DV_3A, // uabdl2
        IF_DV_2T, // uadalp
        IF_DV_3A, // uaddl
        IF_DV_3A, // uaddl2
        IF_DV_2T, // uaddlp
        IF_DV_3A, // uaddw
        IF_DV_3A, // uaddw2
        IF_DV_3A, // uhadd
        IF_DV_3A, // uhsub
        IF_DV_3A, // urhadd
        IF_DV_3A, // usubl
        IF_DV_3A, // usubl2
        IF_DV_3A, // usubw
        IF_DV_3A, // usubw2
        IF_DV_2M, // shll
        IF_DV_2M, // shll2
        IF_DV_2O, // sshll
        IF_DV_2O, // sshll2
        IF_DV_2O, // ushll
        IF_DV_2O, // ushll2
        IF_DV_2O, // shrn
        IF_DV_2O, // shrn2
        IF_DV_2O, // rshrn
        IF_DV_2O, // rshrn2
        IF_DV_2O, // sqrshrn2
        IF_DV_2O, // sqrshrun2
        IF_DV_2O, // sqshrn2
        IF_DV_2O, // sqshrun2
        IF_DV_2O, // uqrshrn2
        IF_DV_2O, // uqshrn2
        IF_DV_2O, // sxtl
        IF_DV_2O, // sxtl2
        IF_DV_2O, // uxtl
        IF_DV_2O, // uxtl2
        IF_DV_3C, // tbl
        IF_DV_3C, // tbl_2regs
        IF_DV_3C, // tbl_3regs
        IF_DV_3C, // tbl_4regs
        IF_DV_3C, // tbx
        IF_DV_3C, // tbx_2regs
        IF_DV_3C, // tbx_3regs
        IF_DV_3C, // tbx_4regs
#if FEATURE_LOOP_ALIGN
        IF_SN_0A, // align
#endif
        IF_DV_4B, // eor3
        IF_DV_4B, // bcax
        IF_DV_4B, // sm3ss1
        IF_DV_3H, // sha512h
        IF_DV_3H, // sha512h2
        IF_DV_3H, // sha512su1
        IF_DV_3H, // rax1
        IF_DV_3H, // sm3partw1
        IF_DV_3H, // sm3partw2
        IF_DV_3H, // sm4ekey
        IF_DV_3I, // xar
        IF_DV_2V, // sha512su0
        IF_DV_2V, // sm4e
#if !TARGET_ARM64
#error Unexpected target type
#endif
        IF_NONE, // invalid
        IF_SVE_13A, // mov
        IF_SVE_11A, // st1w
        IF_SVE_9A, // ld1sh
        IF_SVE_9B, // ld1h
        IF_SVE_9C, // ld1w
        IF_SVE_9D, // ld1d
        IF_SVE_9E, // st1h
        IF_SVE_9F, // st1d
        IF_SVE_8A, // pmov
        IF_SVE_8B, // ldff1sh
        IF_SVE_8B, // ldff1w
        IF_SVE_8C, // ldff1h
        IF_SVE_7A, // ld1sw
        IF_SVE_6A, // mul
        IF_SVE_6B, // fdot
        IF_SVE_6C, // ld1sb
        IF_SVE_6D, // ld1b
        IF_SVE_6E, // prfb
        IF_SVE_6E, // prfd
        IF_SVE_6E, // prfh
        IF_SVE_6E, // prfw
        IF_SVE_6F, // ldff1d
        IF_SVE_6F, // ldff1sw
        IF_SVE_6G, // st1b
        IF_SVE_5A, // asr
        IF_SVE_5A, // lsl
        IF_SVE_5A, // lsr
        IF_SVE_5B, // fmul
        IF_SVE_5C, // sdot
        IF_SVE_5C, // udot
        IF_SVE_5D, // ldff1sb
        IF_SVE_5E, // ldff1b
        IF_SVE_4A, // and
        IF_SVE_4A, // bic
        IF_SVE_4A, // eor
        IF_SVE_4A, // orr
        IF_SVE_4B, // fmov
        IF_SVE_4E, // sqdmulh
        IF_SVE_4E, // sqrdmulh
        IF_SVE_4F, // sqrdmlah
        IF_SVE_4F, // sqrdmlsh
        IF_SVE_4G, // mla
        IF_SVE_4G, // mls
        IF_SVE_4H, // fmlalb
        IF_SVE_4H, // fmlalt
        IF_SVE_4I, // index
        IF_SVE_4J, // cpy
        IF_SVE_4K, // ldnt1b
        IF_SVE_4K, // ldnt1h
        IF_SVE_4K, // ldnt1w
        IF_SVE_4L, // stnt1b
        IF_SVE_4L, // stnt1h
        IF_SVE_4L, // stnt1w
        IF_SVE_3A, // add
        IF_SVE_3A, // sub
        IF_SVE_3B, // adr
        IF_SVE_3C, // dup
        IF_SVE_3D, // trn1
        IF_SVE_3D, // trn2
        IF_SVE_3D, // uzp1
        IF_SVE_3D, // uzp2
        IF_SVE_3D, // zip1
        IF_SVE_3D, // zip2
        IF_SVE_3E, // sqadd
        IF_SVE_3E, // sqsub
        IF_SVE_3E, // uqadd
        IF_SVE_3E, // uqsub
        IF_SVE_3F, // fmla
        IF_SVE_3F, // fmls
        IF_SVE_3G, // luti4
        IF_SVE_3H, // fadd
        IF_SVE_3H, // fsub
        IF_SVE_3I, // clasta
        IF_SVE_3I, // clastb
        IF_SVE_3J, // cmpeq
        IF_SVE_3J, // cmpge
        IF_SVE_3J, // cmpgt
        IF_SVE_3J, // cmple
        IF_SVE_3J, // cmplt
        IF_SVE_3J, // cmpne
        IF_SVE_3K, // cmphi
        IF_SVE_3K, // cmphs
        IF_SVE_3K, // cmplo
        IF_SVE_3K, // cmpls
        IF_SVE_3L, // whilege
        IF_SVE_3L, // whilegt
        IF_SVE_3L, // whilehi
        IF_SVE_3L, // whilehs
        IF_SVE_3L, // whilele
        IF_SVE_3L, // whilelo
        IF_SVE_3L, // whilels
        IF_SVE_3L, // whilelt
        IF_SVE_3M, // cdot
        IF_SVE_3N, // cmla
        IF_SVE_3O, // sqrdcmlah
        IF_SVE_3P, // smlalb
        IF_SVE_3P, // smlalt
        IF_SVE_3P, // smlslb
        IF_SVE_3P, // smlslt
        IF_SVE_3P, // umlalb
        IF_SVE_3P, // umlalt
        IF_SVE_3P, // umlslb
        IF_SVE_3P, // umlslt
        IF_SVE_3Q, // sqdmlalb
        IF_SVE_3Q, // sqdmlalt
        IF_SVE_3Q, // sqdmlslb
        IF_SVE_3Q, // sqdmlslt
        IF_SVE_3R, // smullb
        IF_SVE_3R, // smullt
        IF_SVE_3R, // umullb
        IF_SVE_3R, // umullt
        IF_SVE_3S, // sqdmullb
        IF_SVE_3S, // sqdmullt
        IF_SVE_3T, // bfmul
        IF_SVE_3U, // ldnt1d
        IF_SVE_3V, // stnt1d
        IF_SVE_2AA, // ldr
        IF_SVE_2AB, // str
        IF_SVE_2AC, // smax
        IF_SVE_2AC, // smin
        IF_SVE_2AC, // umax
        IF_SVE_2AC, // umin
        IF_SVE_2AD, // addpt
        IF_SVE_2AD, // subpt
        IF_SVE_2AE, // rev
        IF_SVE_2AF, // smulh
        IF_SVE_2AF, // umulh
        IF_SVE_2AG, // orn
        IF_SVE_2AH, // ext
        IF_SVE_2AI, // sqshl
        IF_SVE_2AI, // uqshl
        IF_SVE_2AJ, // fcmeq
        IF_SVE_2AJ, // fcmge
        IF_SVE_2AJ, // fcmgt
        IF_SVE_2AJ, // fcmle
        IF_SVE_2AJ, // fcmlt
        IF_SVE_2AJ, // fcmne
        IF_SVE_2AK, // tbl
        IF_SVE_2AL, // luti2
        IF_SVE_2AM, // fmax
        IF_SVE_2AM, // fmaxnm
        IF_SVE_2AM, // fmin
        IF_SVE_2AM, // fminnm
        IF_SVE_2AM, // fsubr
        IF_SVE_2AN, // usdot
        IF_SVE_2AO, // fcmla
        IF_SVE_2AP, // bfdot
        IF_SVE_2AQ, // fmlallbb
        IF_SVE_2AQ, // fmlallbt
        IF_SVE_2AQ, // fmlalltb
        IF_SVE_2AQ, // fmlalltt
        IF_SVE_2AR, // not
        IF_SVE_2AT, // subr
        IF_SVE_2AU, // movprfx
        IF_SVE_2AV, // decd
        IF_SVE_2AV, // dech
        IF_SVE_2AV, // decw
        IF_SVE_2AV, // incd
        IF_SVE_2AV, // inch
        IF_SVE_2AV, // incw
        IF_SVE_2AW, // sqdecd
        IF_SVE_2AW, // sqdech
        IF_SVE_2AW, // sqdecw
        IF_SVE_2AW, // sqincd
        IF_SVE_2AW, // sqinch
        IF_SVE_2AW, // sqincw
        IF_SVE_2AW, // uqdecd
        IF_SVE_2AW, // uqdech
        IF_SVE_2AW, // uqdecw
        IF_SVE_2AW, // uqincd
        IF_SVE_2AW, // uqinch
        IF_SVE_2AW, // uqincw
        IF_SVE_2AX, // insr
        IF_SVE_2AY, // lasta
        IF_SVE_2AY, // lastb
        IF_SVE_2AZ, // splice
        IF_SVE_2BA, // sel
        IF_SVE_2BB, // movs
        IF_SVE_2BC, // ptrue
        IF_SVE_2BD, // rdffr
        IF_SVE_2BE, // cntp
        IF_SVE_2BF, // decp
        IF_SVE_2BF, // incp
        IF_SVE_2BG, // sqdecp
        IF_SVE_2BG, // sqincp
        IF_SVE_2BG, // uqdecp
        IF_SVE_2BG, // uqincp
        IF_SVE_2BH, // pext
        IF_SVE_2BI, // pmullb
        IF_SVE_2BI, // pmullt
        IF_SVE_2BJ, // fcvtnt
        IF_SVE_2BK, // bfmla
        IF_SVE_2BK, // bfmls
        IF_SVE_2BL, // bfmlalb
        IF_SVE_2BL, // bfmlalt
        IF_SVE_2BL, // bfmlslb
        IF_SVE_2BL, // bfmlslt
        IF_SVE_2BL, // fmlslb
        IF_SVE_2BL, // fmlslt
        IF_SVE_2BM, // bfadd
        IF_SVE_2BM, // bfsub
        IF_SVE_2BN, // ldnt1sb
        IF_SVE_2BN, // ldnt1sh
        IF_SVE_2BO, // ld1rob
        IF_SVE_2BO, // ld1rod
        IF_SVE_2BO, // ld1roh
        IF_SVE_2BO, // ld1row
        IF_SVE_2BO, // ld1rqb
        IF_SVE_2BO, // ld1rqd
        IF_SVE_2BO, // ld1rqh
        IF_SVE_2BO, // ld1rqw
        IF_SVE_2BP, // ld2q
        IF_SVE_2BP, // ld3q
        IF_SVE_2BP, // ld4q
        IF_SVE_2BQ, // ld2b
        IF_SVE_2BQ, // ld2d
        IF_SVE_2BQ, // ld2h
        IF_SVE_2BQ, // ld2w
        IF_SVE_2BQ, // ld3b
        IF_SVE_2BQ, // ld3d
        IF_SVE_2BQ, // ld3h
        IF_SVE_2BQ, // ld3w
        IF_SVE_2BQ, // ld4b
        IF_SVE_2BQ, // ld4d
        IF_SVE_2BQ, // ld4h
        IF_SVE_2BQ, // ld4w
        IF_SVE_2BR, // st2b
        IF_SVE_2BR, // st2d
        IF_SVE_2BR, // st2h
        IF_SVE_2BR, // st2w
        IF_SVE_2BR, // st3b
        IF_SVE_2BR, // st3d
        IF_SVE_2BR, // st3h
        IF_SVE_2BR, // st3w
        IF_SVE_2BR, // st4b
        IF_SVE_2BR, // st4d
        IF_SVE_2BR, // st4h
        IF_SVE_2BR, // st4w
        IF_SVE_2BS, // st2q
        IF_SVE_2BS, // st3q
        IF_SVE_2BS, // st4q
        IF_SVE_AQ_3A, // abs
        IF_SVE_AQ_3A, // neg
        IF_SVE_AQ_3A, // sxtb
        IF_SVE_AQ_3A, // sxth
        IF_SVE_AQ_3A, // sxtw
        IF_SVE_AQ_3A, // uxtb
        IF_SVE_AQ_3A, // uxth
        IF_SVE_AQ_3A, // uxtw
        IF_SVE_CZ_4A, // ands
        IF_SVE_CZ_4A, // bics
        IF_SVE_CZ_4A, // eors
        IF_SVE_CZ_4A, // nand
        IF_SVE_CZ_4A, // nands
        IF_SVE_CZ_4A, // nor
        IF_SVE_CZ_4A, // nors
        IF_SVE_CZ_4A, // nots
        IF_SVE_CZ_4A, // orns
        IF_SVE_CZ_4A, // orrs
        IF_SVE_CU_3A, // rbit
        IF_SVE_CU_3A, // revb
        IF_SVE_CU_3A, // revh
        IF_SVE_CU_3A, // revw
        IF_SVE_AP_3A, // cls
        IF_SVE_AP_3A, // clz
        IF_SVE_AP_3A, // cnot
        IF_SVE_AP_3A, // cnt
        IF_SVE_AP_3A, // fabs
        IF_SVE_AP_3A, // fneg
        IF_SVE_AC_3A, // sdiv
        IF_SVE_AC_3A, // sdivr
        IF_SVE_AC_3A, // udiv
        IF_SVE_AC_3A, // udivr
        IF_SVE_BS_1A, // eon
        IF_SVE_AK_3A, // smaxv
        IF_SVE_AK_3A, // sminv
        IF_SVE_AK_3A, // umaxv
        IF_SVE_AK_3A, // uminv
        IF_SVE_HE_3A, // faddv
        IF_SVE_HE_3A, // fmaxnmv
        IF_SVE_HE_3A, // fmaxv
        IF_SVE_HE_3A, // fminnmv
        IF_SVE_HE_3A, // fminv
        IF_SVE_AA_3A, // addp
        IF_SVE_AA_3A, // smaxp
        IF_SVE_AA_3A, // sminp
        IF_SVE_AA_3A, // umaxp
        IF_SVE_AA_3A, // uminp
        IF_SVE_GR_3A, // faddp
        IF_SVE_GR_3A, // fmaxnmp
        IF_SVE_GR_3A, // fmaxp
        IF_SVE_GR_3A, // fminnmp
        IF_SVE_GR_3A, // fminp
        IF_SVE_FU_2A, // srsra
        IF_SVE_FU_2A, // ssra
        IF_SVE_FU_2A, // ursra
        IF_SVE_FU_2A, // usra
        IF_SVE_AM_2A, // asrd
        IF_SVE_AM_2A, // sqshlu
        IF_SVE_AM_2A, // srshr
        IF_SVE_AM_2A, // urshr
        IF_SVE_GA_2A, // sqrshrn
        IF_SVE_GA_2A, // sqrshrun
        IF_SVE_GA_2A, // uqrshrn
        IF_SVE_FT_2A, // sli
        IF_SVE_FT_2A, // sri
        IF_SVE_AA_3A, // sqrshl
        IF_SVE_AA_3A, // sqrshlr
        IF_SVE_AA_3A, // sqshlr
        IF_SVE_AA_3A, // srshl
        IF_SVE_AA_3A, // srshlr
        IF_SVE_AA_3A, // uqrshl
        IF_SVE_AA_3A, // uqrshlr
        IF_SVE_AA_3A, // uqshlr
        IF_SVE_AA_3A, // urshl
        IF_SVE_AA_3A, // urshlr
        IF_SVE_HL_3A, // fabd
        IF_SVE_HL_3A, // famax
        IF_SVE_HL_3A, // famin
        IF_SVE_HL_3A, // fdiv
        IF_SVE_HL_3A, // fdivr
        IF_SVE_HL_3A, // fmulx
        IF_SVE_HL_3A, // fscale
        IF_SVE_AT_3A, // frecps
        IF_SVE_AT_3A, // frsqrts
        IF_SVE_AT_3A, // ftsmul
        IF_SVE_HT_4A, // facge
        IF_SVE_HT_4A, // facgt
        IF_SVE_HT_4A, // facle
        IF_SVE_HT_4A, // faclt
        IF_SVE_HT_4A, // fcmuo
        IF_SVE_AA_3A, // sqsubr
        IF_SVE_AA_3A, // suqadd
        IF_SVE_AA_3A, // uqsubr
        IF_SVE_AA_3A, // usqadd
        IF_SVE_ES_3A, // sqabs
        IF_SVE_ES_3A, // sqneg
        IF_SVE_ES_3A, // urecpe
        IF_SVE_ES_3A, // ursqrte
        IF_SVE_HF_2A, // frecpe
        IF_SVE_HF_2A, // frsqrte
        IF_SVE_HR_3A, // frecpx
        IF_SVE_HR_3A, // fsqrt
        IF_SVE_BZ_3A, // tbx
        IF_SVE_AA_3A, // shadd
        IF_SVE_AA_3A, // shsub
        IF_SVE_AA_3A, // shsubr
        IF_SVE_AA_3A, // srhadd
        IF_SVE_AA_3A, // uhadd
        IF_SVE_AA_3A, // uhsub
        IF_SVE_AA_3A, // uhsubr
        IF_SVE_AA_3A, // urhadd
        IF_SVE_AA_3A, // sabd
        IF_SVE_AA_3A, // uabd
        IF_SVE_FW_3A, // saba
        IF_SVE_FW_3A, // uaba
        IF_SVE_BD_3B, // pmul
        IF_SVE_AV_3A, // bcax
        IF_SVE_AV_3A, // bsl
        IF_SVE_AV_3A, // bsl1n
        IF_SVE_AV_3A, // bsl2n
        IF_SVE_AV_3A, // eor3
        IF_SVE_AV_3A, // nbsl
        IF_SVE_HG_2A, // bfcvtn
        IF_SVE_HG_2A, // fcvtn
        IF_SVE_HG_2A, // fcvtnb
        IF_SVE_GP_3A, // fcadd
        IF_SVE_FO_3A, // smmla
        IF_SVE_FO_3A, // ummla
        IF_SVE_FO_3A, // usmmla
        IF_SVE_HD_3A, // bfmmla
        IF_SVE_EQ_3A, // sadalp
        IF_SVE_EQ_3A, // uadalp
        IF_SVE_HQ_3A, // frinta
        IF_SVE_HQ_3A, // frinti
        IF_SVE_HQ_3A, // frintm
        IF_SVE_HQ_3A, // frintn
        IF_SVE_HQ_3A, // frintp
        IF_SVE_HQ_3A, // frintx
        IF_SVE_HQ_3A, // frintz
        IF_SVE_EZ_3A, // sudot
        IF_SVE_GK_2A, // aesd
        IF_SVE_GK_2A, // aese
        IF_SVE_GK_2A, // sm4e
        IF_SVE_GL_1A, // aesimc
        IF_SVE_GL_1A, // aesmc
        IF_SVE_GJ_3A, // rax1
        IF_SVE_GJ_3A, // sm4ekey
        IF_SVE_AW_2A, // xar
        IF_SVE_AF_3A, // andv
        IF_SVE_AF_3A, // eorv
        IF_SVE_AF_3A, // orv
        IF_SVE_AG_3A, // andqv
        IF_SVE_AG_3A, // eorqv
        IF_SVE_AG_3A, // orqv
        IF_SVE_AI_3A, // saddv
        IF_SVE_AI_3A, // uaddv
        IF_SVE_AJ_3A, // addqv
        IF_SVE_AL_3A, // smaxqv
        IF_SVE_AL_3A, // sminqv
        IF_SVE_AL_3A, // umaxqv
        IF_SVE_AL_3A, // uminqv
        IF_SVE_AA_3A, // asrr
        IF_SVE_AA_3A, // lslr
        IF_SVE_AA_3A, // lsrr
        IF_SVE_AS_4A, // mad
        IF_SVE_AS_4A, // msb
        IF_SVE_BB_2A, // addpl
        IF_SVE_BB_2A, // addvl
        IF_SVE_BC_1A, // rdvl
        IF_SVE_BJ_2A, // fexpa
        IF_SVE_AT_3A, // ftssel
        IF_SVE_BL_1A, // cntb
        IF_SVE_BL_1A, // cntd
        IF_SVE_BL_1A, // cnth
        IF_SVE_BL_1A, // cntw
        IF_SVE_BM_1A, // decb
        IF_SVE_BM_1A, // incb
        IF_SVE_BO_1A, // sqdecb
        IF_SVE_BO_1A, // sqincb
        IF_SVE_BO_1A, // uqdecb
        IF_SVE_BO_1A, // uqincb
        IF_SVE_BT_1A, // dupm
        IF_SVE_BU_2A, // fcpy
        IF_SVE_BX_2A, // dupq
        IF_SVE_BY_2A, // extq
        IF_SVE_AT_3A, // tbxq
        IF_SVE_CH_2A, // sunpkhi
        IF_SVE_CH_2A, // sunpklo
        IF_SVE_CH_2A, // uunpkhi
        IF_SVE_CH_2A, // uunpklo
        IF_SVE_CK_2A, // punpkhi
        IF_SVE_CK_2A, // punpklo
        IF_SVE_CL_3A, // compact
        IF_SVE_CT_3A, // revd
        IF_SVE_DA_4A, // brkpa
        IF_SVE_DA_4A, // brkpas
        IF_SVE_DA_4A, // brkpb
        IF_SVE_DA_4A, // brkpbs
        IF_SVE_DB_3A, // brka
        IF_SVE_DB_3A, // brkb
        IF_SVE_DB_3B, // brkas
        IF_SVE_DB_3B, // brkbs
        IF_SVE_DC_3A, // brkn
        IF_SVE_DC_3A, // brkns
        IF_SVE_DD_2A, // pfirst
        IF_SVE_DE_1A, // ptrues
        IF_SVE_DF_2A, // pnext
        IF_SVE_DG_2A, // rdffrs
        IF_SVE_DI_2A, // ptest
        IF_SVE_DJ_1A, // pfalse
        IF_SVE_DQ_0A, // setffr
        IF_SVE_DR_1A, // wrffr
        IF_SVE_DS_2A, // ctermeq
        IF_SVE_DS_2A, // ctermne
        IF_SVE_DU_3A, // whilerw
        IF_SVE_DU_3A, // whilewr
        IF_SVE_DV_4A, // psel
        IF_SVE_EA_1A, // fdup
        IF_SVE_EL_3A, // sqdmlalbt
        IF_SVE_EL_3A, // sqdmlslbt
        IF_SVE_AT_3A, // sclamp
        IF_SVE_AT_3A, // uclamp
        IF_SVE_EW_3A, // mlapt
        IF_SVE_EW_3B, // madpt
        IF_SVE_EX_3A, // tblq
        IF_SVE_EX_3A, // uzpq1
        IF_SVE_EX_3A, // uzpq2
        IF_SVE_EX_3A, // zipq1
        IF_SVE_EX_3A, // zipq2
        IF_SVE_FL_3A, // sabdlb
        IF_SVE_FL_3A, // sabdlt
        IF_SVE_FL_3A, // saddlb
        IF_SVE_FL_3A, // saddlt
        IF_SVE_FL_3A, // ssublb
        IF_SVE_FL_3A, // ssublt
        IF_SVE_FL_3A, // uabdlb
        IF_SVE_FL_3A, // uabdlt
        IF_SVE_FL_3A, // uaddlb
        IF_SVE_FL_3A, // uaddlt
        IF_SVE_FL_3A, // usublb
        IF_SVE_FL_3A, // usublt
        IF_SVE_FM_3A, // saddwb
        IF_SVE_FM_3A, // saddwt
        IF_SVE_FM_3A, // ssubwb
        IF_SVE_FM_3A, // ssubwt
        IF_SVE_FM_3A, // uaddwb
        IF_SVE_FM_3A, // uaddwt
        IF_SVE_FM_3A, // usubwb
        IF_SVE_FM_3A, // usubwt
        IF_SVE_AT_3A, // eorbt
        IF_SVE_AT_3A, // eortb
        IF_SVE_AT_3A, // bdep
        IF_SVE_AT_3A, // bext
        IF_SVE_AT_3A, // bgrp
        IF_SVE_FR_2A, // sshllb
        IF_SVE_FR_2A, // sshllt
        IF_SVE_FR_2A, // ushllb
        IF_SVE_FR_2A, // ushllt
        IF_SVE_FL_3A, // saddlbt
        IF_SVE_FL_3A, // ssublbt
        IF_SVE_FL_3A, // ssubltb
        IF_SVE_FV_2A, // cadd
        IF_SVE_FV_2A, // sqcadd
        IF_SVE_EL_3A, // sabalb
        IF_SVE_EL_3A, // sabalt
        IF_SVE_EL_3A, // uabalb
        IF_SVE_EL_3A, // uabalt
        IF_SVE_FY_3A, // adclb
        IF_SVE_FY_3A, // adclt
        IF_SVE_FY_3A, // sbclb
        IF_SVE_FY_3A, // sbclt
        IF_SVE_FZ_2A, // sqcvtn
        IF_SVE_FZ_2A, // sqcvtun
        IF_SVE_FZ_2A, // uqcvtn
        IF_SVE_GB_2A, // rshrnb
        IF_SVE_GB_2A, // rshrnt
        IF_SVE_GB_2A, // shrnb
        IF_SVE_GB_2A, // shrnt
        IF_SVE_GB_2A, // sqrshrnb
        IF_SVE_GB_2A, // sqrshrnt
        IF_SVE_GB_2A, // sqrshrunb
        IF_SVE_GB_2A, // sqrshrunt
        IF_SVE_GB_2A, // sqshrnb
        IF_SVE_GB_2A, // sqshrnt
        IF_SVE_GB_2A, // sqshrunb
        IF_SVE_GB_2A, // sqshrunt
        IF_SVE_GB_2A, // uqrshrnb
        IF_SVE_GB_2A, // uqrshrnt
        IF_SVE_GB_2A, // uqshrnb
        IF_SVE_GB_2A, // uqshrnt
        IF_SVE_GC_3A, // addhnb
        IF_SVE_GC_3A, // addhnt
        IF_SVE_GC_3A, // raddhnb
        IF_SVE_GC_3A, // raddhnt
        IF_SVE_GC_3A, // rsubhnb
        IF_SVE_GC_3A, // rsubhnt
        IF_SVE_GC_3A, // subhnb
        IF_SVE_GC_3A, // subhnt
        IF_SVE_GD_2A, // sqxtnb
        IF_SVE_GD_2A, // sqxtnt
        IF_SVE_GD_2A, // sqxtunb
        IF_SVE_GD_2A, // sqxtunt
        IF_SVE_GD_2A, // uqxtnb
        IF_SVE_GD_2A, // uqxtnt
        IF_SVE_GE_4A, // match
        IF_SVE_GE_4A, // nmatch
        IF_SVE_GF_3A, // histseg
        IF_SVE_GI_4A, // histcnt
        IF_SVE_GQ_3A, // bfcvtnt
        IF_SVE_GQ_3A, // fcvtlt
        IF_SVE_GQ_3A, // fcvtxnt
        IF_SVE_GS_3A, // faddqv
        IF_SVE_GS_3A, // fmaxnmqv
        IF_SVE_GS_3A, // fmaxqv
        IF_SVE_GS_3A, // fminnmqv
        IF_SVE_GS_3A, // fminqv
        IF_SVE_AT_3A, // fclamp
        IF_SVE_GW_3B, // bfclamp
        IF_SVE_HD_3A_A, // fmmla
        IF_SVE_HH_2A, // bf1cvt
        IF_SVE_HH_2A, // bf1cvtlt
        IF_SVE_HH_2A, // bf2cvt
        IF_SVE_HH_2A, // bf2cvtlt
        IF_SVE_HH_2A, // f1cvt
        IF_SVE_HH_2A, // f1cvtlt
        IF_SVE_HH_2A, // f2cvt
        IF_SVE_HH_2A, // f2cvtlt
        IF_SVE_HJ_3A, // fadda
        IF_SVE_HL_3B, // bfmax
        IF_SVE_HL_3B, // bfmaxnm
        IF_SVE_HL_3B, // bfmin
        IF_SVE_HL_3B, // bfminnm
        IF_SVE_HN_2A, // ftmad
        IF_SVE_HO_3A, // bfcvt
        IF_SVE_HO_3B, // fcvt
        IF_SVE_HO_3C, // fcvtx
        IF_SVE_HP_3A, // flogb
        IF_SVE_HP_3B, // fcvtzs
        IF_SVE_HP_3B, // fcvtzu
        IF_SVE_HS_3A, // scvtf
        IF_SVE_HS_3A, // ucvtf
        IF_SVE_HU_4A, // fnmla
        IF_SVE_HU_4A, // fnmls
        IF_SVE_HV_4A, // fmad
        IF_SVE_HV_4A, // fmsb
        IF_SVE_HV_4A, // fnmad
        IF_SVE_HV_4A, // fnmsb
        IF_SVE_IC_3A_C, // ld1rb
        IF_SVE_IC_3A, // ld1rd
        IF_SVE_IC_3A, // ld1rsw
        IF_SVE_IC_3A_B, // ld1rh
        IF_SVE_IC_3A_B, // ld1rsb
        IF_SVE_IC_3A_A, // ld1rsh
        IF_SVE_IC_3A_A, // ld1rw
        IF_SVE_IL_3A_C, // ldnf1b
        IF_SVE_IL_3A, // ldnf1d
        IF_SVE_IL_3A, // ldnf1sw
        IF_SVE_IL_3A_B, // ldnf1h
        IF_SVE_IL_3A_B, // ldnf1sb
        IF_SVE_IL_3A_A, // ldnf1sh
        IF_SVE_IL_3A_A, // ldnf1w
        IF_SVE_IW_4A, // ld1q
        IF_SVE_IX_4A, // ldnt1sw
        IF_SVE_IY_4A, // st1q
#elif TARGET_LOONGARCH64
#if !TARGET_LOONGARCH64
#error Unexpected target type
#endif
#if FEATURE_SIMD
#endif
#elif TARGET_RISCV64
#if !TARGET_RISCV64
#error Unexpected target type
#endif
#elif TARGET_WASM
#if !TARGET_WASM
#error Unexpected target type
#endif
#else
#error Unsupported or unset target architecture
#endif

    ];
#endif
}