// Copyright (c) Tanner Gooding and Contributors. Licensed under the MIT License (MIT). See License.md in the repository root for more information.
//
// Based on the RyuJIT compiler from dotnet/runtime.
// Original source is Copyright (c) .NET Foundation and Contributors. Licensed under the MIT License (MIT).

using System;

namespace RyuJitSharp;

public partial class Emitter
{
#if TARGET_XARCH
    internal static ReadOnlySpan<byte> emitInsModeFmtTab => [
#if TARGET_XARCH
#if !TARGET_XARCH
#error Unexpected target type
#endif
        (byte)IUM_RD, // INS_invalid
        (byte)IUM_RD, // INS_push
        (byte)IUM_WR, // INS_pop
        (byte)IUM_RD, // INS_push_hide
        (byte)IUM_WR, // INS_pop_hide
        (byte)IUM_RD, // INS_push2
        (byte)IUM_WR, // INS_pop2
        (byte)IUM_RW, // INS_inc
        (byte)IUM_RW, // INS_inc_l
        (byte)IUM_RW, // INS_dec
        (byte)IUM_RW, // INS_dec_l
        (byte)IUM_RW, // INS_bswap
        (byte)IUM_RW, // INS_add
        (byte)IUM_RW, // INS_or
        (byte)IUM_RW, // INS_adc
        (byte)IUM_RW, // INS_sbb
        (byte)IUM_RW, // INS_and
        (byte)IUM_RW, // INS_sub
        (byte)IUM_RW, // INS_sub_hide
        (byte)IUM_RW, // INS_xor
        (byte)IUM_RD, // INS_cmp
        (byte)IUM_RD, // INS_test
        (byte)IUM_WR, // INS_mov
        (byte)IUM_WR, // INS_lea
        (byte)IUM_RD, // INS_bt
        (byte)IUM_RW, // INS_bts
        (byte)IUM_RW, // INS_btr
        (byte)IUM_RW, // INS_btc
        (byte)IUM_WR, // INS_bsr
        (byte)IUM_WR, // INS_bsf
        (byte)IUM_WR, // INS_movsx
#if TARGET_AMD64
        (byte)IUM_WR, // INS_movsxd
#endif
        (byte)IUM_WR, // INS_movzx
        (byte)IUM_WR, // INS_cmovo
        (byte)IUM_WR, // INS_cmovno
        (byte)IUM_WR, // INS_cmovb
        (byte)IUM_WR, // INS_cmovae
        (byte)IUM_WR, // INS_cmove
        (byte)IUM_WR, // INS_cmovne
        (byte)IUM_WR, // INS_cmovbe
        (byte)IUM_WR, // INS_cmova
        (byte)IUM_WR, // INS_cmovs
        (byte)IUM_WR, // INS_cmovns
        (byte)IUM_WR, // INS_cmovp
        (byte)IUM_WR, // INS_cmovnp
        (byte)IUM_WR, // INS_cmovl
        (byte)IUM_WR, // INS_cmovge
        (byte)IUM_WR, // INS_cmovle
        (byte)IUM_WR, // INS_cmovg
        (byte)IUM_RW, // INS_xchg
        (byte)IUM_RW, // INS_imul
        (byte)IUM_RD, // INS_imul_AX
        (byte)IUM_RD, // INS_imul_CX
        (byte)IUM_RD, // INS_imul_DX
        (byte)IUM_RD, // INS_imul_BX
        (byte)IUM_RD, // INS_imul_SP
        (byte)IUM_RD, // INS_imul_BP
        (byte)IUM_RD, // INS_imul_SI
        (byte)IUM_RD, // INS_imul_DI
#if TARGET_AMD64
        (byte)IUM_RD, // INS_imul_08
        (byte)IUM_RD, // INS_imul_09
        (byte)IUM_RD, // INS_imul_10
        (byte)IUM_RD, // INS_imul_11
        (byte)IUM_RD, // INS_imul_12
        (byte)IUM_RD, // INS_imul_13
        (byte)IUM_RD, // INS_imul_14
        (byte)IUM_RD, // INS_imul_15
        (byte)IUM_RD, // INS_imul_16
        (byte)IUM_RD, // INS_imul_17
        (byte)IUM_RD, // INS_imul_18
        (byte)IUM_RD, // INS_imul_19
        (byte)IUM_RD, // INS_imul_20
        (byte)IUM_RD, // INS_imul_21
        (byte)IUM_RD, // INS_imul_22
        (byte)IUM_RD, // INS_imul_23
        (byte)IUM_RD, // INS_imul_24
        (byte)IUM_RD, // INS_imul_25
        (byte)IUM_RD, // INS_imul_26
        (byte)IUM_RD, // INS_imul_27
        (byte)IUM_RD, // INS_imul_28
        (byte)IUM_RD, // INS_imul_29
        (byte)IUM_RD, // INS_imul_30
        (byte)IUM_RD, // INS_imul_31
#endif
        (byte)IUM_WR, // INS_addpd
        (byte)IUM_WR, // INS_addps
        (byte)IUM_WR, // INS_addsd
        (byte)IUM_WR, // INS_addss
        (byte)IUM_WR, // INS_addsubpd
        (byte)IUM_WR, // INS_addsubps
        (byte)IUM_WR, // INS_andnpd
        (byte)IUM_WR, // INS_andnps
        (byte)IUM_WR, // INS_andpd
        (byte)IUM_WR, // INS_andps
        (byte)IUM_WR, // INS_blendpd
        (byte)IUM_WR, // INS_blendps
        (byte)IUM_WR, // INS_blendvpd
        (byte)IUM_WR, // INS_blendvps
        (byte)IUM_WR, // INS_cmppd
        (byte)IUM_WR, // INS_cmpps
        (byte)IUM_WR, // INS_cmpsd
        (byte)IUM_WR, // INS_cmpss
        (byte)IUM_RD, // INS_comisd
        (byte)IUM_RD, // INS_comiss
        (byte)IUM_WR, // INS_cvtdq2pd
        (byte)IUM_WR, // INS_cvtdq2ps
        (byte)IUM_WR, // INS_cvtpd2dq
        (byte)IUM_WR, // INS_cvtpd2ps
        (byte)IUM_WR, // INS_cvtps2dq
        (byte)IUM_WR, // INS_cvtps2pd
        (byte)IUM_WR, // INS_cvtsd2si32
        (byte)IUM_WR, // INS_cvtsd2si64
        (byte)IUM_WR, // INS_cvtsd2ss
        (byte)IUM_WR, // INS_cvtsi2sd32
        (byte)IUM_WR, // INS_cvtsi2sd64
        (byte)IUM_WR, // INS_cvtsi2ss32
        (byte)IUM_WR, // INS_cvtsi2ss64
        (byte)IUM_WR, // INS_cvtss2sd
        (byte)IUM_WR, // INS_cvtss2si32
        (byte)IUM_WR, // INS_cvtss2si64
        (byte)IUM_WR, // INS_cvttpd2dq
        (byte)IUM_WR, // INS_cvttps2dq
        (byte)IUM_WR, // INS_cvttsd2si32
        (byte)IUM_WR, // INS_cvttsd2si64
        (byte)IUM_WR, // INS_cvttss2si32
        (byte)IUM_WR, // INS_cvttss2si64
        (byte)IUM_WR, // INS_divpd
        (byte)IUM_WR, // INS_divps
        (byte)IUM_WR, // INS_divsd
        (byte)IUM_WR, // INS_divss
        (byte)IUM_WR, // INS_dppd
        (byte)IUM_WR, // INS_dpps
        (byte)IUM_WR, // INS_extractps
        (byte)IUM_WR, // INS_haddpd
        (byte)IUM_WR, // INS_haddps
        (byte)IUM_WR, // INS_hsubpd
        (byte)IUM_WR, // INS_hsubps
        (byte)IUM_WR, // INS_insertps
        (byte)IUM_WR, // INS_lddqu
        (byte)IUM_RD, // INS_lfence
        (byte)IUM_WR, // INS_maskmovdqu
        (byte)IUM_WR, // INS_maxpd
        (byte)IUM_WR, // INS_maxps
        (byte)IUM_WR, // INS_maxsd
        (byte)IUM_WR, // INS_maxss
        (byte)IUM_RD, // INS_mfence
        (byte)IUM_WR, // INS_minpd
        (byte)IUM_WR, // INS_minps
        (byte)IUM_WR, // INS_minsd
        (byte)IUM_WR, // INS_minss
        (byte)IUM_WR, // INS_movapd
        (byte)IUM_WR, // INS_movaps
        (byte)IUM_WR, // INS_movd32
        (byte)IUM_WR, // INS_movd64
        (byte)IUM_WR, // INS_movddup
        (byte)IUM_WR, // INS_movdqa32
        (byte)IUM_WR, // INS_movdqu32
        (byte)IUM_WR, // INS_movhlps
        (byte)IUM_WR, // INS_movhpd
        (byte)IUM_WR, // INS_movhps
        (byte)IUM_WR, // INS_movlhps
        (byte)IUM_WR, // INS_movlpd
        (byte)IUM_WR, // INS_movlps
        (byte)IUM_WR, // INS_movmskpd
        (byte)IUM_WR, // INS_movmskps
        (byte)IUM_WR, // INS_movntdq
        (byte)IUM_WR, // INS_movntdqa
        (byte)IUM_WR, // INS_movnti32
        (byte)IUM_WR, // INS_movnti64
        (byte)IUM_WR, // INS_movntpd
        (byte)IUM_WR, // INS_movntps
        (byte)IUM_WR, // INS_movq
        (byte)IUM_WR, // INS_movsd_simd
        (byte)IUM_WR, // INS_movshdup
        (byte)IUM_WR, // INS_movsldup
        (byte)IUM_WR, // INS_movss
        (byte)IUM_WR, // INS_movupd
        (byte)IUM_WR, // INS_movups
        (byte)IUM_WR, // INS_mpsadbw
        (byte)IUM_WR, // INS_mulpd
        (byte)IUM_WR, // INS_mulps
        (byte)IUM_WR, // INS_mulsd
        (byte)IUM_WR, // INS_mulss
        (byte)IUM_WR, // INS_orpd
        (byte)IUM_WR, // INS_orps
        (byte)IUM_WR, // INS_pabsb
        (byte)IUM_WR, // INS_pabsd
        (byte)IUM_WR, // INS_pabsw
        (byte)IUM_WR, // INS_packssdw
        (byte)IUM_WR, // INS_packsswb
        (byte)IUM_WR, // INS_packusdw
        (byte)IUM_WR, // INS_packuswb
        (byte)IUM_WR, // INS_paddb
        (byte)IUM_WR, // INS_paddd
        (byte)IUM_WR, // INS_paddq
        (byte)IUM_WR, // INS_paddsb
        (byte)IUM_WR, // INS_paddsw
        (byte)IUM_WR, // INS_paddusb
        (byte)IUM_WR, // INS_paddusw
        (byte)IUM_WR, // INS_paddw
        (byte)IUM_WR, // INS_palignr
        (byte)IUM_WR, // INS_pandd
        (byte)IUM_WR, // INS_pandnd
        (byte)IUM_WR, // INS_pavgb
        (byte)IUM_WR, // INS_pavgw
        (byte)IUM_WR, // INS_pblendvb
        (byte)IUM_WR, // INS_pblendw
        (byte)IUM_WR, // INS_pcmpeqb
        (byte)IUM_WR, // INS_pcmpeqd
        (byte)IUM_WR, // INS_pcmpeqq
        (byte)IUM_WR, // INS_pcmpeqw
        (byte)IUM_WR, // INS_pcmpgtb
        (byte)IUM_WR, // INS_pcmpgtd
        (byte)IUM_WR, // INS_pcmpgtq
        (byte)IUM_WR, // INS_pcmpgtw
        (byte)IUM_WR, // INS_pextrb
        (byte)IUM_WR, // INS_pextrd
        (byte)IUM_WR, // INS_pextrq
        (byte)IUM_WR, // INS_phaddd
        (byte)IUM_WR, // INS_pextrw
        (byte)IUM_WR, // INS_phaddsw
        (byte)IUM_WR, // INS_phaddw
        (byte)IUM_WR, // INS_phminposuw
        (byte)IUM_WR, // INS_phsubd
        (byte)IUM_WR, // INS_phsubsw
        (byte)IUM_WR, // INS_phsubw
        (byte)IUM_WR, // INS_pinsrb
        (byte)IUM_WR, // INS_pinsrd
        (byte)IUM_WR, // INS_pinsrq
        (byte)IUM_WR, // INS_pinsrw
        (byte)IUM_WR, // INS_pmaddubsw
        (byte)IUM_WR, // INS_pmaddwd
        (byte)IUM_WR, // INS_pmaxsb
        (byte)IUM_WR, // INS_pmaxsd
        (byte)IUM_WR, // INS_pmaxsw
        (byte)IUM_WR, // INS_pmaxub
        (byte)IUM_WR, // INS_pmaxud
        (byte)IUM_WR, // INS_pmaxuw
        (byte)IUM_WR, // INS_pminsb
        (byte)IUM_WR, // INS_pminsd
        (byte)IUM_WR, // INS_pminsw
        (byte)IUM_WR, // INS_pminub
        (byte)IUM_WR, // INS_pminud
        (byte)IUM_WR, // INS_pminuw
        (byte)IUM_WR, // INS_pmovmskb
        (byte)IUM_WR, // INS_pmovsxbd
        (byte)IUM_WR, // INS_pmovsxbq
        (byte)IUM_WR, // INS_pmovsxbw
        (byte)IUM_WR, // INS_pmovsxdq
        (byte)IUM_WR, // INS_pmovsxwd
        (byte)IUM_WR, // INS_pmovsxwq
        (byte)IUM_WR, // INS_pmovzxbd
        (byte)IUM_WR, // INS_pmovzxbq
        (byte)IUM_WR, // INS_pmovzxbw
        (byte)IUM_WR, // INS_pmovzxdq
        (byte)IUM_WR, // INS_pmovzxwd
        (byte)IUM_WR, // INS_pmovzxwq
        (byte)IUM_WR, // INS_pmuldq
        (byte)IUM_WR, // INS_pmulhrsw
        (byte)IUM_WR, // INS_pmulhuw
        (byte)IUM_WR, // INS_pmulhw
        (byte)IUM_WR, // INS_pmulld
        (byte)IUM_WR, // INS_pmuludq
        (byte)IUM_WR, // INS_pmullw
        (byte)IUM_WR, // INS_pord
        (byte)IUM_RD, // INS_prefetchnta
        (byte)IUM_RD, // INS_prefetcht0
        (byte)IUM_RD, // INS_prefetcht1
        (byte)IUM_RD, // INS_prefetcht2
        (byte)IUM_WR, // INS_psadbw
        (byte)IUM_WR, // INS_pshufb
        (byte)IUM_WR, // INS_pshufd
        (byte)IUM_WR, // INS_pshufhw
        (byte)IUM_WR, // INS_pshuflw
        (byte)IUM_WR, // INS_psignb
        (byte)IUM_WR, // INS_psignd
        (byte)IUM_WR, // INS_psignw
        (byte)IUM_WR, // INS_pslld
        (byte)IUM_WR, // INS_pslldq
        (byte)IUM_WR, // INS_psllq
        (byte)IUM_WR, // INS_psllw
        (byte)IUM_WR, // INS_psrad
        (byte)IUM_WR, // INS_psraw
        (byte)IUM_WR, // INS_psrld
        (byte)IUM_WR, // INS_psrldq
        (byte)IUM_WR, // INS_psrlq
        (byte)IUM_WR, // INS_psrlw
        (byte)IUM_WR, // INS_psubb
        (byte)IUM_WR, // INS_psubd
        (byte)IUM_WR, // INS_psubq
        (byte)IUM_WR, // INS_psubsb
        (byte)IUM_WR, // INS_psubsw
        (byte)IUM_WR, // INS_psubusb
        (byte)IUM_WR, // INS_psubusw
        (byte)IUM_WR, // INS_psubw
        (byte)IUM_RD, // INS_ptest
        (byte)IUM_WR, // INS_punpckhbw
        (byte)IUM_WR, // INS_punpckhdq
        (byte)IUM_WR, // INS_punpckhqdq
        (byte)IUM_WR, // INS_punpckhwd
        (byte)IUM_WR, // INS_punpcklbw
        (byte)IUM_WR, // INS_punpckldq
        (byte)IUM_WR, // INS_punpcklqdq
        (byte)IUM_WR, // INS_punpcklwd
        (byte)IUM_WR, // INS_pxord
        (byte)IUM_WR, // INS_rcpps
        (byte)IUM_WR, // INS_rcpss
        (byte)IUM_WR, // INS_roundpd
        (byte)IUM_WR, // INS_roundps
        (byte)IUM_WR, // INS_roundsd
        (byte)IUM_WR, // INS_roundss
        (byte)IUM_WR, // INS_rsqrtps
        (byte)IUM_WR, // INS_rsqrtss
        (byte)IUM_RD, // INS_sfence
        (byte)IUM_WR, // INS_shufpd
        (byte)IUM_WR, // INS_shufps
        (byte)IUM_WR, // INS_sqrtpd
        (byte)IUM_WR, // INS_sqrtps
        (byte)IUM_WR, // INS_sqrtsd
        (byte)IUM_WR, // INS_sqrtss
        (byte)IUM_WR, // INS_subpd
        (byte)IUM_WR, // INS_subps
        (byte)IUM_WR, // INS_subsd
        (byte)IUM_WR, // INS_subss
        (byte)IUM_RD, // INS_ucomisd
        (byte)IUM_RD, // INS_ucomiss
        (byte)IUM_WR, // INS_unpckhpd
        (byte)IUM_WR, // INS_unpckhps
        (byte)IUM_WR, // INS_unpcklpd
        (byte)IUM_WR, // INS_unpcklps
        (byte)IUM_WR, // INS_xorpd
        (byte)IUM_WR, // INS_xorps
        (byte)IUM_WR, // INS_aesdec
        (byte)IUM_WR, // INS_aesdeclast
        (byte)IUM_WR, // INS_aesenc
        (byte)IUM_WR, // INS_aesenclast
        (byte)IUM_WR, // INS_aesimc
        (byte)IUM_WR, // INS_aeskeygenassist
        (byte)IUM_WR, // INS_pclmulqdq
        (byte)IUM_RW, // INS_sha1msg1
        (byte)IUM_RW, // INS_sha1msg2
        (byte)IUM_RW, // INS_sha1nexte
        (byte)IUM_RW, // INS_sha1rnds4
        (byte)IUM_RW, // INS_sha256msg1
        (byte)IUM_RW, // INS_sha256msg2
        (byte)IUM_RW, // INS_sha256rnds2
        (byte)IUM_WR, // INS_gf2p8affineinvqb
        (byte)IUM_WR, // INS_gf2p8affineqb
        (byte)IUM_WR, // INS_gf2p8mulb
        (byte)IUM_WR, // INS_vblendvpd
        (byte)IUM_WR, // INS_vblendvps
        (byte)IUM_WR, // INS_vbroadcastf32x4
        (byte)IUM_WR, // INS_vbroadcastsd
        (byte)IUM_WR, // INS_vbroadcastss
        (byte)IUM_WR, // INS_vextractf32x4
        (byte)IUM_WR, // INS_vinsertf32x4
        (byte)IUM_WR, // INS_vmaskmovpd
        (byte)IUM_WR, // INS_vmaskmovps
        (byte)IUM_WR, // INS_vpblendvb
        (byte)IUM_WR, // INS_vperm2f128
        (byte)IUM_WR, // INS_vpermilpd
        (byte)IUM_WR, // INS_vpermilpdvar
        (byte)IUM_WR, // INS_vpermilps
        (byte)IUM_WR, // INS_vpermilpsvar
        (byte)IUM_RD, // INS_vtestpd
        (byte)IUM_RD, // INS_vtestps
        (byte)IUM_WR, // INS_vzeroupper
        (byte)IUM_WR, // INS_vbroadcasti32x4
        (byte)IUM_WR, // INS_vcvtph2ps
        (byte)IUM_WR, // INS_vcvtps2ph
        (byte)IUM_WR, // INS_vextracti32x4
        (byte)IUM_WR, // INS_vgatherdpd
        (byte)IUM_WR, // INS_vgatherdps
        (byte)IUM_WR, // INS_vgatherqpd
        (byte)IUM_WR, // INS_vgatherqps
        (byte)IUM_WR, // INS_vinserti32x4
        (byte)IUM_WR, // INS_vpblendd
        (byte)IUM_WR, // INS_vpbroadcastb
        (byte)IUM_WR, // INS_vpbroadcastd
        (byte)IUM_WR, // INS_vpbroadcastq
        (byte)IUM_WR, // INS_vpbroadcastw
        (byte)IUM_WR, // INS_vperm2i128
        (byte)IUM_WR, // INS_vpermd
        (byte)IUM_WR, // INS_vpermpd
        (byte)IUM_WR, // INS_vpermps
        (byte)IUM_WR, // INS_vpermq
        (byte)IUM_WR, // INS_vpgatherdd
        (byte)IUM_WR, // INS_vpgatherdq
        (byte)IUM_WR, // INS_vpgatherqd
        (byte)IUM_WR, // INS_vpgatherqq
        (byte)IUM_WR, // INS_vpmaskmovd
        (byte)IUM_WR, // INS_vpmaskmovq
        (byte)IUM_WR, // INS_vpsllvd
        (byte)IUM_WR, // INS_vpsllvq
        (byte)IUM_WR, // INS_vpsravd
        (byte)IUM_WR, // INS_vpsrlvd
        (byte)IUM_WR, // INS_vpsrlvq
        (byte)IUM_RW, // INS_vfmadd132pd
        (byte)IUM_RW, // INS_vfmadd213pd
        (byte)IUM_RW, // INS_vfmadd231pd
        (byte)IUM_RW, // INS_vfmadd132ps
        (byte)IUM_RW, // INS_vfmadd213ps
        (byte)IUM_RW, // INS_vfmadd231ps
        (byte)IUM_RW, // INS_vfmadd132sd
        (byte)IUM_RW, // INS_vfmadd213sd
        (byte)IUM_RW, // INS_vfmadd231sd
        (byte)IUM_RW, // INS_vfmadd132ss
        (byte)IUM_RW, // INS_vfmadd213ss
        (byte)IUM_RW, // INS_vfmadd231ss
        (byte)IUM_RW, // INS_vfmaddsub132pd
        (byte)IUM_RW, // INS_vfmaddsub213pd
        (byte)IUM_RW, // INS_vfmaddsub231pd
        (byte)IUM_RW, // INS_vfmaddsub132ps
        (byte)IUM_RW, // INS_vfmaddsub213ps
        (byte)IUM_RW, // INS_vfmaddsub231ps
        (byte)IUM_RW, // INS_vfmsubadd132pd
        (byte)IUM_RW, // INS_vfmsubadd213pd
        (byte)IUM_RW, // INS_vfmsubadd231pd
        (byte)IUM_RW, // INS_vfmsubadd132ps
        (byte)IUM_RW, // INS_vfmsubadd213ps
        (byte)IUM_RW, // INS_vfmsubadd231ps
        (byte)IUM_RW, // INS_vfmsub132pd
        (byte)IUM_RW, // INS_vfmsub213pd
        (byte)IUM_RW, // INS_vfmsub231pd
        (byte)IUM_RW, // INS_vfmsub132ps
        (byte)IUM_RW, // INS_vfmsub213ps
        (byte)IUM_RW, // INS_vfmsub231ps
        (byte)IUM_RW, // INS_vfmsub132sd
        (byte)IUM_RW, // INS_vfmsub213sd
        (byte)IUM_RW, // INS_vfmsub231sd
        (byte)IUM_RW, // INS_vfmsub132ss
        (byte)IUM_RW, // INS_vfmsub213ss
        (byte)IUM_RW, // INS_vfmsub231ss
        (byte)IUM_RW, // INS_vfnmadd132pd
        (byte)IUM_RW, // INS_vfnmadd213pd
        (byte)IUM_RW, // INS_vfnmadd231pd
        (byte)IUM_RW, // INS_vfnmadd132ps
        (byte)IUM_RW, // INS_vfnmadd213ps
        (byte)IUM_RW, // INS_vfnmadd231ps
        (byte)IUM_RW, // INS_vfnmadd132sd
        (byte)IUM_RW, // INS_vfnmadd213sd
        (byte)IUM_RW, // INS_vfnmadd231sd
        (byte)IUM_RW, // INS_vfnmadd132ss
        (byte)IUM_RW, // INS_vfnmadd213ss
        (byte)IUM_RW, // INS_vfnmadd231ss
        (byte)IUM_RW, // INS_vfnmsub132pd
        (byte)IUM_RW, // INS_vfnmsub213pd
        (byte)IUM_RW, // INS_vfnmsub231pd
        (byte)IUM_RW, // INS_vfnmsub132ps
        (byte)IUM_RW, // INS_vfnmsub213ps
        (byte)IUM_RW, // INS_vfnmsub231ps
        (byte)IUM_RW, // INS_vfnmsub132sd
        (byte)IUM_RW, // INS_vfnmsub213sd
        (byte)IUM_RW, // INS_vfnmsub231sd
        (byte)IUM_RW, // INS_vfnmsub132ss
        (byte)IUM_RW, // INS_vfnmsub213ss
        (byte)IUM_RW, // INS_vfnmsub231ss
        (byte)IUM_WR, // INS_andn
        (byte)IUM_WR, // INS_bextr
        (byte)IUM_WR, // INS_blsi
        (byte)IUM_WR, // INS_blsmsk
        (byte)IUM_WR, // INS_blsr
        (byte)IUM_WR, // INS_bzhi
        (byte)IUM_WR, // INS_mulx
        (byte)IUM_WR, // INS_pdep
        (byte)IUM_WR, // INS_pext
        (byte)IUM_WR, // INS_rorx
        (byte)IUM_WR, // INS_sarx
        (byte)IUM_WR, // INS_shlx
        (byte)IUM_WR, // INS_shrx
        (byte)IUM_RW, // INS_vpdpbusd
        (byte)IUM_RW, // INS_vpdpbusds
        (byte)IUM_RW, // INS_vpdpwssd
        (byte)IUM_RW, // INS_vpdpwssds
        (byte)IUM_WR, // INS_vpdpwsud
        (byte)IUM_WR, // INS_vpdpwsuds
        (byte)IUM_WR, // INS_vpdpwusd
        (byte)IUM_WR, // INS_vpdpwusds
        (byte)IUM_WR, // INS_vpdpwuud
        (byte)IUM_WR, // INS_vpdpwuuds
        (byte)IUM_WR, // INS_vpdpbssd
        (byte)IUM_WR, // INS_vpdpbssds
        (byte)IUM_WR, // INS_vpdpbsud
        (byte)IUM_WR, // INS_vpdpbsuds
        (byte)IUM_WR, // INS_vpdpbuud
        (byte)IUM_WR, // INS_vpdpbuuds
        (byte)IUM_WR, // INS_vbmacor16x16x16
        (byte)IUM_WR, // INS_vbmacxor16x16x16
        (byte)IUM_WR, // INS_vbitrev
        (byte)IUM_RW, // INS_vpmadd52huq
        (byte)IUM_RW, // INS_vpmadd52luq
        (byte)IUM_WR, // INS_kaddb
        (byte)IUM_WR, // INS_kaddd
        (byte)IUM_WR, // INS_kaddq
        (byte)IUM_WR, // INS_kaddw
        (byte)IUM_WR, // INS_kandb
        (byte)IUM_WR, // INS_kandd
        (byte)IUM_WR, // INS_kandnb
        (byte)IUM_WR, // INS_kandnd
        (byte)IUM_WR, // INS_kandnq
        (byte)IUM_WR, // INS_kandnw
        (byte)IUM_WR, // INS_kandq
        (byte)IUM_WR, // INS_kandw
        (byte)IUM_WR, // INS_kmovb_gpr
        (byte)IUM_WR, // INS_kmovb_msk
        (byte)IUM_WR, // INS_kmovd_gpr
        (byte)IUM_WR, // INS_kmovd_msk
        (byte)IUM_WR, // INS_kmovq_gpr
        (byte)IUM_WR, // INS_kmovq_msk
        (byte)IUM_WR, // INS_kmovw_gpr
        (byte)IUM_WR, // INS_kmovw_msk
        (byte)IUM_WR, // INS_knotb
        (byte)IUM_WR, // INS_knotd
        (byte)IUM_WR, // INS_knotq
        (byte)IUM_WR, // INS_knotw
        (byte)IUM_WR, // INS_korb
        (byte)IUM_WR, // INS_kord
        (byte)IUM_WR, // INS_korq
        (byte)IUM_RD, // INS_kortestb
        (byte)IUM_RD, // INS_kortestd
        (byte)IUM_RD, // INS_kortestq
        (byte)IUM_RD, // INS_kortestw
        (byte)IUM_WR, // INS_korw
        (byte)IUM_WR, // INS_kshiftlb
        (byte)IUM_WR, // INS_kshiftld
        (byte)IUM_WR, // INS_kshiftlq
        (byte)IUM_WR, // INS_kshiftlw
        (byte)IUM_WR, // INS_kshiftrb
        (byte)IUM_WR, // INS_kshiftrd
        (byte)IUM_WR, // INS_kshiftrq
        (byte)IUM_WR, // INS_kshiftrw
        (byte)IUM_RD, // INS_ktestb
        (byte)IUM_RD, // INS_ktestd
        (byte)IUM_RD, // INS_ktestq
        (byte)IUM_RD, // INS_ktestw
        (byte)IUM_WR, // INS_kunpckbw
        (byte)IUM_WR, // INS_kunpckdq
        (byte)IUM_WR, // INS_kunpckwd
        (byte)IUM_WR, // INS_kxnorb
        (byte)IUM_WR, // INS_kxnord
        (byte)IUM_WR, // INS_kxnorq
        (byte)IUM_WR, // INS_kxnorw
        (byte)IUM_WR, // INS_kxorb
        (byte)IUM_WR, // INS_kxord
        (byte)IUM_WR, // INS_kxorq
        (byte)IUM_WR, // INS_kxorw
        (byte)IUM_WR, // INS_valignd
        (byte)IUM_WR, // INS_valignq
        (byte)IUM_WR, // INS_vblendmpd
        (byte)IUM_WR, // INS_vblendmps
        (byte)IUM_WR, // INS_vbroadcastf32x2
        (byte)IUM_WR, // INS_vbroadcastf32x8
        (byte)IUM_WR, // INS_vbroadcastf64x2
        (byte)IUM_WR, // INS_vbroadcastf64x4
        (byte)IUM_WR, // INS_vbroadcasti32x2
        (byte)IUM_WR, // INS_vbroadcasti32x8
        (byte)IUM_WR, // INS_vbroadcasti64x2
        (byte)IUM_WR, // INS_vbroadcasti64x4
        (byte)IUM_WR, // INS_vcmppd
        (byte)IUM_WR, // INS_vcmpps
        (byte)IUM_WR, // INS_vcmpsd
        (byte)IUM_WR, // INS_vcmpss
        (byte)IUM_WR, // INS_vcompresspd
        (byte)IUM_WR, // INS_vcompressps
        (byte)IUM_WR, // INS_vcvtpd2qq
        (byte)IUM_WR, // INS_vcvtpd2udq
        (byte)IUM_WR, // INS_vcvtpd2uqq
        (byte)IUM_WR, // INS_vcvtps2qq
        (byte)IUM_WR, // INS_vcvtps2udq
        (byte)IUM_WR, // INS_vcvtps2uqq
        (byte)IUM_WR, // INS_vcvtqq2pd
        (byte)IUM_WR, // INS_vcvtqq2ps
        (byte)IUM_WR, // INS_vcvtsd2usi32
        (byte)IUM_WR, // INS_vcvtsd2usi64
        (byte)IUM_WR, // INS_vcvtss2usi32
        (byte)IUM_WR, // INS_vcvtss2usi64
        (byte)IUM_WR, // INS_vcvttpd2qq
        (byte)IUM_WR, // INS_vcvttpd2udq
        (byte)IUM_WR, // INS_vcvttpd2uqq
        (byte)IUM_WR, // INS_vcvttps2qq
        (byte)IUM_WR, // INS_vcvttps2udq
        (byte)IUM_WR, // INS_vcvttps2uqq
        (byte)IUM_WR, // INS_vcvttsd2usi32
        (byte)IUM_WR, // INS_vcvttsd2usi64
        (byte)IUM_WR, // INS_vcvttss2usi32
        (byte)IUM_WR, // INS_vcvttss2usi64
        (byte)IUM_WR, // INS_vcvtudq2pd
        (byte)IUM_WR, // INS_vcvtudq2ps
        (byte)IUM_WR, // INS_vcvtuqq2pd
        (byte)IUM_WR, // INS_vcvtuqq2ps
        (byte)IUM_WR, // INS_vcvtusi2sd32
        (byte)IUM_WR, // INS_vcvtusi2sd64
        (byte)IUM_WR, // INS_vcvtusi2ss32
        (byte)IUM_WR, // INS_vcvtusi2ss64
        (byte)IUM_WR, // INS_vdbpsadbw
        (byte)IUM_WR, // INS_vexpandpd
        (byte)IUM_WR, // INS_vexpandps
        (byte)IUM_WR, // INS_vextractf32x8
        (byte)IUM_WR, // INS_vextractf64x2
        (byte)IUM_WR, // INS_vextractf64x4
        (byte)IUM_WR, // INS_vextracti32x8
        (byte)IUM_WR, // INS_vextracti64x2
        (byte)IUM_WR, // INS_vextracti64x4
        (byte)IUM_RW, // INS_vfixupimmpd
        (byte)IUM_RW, // INS_vfixupimmps
        (byte)IUM_RW, // INS_vfixupimmsd
        (byte)IUM_RW, // INS_vfixupimmss
        (byte)IUM_WR, // INS_vfpclasspd
        (byte)IUM_WR, // INS_vfpclassps
        (byte)IUM_WR, // INS_vfpclasssd
        (byte)IUM_WR, // INS_vfpclassss
        (byte)IUM_WR, // INS_vgatherdpd_msk
        (byte)IUM_WR, // INS_vgatherdps_msk
        (byte)IUM_WR, // INS_vgatherqpd_msk
        (byte)IUM_WR, // INS_vgatherqps_msk
        (byte)IUM_WR, // INS_vgetexppd
        (byte)IUM_WR, // INS_vgetexpps
        (byte)IUM_WR, // INS_vgetexpsd
        (byte)IUM_WR, // INS_vgetexpss
        (byte)IUM_WR, // INS_vgetmantpd
        (byte)IUM_WR, // INS_vgetmantps
        (byte)IUM_WR, // INS_vgetmantsd
        (byte)IUM_WR, // INS_vgetmantss
        (byte)IUM_WR, // INS_vinsertf32x8
        (byte)IUM_WR, // INS_vinsertf64x2
        (byte)IUM_WR, // INS_vinsertf64x4
        (byte)IUM_WR, // INS_vinserti32x8
        (byte)IUM_WR, // INS_vinserti64x2
        (byte)IUM_WR, // INS_vinserti64x4
        (byte)IUM_WR, // INS_vmovdqa64
        (byte)IUM_WR, // INS_vmovdqu16
        (byte)IUM_WR, // INS_vmovdqu64
        (byte)IUM_WR, // INS_vmovdqu8
        (byte)IUM_WR, // INS_vpabsq
        (byte)IUM_WR, // INS_vpandnq
        (byte)IUM_WR, // INS_vpandq
        (byte)IUM_WR, // INS_vpblendmb
        (byte)IUM_WR, // INS_vpblendmd
        (byte)IUM_WR, // INS_vpblendmq
        (byte)IUM_WR, // INS_vpblendmw
        (byte)IUM_WR, // INS_vpbroadcastb_gpr
        (byte)IUM_WR, // INS_vpbroadcastd_gpr
        (byte)IUM_WR, // INS_vpbroadcastq_gpr
        (byte)IUM_WR, // INS_vpbroadcastw_gpr
        (byte)IUM_WR, // INS_vpcmpb
        (byte)IUM_WR, // INS_vpcmpd
        (byte)IUM_WR, // INS_vpcmpeqb
        (byte)IUM_WR, // INS_vpcmpeqd
        (byte)IUM_WR, // INS_vpcmpeqq
        (byte)IUM_WR, // INS_vpcmpeqw
        (byte)IUM_WR, // INS_vpcmpgtb
        (byte)IUM_WR, // INS_vpcmpgtd
        (byte)IUM_WR, // INS_vpcmpgtq
        (byte)IUM_WR, // INS_vpcmpgtw
        (byte)IUM_WR, // INS_vpcmpq
        (byte)IUM_WR, // INS_vpcmpub
        (byte)IUM_WR, // INS_vpcmpud
        (byte)IUM_WR, // INS_vpcmpuq
        (byte)IUM_WR, // INS_vpcmpuw
        (byte)IUM_WR, // INS_vpcmpw
        (byte)IUM_WR, // INS_vpcompressd
        (byte)IUM_WR, // INS_vpcompressq
        (byte)IUM_WR, // INS_vpconflictd
        (byte)IUM_WR, // INS_vpconflictq
        (byte)IUM_RW, // INS_vpermi2d
        (byte)IUM_RW, // INS_vpermi2pd
        (byte)IUM_RW, // INS_vpermi2ps
        (byte)IUM_RW, // INS_vpermi2q
        (byte)IUM_RW, // INS_vpermi2w
        (byte)IUM_WR, // INS_vpermpd_reg
        (byte)IUM_WR, // INS_vpermq_reg
        (byte)IUM_RW, // INS_vpermt2d
        (byte)IUM_RW, // INS_vpermt2pd
        (byte)IUM_RW, // INS_vpermt2ps
        (byte)IUM_RW, // INS_vpermt2q
        (byte)IUM_RW, // INS_vpermt2w
        (byte)IUM_WR, // INS_vpermw
        (byte)IUM_WR, // INS_vpexpandd
        (byte)IUM_WR, // INS_vpexpandq
        (byte)IUM_WR, // INS_vpgatherdd_msk
        (byte)IUM_WR, // INS_vpgatherdq_msk
        (byte)IUM_WR, // INS_vpgatherqd_msk
        (byte)IUM_WR, // INS_vpgatherqq_msk
        (byte)IUM_WR, // INS_vplzcntd
        (byte)IUM_WR, // INS_vplzcntq
        (byte)IUM_WR, // INS_vpmaxsq
        (byte)IUM_WR, // INS_vpmaxuq
        (byte)IUM_WR, // INS_vpminsq
        (byte)IUM_WR, // INS_vpminuq
        (byte)IUM_WR, // INS_vpmovb2m
        (byte)IUM_WR, // INS_vpmovd2m
        (byte)IUM_WR, // INS_vpmovdb
        (byte)IUM_WR, // INS_vpmovdw
        (byte)IUM_WR, // INS_vpmovm2b
        (byte)IUM_WR, // INS_vpmovm2d
        (byte)IUM_WR, // INS_vpmovm2q
        (byte)IUM_WR, // INS_vpmovm2w
        (byte)IUM_WR, // INS_vpmovq2m
        (byte)IUM_WR, // INS_vpmovqb
        (byte)IUM_WR, // INS_vpmovqd
        (byte)IUM_WR, // INS_vpmovqw
        (byte)IUM_WR, // INS_vpmovsdb
        (byte)IUM_WR, // INS_vpmovsdw
        (byte)IUM_WR, // INS_vpmovsqb
        (byte)IUM_WR, // INS_vpmovsqd
        (byte)IUM_WR, // INS_vpmovsqw
        (byte)IUM_WR, // INS_vpmovswb
        (byte)IUM_WR, // INS_vpmovusdb
        (byte)IUM_WR, // INS_vpmovusdw
        (byte)IUM_WR, // INS_vpmovusqb
        (byte)IUM_WR, // INS_vpmovusqd
        (byte)IUM_WR, // INS_vpmovusqw
        (byte)IUM_WR, // INS_vpmovuswb
        (byte)IUM_WR, // INS_vpmovw2m
        (byte)IUM_WR, // INS_vpmovwb
        (byte)IUM_WR, // INS_vpmullq
        (byte)IUM_WR, // INS_vporq
        (byte)IUM_WR, // INS_vprold
        (byte)IUM_WR, // INS_vprolq
        (byte)IUM_WR, // INS_vprolvd
        (byte)IUM_WR, // INS_vprolvq
        (byte)IUM_WR, // INS_vprord
        (byte)IUM_WR, // INS_vprorq
        (byte)IUM_WR, // INS_vprorvd
        (byte)IUM_WR, // INS_vprorvq
        (byte)IUM_WR, // INS_vpscatterdd_msk
        (byte)IUM_WR, // INS_vpscatterdq_msk
        (byte)IUM_WR, // INS_vpscatterqd_msk
        (byte)IUM_WR, // INS_vpscatterqq_msk
        (byte)IUM_WR, // INS_vpsllvw
        (byte)IUM_WR, // INS_vpsraq
        (byte)IUM_WR, // INS_vpsravq
        (byte)IUM_WR, // INS_vpsravw
        (byte)IUM_WR, // INS_vpsrlvw
        (byte)IUM_RW, // INS_vpternlogd
        (byte)IUM_RW, // INS_vpternlogq
        (byte)IUM_RD, // INS_vptestmb
        (byte)IUM_RD, // INS_vptestmd
        (byte)IUM_RD, // INS_vptestmq
        (byte)IUM_RD, // INS_vptestmw
        (byte)IUM_RD, // INS_vptestnmb
        (byte)IUM_RD, // INS_vptestnmd
        (byte)IUM_RD, // INS_vptestnmq
        (byte)IUM_RD, // INS_vptestnmw
        (byte)IUM_WR, // INS_vpxorq
        (byte)IUM_WR, // INS_vrangepd
        (byte)IUM_WR, // INS_vrangeps
        (byte)IUM_WR, // INS_vrangesd
        (byte)IUM_WR, // INS_vrangess
        (byte)IUM_WR, // INS_vrcp14pd
        (byte)IUM_WR, // INS_vrcp14ps
        (byte)IUM_WR, // INS_vrcp14sd
        (byte)IUM_WR, // INS_vrcp14ss
        (byte)IUM_WR, // INS_vreducepd
        (byte)IUM_WR, // INS_vreduceps
        (byte)IUM_WR, // INS_vreducesd
        (byte)IUM_WR, // INS_vreducess
        (byte)IUM_WR, // INS_vrndscalepd
        (byte)IUM_WR, // INS_vrndscaleps
        (byte)IUM_WR, // INS_vrndscalesd
        (byte)IUM_WR, // INS_vrndscaless
        (byte)IUM_WR, // INS_vrsqrt14pd
        (byte)IUM_WR, // INS_vrsqrt14ps
        (byte)IUM_WR, // INS_vrsqrt14sd
        (byte)IUM_WR, // INS_vrsqrt14ss
        (byte)IUM_WR, // INS_vscalefpd
        (byte)IUM_WR, // INS_vscalefps
        (byte)IUM_WR, // INS_vscalefsd
        (byte)IUM_WR, // INS_vscalefss
        (byte)IUM_WR, // INS_vscatterdpd_msk
        (byte)IUM_WR, // INS_vscatterdps_msk
        (byte)IUM_WR, // INS_vscatterqpd_msk
        (byte)IUM_WR, // INS_vscatterqps_msk
        (byte)IUM_WR, // INS_vshuff32x4
        (byte)IUM_WR, // INS_vshuff64x2
        (byte)IUM_WR, // INS_vshufi32x4
        (byte)IUM_WR, // INS_vshufi64x2
        (byte)IUM_WR, // INS_vpermb
        (byte)IUM_RW, // INS_vpermi2b
        (byte)IUM_RW, // INS_vpermt2b
        (byte)IUM_WR, // INS_vpmultishiftqb
        (byte)IUM_WR, // INS_vpcompressb
        (byte)IUM_WR, // INS_vpcompressw
        (byte)IUM_WR, // INS_vpexpandb
        (byte)IUM_WR, // INS_vpexpandw
        (byte)IUM_WR, // INS_vpopcntb
        (byte)IUM_WR, // INS_vpopcntd
        (byte)IUM_WR, // INS_vpopcntq
        (byte)IUM_WR, // INS_vpopcntw
        (byte)IUM_WR, // INS_vpshldd
        (byte)IUM_WR, // INS_vpshldq
        (byte)IUM_WR, // INS_vpshldvd
        (byte)IUM_WR, // INS_vpshldvq
        (byte)IUM_WR, // INS_vpshldvw
        (byte)IUM_WR, // INS_vpshldw
        (byte)IUM_WR, // INS_vpshrdd
        (byte)IUM_WR, // INS_vpshrdq
        (byte)IUM_WR, // INS_vpshrdvd
        (byte)IUM_WR, // INS_vpshrdvq
        (byte)IUM_WR, // INS_vpshrdvw
        (byte)IUM_WR, // INS_vpshrdw
        (byte)IUM_WR, // INS_vpshufbitqmb
        (byte)IUM_WR, // INS_vaddph
        (byte)IUM_WR, // INS_vaddsh
        (byte)IUM_WR, // INS_vcmpph
        (byte)IUM_WR, // INS_vcmpsh
        (byte)IUM_RD, // INS_vcomish
        (byte)IUM_WR, // INS_vcvtdq2ph
        (byte)IUM_WR, // INS_vcvtne2ps2bf16
        (byte)IUM_WR, // INS_vcvtneps2bf16
        (byte)IUM_WR, // INS_vcvtpd2ph
        (byte)IUM_WR, // INS_vcvtph2dq
        (byte)IUM_WR, // INS_vcvtph2pd
        (byte)IUM_WR, // INS_vcvtph2psx
        (byte)IUM_WR, // INS_vcvtph2qq
        (byte)IUM_WR, // INS_vcvtph2udq
        (byte)IUM_WR, // INS_vcvtph2uqq
        (byte)IUM_WR, // INS_vcvtph2uw
        (byte)IUM_WR, // INS_vcvtph2w
        (byte)IUM_WR, // INS_vcvtps2phx
        (byte)IUM_WR, // INS_vcvtqq2ph
        (byte)IUM_WR, // INS_vcvtsd2sh
        (byte)IUM_WR, // INS_vcvtsh2sd
        (byte)IUM_WR, // INS_vcvtsh2si32
        (byte)IUM_WR, // INS_vcvtsh2si64
        (byte)IUM_WR, // INS_vcvtsh2ss
        (byte)IUM_WR, // INS_vcvtsh2usi32
        (byte)IUM_WR, // INS_vcvtsh2usi64
        (byte)IUM_WR, // INS_vcvtsi2sh32
        (byte)IUM_WR, // INS_vcvtsi2sh64
        (byte)IUM_WR, // INS_vcvtss2sh
        (byte)IUM_WR, // INS_vcvttph2dq
        (byte)IUM_WR, // INS_vcvttph2qq
        (byte)IUM_WR, // INS_vcvttph2udq
        (byte)IUM_WR, // INS_vcvttph2uqq
        (byte)IUM_WR, // INS_vcvttph2uw
        (byte)IUM_WR, // INS_vcvttph2w
        (byte)IUM_WR, // INS_vcvttsh2si32
        (byte)IUM_WR, // INS_vcvttsh2si64
        (byte)IUM_WR, // INS_vcvttsh2usi32
        (byte)IUM_WR, // INS_vcvttsh2usi64
        (byte)IUM_WR, // INS_vcvtudq2ph
        (byte)IUM_WR, // INS_vcvtuqq2ph
        (byte)IUM_WR, // INS_vcvtusi2sh32
        (byte)IUM_WR, // INS_vcvtusi2sh64
        (byte)IUM_WR, // INS_vcvtuw2ph
        (byte)IUM_WR, // INS_vcvtw2ph
        (byte)IUM_WR, // INS_vdivph
        (byte)IUM_WR, // INS_vdivsh
        (byte)IUM_WR, // INS_vdpbf16ps
        (byte)IUM_RW, // INS_vfcmaddcph
        (byte)IUM_RW, // INS_vfcmaddcsh
        (byte)IUM_WR, // INS_vfcmulcph
        (byte)IUM_WR, // INS_vfcmulcsh
        (byte)IUM_WR, // INS_vfmulcph
        (byte)IUM_WR, // INS_vfmulcsh
        (byte)IUM_RW, // INS_vfmadd132ph
        (byte)IUM_RW, // INS_vfmadd213ph
        (byte)IUM_RW, // INS_vfmadd231ph
        (byte)IUM_RW, // INS_vfmadd132sh
        (byte)IUM_RW, // INS_vfmadd213sh
        (byte)IUM_RW, // INS_vfmadd231sh
        (byte)IUM_RW, // INS_vfmaddcph
        (byte)IUM_RW, // INS_vfmaddcsh
        (byte)IUM_RW, // INS_vfmaddsub132ph
        (byte)IUM_RW, // INS_vfmaddsub213ph
        (byte)IUM_RW, // INS_vfmaddsub231ph
        (byte)IUM_RW, // INS_vfmsub132ph
        (byte)IUM_RW, // INS_vfmsub213ph
        (byte)IUM_RW, // INS_vfmsub231ph
        (byte)IUM_RW, // INS_vfmsub132sh
        (byte)IUM_RW, // INS_vfmsub213sh
        (byte)IUM_RW, // INS_vfmsub231sh
        (byte)IUM_RW, // INS_vfmsubadd132ph
        (byte)IUM_RW, // INS_vfmsubadd213ph
        (byte)IUM_RW, // INS_vfmsubadd231ph
        (byte)IUM_RW, // INS_vfnmadd132ph
        (byte)IUM_RW, // INS_vfnmadd213ph
        (byte)IUM_RW, // INS_vfnmadd231ph
        (byte)IUM_RW, // INS_vfnmadd132sh
        (byte)IUM_RW, // INS_vfnmadd213sh
        (byte)IUM_RW, // INS_vfnmadd231sh
        (byte)IUM_RW, // INS_vfnmsub132ph
        (byte)IUM_RW, // INS_vfnmsub213ph
        (byte)IUM_RW, // INS_vfnmsub231ph
        (byte)IUM_RW, // INS_vfnmsub132sh
        (byte)IUM_RW, // INS_vfnmsub213sh
        (byte)IUM_RW, // INS_vfnmsub231sh
        (byte)IUM_WR, // INS_vfpclassph
        (byte)IUM_WR, // INS_vfpclasssh
        (byte)IUM_WR, // INS_vgetexpph
        (byte)IUM_WR, // INS_vgetexpsh
        (byte)IUM_WR, // INS_vgetmantph
        (byte)IUM_WR, // INS_vgetmantsh
        (byte)IUM_WR, // INS_vmaxph
        (byte)IUM_WR, // INS_vmaxsh
        (byte)IUM_WR, // INS_vminsh
        (byte)IUM_WR, // INS_vminph
        (byte)IUM_WR, // INS_vmovsh
        (byte)IUM_WR, // INS_vmovw
        (byte)IUM_WR, // INS_vmulph
        (byte)IUM_WR, // INS_vmulsh
        (byte)IUM_WR, // INS_vrcpph
        (byte)IUM_WR, // INS_vrcpsh
        (byte)IUM_WR, // INS_vreduceph
        (byte)IUM_WR, // INS_vreducesh
        (byte)IUM_WR, // INS_vrndscaleph
        (byte)IUM_WR, // INS_vrndscalesh
        (byte)IUM_WR, // INS_vrsqrtph
        (byte)IUM_WR, // INS_vrsqrtsh
        (byte)IUM_WR, // INS_vscalefph
        (byte)IUM_WR, // INS_vscalefsh
        (byte)IUM_WR, // INS_vsqrtph
        (byte)IUM_WR, // INS_vsqrtsh
        (byte)IUM_WR, // INS_vsubph
        (byte)IUM_WR, // INS_vsubsh
        (byte)IUM_RD, // INS_vucomish
        (byte)IUM_WR, // INS_vp2intersectd
        (byte)IUM_WR, // INS_vp2intersectq
        (byte)IUM_RD, // INS_vcomxsd
        (byte)IUM_RD, // INS_vcomxss
        (byte)IUM_WR, // INS_vcvtps2ibs
        (byte)IUM_WR, // INS_vcvtps2iubs
        (byte)IUM_WR, // INS_vcvttpd2dqs
        (byte)IUM_WR, // INS_vcvttpd2qqs
        (byte)IUM_WR, // INS_vcvttpd2udqs
        (byte)IUM_WR, // INS_vcvttpd2uqqs
        (byte)IUM_WR, // INS_vcvttps2dqs
        (byte)IUM_WR, // INS_vcvttps2ibs
        (byte)IUM_WR, // INS_vcvttps2iubs
        (byte)IUM_WR, // INS_vcvttps2qqs
        (byte)IUM_WR, // INS_vcvttps2udqs
        (byte)IUM_WR, // INS_vcvttps2uqqs
        (byte)IUM_WR, // INS_vcvttsd2sis32
        (byte)IUM_WR, // INS_vcvttsd2sis64
        (byte)IUM_WR, // INS_vcvttsd2usis32
        (byte)IUM_WR, // INS_vcvttsd2usis64
        (byte)IUM_WR, // INS_vcvttss2sis32
        (byte)IUM_WR, // INS_vcvttss2sis64
        (byte)IUM_WR, // INS_vcvttss2usis32
        (byte)IUM_WR, // INS_vcvttss2usis64
        (byte)IUM_WR, // INS_vminmaxpd
        (byte)IUM_WR, // INS_vminmaxps
        (byte)IUM_WR, // INS_vminmaxsd
        (byte)IUM_WR, // INS_vminmaxss
        (byte)IUM_WR, // INS_vmovd_simd
        (byte)IUM_WR, // INS_vmovw_simd
        (byte)IUM_WR, // INS_vmpsadbw
        (byte)IUM_RD, // INS_vucomxsd
        (byte)IUM_RD, // INS_vucomxss
#if TARGET_AMD64
        (byte)IUM_RD, // INS_ccmpo
        (byte)IUM_RD, // INS_ccmpno
        (byte)IUM_RD, // INS_ccmpb
        (byte)IUM_RD, // INS_ccmpae
        (byte)IUM_RD, // INS_ccmpe
        (byte)IUM_RD, // INS_ccmpne
        (byte)IUM_RD, // INS_ccmpbe
        (byte)IUM_RD, // INS_ccmpa
        (byte)IUM_RD, // INS_ccmps
        (byte)IUM_RD, // INS_ccmpns
        (byte)IUM_RD, // INS_ccmpt
        (byte)IUM_RD, // INS_ccmpf
        (byte)IUM_RD, // INS_ccmpl
        (byte)IUM_RD, // INS_ccmpge
        (byte)IUM_RD, // INS_ccmple
        (byte)IUM_RD, // INS_ccmpg
        (byte)IUM_WR, // INS_cfcmovo
        (byte)IUM_WR, // INS_cfcmovno
        (byte)IUM_WR, // INS_cfcmovb
        (byte)IUM_WR, // INS_cfcmovae
        (byte)IUM_WR, // INS_cfcmove
        (byte)IUM_WR, // INS_cfcmovne
        (byte)IUM_WR, // INS_cfcmovbe
        (byte)IUM_WR, // INS_cfcmova
        (byte)IUM_WR, // INS_cfcmovs
        (byte)IUM_WR, // INS_cfcmovns
        (byte)IUM_WR, // INS_cfcmovp
        (byte)IUM_WR, // INS_cfcmovnp
        (byte)IUM_WR, // INS_cfcmovl
        (byte)IUM_WR, // INS_cfcmovge
        (byte)IUM_WR, // INS_cfcmovle
        (byte)IUM_WR, // INS_cfcmovg
        (byte)IUM_RD, // INS_ctesto
        (byte)IUM_RD, // INS_ctestno
        (byte)IUM_RD, // INS_ctestb
        (byte)IUM_RD, // INS_ctestae
        (byte)IUM_RD, // INS_cteste
        (byte)IUM_RD, // INS_ctestne
        (byte)IUM_RD, // INS_ctestbe
        (byte)IUM_RD, // INS_ctesta
        (byte)IUM_RD, // INS_ctests
        (byte)IUM_RD, // INS_ctestns
        (byte)IUM_RD, // INS_ctestt
        (byte)IUM_RD, // INS_ctestf
        (byte)IUM_RD, // INS_ctestl
        (byte)IUM_RD, // INS_ctestge
        (byte)IUM_RD, // INS_ctestle
        (byte)IUM_RD, // INS_ctestg
        (byte)IUM_RW, // INS_crc32_apx
        (byte)IUM_WR, // INS_movbe_apx
        (byte)IUM_WR, // INS_seto_apx
        (byte)IUM_WR, // INS_setno_apx
        (byte)IUM_WR, // INS_setb_apx
        (byte)IUM_WR, // INS_setae_apx
        (byte)IUM_WR, // INS_sete_apx
        (byte)IUM_WR, // INS_setne_apx
        (byte)IUM_WR, // INS_setbe_apx
        (byte)IUM_WR, // INS_seta_apx
        (byte)IUM_WR, // INS_sets_apx
        (byte)IUM_WR, // INS_setns_apx
        (byte)IUM_WR, // INS_setp_apx
        (byte)IUM_WR, // INS_setnp_apx
        (byte)IUM_WR, // INS_setl_apx
        (byte)IUM_WR, // INS_setge_apx
        (byte)IUM_WR, // INS_setle_apx
        (byte)IUM_WR, // INS_setg_apx
#endif
        (byte)IUM_RW, // INS_crc32
        (byte)IUM_WR, // INS_tzcnt
#if TARGET_AMD64
        (byte)IUM_WR, // INS_tzcnt_apx
#endif
        (byte)IUM_WR, // INS_lzcnt
#if TARGET_AMD64
        (byte)IUM_WR, // INS_lzcnt_apx
#endif
        (byte)IUM_WR, // INS_movbe
        (byte)IUM_WR, // INS_popcnt
#if TARGET_AMD64
        (byte)IUM_WR, // INS_popcnt_apx
#endif
        (byte)IUM_RD, // INS_tpause
        (byte)IUM_RD, // INS_umonitor
        (byte)IUM_RD, // INS_umwait
        (byte)IUM_RW, // INS_neg
        (byte)IUM_RW, // INS_not
        (byte)IUM_RW, // INS_rol
        (byte)IUM_RW, // INS_rol_1
        (byte)IUM_RW, // INS_rol_N
        (byte)IUM_RW, // INS_ror
        (byte)IUM_RW, // INS_ror_1
        (byte)IUM_RW, // INS_ror_N
        (byte)IUM_RW, // INS_rcl
        (byte)IUM_RW, // INS_rcl_1
        (byte)IUM_RW, // INS_rcl_N
        (byte)IUM_RW, // INS_rcr
        (byte)IUM_RW, // INS_rcr_1
        (byte)IUM_RW, // INS_rcr_N
        (byte)IUM_RW, // INS_shl
        (byte)IUM_RW, // INS_shl_1
        (byte)IUM_RW, // INS_shl_N
        (byte)IUM_RW, // INS_shr
        (byte)IUM_RW, // INS_shr_1
        (byte)IUM_RW, // INS_shr_N
        (byte)IUM_RW, // INS_sar
        (byte)IUM_RW, // INS_sar_1
        (byte)IUM_RW, // INS_sar_N
        (byte)IUM_RD, // INS_ret
        (byte)IUM_RD, // INS_loop
        (byte)IUM_RD, // INS_call
        (byte)IUM_RD, // INS_r_movsb
        (byte)IUM_RD, // INS_r_movsd
#if TARGET_AMD64
        (byte)IUM_RD, // INS_r_movsq
#endif
        (byte)IUM_RD, // INS_movsb
        (byte)IUM_RD, // INS_movsd
#if TARGET_AMD64
        (byte)IUM_RD, // INS_movsq
#endif
        (byte)IUM_RD, // INS_r_stosb
        (byte)IUM_RD, // INS_r_stosd
#if TARGET_AMD64
        (byte)IUM_RD, // INS_r_stosq
#endif
        (byte)IUM_RD, // INS_stosb
        (byte)IUM_RD, // INS_stosd
#if TARGET_AMD64
        (byte)IUM_RD, // INS_stosq
#endif
        (byte)IUM_RD, // INS_int3
        (byte)IUM_RD, // INS_nop
        (byte)IUM_RD, // INS_pause
        (byte)IUM_RD, // INS_lock
        (byte)IUM_RD, // INS_leave
        (byte)IUM_RD, // INS_serialize
        (byte)IUM_RD, // INS_cwde
        (byte)IUM_RD, // INS_cdq
        (byte)IUM_RD, // INS_idiv
        (byte)IUM_RD, // INS_imulEAX
        (byte)IUM_RD, // INS_div
        (byte)IUM_RD, // INS_mulEAX
        (byte)IUM_RD, // INS_sahf
        (byte)IUM_RW, // INS_xadd
        (byte)IUM_RW, // INS_cmpxchg
        (byte)IUM_RW, // INS_shld
        (byte)IUM_RW, // INS_shrd
#if TARGET_X86
        (byte)IUM_WR, // INS_fld
        (byte)IUM_WR, // INS_fstp
#endif
        (byte)IUM_WR, // INS_seto
        (byte)IUM_WR, // INS_setno
        (byte)IUM_WR, // INS_setb
        (byte)IUM_WR, // INS_setae
        (byte)IUM_WR, // INS_sete
        (byte)IUM_WR, // INS_setne
        (byte)IUM_WR, // INS_setbe
        (byte)IUM_WR, // INS_seta
        (byte)IUM_WR, // INS_sets
        (byte)IUM_WR, // INS_setns
        (byte)IUM_WR, // INS_setp
        (byte)IUM_WR, // INS_setnp
        (byte)IUM_WR, // INS_setl
        (byte)IUM_WR, // INS_setge
        (byte)IUM_WR, // INS_setle
        (byte)IUM_WR, // INS_setg
        (byte)IUM_RD, // INS_tail_i_jmp
        (byte)IUM_RD, // INS_i_jmp
        (byte)IUM_RD, // INS_jmp
        (byte)IUM_RD, // INS_jo
        (byte)IUM_RD, // INS_jno
        (byte)IUM_RD, // INS_jb
        (byte)IUM_RD, // INS_jae
        (byte)IUM_RD, // INS_je
        (byte)IUM_RD, // INS_jne
        (byte)IUM_RD, // INS_jbe
        (byte)IUM_RD, // INS_ja
        (byte)IUM_RD, // INS_js
        (byte)IUM_RD, // INS_jns
        (byte)IUM_RD, // INS_jp
        (byte)IUM_RD, // INS_jnp
        (byte)IUM_RD, // INS_jl
        (byte)IUM_RD, // INS_jge
        (byte)IUM_RD, // INS_jle
        (byte)IUM_RD, // INS_jg
        (byte)IUM_RD, // INS_l_jmp
        (byte)IUM_RD, // INS_l_jo
        (byte)IUM_RD, // INS_l_jno
        (byte)IUM_RD, // INS_l_jb
        (byte)IUM_RD, // INS_l_jae
        (byte)IUM_RD, // INS_l_je
        (byte)IUM_RD, // INS_l_jne
        (byte)IUM_RD, // INS_l_jbe
        (byte)IUM_RD, // INS_l_ja
        (byte)IUM_RD, // INS_l_js
        (byte)IUM_RD, // INS_l_jns
        (byte)IUM_RD, // INS_l_jp
        (byte)IUM_RD, // INS_l_jnp
        (byte)IUM_RD, // INS_l_jl
        (byte)IUM_RD, // INS_l_jge
        (byte)IUM_RD, // INS_l_jle
        (byte)IUM_RD, // INS_l_jg
        (byte)IUM_RD, // INS_align
        (byte)IUM_RD, // INS_data16
#elif TARGET_ARM
#if !TARGET_ARM
#error Unexpected target type
#endif
#if FEATURE_PLI_INSTRUCTION
#endif
#if FEATURE_ITINSTRUCTION
#endif
#elif TARGET_ARM64
#if !TARGET_ARM64
#error Unexpected target type
#endif
#if FEATURE_LOOP_ALIGN
#endif
#if !TARGET_ARM64
#error Unexpected target type
#endif
#elif TARGET_LOONGARCH64
#if !TARGET_LOONGARCH64
#error Unexpected target type
#endif
#if FEATURE_SIMD
#endif
#elif TARGET_RISCV64
#if !TARGET_RISCV64
#error Unexpected target type
#endif
#elif TARGET_WASM
#if !TARGET_WASM
#error Unexpected target type
#endif
#else
#error Unsupported or unset target architecture
#endif

    ];
#endif
}