// Copyright (c) Tanner Gooding and Contributors. Licensed under the MIT License (MIT). See License.md in the repository root for more information.
//
// Based on the RyuJIT compiler from dotnet/runtime.
// Original source is Copyright (c) .NET Foundation and Contributors. Licensed under the MIT License (MIT).

namespace RyuJitSharp;

// Memory-kind ordinals index the matching names and allocation statistics.
internal enum CompMemKind
{
    CMK_ABI,
    CMK_AssertionProp,
    CMK_ASTNode,
    CMK_InstDesc,
    CMK_ImpStack,
    CMK_BasicBlock,
    CMK_CallArgs,
    CMK_FlowEdge,
    CMK_DepthFirstSearch,
    CMK_Loops,
    CMK_TreeStatementList,
    CMK_SiScope,
    CMK_DominatorMemory,
    CMK_Lower,
    CMK_LSRA,
    CMK_LSRA_Interval,
    CMK_LSRA_RefPosition,
    CMK_Reachability,
    CMK_RedundantBranch,
    CMK_SSA,
    CMK_ValueNumber,
    CMK_LvaTable,
    CMK_UnwindInfo,
    CMK_hashBv,
    CMK_bitset,
    CMK_FixedBitVect,
    CMK_Generic,
    CMK_LocalAddressVisitor,
    CMK_FieldSeqStore,
    CMK_MemorySsaMap,
    CMK_MemoryPhiArg,
    CMK_CSE,
    CMK_GC,
    CMK_CorTailCallInfo,
    CMK_Inlining,
    CMK_ArrayStack,
    CMK_DebugInfo,
    CMK_DebugOnly,
    CMK_Codegen,
    CMK_LoopOpt,
    CMK_LoopClone,
    CMK_LoopUnroll,
    CMK_LoopHoist,
    CMK_LoopIVOpts,
    CMK_Unknown,
    CMK_RangeCheck,
    CMK_CopyProp,
    CMK_Promotion,
    CMK_SideEffects,
    CMK_ObjectAllocator,
    CMK_VariableLiveRanges,
    CMK_ClassLayout,
    CMK_EarlyProp,
    CMK_ZeroInit,
    CMK_Pgo,
    CMK_MaskConversionOpt,
    CMK_TryRegionClone,
    CMK_Async,
    CMK_RangeCheckCloning,
    CMK_WasmSccTransform,
    CMK_WasmCfgLowering,
    CMK_WasmEH,
    CMK_WasmSpillRefs,
    CMK_Count,
}
