// Copyright © Tanner Gooding and Contributors. Licensed under the MIT License (MIT). See License.md in the repository root for more information.
//
// Based on the RyuJIT compiler from dotnet/runtime.
// Original source is Copyright (c) .NET Foundation and Contributors. Licensed under the MIT License (MIT).

using System;

namespace RyuJitSharp;

public static class OPCODEExtensions
{
    private const byte InlineNone_size = 0;
    private const byte ShortInlineVar_size = 1;
    private const byte InlineVar_size = 2;
    private const byte ShortInlineI_size = 1;
    private const byte InlineI_size = 4;
    private const byte InlineI8_size = 8;
    private const byte ShortInlineR_size = 4;
    private const byte InlineR_size = 8;
    private const byte ShortInlineBrTarget_size = 1;
    private const byte InlineBrTarget_size = 4;
    private const byte InlineMethod_size = 4;
    private const byte InlineField_size = 4;
    private const byte InlineType_size = 4;
    private const byte InlineString_size = 4;
    private const byte InlineSig_size = 4;
    private const byte InlineRVA_size = 4;
    private const byte InlineTok_size = 4;
    private const byte InlineSwitch_size = 0;   // for now
    private const byte InlinePhi_size = 0;      // for now
    private const byte InlineVarTok_size = 0;   // remove

#if DEBUG
    private static ReadOnlySpan<OPCODE_FORMAT> s_argKinds => [
        InlineNone,                 // CEE_NOP
        InlineNone,                 // CEE_BREAK
        InlineNone,                 // CEE_LDARG_0
        InlineNone,                 // CEE_LDARG_1
        InlineNone,                 // CEE_LDARG_2
        InlineNone,                 // CEE_LDARG_3
        InlineNone,                 // CEE_LDLOC_0
        InlineNone,                 // CEE_LDLOC_1
        InlineNone,                 // CEE_LDLOC_2
        InlineNone,                 // CEE_LDLOC_3
        InlineNone,                 // CEE_STLOC_0
        InlineNone,                 // CEE_STLOC_1
        InlineNone,                 // CEE_STLOC_2
        InlineNone,                 // CEE_STLOC_3
        ShortInlineVar,             // CEE_LDARG_S
        ShortInlineVar,             // CEE_LDARGA_S
        ShortInlineVar,             // CEE_STARG_S
        ShortInlineVar,             // CEE_LDLOC_S
        ShortInlineVar,             // CEE_LDLOCA_S
        ShortInlineVar,             // CEE_STLOC_S
        InlineNone,                 // CEE_LDNULL
        InlineNone,                 // CEE_LDC_I4_M1
        InlineNone,                 // CEE_LDC_I4_0
        InlineNone,                 // CEE_LDC_I4_1
        InlineNone,                 // CEE_LDC_I4_2
        InlineNone,                 // CEE_LDC_I4_3
        InlineNone,                 // CEE_LDC_I4_4
        InlineNone,                 // CEE_LDC_I4_5
        InlineNone,                 // CEE_LDC_I4_6
        InlineNone,                 // CEE_LDC_I4_7
        InlineNone,                 // CEE_LDC_I4_8
        ShortInlineI,               // CEE_LDC_I4_S
        InlineI,                    // CEE_LDC_I4
        InlineI8,                   // CEE_LDC_I8
        ShortInlineR,               // CEE_LDC_R4
        InlineR,                    // CEE_LDC_R8
        InlineNone,                 // CEE_UNUSED49
        InlineNone,                 // CEE_DUP
        InlineNone,                 // CEE_POP
        InlineMethod,               // CEE_JMP
        InlineMethod,               // CEE_CALL
        InlineSig,                  // CEE_CALLI
        InlineNone,                 // CEE_RET
        ShortInlineBrTarget,        // CEE_BR_S
        ShortInlineBrTarget,        // CEE_BRFALSE_S
        ShortInlineBrTarget,        // CEE_BRTRUE_S
        ShortInlineBrTarget,        // CEE_BEQ_S
        ShortInlineBrTarget,        // CEE_BGE_S
        ShortInlineBrTarget,        // CEE_BGT_S
        ShortInlineBrTarget,        // CEE_BLE_S
        ShortInlineBrTarget,        // CEE_BLT_S
        ShortInlineBrTarget,        // CEE_BNE_UN_S
        ShortInlineBrTarget,        // CEE_BGE_UN_S
        ShortInlineBrTarget,        // CEE_BGT_UN_S
        ShortInlineBrTarget,        // CEE_BLE_UN_S
        ShortInlineBrTarget,        // CEE_BLT_UN_S
        InlineBrTarget,             // CEE_BR
        InlineBrTarget,             // CEE_BRFALSE
        InlineBrTarget,             // CEE_BRTRUE
        InlineBrTarget,             // CEE_BEQ
        InlineBrTarget,             // CEE_BGE
        InlineBrTarget,             // CEE_BGT
        InlineBrTarget,             // CEE_BLE
        InlineBrTarget,             // CEE_BLT
        InlineBrTarget,             // CEE_BNE_UN
        InlineBrTarget,             // CEE_BGE_UN
        InlineBrTarget,             // CEE_BGT_UN
        InlineBrTarget,             // CEE_BLE_UN
        InlineBrTarget,             // CEE_BLT_UN
        InlineSwitch,               // CEE_SWITCH
        InlineNone,                 // CEE_LDIND_I1
        InlineNone,                 // CEE_LDIND_U1
        InlineNone,                 // CEE_LDIND_I2
        InlineNone,                 // CEE_LDIND_U2
        InlineNone,                 // CEE_LDIND_I4
        InlineNone,                 // CEE_LDIND_U4
        InlineNone,                 // CEE_LDIND_I8
        InlineNone,                 // CEE_LDIND_I
        InlineNone,                 // CEE_LDIND_R4
        InlineNone,                 // CEE_LDIND_R8
        InlineNone,                 // CEE_LDIND_REF
        InlineNone,                 // CEE_STIND_REF
        InlineNone,                 // CEE_STIND_I1
        InlineNone,                 // CEE_STIND_I2
        InlineNone,                 // CEE_STIND_I4
        InlineNone,                 // CEE_STIND_I8
        InlineNone,                 // CEE_STIND_R4
        InlineNone,                 // CEE_STIND_R8
        InlineNone,                 // CEE_ADD
        InlineNone,                 // CEE_SUB
        InlineNone,                 // CEE_MUL
        InlineNone,                 // CEE_DIV
        InlineNone,                 // CEE_DIV_UN
        InlineNone,                 // CEE_REM
        InlineNone,                 // CEE_REM_UN
        InlineNone,                 // CEE_AND
        InlineNone,                 // CEE_OR
        InlineNone,                 // CEE_XOR
        InlineNone,                 // CEE_SHL
        InlineNone,                 // CEE_SHR
        InlineNone,                 // CEE_SHR_UN
        InlineNone,                 // CEE_NEG
        InlineNone,                 // CEE_NOT
        InlineNone,                 // CEE_CONV_I1
        InlineNone,                 // CEE_CONV_I2
        InlineNone,                 // CEE_CONV_I4
        InlineNone,                 // CEE_CONV_I8
        InlineNone,                 // CEE_CONV_R4
        InlineNone,                 // CEE_CONV_R8
        InlineNone,                 // CEE_CONV_U4
        InlineNone,                 // CEE_CONV_U8
        InlineMethod,               // CEE_CALLVIRT
        InlineType,                 // CEE_CPOBJ
        InlineType,                 // CEE_LDOBJ
        InlineString,               // CEE_LDSTR
        InlineMethod,               // CEE_NEWOBJ
        InlineType,                 // CEE_CASTCLASS
        InlineType,                 // CEE_ISINST
        InlineNone,                 // CEE_CONV_R_UN
        InlineNone,                 // CEE_UNUSED58
        InlineNone,                 // CEE_UNUSED1
        InlineType,                 // CEE_UNBOX
        InlineNone,                 // CEE_THROW
        InlineField,                // CEE_LDFLD
        InlineField,                // CEE_LDFLDA
        InlineField,                // CEE_STFLD
        InlineField,                // CEE_LDSFLD
        InlineField,                // CEE_LDSFLDA
        InlineField,                // CEE_STSFLD
        InlineType,                 // CEE_STOBJ
        InlineNone,                 // CEE_CONV_OVF_I1_UN
        InlineNone,                 // CEE_CONV_OVF_I2_UN
        InlineNone,                 // CEE_CONV_OVF_I4_UN
        InlineNone,                 // CEE_CONV_OVF_I8_UN
        InlineNone,                 // CEE_CONV_OVF_U1_UN
        InlineNone,                 // CEE_CONV_OVF_U2_UN
        InlineNone,                 // CEE_CONV_OVF_U4_UN
        InlineNone,                 // CEE_CONV_OVF_U8_UN
        InlineNone,                 // CEE_CONV_OVF_I_UN
        InlineNone,                 // CEE_CONV_OVF_U_UN
        InlineType,                 // CEE_BOX
        InlineType,                 // CEE_NEWARR
        InlineNone,                 // CEE_LDLEN
        InlineType,                 // CEE_LDELEMA
        InlineNone,                 // CEE_LDELEM_I1
        InlineNone,                 // CEE_LDELEM_U1
        InlineNone,                 // CEE_LDELEM_I2
        InlineNone,                 // CEE_LDELEM_U2
        InlineNone,                 // CEE_LDELEM_I4
        InlineNone,                 // CEE_LDELEM_U4
        InlineNone,                 // CEE_LDELEM_I8
        InlineNone,                 // CEE_LDELEM_I
        InlineNone,                 // CEE_LDELEM_R4
        InlineNone,                 // CEE_LDELEM_R8
        InlineNone,                 // CEE_LDELEM_REF
        InlineNone,                 // CEE_STELEM_I
        InlineNone,                 // CEE_STELEM_I1
        InlineNone,                 // CEE_STELEM_I2
        InlineNone,                 // CEE_STELEM_I4
        InlineNone,                 // CEE_STELEM_I8
        InlineNone,                 // CEE_STELEM_R4
        InlineNone,                 // CEE_STELEM_R8
        InlineNone,                 // CEE_STELEM_REF
        InlineType,                 // CEE_LDELEM
        InlineType,                 // CEE_STELEM
        InlineType,                 // CEE_UNBOX_ANY
        InlineNone,                 // CEE_UNUSED5
        InlineNone,                 // CEE_UNUSED6
        InlineNone,                 // CEE_UNUSED7
        InlineNone,                 // CEE_UNUSED8
        InlineNone,                 // CEE_UNUSED9
        InlineNone,                 // CEE_UNUSED10
        InlineNone,                 // CEE_UNUSED11
        InlineNone,                 // CEE_UNUSED12
        InlineNone,                 // CEE_UNUSED13
        InlineNone,                 // CEE_UNUSED14
        InlineNone,                 // CEE_UNUSED15
        InlineNone,                 // CEE_UNUSED16
        InlineNone,                 // CEE_UNUSED17
        InlineNone,                 // CEE_CONV_OVF_I1
        InlineNone,                 // CEE_CONV_OVF_U1
        InlineNone,                 // CEE_CONV_OVF_I2
        InlineNone,                 // CEE_CONV_OVF_U2
        InlineNone,                 // CEE_CONV_OVF_I4
        InlineNone,                 // CEE_CONV_OVF_U4
        InlineNone,                 // CEE_CONV_OVF_I8
        InlineNone,                 // CEE_CONV_OVF_U8
        InlineNone,                 // CEE_UNUSED50
        InlineNone,                 // CEE_UNUSED18
        InlineNone,                 // CEE_UNUSED19
        InlineNone,                 // CEE_UNUSED20
        InlineNone,                 // CEE_UNUSED21
        InlineNone,                 // CEE_UNUSED22
        InlineNone,                 // CEE_UNUSED23
        InlineType,                 // CEE_REFANYVAL
        InlineNone,                 // CEE_CKFINITE
        InlineNone,                 // CEE_UNUSED24
        InlineNone,                 // CEE_UNUSED25
        InlineType,                 // CEE_MKREFANY
        InlineNone,                 // CEE_UNUSED59
        InlineNone,                 // CEE_UNUSED60
        InlineNone,                 // CEE_UNUSED61
        InlineNone,                 // CEE_UNUSED62
        InlineNone,                 // CEE_UNUSED63
        InlineNone,                 // CEE_UNUSED64
        InlineNone,                 // CEE_UNUSED65
        InlineNone,                 // CEE_UNUSED66
        InlineNone,                 // CEE_UNUSED67
        InlineTok,                  // CEE_LDTOKEN
        InlineNone,                 // CEE_CONV_U2
        InlineNone,                 // CEE_CONV_U1
        InlineNone,                 // CEE_CONV_I
        InlineNone,                 // CEE_CONV_OVF_I
        InlineNone,                 // CEE_CONV_OVF_U
        InlineNone,                 // CEE_ADD_OVF
        InlineNone,                 // CEE_ADD_OVF_UN
        InlineNone,                 // CEE_MUL_OVF
        InlineNone,                 // CEE_MUL_OVF_UN
        InlineNone,                 // CEE_SUB_OVF
        InlineNone,                 // CEE_SUB_OVF_UN
        InlineNone,                 // CEE_ENDFINALLY
        InlineBrTarget,             // CEE_LEAVE
        ShortInlineBrTarget,        // CEE_LEAVE_S
        InlineNone,                 // CEE_STIND_I
        InlineNone,                 // CEE_CONV_U
        InlineNone,                 // CEE_UNUSED26
        InlineNone,                 // CEE_UNUSED27
        InlineNone,                 // CEE_UNUSED28
        InlineNone,                 // CEE_UNUSED29
        InlineNone,                 // CEE_UNUSED30
        InlineNone,                 // CEE_UNUSED31
        InlineNone,                 // CEE_UNUSED32
        InlineNone,                 // CEE_UNUSED33
        InlineNone,                 // CEE_UNUSED34
        InlineNone,                 // CEE_UNUSED35
        InlineNone,                 // CEE_UNUSED36
        InlineNone,                 // CEE_UNUSED37
        InlineNone,                 // CEE_UNUSED38
        InlineNone,                 // CEE_UNUSED39
        InlineNone,                 // CEE_UNUSED40
        InlineNone,                 // CEE_UNUSED41
        InlineNone,                 // CEE_UNUSED42
        InlineNone,                 // CEE_UNUSED43
        InlineNone,                 // CEE_UNUSED44
        InlineNone,                 // CEE_UNUSED45
        InlineNone,                 // CEE_UNUSED46
        InlineNone,                 // CEE_UNUSED47
        InlineNone,                 // CEE_UNUSED48
        InlineNone,                 // CEE_PREFIX7
        InlineNone,                 // CEE_PREFIX6
        InlineNone,                 // CEE_PREFIX5
        InlineNone,                 // CEE_PREFIX4
        InlineNone,                 // CEE_PREFIX3
        InlineNone,                 // CEE_PREFIX2
        InlineNone,                 // CEE_PREFIX1
        InlineNone,                 // CEE_PREFIXREF

        InlineNone,                 // CEE_ARGLIST
        InlineNone,                 // CEE_CEQ
        InlineNone,                 // CEE_CGT
        InlineNone,                 // CEE_CGT_UN
        InlineNone,                 // CEE_CLT
        InlineNone,                 // CEE_CLT_UN
        InlineMethod,               // CEE_LDFTN
        InlineMethod,               // CEE_LDVIRTFTN
        InlineNone,                 // CEE_UNUSED56
        InlineVar,                  // CEE_LDARG
        InlineVar,                  // CEE_LDARGA
        InlineVar,                  // CEE_STARG
        InlineVar,                  // CEE_LDLOC
        InlineVar,                  // CEE_LDLOCA
        InlineVar,                  // CEE_STLOC
        InlineNone,                 // CEE_LOCALLOC
        InlineNone,                 // CEE_UNUSED57
        InlineNone,                 // CEE_ENDFILTER
        ShortInlineI,               // CEE_UNALIGNED
        InlineNone,                 // CEE_VOLATILE
        InlineNone,                 // CEE_TAILCALL
        InlineType,                 // CEE_INITOBJ
        InlineType,                 // CEE_CONSTRAINED
        InlineNone,                 // CEE_CPBLK
        InlineNone,                 // CEE_INITBLK
        InlineNone,                 // CEE_UNUSED69
        InlineNone,                 // CEE_RETHROW
        InlineNone,                 // CEE_UNUSED51
        InlineType,                 // CEEOF
        InlineNone,                 // CEE_REFANYTYPE
        InlineNone,                 // CEE_READONLY
        InlineNone,                 // CEE_UNUSED53
        InlineNone,                 // CEE_UNUSED54
        InlineNone,                 // CEE_UNUSED55
        InlineNone,                 // CEE_UNUSED70

#if !OPDEF_REAL_OPCODES_ONLY
        InlineNone,                 // CEE_ILLEGAL
        InlineNone,                 // CEE_MACRO_END
        InlineNone,                 // CEE_CODE_LABEL
#endif
    ];

    private static ReadOnlySpan<OpFlow> s_flowKinds => [
        FLOW_NEXT,              // CEE_NOP
        FLOW_BREAK,             // CEE_BREAK
        FLOW_NEXT,              // CEE_LDARG_0
        FLOW_NEXT,              // CEE_LDARG_1
        FLOW_NEXT,              // CEE_LDARG_2
        FLOW_NEXT,              // CEE_LDARG_3
        FLOW_NEXT,              // CEE_LDLOC_0
        FLOW_NEXT,              // CEE_LDLOC_1
        FLOW_NEXT,              // CEE_LDLOC_2
        FLOW_NEXT,              // CEE_LDLOC_3
        FLOW_NEXT,              // CEE_STLOC_0
        FLOW_NEXT,              // CEE_STLOC_1
        FLOW_NEXT,              // CEE_STLOC_2
        FLOW_NEXT,              // CEE_STLOC_3
        FLOW_NEXT,              // CEE_LDARG_S
        FLOW_NEXT,              // CEE_LDARGA_S
        FLOW_NEXT,              // CEE_STARG_S
        FLOW_NEXT,              // CEE_LDLOC_S
        FLOW_NEXT,              // CEE_LDLOCA_S
        FLOW_NEXT,              // CEE_STLOC_S
        FLOW_NEXT,              // CEE_LDNULL
        FLOW_NEXT,              // CEE_LDC_I4_M1
        FLOW_NEXT,              // CEE_LDC_I4_0
        FLOW_NEXT,              // CEE_LDC_I4_1
        FLOW_NEXT,              // CEE_LDC_I4_2
        FLOW_NEXT,              // CEE_LDC_I4_3
        FLOW_NEXT,              // CEE_LDC_I4_4
        FLOW_NEXT,              // CEE_LDC_I4_5
        FLOW_NEXT,              // CEE_LDC_I4_6
        FLOW_NEXT,              // CEE_LDC_I4_7
        FLOW_NEXT,              // CEE_LDC_I4_8
        FLOW_NEXT,              // CEE_LDC_I4_S
        FLOW_NEXT,              // CEE_LDC_I4
        FLOW_NEXT,              // CEE_LDC_I8
        FLOW_NEXT,              // CEE_LDC_R4
        FLOW_NEXT,              // CEE_LDC_R8
        FLOW_NEXT,              // CEE_UNUSED49
        FLOW_NEXT,              // CEE_DUP
        FLOW_NEXT,              // CEE_POP
        FLOW_CALL,              // CEE_JMP
        FLOW_CALL,              // CEE_CALL
        FLOW_CALL,              // CEE_CALLI
        FLOW_RETURN,            // CEE_RET
        FLOW_BRANCH,            // CEE_BR_S
        FLOW_COND_BRANCH,       // CEE_BRFALSE_S
        FLOW_COND_BRANCH,       // CEE_BRTRUE_S
        FLOW_COND_BRANCH,       // CEE_BEQ_S
        FLOW_COND_BRANCH,       // CEE_BGE_S
        FLOW_COND_BRANCH,       // CEE_BGT_S
        FLOW_COND_BRANCH,       // CEE_BLE_S
        FLOW_COND_BRANCH,       // CEE_BLT_S
        FLOW_COND_BRANCH,       // CEE_BNE_UN_S
        FLOW_COND_BRANCH,       // CEE_BGE_UN_S
        FLOW_COND_BRANCH,       // CEE_BGT_UN_S
        FLOW_COND_BRANCH,       // CEE_BLE_UN_S
        FLOW_COND_BRANCH,       // CEE_BLT_UN_S
        FLOW_BRANCH,            // CEE_BR
        FLOW_COND_BRANCH,       // CEE_BRFALSE
        FLOW_COND_BRANCH,       // CEE_BRTRUE
        FLOW_COND_BRANCH,       // CEE_BEQ
        FLOW_COND_BRANCH,       // CEE_BGE
        FLOW_COND_BRANCH,       // CEE_BGT
        FLOW_COND_BRANCH,       // CEE_BLE
        FLOW_COND_BRANCH,       // CEE_BLT
        FLOW_COND_BRANCH,       // CEE_BNE_UN
        FLOW_COND_BRANCH,       // CEE_BGE_UN
        FLOW_COND_BRANCH,       // CEE_BGT_UN
        FLOW_COND_BRANCH,       // CEE_BLE_UN
        FLOW_COND_BRANCH,       // CEE_BLT_UN
        FLOW_COND_BRANCH,       // CEE_SWITCH
        FLOW_NEXT,              // CEE_LDIND_I1
        FLOW_NEXT,              // CEE_LDIND_U1
        FLOW_NEXT,              // CEE_LDIND_I2
        FLOW_NEXT,              // CEE_LDIND_U2
        FLOW_NEXT,              // CEE_LDIND_I4
        FLOW_NEXT,              // CEE_LDIND_U4
        FLOW_NEXT,              // CEE_LDIND_I8
        FLOW_NEXT,              // CEE_LDIND_I
        FLOW_NEXT,              // CEE_LDIND_R4
        FLOW_NEXT,              // CEE_LDIND_R8
        FLOW_NEXT,              // CEE_LDIND_REF
        FLOW_NEXT,              // CEE_STIND_REF
        FLOW_NEXT,              // CEE_STIND_I1
        FLOW_NEXT,              // CEE_STIND_I2
        FLOW_NEXT,              // CEE_STIND_I4
        FLOW_NEXT,              // CEE_STIND_I8
        FLOW_NEXT,              // CEE_STIND_R4
        FLOW_NEXT,              // CEE_STIND_R8
        FLOW_NEXT,              // CEE_ADD
        FLOW_NEXT,              // CEE_SUB
        FLOW_NEXT,              // CEE_MUL
        FLOW_NEXT,              // CEE_DIV
        FLOW_NEXT,              // CEE_DIV_UN
        FLOW_NEXT,              // CEE_REM
        FLOW_NEXT,              // CEE_REM_UN
        FLOW_NEXT,              // CEE_AND
        FLOW_NEXT,              // CEE_OR
        FLOW_NEXT,              // CEE_XOR
        FLOW_NEXT,              // CEE_SHL
        FLOW_NEXT,              // CEE_SHR
        FLOW_NEXT,              // CEE_SHR_UN
        FLOW_NEXT,              // CEE_NEG
        FLOW_NEXT,              // CEE_NOT
        FLOW_NEXT,              // CEE_CONV_I1
        FLOW_NEXT,              // CEE_CONV_I2
        FLOW_NEXT,              // CEE_CONV_I4
        FLOW_NEXT,              // CEE_CONV_I8
        FLOW_NEXT,              // CEE_CONV_R4
        FLOW_NEXT,              // CEE_CONV_R8
        FLOW_NEXT,              // CEE_CONV_U4
        FLOW_NEXT,              // CEE_CONV_U8
        FLOW_CALL,              // CEE_CALLVIRT
        FLOW_NEXT,              // CEE_CPOBJ
        FLOW_NEXT,              // CEE_LDOBJ
        FLOW_NEXT,              // CEE_LDSTR
        FLOW_CALL,              // CEE_NEWOBJ
        FLOW_NEXT,              // CEE_CASTCLASS
        FLOW_NEXT,              // CEE_ISINST
        FLOW_NEXT,              // CEE_CONV_R_UN
        FLOW_NEXT,              // CEE_UNUSED58
        FLOW_NEXT,              // CEE_UNUSED1
        FLOW_NEXT,              // CEE_UNBOX
        FLOW_THROW,             // CEE_THROW
        FLOW_NEXT,              // CEE_LDFLD
        FLOW_NEXT,              // CEE_LDFLDA
        FLOW_NEXT,              // CEE_STFLD
        FLOW_NEXT,              // CEE_LDSFLD
        FLOW_NEXT,              // CEE_LDSFLDA
        FLOW_NEXT,              // CEE_STSFLD
        FLOW_NEXT,              // CEE_STOBJ
        FLOW_NEXT,              // CEE_CONV_OVF_I1_UN
        FLOW_NEXT,              // CEE_CONV_OVF_I2_UN
        FLOW_NEXT,              // CEE_CONV_OVF_I4_UN
        FLOW_NEXT,              // CEE_CONV_OVF_I8_UN
        FLOW_NEXT,              // CEE_CONV_OVF_U1_UN
        FLOW_NEXT,              // CEE_CONV_OVF_U2_UN
        FLOW_NEXT,              // CEE_CONV_OVF_U4_UN
        FLOW_NEXT,              // CEE_CONV_OVF_U8_UN
        FLOW_NEXT,              // CEE_CONV_OVF_I_UN
        FLOW_NEXT,              // CEE_CONV_OVF_U_UN
        FLOW_NEXT,              // CEE_BOX
        FLOW_NEXT,              // CEE_NEWARR
        FLOW_NEXT,              // CEE_LDLEN
        FLOW_NEXT,              // CEE_LDELEMA
        FLOW_NEXT,              // CEE_LDELEM_I1
        FLOW_NEXT,              // CEE_LDELEM_U1
        FLOW_NEXT,              // CEE_LDELEM_I2
        FLOW_NEXT,              // CEE_LDELEM_U2
        FLOW_NEXT,              // CEE_LDELEM_I4
        FLOW_NEXT,              // CEE_LDELEM_U4
        FLOW_NEXT,              // CEE_LDELEM_I8
        FLOW_NEXT,              // CEE_LDELEM_I
        FLOW_NEXT,              // CEE_LDELEM_R4
        FLOW_NEXT,              // CEE_LDELEM_R8
        FLOW_NEXT,              // CEE_LDELEM_REF
        FLOW_NEXT,              // CEE_STELEM_I
        FLOW_NEXT,              // CEE_STELEM_I1
        FLOW_NEXT,              // CEE_STELEM_I2
        FLOW_NEXT,              // CEE_STELEM_I4
        FLOW_NEXT,              // CEE_STELEM_I8
        FLOW_NEXT,              // CEE_STELEM_R4
        FLOW_NEXT,              // CEE_STELEM_R8
        FLOW_NEXT,              // CEE_STELEM_REF
        FLOW_NEXT,              // CEE_LDELEM
        FLOW_NEXT,              // CEE_STELEM
        FLOW_NEXT,              // CEE_UNBOX_ANY
        FLOW_NEXT,              // CEE_UNUSED5
        FLOW_NEXT,              // CEE_UNUSED6
        FLOW_NEXT,              // CEE_UNUSED7
        FLOW_NEXT,              // CEE_UNUSED8
        FLOW_NEXT,              // CEE_UNUSED9
        FLOW_NEXT,              // CEE_UNUSED10
        FLOW_NEXT,              // CEE_UNUSED11
        FLOW_NEXT,              // CEE_UNUSED12
        FLOW_NEXT,              // CEE_UNUSED13
        FLOW_NEXT,              // CEE_UNUSED14
        FLOW_NEXT,              // CEE_UNUSED15
        FLOW_NEXT,              // CEE_UNUSED16
        FLOW_NEXT,              // CEE_UNUSED17
        FLOW_NEXT,              // CEE_CONV_OVF_I1
        FLOW_NEXT,              // CEE_CONV_OVF_U1
        FLOW_NEXT,              // CEE_CONV_OVF_I2
        FLOW_NEXT,              // CEE_CONV_OVF_U2
        FLOW_NEXT,              // CEE_CONV_OVF_I4
        FLOW_NEXT,              // CEE_CONV_OVF_U4
        FLOW_NEXT,              // CEE_CONV_OVF_I8
        FLOW_NEXT,              // CEE_CONV_OVF_U8
        FLOW_NEXT,              // CEE_UNUSED50
        FLOW_NEXT,              // CEE_UNUSED18
        FLOW_NEXT,              // CEE_UNUSED19
        FLOW_NEXT,              // CEE_UNUSED20
        FLOW_NEXT,              // CEE_UNUSED21
        FLOW_NEXT,              // CEE_UNUSED22
        FLOW_NEXT,              // CEE_UNUSED23
        FLOW_NEXT,              // CEE_REFANYVAL
        FLOW_NEXT,              // CEE_CKFINITE
        FLOW_NEXT,              // CEE_UNUSED24
        FLOW_NEXT,              // CEE_UNUSED25
        FLOW_NEXT,              // CEE_MKREFANY
        FLOW_NEXT,              // CEE_UNUSED59
        FLOW_NEXT,              // CEE_UNUSED60
        FLOW_NEXT,              // CEE_UNUSED61
        FLOW_NEXT,              // CEE_UNUSED62
        FLOW_NEXT,              // CEE_UNUSED63
        FLOW_NEXT,              // CEE_UNUSED64
        FLOW_NEXT,              // CEE_UNUSED65
        FLOW_NEXT,              // CEE_UNUSED66
        FLOW_NEXT,              // CEE_UNUSED67
        FLOW_NEXT,              // CEE_LDTOKEN
        FLOW_NEXT,              // CEE_CONV_U2
        FLOW_NEXT,              // CEE_CONV_U1
        FLOW_NEXT,              // CEE_CONV_I
        FLOW_NEXT,              // CEE_CONV_OVF_I
        FLOW_NEXT,              // CEE_CONV_OVF_U
        FLOW_NEXT,              // CEE_ADD_OVF
        FLOW_NEXT,              // CEE_ADD_OVF_UN
        FLOW_NEXT,              // CEE_MUL_OVF
        FLOW_NEXT,              // CEE_MUL_OVF_UN
        FLOW_NEXT,              // CEE_SUB_OVF
        FLOW_NEXT,              // CEE_SUB_OVF_UN
        FLOW_RETURN,            // CEE_ENDFINALLY
        FLOW_BRANCH,            // CEE_LEAVE
        FLOW_BRANCH,            // CEE_LEAVE_S
        FLOW_NEXT,              // CEE_STIND_I
        FLOW_NEXT,              // CEE_CONV_U
        FLOW_NEXT,              // CEE_UNUSED26
        FLOW_NEXT,              // CEE_UNUSED27
        FLOW_NEXT,              // CEE_UNUSED28
        FLOW_NEXT,              // CEE_UNUSED29
        FLOW_NEXT,              // CEE_UNUSED30
        FLOW_NEXT,              // CEE_UNUSED31
        FLOW_NEXT,              // CEE_UNUSED32
        FLOW_NEXT,              // CEE_UNUSED33
        FLOW_NEXT,              // CEE_UNUSED34
        FLOW_NEXT,              // CEE_UNUSED35
        FLOW_NEXT,              // CEE_UNUSED36
        FLOW_NEXT,              // CEE_UNUSED37
        FLOW_NEXT,              // CEE_UNUSED38
        FLOW_NEXT,              // CEE_UNUSED39
        FLOW_NEXT,              // CEE_UNUSED40
        FLOW_NEXT,              // CEE_UNUSED41
        FLOW_NEXT,              // CEE_UNUSED42
        FLOW_NEXT,              // CEE_UNUSED43
        FLOW_NEXT,              // CEE_UNUSED44
        FLOW_NEXT,              // CEE_UNUSED45
        FLOW_NEXT,              // CEE_UNUSED46
        FLOW_NEXT,              // CEE_UNUSED47
        FLOW_NEXT,              // CEE_UNUSED48
        FLOW_META,              // CEE_PREFIX7
        FLOW_META,              // CEE_PREFIX6
        FLOW_META,              // CEE_PREFIX5
        FLOW_META,              // CEE_PREFIX4
        FLOW_META,              // CEE_PREFIX3
        FLOW_META,              // CEE_PREFIX2
        FLOW_META,              // CEE_PREFIX1
        FLOW_META,              // CEE_PREFIXREF

        FLOW_NEXT,              // CEE_ARGLIST
        FLOW_NEXT,              // CEE_CEQ
        FLOW_NEXT,              // CEE_CGT
        FLOW_NEXT,              // CEE_CGT_UN
        FLOW_NEXT,              // CEE_CLT
        FLOW_NEXT,              // CEE_CLT_UN
        FLOW_NEXT,              // CEE_LDFTN
        FLOW_NEXT,              // CEE_LDVIRTFTN
        FLOW_NEXT,              // CEE_UNUSED56
        FLOW_NEXT,              // CEE_LDARG
        FLOW_NEXT,              // CEE_LDARGA
        FLOW_NEXT,              // CEE_STARG
        FLOW_NEXT,              // CEE_LDLOC
        FLOW_NEXT,              // CEE_LDLOCA
        FLOW_NEXT,              // CEE_STLOC
        FLOW_NEXT,              // CEE_LOCALLOC
        FLOW_NEXT,              // CEE_UNUSED57
        FLOW_RETURN,            // CEE_ENDFILTER
        FLOW_META,              // CEE_UNALIGNED
        FLOW_META,              // CEE_VOLATILE
        FLOW_META,              // CEE_TAILCALL
        FLOW_NEXT,              // CEE_INITOBJ
        FLOW_META,              // CEE_CONSTRAINED
        FLOW_NEXT,              // CEE_CPBLK
        FLOW_NEXT,              // CEE_INITBLK
        FLOW_NEXT,              // CEE_UNUSED69
        FLOW_THROW,             // CEE_RETHROW
        FLOW_NEXT,              // CEE_UNUSED51
        FLOW_NEXT,              // CEEOF
        FLOW_NEXT,              // CEE_REFANYTYPE
        FLOW_META,              // CEE_READONLY
        FLOW_NEXT,              // CEE_UNUSED53
        FLOW_NEXT,              // CEE_UNUSED54
        FLOW_NEXT,              // CEE_UNUSED55
        FLOW_NEXT,              // CEE_UNUSED70

#if !OPDEF_REAL_OPCODES_ONLY
        FLOW_META,              // CEE_ILLEGAL
        FLOW_META,              // CEE_MACRO_END
        FLOW_META,              // CEE_CODE_LABEL
#endif
    ];

    private static readonly string[] s_names = [
        "nop",              // CEE_NOP
        "break",            // CEE_BREAK
        "ldarg.0",          // CEE_LDARG_0
        "ldarg.1",          // CEE_LDARG_1
        "ldarg.2",          // CEE_LDARG_2
        "ldarg.3",          // CEE_LDARG_3
        "ldloc.0",          // CEE_LDLOC_0
        "ldloc.1",          // CEE_LDLOC_1
        "ldloc.2",          // CEE_LDLOC_2
        "ldloc.3",          // CEE_LDLOC_3
        "stloc.0",          // CEE_STLOC_0
        "stloc.1",          // CEE_STLOC_1
        "stloc.2",          // CEE_STLOC_2
        "stloc.3",          // CEE_STLOC_3
        "ldarg.s",          // CEE_LDARG_S
        "ldarga.s",         // CEE_LDARGA_S
        "starg.s",          // CEE_STARG_S
        "ldloc.s",          // CEE_LDLOC_S
        "ldloca.s",         // CEE_LDLOCA_S
        "stloc.s",          // CEE_STLOC_S
        "ldnull",           // CEE_LDNULL
        "ldc.i4.m1",        // CEE_LDC_I4_M1
        "ldc.i4.0",         // CEE_LDC_I4_0
        "ldc.i4.1",         // CEE_LDC_I4_1
        "ldc.i4.2",         // CEE_LDC_I4_2
        "ldc.i4.3",         // CEE_LDC_I4_3
        "ldc.i4.4",         // CEE_LDC_I4_4
        "ldc.i4.5",         // CEE_LDC_I4_5
        "ldc.i4.6",         // CEE_LDC_I4_6
        "ldc.i4.7",         // CEE_LDC_I4_7
        "ldc.i4.8",         // CEE_LDC_I4_8
        "ldc.i4.s",         // CEE_LDC_I4_S
        "ldc.i4",           // CEE_LDC_I4
        "ldc.i8",           // CEE_LDC_I8
        "ldc.r4",           // CEE_LDC_R4
        "ldc.r8",           // CEE_LDC_R8
        "unused",           // CEE_UNUSED49
        "dup",              // CEE_DUP
        "pop",              // CEE_POP
        "jmp",              // CEE_JMP
        "call",             // CEE_CALL
        "calli",            // CEE_CALLI
        "ret",              // CEE_RET
        "br.s",             // CEE_BR_S
        "brfalse.s",        // CEE_BRFALSE_S
        "brtrue.s",         // CEE_BRTRUE_S
        "beq.s",            // CEE_BEQ_S
        "bge.s",            // CEE_BGE_S
        "bgt.s",            // CEE_BGT_S
        "ble.s",            // CEE_BLE_S
        "blt.s",            // CEE_BLT_S
        "bne.un.s",         // CEE_BNE_UN_S
        "bge.un.s",         // CEE_BGE_UN_S
        "bgt.un.s",         // CEE_BGT_UN_S
        "ble.un.s",         // CEE_BLE_UN_S
        "blt.un.s",         // CEE_BLT_UN_S
        "br",               // CEE_BR
        "brfalse",          // CEE_BRFALSE
        "brtrue",           // CEE_BRTRUE
        "beq",              // CEE_BEQ
        "bge",              // CEE_BGE
        "bgt",              // CEE_BGT
        "ble",              // CEE_BLE
        "blt",              // CEE_BLT
        "bne.un",           // CEE_BNE_UN
        "bge.un",           // CEE_BGE_UN
        "bgt.un",           // CEE_BGT_UN
        "ble.un",           // CEE_BLE_UN
        "blt.un",           // CEE_BLT_UN
        "switch",           // CEE_SWITCH
        "ldind.i1",         // CEE_LDIND_I1
        "ldind.u1",         // CEE_LDIND_U1
        "ldind.i2",         // CEE_LDIND_I2
        "ldind.u2",         // CEE_LDIND_U2
        "ldind.i4",         // CEE_LDIND_I4
        "ldind.u4",         // CEE_LDIND_U4
        "ldind.i8",         // CEE_LDIND_I8
        "ldind.i",          // CEE_LDIND_I
        "ldind.r4",         // CEE_LDIND_R4
        "ldind.r8",         // CEE_LDIND_R8
        "ldind.ref",        // CEE_LDIND_REF
        "stind.ref",        // CEE_STIND_REF
        "stind.i1",         // CEE_STIND_I1
        "stind.i2",         // CEE_STIND_I2
        "stind.i4",         // CEE_STIND_I4
        "stind.i8",         // CEE_STIND_I8
        "stind.r4",         // CEE_STIND_R4
        "stind.r8",         // CEE_STIND_R8
        "add",              // CEE_ADD
        "sub",              // CEE_SUB
        "mul",              // CEE_MUL
        "div",              // CEE_DIV
        "div.un",           // CEE_DIV_UN
        "rem",              // CEE_REM
        "rem.un",           // CEE_REM_UN
        "and",              // CEE_AND
        "or",               // CEE_OR
        "xor",              // CEE_XOR
        "shl",              // CEE_SHL
        "shr",              // CEE_SHR
        "shr.un",           // CEE_SHR_UN
        "neg",              // CEE_NEG
        "not",              // CEE_NOT
        "conv.i1",          // CEE_CONV_I1
        "conv.i2",          // CEE_CONV_I2
        "conv.i4",          // CEE_CONV_I4
        "conv.i8",          // CEE_CONV_I8
        "conv.r4",          // CEE_CONV_R4
        "conv.r8",          // CEE_CONV_R8
        "conv.u4",          // CEE_CONV_U4
        "conv.u8",          // CEE_CONV_U8
        "callvirt",         // CEE_CALLVIRT
        "cpobj",            // CEE_CPOBJ
        "ldobj",            // CEE_LDOBJ
        "ldstr",            // CEE_LDSTR
        "newobj",           // CEE_NEWOBJ
        "castclass",        // CEE_CASTCLASS
        "isinst",           // CEE_ISINST
        "conv.r.un",        // CEE_CONV_R_UN
        "unused",           // CEE_UNUSED58
        "unused",           // CEE_UNUSED1
        "unbox",            // CEE_UNBOX
        "throw",            // CEE_THROW
        "ldfld",            // CEE_LDFLD
        "ldflda",           // CEE_LDFLDA
        "stfld",            // CEE_STFLD
        "ldsfld",           // CEE_LDSFLD
        "ldsflda",          // CEE_LDSFLDA
        "stsfld",           // CEE_STSFLD
        "stobj",            // CEE_STOBJ
        "conv.ovf.i1.un",   // CEE_CONV_OVF_I1_UN
        "conv.ovf.i2.un",   // CEE_CONV_OVF_I2_UN
        "conv.ovf.i4.un",   // CEE_CONV_OVF_I4_UN
        "conv.ovf.i8.un",   // CEE_CONV_OVF_I8_UN
        "conv.ovf.u1.un",   // CEE_CONV_OVF_U1_UN
        "conv.ovf.u2.un",   // CEE_CONV_OVF_U2_UN
        "conv.ovf.u4.un",   // CEE_CONV_OVF_U4_UN
        "conv.ovf.u8.un",   // CEE_CONV_OVF_U8_UN
        "conv.ovf.i.un",    // CEE_CONV_OVF_I_UN
        "conv.ovf.u.un",    // CEE_CONV_OVF_U_UN
        "box",              // CEE_BOX
        "newarr",           // CEE_NEWARR
        "ldlen",            // CEE_LDLEN
        "ldelema",          // CEE_LDELEMA
        "ldelem.i1",        // CEE_LDELEM_I1
        "ldelem.u1",        // CEE_LDELEM_U1
        "ldelem.i2",        // CEE_LDELEM_I2
        "ldelem.u2",        // CEE_LDELEM_U2
        "ldelem.i4",        // CEE_LDELEM_I4
        "ldelem.u4",        // CEE_LDELEM_U4
        "ldelem.i8",        // CEE_LDELEM_I8
        "ldelem.i",         // CEE_LDELEM_I
        "ldelem.r4",        // CEE_LDELEM_R4
        "ldelem.r8",        // CEE_LDELEM_R8
        "ldelem.ref",       // CEE_LDELEM_REF
        "stelem.i",         // CEE_STELEM_I
        "stelem.i1",        // CEE_STELEM_I1
        "stelem.i2",        // CEE_STELEM_I2
        "stelem.i4",        // CEE_STELEM_I4
        "stelem.i8",        // CEE_STELEM_I8
        "stelem.r4",        // CEE_STELEM_R4
        "stelem.r8",        // CEE_STELEM_R8
        "stelem.ref",       // CEE_STELEM_REF
        "ldelem",           // CEE_LDELEM
        "stelem",           // CEE_STELEM
        "unbox.any",        // CEE_UNBOX_ANY
        "unused",           // CEE_UNUSED5
        "unused",           // CEE_UNUSED6
        "unused",           // CEE_UNUSED7
        "unused",           // CEE_UNUSED8
        "unused",           // CEE_UNUSED9
        "unused",           // CEE_UNUSED10
        "unused",           // CEE_UNUSED11
        "unused",           // CEE_UNUSED12
        "unused",           // CEE_UNUSED13
        "unused",           // CEE_UNUSED14
        "unused",           // CEE_UNUSED15
        "unused",           // CEE_UNUSED16
        "unused",           // CEE_UNUSED17
        "conv.ovf.i1",      // CEE_CONV_OVF_I1
        "conv.ovf.u1",      // CEE_CONV_OVF_U1
        "conv.ovf.i2",      // CEE_CONV_OVF_I2
        "conv.ovf.u2",      // CEE_CONV_OVF_U2
        "conv.ovf.i4",      // CEE_CONV_OVF_I4
        "conv.ovf.u4",      // CEE_CONV_OVF_U4
        "conv.ovf.i8",      // CEE_CONV_OVF_I8
        "conv.ovf.u8",      // CEE_CONV_OVF_U8
        "unused",           // CEE_UNUSED50
        "unused",           // CEE_UNUSED18
        "unused",           // CEE_UNUSED19
        "unused",           // CEE_UNUSED20
        "unused",           // CEE_UNUSED21
        "unused",           // CEE_UNUSED22
        "unused",           // CEE_UNUSED23
        "refanyval",        // CEE_REFANYVAL
        "ckfinite",         // CEE_CKFINITE
        "unused",           // CEE_UNUSED24
        "unused",           // CEE_UNUSED25
        "mkrefany",         // CEE_MKREFANY
        "unused",           // CEE_UNUSED59
        "unused",           // CEE_UNUSED60
        "unused",           // CEE_UNUSED61
        "unused",           // CEE_UNUSED62
        "unused",           // CEE_UNUSED63
        "unused",           // CEE_UNUSED64
        "unused",           // CEE_UNUSED65
        "unused",           // CEE_UNUSED66
        "unused",           // CEE_UNUSED67
        "ldtoken",          // CEE_LDTOKEN
        "conv.u2",          // CEE_CONV_U2
        "conv.u1",          // CEE_CONV_U1
        "conv.i",           // CEE_CONV_I
        "conv.ovf.i",       // CEE_CONV_OVF_I
        "conv.ovf.u",       // CEE_CONV_OVF_U
        "add.ovf",          // CEE_ADD_OVF
        "add.ovf.un",       // CEE_ADD_OVF_UN
        "mul.ovf",          // CEE_MUL_OVF
        "mul.ovf.un",       // CEE_MUL_OVF_UN
        "sub.ovf",          // CEE_SUB_OVF
        "sub.ovf.un",       // CEE_SUB_OVF_UN
        "endfinally",       // CEE_ENDFINALLY
        "leave",            // CEE_LEAVE
        "leave.s",          // CEE_LEAVE_S
        "stind.i",          // CEE_STIND_I
        "conv.u",           // CEE_CONV_U
        "unused",           // CEE_UNUSED26
        "unused",           // CEE_UNUSED27
        "unused",           // CEE_UNUSED28
        "unused",           // CEE_UNUSED29
        "unused",           // CEE_UNUSED30
        "unused",           // CEE_UNUSED31
        "unused",           // CEE_UNUSED32
        "unused",           // CEE_UNUSED33
        "unused",           // CEE_UNUSED34
        "unused",           // CEE_UNUSED35
        "unused",           // CEE_UNUSED36
        "unused",           // CEE_UNUSED37
        "unused",           // CEE_UNUSED38
        "unused",           // CEE_UNUSED39
        "unused",           // CEE_UNUSED40
        "unused",           // CEE_UNUSED41
        "unused",           // CEE_UNUSED42
        "unused",           // CEE_UNUSED43
        "unused",           // CEE_UNUSED44
        "unused",           // CEE_UNUSED45
        "unused",           // CEE_UNUSED46
        "unused",           // CEE_UNUSED47
        "unused",           // CEE_UNUSED48
        "prefix7",          // CEE_PREFIX7
        "prefix6",          // CEE_PREFIX6
        "prefix5",          // CEE_PREFIX5
        "prefix4",          // CEE_PREFIX4
        "prefix3",          // CEE_PREFIX3
        "prefix2",          // CEE_PREFIX2
        "prefix1",          // CEE_PREFIX1
        "prefixref",        // CEE_PREFIXREF

        "arglist",          // CEE_ARGLIST
        "ceq",              // CEE_CEQ
        "cgt",              // CEE_CGT
        "cgt.un",           // CEE_CGT_UN
        "clt",              // CEE_CLT
        "clt.un",           // CEE_CLT_UN
        "ldftn",            // CEE_LDFTN
        "ldvirtftn",        // CEE_LDVIRTFTN
        "unused",           // CEE_UNUSED56
        "ldarg",            // CEE_LDARG
        "ldarga",           // CEE_LDARGA
        "starg",            // CEE_STARG
        "ldloc",            // CEE_LDLOC
        "ldloca",           // CEE_LDLOCA
        "stloc",            // CEE_STLOC
        "localloc",         // CEE_LOCALLOC
        "unused",           // CEE_UNUSED57
        "endfilter",        // CEE_ENDFILTER
        "unaligned.",       // CEE_UNALIGNED
        "volatile.",        // CEE_VOLATILE
        "tail.",            // CEE_TAILCALL
        "initobj",          // CEE_INITOBJ
        "constrained.",     // CEE_CONSTRAINED
        "cpblk",            // CEE_CPBLK
        "initblk",          // CEE_INITBLK
        "unused",           // CEE_UNUSED69
        "rethrow",          // CEE_RETHROW
        "unused",           // CEE_UNUSED51
        "sizeof",           // CEEOF
        "refanytype",       // CEE_REFANYTYPE
        "readonly.",        // CEE_READONLY
        "unused",           // CEE_UNUSED53
        "unused",           // CEE_UNUSED54
        "unused",           // CEE_UNUSED55
        "unused",           // CEE_UNUSED70

#if !OPDEF_REAL_OPCODES_ONLY
        "illegal",          // CEE_ILLEGAL
        "endmac",           // CEE_MACRO_END
        "codelabel",        // CEE_CODE_LABEL
#endif
    ];
#endif

    private static ReadOnlySpan<byte> s_sizes => [
        InlineNone_size,                // CEE_NOP
        InlineNone_size,                // CEE_BREAK
        InlineNone_size,                // CEE_LDARG_0
        InlineNone_size,                // CEE_LDARG_1
        InlineNone_size,                // CEE_LDARG_2
        InlineNone_size,                // CEE_LDARG_3
        InlineNone_size,                // CEE_LDLOC_0
        InlineNone_size,                // CEE_LDLOC_1
        InlineNone_size,                // CEE_LDLOC_2
        InlineNone_size,                // CEE_LDLOC_3
        InlineNone_size,                // CEE_STLOC_0
        InlineNone_size,                // CEE_STLOC_1
        InlineNone_size,                // CEE_STLOC_2
        InlineNone_size,                // CEE_STLOC_3
        ShortInlineVar_size,            // CEE_LDARG_S
        ShortInlineVar_size,            // CEE_LDARGA_S
        ShortInlineVar_size,            // CEE_STARG_S
        ShortInlineVar_size,            // CEE_LDLOC_S
        ShortInlineVar_size,            // CEE_LDLOCA_S
        ShortInlineVar_size,            // CEE_STLOC_S
        InlineNone_size,                // CEE_LDNULL
        InlineNone_size,                // CEE_LDC_I4_M1
        InlineNone_size,                // CEE_LDC_I4_0
        InlineNone_size,                // CEE_LDC_I4_1
        InlineNone_size,                // CEE_LDC_I4_2
        InlineNone_size,                // CEE_LDC_I4_3
        InlineNone_size,                // CEE_LDC_I4_4
        InlineNone_size,                // CEE_LDC_I4_5
        InlineNone_size,                // CEE_LDC_I4_6
        InlineNone_size,                // CEE_LDC_I4_7
        InlineNone_size,                // CEE_LDC_I4_8
        ShortInlineI_size,              // CEE_LDC_I4_S
        InlineI_size,                   // CEE_LDC_I4
        InlineI8_size,                  // CEE_LDC_I8
        ShortInlineR_size,              // CEE_LDC_R4
        InlineR_size,                   // CEE_LDC_R8
        InlineNone_size,                // CEE_UNUSED49
        InlineNone_size,                // CEE_DUP
        InlineNone_size,                // CEE_POP
        InlineMethod_size,              // CEE_JMP
        InlineMethod_size,              // CEE_CALL
        InlineSig_size,                 // CEE_CALLI
        InlineNone_size,                // CEE_RET
        ShortInlineBrTarget_size,       // CEE_BR_S
        ShortInlineBrTarget_size,       // CEE_BRFALSE_S
        ShortInlineBrTarget_size,       // CEE_BRTRUE_S
        ShortInlineBrTarget_size,       // CEE_BEQ_S
        ShortInlineBrTarget_size,       // CEE_BGE_S
        ShortInlineBrTarget_size,       // CEE_BGT_S
        ShortInlineBrTarget_size,       // CEE_BLE_S
        ShortInlineBrTarget_size,       // CEE_BLT_S
        ShortInlineBrTarget_size,       // CEE_BNE_UN_S
        ShortInlineBrTarget_size,       // CEE_BGE_UN_S
        ShortInlineBrTarget_size,       // CEE_BGT_UN_S
        ShortInlineBrTarget_size,       // CEE_BLE_UN_S
        ShortInlineBrTarget_size,       // CEE_BLT_UN_S
        InlineBrTarget_size,            // CEE_BR
        InlineBrTarget_size,            // CEE_BRFALSE
        InlineBrTarget_size,            // CEE_BRTRUE
        InlineBrTarget_size,            // CEE_BEQ
        InlineBrTarget_size,            // CEE_BGE
        InlineBrTarget_size,            // CEE_BGT
        InlineBrTarget_size,            // CEE_BLE
        InlineBrTarget_size,            // CEE_BLT
        InlineBrTarget_size,            // CEE_BNE_UN
        InlineBrTarget_size,            // CEE_BGE_UN
        InlineBrTarget_size,            // CEE_BGT_UN
        InlineBrTarget_size,            // CEE_BLE_UN
        InlineBrTarget_size,            // CEE_BLT_UN
        InlineSwitch_size,              // CEE_SWITCH
        InlineNone_size,                // CEE_LDIND_I1
        InlineNone_size,                // CEE_LDIND_U1
        InlineNone_size,                // CEE_LDIND_I2
        InlineNone_size,                // CEE_LDIND_U2
        InlineNone_size,                // CEE_LDIND_I4
        InlineNone_size,                // CEE_LDIND_U4
        InlineNone_size,                // CEE_LDIND_I8
        InlineNone_size,                // CEE_LDIND_I
        InlineNone_size,                // CEE_LDIND_R4
        InlineNone_size,                // CEE_LDIND_R8
        InlineNone_size,                // CEE_LDIND_REF
        InlineNone_size,                // CEE_STIND_REF
        InlineNone_size,                // CEE_STIND_I1
        InlineNone_size,                // CEE_STIND_I2
        InlineNone_size,                // CEE_STIND_I4
        InlineNone_size,                // CEE_STIND_I8
        InlineNone_size,                // CEE_STIND_R4
        InlineNone_size,                // CEE_STIND_R8
        InlineNone_size,                // CEE_ADD
        InlineNone_size,                // CEE_SUB
        InlineNone_size,                // CEE_MUL
        InlineNone_size,                // CEE_DIV
        InlineNone_size,                // CEE_DIV_UN
        InlineNone_size,                // CEE_REM
        InlineNone_size,                // CEE_REM_UN
        InlineNone_size,                // CEE_AND
        InlineNone_size,                // CEE_OR
        InlineNone_size,                // CEE_XOR
        InlineNone_size,                // CEE_SHL
        InlineNone_size,                // CEE_SHR
        InlineNone_size,                // CEE_SHR_UN
        InlineNone_size,                // CEE_NEG
        InlineNone_size,                // CEE_NOT
        InlineNone_size,                // CEE_CONV_I1
        InlineNone_size,                // CEE_CONV_I2
        InlineNone_size,                // CEE_CONV_I4
        InlineNone_size,                // CEE_CONV_I8
        InlineNone_size,                // CEE_CONV_R4
        InlineNone_size,                // CEE_CONV_R8
        InlineNone_size,                // CEE_CONV_U4
        InlineNone_size,                // CEE_CONV_U8
        InlineMethod_size,              // CEE_CALLVIRT
        InlineType_size,                // CEE_CPOBJ
        InlineType_size,                // CEE_LDOBJ
        InlineString_size,              // CEE_LDSTR
        InlineMethod_size,              // CEE_NEWOBJ
        InlineType_size,                // CEE_CASTCLASS
        InlineType_size,                // CEE_ISINST
        InlineNone_size,                // CEE_CONV_R_UN
        InlineNone_size,                // CEE_UNUSED58
        InlineNone_size,                // CEE_UNUSED1
        InlineType_size,                // CEE_UNBOX
        InlineNone_size,                // CEE_THROW
        InlineField_size,               // CEE_LDFLD
        InlineField_size,               // CEE_LDFLDA
        InlineField_size,               // CEE_STFLD
        InlineField_size,               // CEE_LDSFLD
        InlineField_size,               // CEE_LDSFLDA
        InlineField_size,               // CEE_STSFLD
        InlineType_size,                // CEE_STOBJ
        InlineNone_size,                // CEE_CONV_OVF_I1_UN
        InlineNone_size,                // CEE_CONV_OVF_I2_UN
        InlineNone_size,                // CEE_CONV_OVF_I4_UN
        InlineNone_size,                // CEE_CONV_OVF_I8_UN
        InlineNone_size,                // CEE_CONV_OVF_U1_UN
        InlineNone_size,                // CEE_CONV_OVF_U2_UN
        InlineNone_size,                // CEE_CONV_OVF_U4_UN
        InlineNone_size,                // CEE_CONV_OVF_U8_UN
        InlineNone_size,                // CEE_CONV_OVF_I_UN
        InlineNone_size,                // CEE_CONV_OVF_U_UN
        InlineType_size,                // CEE_BOX
        InlineType_size,                // CEE_NEWARR
        InlineNone_size,                // CEE_LDLEN
        InlineType_size,                // CEE_LDELEMA
        InlineNone_size,                // CEE_LDELEM_I1
        InlineNone_size,                // CEE_LDELEM_U1
        InlineNone_size,                // CEE_LDELEM_I2
        InlineNone_size,                // CEE_LDELEM_U2
        InlineNone_size,                // CEE_LDELEM_I4
        InlineNone_size,                // CEE_LDELEM_U4
        InlineNone_size,                // CEE_LDELEM_I8
        InlineNone_size,                // CEE_LDELEM_I
        InlineNone_size,                // CEE_LDELEM_R4
        InlineNone_size,                // CEE_LDELEM_R8
        InlineNone_size,                // CEE_LDELEM_REF
        InlineNone_size,                // CEE_STELEM_I
        InlineNone_size,                // CEE_STELEM_I1
        InlineNone_size,                // CEE_STELEM_I2
        InlineNone_size,                // CEE_STELEM_I4
        InlineNone_size,                // CEE_STELEM_I8
        InlineNone_size,                // CEE_STELEM_R4
        InlineNone_size,                // CEE_STELEM_R8
        InlineNone_size,                // CEE_STELEM_REF
        InlineType_size,                // CEE_LDELEM
        InlineType_size,                // CEE_STELEM
        InlineType_size,                // CEE_UNBOX_ANY
        InlineNone_size,                // CEE_UNUSED5
        InlineNone_size,                // CEE_UNUSED6
        InlineNone_size,                // CEE_UNUSED7
        InlineNone_size,                // CEE_UNUSED8
        InlineNone_size,                // CEE_UNUSED9
        InlineNone_size,                // CEE_UNUSED10
        InlineNone_size,                // CEE_UNUSED11
        InlineNone_size,                // CEE_UNUSED12
        InlineNone_size,                // CEE_UNUSED13
        InlineNone_size,                // CEE_UNUSED14
        InlineNone_size,                // CEE_UNUSED15
        InlineNone_size,                // CEE_UNUSED16
        InlineNone_size,                // CEE_UNUSED17
        InlineNone_size,                // CEE_CONV_OVF_I1
        InlineNone_size,                // CEE_CONV_OVF_U1
        InlineNone_size,                // CEE_CONV_OVF_I2
        InlineNone_size,                // CEE_CONV_OVF_U2
        InlineNone_size,                // CEE_CONV_OVF_I4
        InlineNone_size,                // CEE_CONV_OVF_U4
        InlineNone_size,                // CEE_CONV_OVF_I8
        InlineNone_size,                // CEE_CONV_OVF_U8
        InlineNone_size,                // CEE_UNUSED50
        InlineNone_size,                // CEE_UNUSED18
        InlineNone_size,                // CEE_UNUSED19
        InlineNone_size,                // CEE_UNUSED20
        InlineNone_size,                // CEE_UNUSED21
        InlineNone_size,                // CEE_UNUSED22
        InlineNone_size,                // CEE_UNUSED23
        InlineType_size,                // CEE_REFANYVAL
        InlineNone_size,                // CEE_CKFINITE
        InlineNone_size,                // CEE_UNUSED24
        InlineNone_size,                // CEE_UNUSED25
        InlineType_size,                // CEE_MKREFANY
        InlineNone_size,                // CEE_UNUSED59
        InlineNone_size,                // CEE_UNUSED60
        InlineNone_size,                // CEE_UNUSED61
        InlineNone_size,                // CEE_UNUSED62
        InlineNone_size,                // CEE_UNUSED63
        InlineNone_size,                // CEE_UNUSED64
        InlineNone_size,                // CEE_UNUSED65
        InlineNone_size,                // CEE_UNUSED66
        InlineNone_size,                // CEE_UNUSED67
        InlineTok_size,                 // CEE_LDTOKEN
        InlineNone_size,                // CEE_CONV_U2
        InlineNone_size,                // CEE_CONV_U1
        InlineNone_size,                // CEE_CONV_I
        InlineNone_size,                // CEE_CONV_OVF_I
        InlineNone_size,                // CEE_CONV_OVF_U
        InlineNone_size,                // CEE_ADD_OVF
        InlineNone_size,                // CEE_ADD_OVF_UN
        InlineNone_size,                // CEE_MUL_OVF
        InlineNone_size,                // CEE_MUL_OVF_UN
        InlineNone_size,                // CEE_SUB_OVF
        InlineNone_size,                // CEE_SUB_OVF_UN
        InlineNone_size,                // CEE_ENDFINALLY
        InlineBrTarget_size,            // CEE_LEAVE
        ShortInlineBrTarget_size,       // CEE_LEAVE_S
        InlineNone_size,                // CEE_STIND_I
        InlineNone_size,                // CEE_CONV_U
        InlineNone_size,                // CEE_UNUSED26
        InlineNone_size,                // CEE_UNUSED27
        InlineNone_size,                // CEE_UNUSED28
        InlineNone_size,                // CEE_UNUSED29
        InlineNone_size,                // CEE_UNUSED30
        InlineNone_size,                // CEE_UNUSED31
        InlineNone_size,                // CEE_UNUSED32
        InlineNone_size,                // CEE_UNUSED33
        InlineNone_size,                // CEE_UNUSED34
        InlineNone_size,                // CEE_UNUSED35
        InlineNone_size,                // CEE_UNUSED36
        InlineNone_size,                // CEE_UNUSED37
        InlineNone_size,                // CEE_UNUSED38
        InlineNone_size,                // CEE_UNUSED39
        InlineNone_size,                // CEE_UNUSED40
        InlineNone_size,                // CEE_UNUSED41
        InlineNone_size,                // CEE_UNUSED42
        InlineNone_size,                // CEE_UNUSED43
        InlineNone_size,                // CEE_UNUSED44
        InlineNone_size,                // CEE_UNUSED45
        InlineNone_size,                // CEE_UNUSED46
        InlineNone_size,                // CEE_UNUSED47
        InlineNone_size,                // CEE_UNUSED48
        InlineNone_size,                // CEE_PREFIX7
        InlineNone_size,                // CEE_PREFIX6
        InlineNone_size,                // CEE_PREFIX5
        InlineNone_size,                // CEE_PREFIX4
        InlineNone_size,                // CEE_PREFIX3
        InlineNone_size,                // CEE_PREFIX2
        InlineNone_size,                // CEE_PREFIX1
        InlineNone_size,                // CEE_PREFIXREF

        InlineNone_size,                // CEE_ARGLIST
        InlineNone_size,                // CEE_CEQ
        InlineNone_size,                // CEE_CGT
        InlineNone_size,                // CEE_CGT_UN
        InlineNone_size,                // CEE_CLT
        InlineNone_size,                // CEE_CLT_UN
        InlineMethod_size,              // CEE_LDFTN
        InlineMethod_size,              // CEE_LDVIRTFTN
        InlineNone_size,                // CEE_UNUSED56
        InlineVar_size,                 // CEE_LDARG
        InlineVar_size,                 // CEE_LDARGA
        InlineVar_size,                 // CEE_STARG
        InlineVar_size,                 // CEE_LDLOC
        InlineVar_size,                 // CEE_LDLOCA
        InlineVar_size,                 // CEE_STLOC
        InlineNone_size,                // CEE_LOCALLOC
        InlineNone_size,                // CEE_UNUSED57
        InlineNone_size,                // CEE_ENDFILTER
        ShortInlineI_size,              // CEE_UNALIGNED
        InlineNone_size,                // CEE_VOLATILE
        InlineNone_size,                // CEE_TAILCALL
        InlineType_size,                // CEE_INITOBJ
        InlineType_size,                // CEE_CONSTRAINED
        InlineNone_size,                // CEE_CPBLK
        InlineNone_size,                // CEE_INITBLK
        InlineNone_size,                // CEE_UNUSED69
        InlineNone_size,                // CEE_RETHROW
        InlineNone_size,                // CEE_UNUSED51
        InlineType_size,                // CEE_SIZEOF
        InlineNone_size,                // CEE_REFANYTYPE
        InlineNone_size,                // CEE_READONLY
        InlineNone_size,                // CEE_UNUSED53
        InlineNone_size,                // CEE_UNUSED54
        InlineNone_size,                // CEE_UNUSED55
        InlineNone_size,                // CEE_UNUSED70

#if !OPDEF_REAL_OPCODES_ONLY
        InlineNone_size,                // CEE_ILLEGAL
        InlineNone_size,                // CEE_MACRO_END
        InlineNone_size,                // CEE_CODE_LABEL
#endif
    ];

    extension(OPCODE opcode)
    {
#if DEBUG
        public OPCODE_FORMAT ArgKind
        {
            get
            {
                assert(s_argKinds.Length == (int)(CEE_COUNT));
                return s_argKinds[(int)(opcode)];
            }
        }

        public OpFlow FlowKind
        {
            get
            {
                assert(s_flowKinds.Length == (int)(CEE_COUNT));
                return s_flowKinds[(int)(opcode)];
            }
        }

        public string Name
        {
            get
            {
                assert(s_names.Length == (int)(CEE_COUNT));
                return s_names[(int)(opcode)];
            }
        }
#endif

        public byte Size
        {
            get
            {
                assert(s_sizes.Length == (int)(CEE_COUNT));
                return s_sizes[(int)(opcode)];
            }
        }
    }
}
