<?xml version="1.0" encoding="utf-8"?>
<!-- Copyright © Tanner Gooding and Contributors. Licensed under the MIT License (MIT). See License.md in the repository root for more information. -->
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net10.0</TargetFrameworks>
  </PropertyGroup>

  <PropertyGroup>
    <!-- CS1591: Missing XML comment for publicly visible type or member 'Type_or_Member' -->
    <!-- IDE0060: Remove unused parameter -->
    <!-- IDE0130: Namespace does not match folder structure-->
    <NoWarn>$(NoWarn);CS1591;IDE0060;IDE0130</NoWarn>
  </PropertyGroup>

</Project>
