// Copyright © Tanner Gooding and Contributors. Licensed under the MIT License (MIT). See License.md in the repository root for more information.
//
// Based on the RyuJIT compiler from dotnet/runtime.
// Original source is Copyright (c) .NET Foundation and Contributors. Licensed under the MIT License (MIT).

global using static RyuJitSharp.CORINFO_InstructionSet;

namespace RyuJitSharp;

public enum CORINFO_InstructionSet
{
    InstructionSet_ILLEGAL = 0,

#if TARGET_XARCH
    InstructionSet_X86Base,
    InstructionSet_AVX,
    InstructionSet_AVX2,
    InstructionSet_AVX512,
    InstructionSet_AVX512v2,
    InstructionSet_AVX512v3,
    InstructionSet_AVX10v1,
    InstructionSet_AVX10v2,
    InstructionSet_APX,
    InstructionSet_AES,
    InstructionSet_AES_V256,
    InstructionSet_AES_V512,
    InstructionSet_AVX512VP2INTERSECT,
    InstructionSet_AVXIFMA,
    InstructionSet_AVXVNNI,
    InstructionSet_AVX512BMM,
    InstructionSet_GFNI,
    InstructionSet_GFNI_V256,
    InstructionSet_GFNI_V512,
    InstructionSet_SHA,
    InstructionSet_WAITPKG,
    InstructionSet_X86Serialize,
    InstructionSet_Vector128,
    InstructionSet_Vector256,
    InstructionSet_Vector512,
    InstructionSet_VectorT128,
    InstructionSet_VectorT256,
    InstructionSet_VectorT512,
    InstructionSet_AVXVNNIINT,
    InstructionSet_AVXVNNIINT_V512,
    InstructionSet_X86Base_X64,
    InstructionSet_AVX_X64,
    InstructionSet_AVX2_X64,
    InstructionSet_AVX512_X64,
    InstructionSet_AVX512v2_X64,
    InstructionSet_AVX512v3_X64,
    InstructionSet_AVX10v1_X64,
    InstructionSet_AVX10v2_X64,
    InstructionSet_AES_X64,
    InstructionSet_AVX512VP2INTERSECT_X64,
    InstructionSet_AVXIFMA_X64,
    InstructionSet_AVXVNNI_X64,
    InstructionSet_GFNI_X64,
    InstructionSet_SHA_X64,
    InstructionSet_WAITPKG_X64,
    InstructionSet_X86Serialize_X64,
#elif TARGET_ARM64
    InstructionSet_ArmBase,
    InstructionSet_AdvSimd,
    InstructionSet_Aes,
    InstructionSet_Crc32,
    InstructionSet_Dp,
    InstructionSet_Rdm,
    InstructionSet_Sha1,
    InstructionSet_Sha256,
    InstructionSet_Atomics,
    InstructionSet_Vector64,
    InstructionSet_Vector128,
    InstructionSet_VectorT,
    InstructionSet_Dczva,
    InstructionSet_Rcpc,
    InstructionSet_VectorT128,
    InstructionSet_Rcpc2,
    InstructionSet_Sve,
    InstructionSet_Sve2,
    InstructionSet_Sha3,
    InstructionSet_Sm4,
    InstructionSet_SveAes,
    InstructionSet_SveSha3,
    InstructionSet_SveSm4,
    InstructionSet_ArmBase_Arm64,
    InstructionSet_AdvSimd_Arm64,
    InstructionSet_Aes_Arm64,
    InstructionSet_Crc32_Arm64,
    InstructionSet_Dp_Arm64,
    InstructionSet_Rdm_Arm64,
    InstructionSet_Sha1_Arm64,
    InstructionSet_Sha256_Arm64,
    InstructionSet_Sve_Arm64,
    InstructionSet_Sve2_Arm64,
    InstructionSet_Sha3_Arm64,
    InstructionSet_Sm4_Arm64,
    InstructionSet_SveAes_Arm64,
    InstructionSet_SveSha3_Arm64,
    InstructionSet_SveSm4_Arm64,
#elif TARGET_RISCV64
    InstructionSet_RiscV64Base,
    InstructionSet_Zba,
    InstructionSet_Zbb,
    InstructionSet_Zbs,
#endif

    InstructionSet_NONE = 127,
}