// Copyright © Tanner Gooding and Contributors. Licensed under the MIT License (MIT). See License.md in the repository root for more information.
//
// Based on the RyuJIT compiler from dotnet/runtime.
// Original source is Copyright (c) .NET Foundation and Contributors. Licensed under the MIT License (MIT).

using System;

namespace RyuJitSharp;

public partial class CodeSeqSM
{
    private static ReadOnlySpan<SM_OPCODE> s_opcodeMap => [
        SM_NOSHOW, // CEE_NOP
        SM_NOSHOW, // CEE_BREAK
        SM_LDARG_0, // CEE_LDARG_0
        SM_LDARG_1, // CEE_LDARG_1
        SM_LDARG_2, // CEE_LDARG_2
        SM_LDARG_3, // CEE_LDARG_3
        SM_LDLOC_0, // CEE_LDLOC_0
        SM_LDLOC_1, // CEE_LDLOC_1
        SM_LDLOC_2, // CEE_LDLOC_2
        SM_LDLOC_3, // CEE_LDLOC_3
        SM_STLOC_0, // CEE_STLOC_0
        SM_STLOC_1, // CEE_STLOC_1
        SM_STLOC_2, // CEE_STLOC_2
        SM_STLOC_3, // CEE_STLOC_3
        SM_LDARG_S, // CEE_LDARG_S
        SM_LDARGA_S, // CEE_LDARGA_S
        SM_STARG_S, // CEE_STARG_S
        SM_LDLOC_S, // CEE_LDLOC_S
        SM_LDLOCA_S, // CEE_LDLOCA_S
        SM_STLOC_S, // CEE_STLOC_S
        SM_LDNULL, // CEE_LDNULL
        SM_LDC_I4_M1, // CEE_LDC_I4_M1
        SM_LDC_I4_0, // CEE_LDC_I4_0
        SM_LDC_I4_1, // CEE_LDC_I4_1
        SM_LDC_I4_2, // CEE_LDC_I4_2
        SM_LDC_I4_3, // CEE_LDC_I4_3
        SM_LDC_I4_4, // CEE_LDC_I4_4
        SM_LDC_I4_5, // CEE_LDC_I4_5
        SM_LDC_I4_6, // CEE_LDC_I4_6
        SM_LDC_I4_7, // CEE_LDC_I4_7
        SM_LDC_I4_8, // CEE_LDC_I4_8
        SM_LDC_I4_S, // CEE_LDC_I4_S
        SM_LDC_I4, // CEE_LDC_I4
        SM_LDC_I8, // CEE_LDC_I8
        SM_LDC_R4, // CEE_LDC_R4
        SM_LDC_R8, // CEE_LDC_R8
        SM_UNUSED, // CEE_UNUSED49
        SM_DUP, // CEE_DUP
        SM_POP, // CEE_POP
        SM_NOSHOW, // CEE_JMP
        SM_CALL, // CEE_CALL
        SM_CALLI, // CEE_CALLI
        SM_RET, // CEE_RET
        SM_BR_S, // CEE_BR_S
        SM_BRFALSE_S, // CEE_BRFALSE_S
        SM_BRTRUE_S, // CEE_BRTRUE_S
        SM_BEQ_S, // CEE_BEQ_S
        SM_BGE_S, // CEE_BGE_S
        SM_BGT_S, // CEE_BGT_S
        SM_BLE_S, // CEE_BLE_S
        SM_BLT_S, // CEE_BLT_S
        SM_BNE_UN_S, // CEE_BNE_UN_S
        SM_BGE_UN_S, // CEE_BGE_UN_S
        SM_BGT_UN_S, // CEE_BGT_UN_S
        SM_BLE_UN_S, // CEE_BLE_UN_S
        SM_BLT_UN_S, // CEE_BLT_UN_S
        SM_LONG_BRANCH, // CEE_BR
        SM_LONG_BRANCH, // CEE_BRFALSE
        SM_LONG_BRANCH, // CEE_BRTRUE
        SM_LONG_BRANCH, // CEE_BEQ
        SM_LONG_BRANCH, // CEE_BGE
        SM_LONG_BRANCH, // CEE_BGT
        SM_LONG_BRANCH, // CEE_BLE
        SM_LONG_BRANCH, // CEE_BLT
        SM_LONG_BRANCH, // CEE_BNE_UN
        SM_LONG_BRANCH, // CEE_BGE_UN
        SM_LONG_BRANCH, // CEE_BGT_UN
        SM_LONG_BRANCH, // CEE_BLE_UN
        SM_LONG_BRANCH, // CEE_BLT_UN
        SM_SWITCH, // CEE_SWITCH
        SM_LDIND_I1, // CEE_LDIND_I1
        SM_LDIND_U1, // CEE_LDIND_U1
        SM_LDIND_I2, // CEE_LDIND_I2
        SM_LDIND_U2, // CEE_LDIND_U2
        SM_LDIND_I4, // CEE_LDIND_I4
        SM_LDIND_U4, // CEE_LDIND_U4
        SM_LDIND_I8, // CEE_LDIND_I8
        SM_LDIND_I, // CEE_LDIND_I
        SM_LDIND_R4, // CEE_LDIND_R4
        SM_LDIND_R8, // CEE_LDIND_R8
        SM_LDIND_REF, // CEE_LDIND_REF
        SM_STIND_REF, // CEE_STIND_REF
        SM_STIND_I1, // CEE_STIND_I1
        SM_STIND_I2, // CEE_STIND_I2
        SM_STIND_I4, // CEE_STIND_I4
        SM_STIND_I8, // CEE_STIND_I8
        SM_STIND_R4, // CEE_STIND_R4
        SM_STIND_R8, // CEE_STIND_R8
        SM_ADD, // CEE_ADD
        SM_SUB, // CEE_SUB
        SM_MUL, // CEE_MUL
        SM_DIV, // CEE_DIV
        SM_DIV_UN, // CEE_DIV_UN
        SM_REM, // CEE_REM
        SM_REM_UN, // CEE_REM_UN
        SM_AND, // CEE_AND
        SM_OR, // CEE_OR
        SM_XOR, // CEE_XOR
        SM_SHL, // CEE_SHL
        SM_SHR, // CEE_SHR
        SM_SHR_UN, // CEE_SHR_UN
        SM_NEG, // CEE_NEG
        SM_NOT, // CEE_NOT
        SM_CONV_I1, // CEE_CONV_I1
        SM_CONV_I2, // CEE_CONV_I2
        SM_CONV_I4, // CEE_CONV_I4
        SM_CONV_I8, // CEE_CONV_I8
        SM_CONV_R4, // CEE_CONV_R4
        SM_CONV_R8, // CEE_CONV_R8
        SM_CONV_U4, // CEE_CONV_U4
        SM_CONV_U8, // CEE_CONV_U8
        SM_CALLVIRT, // CEE_CALLVIRT
        SM_CPOBJ, // CEE_CPOBJ
        SM_LDOBJ, // CEE_LDOBJ
        SM_LDSTR, // CEE_LDSTR
        SM_NEWOBJ, // CEE_NEWOBJ
        SM_CASTCLASS, // CEE_CASTCLASS
        SM_ISINST, // CEE_ISINST
        SM_CONV_R_UN, // CEE_CONV_R_UN
        SM_UNUSED, // CEE_UNUSED58
        SM_UNUSED, // CEE_UNUSED1
        SM_UNBOX, // CEE_UNBOX
        SM_THROW, // CEE_THROW
        SM_LDFLD, // CEE_LDFLD
        SM_LDFLDA, // CEE_LDFLDA
        SM_STFLD, // CEE_STFLD
        SM_LDSFLD, // CEE_LDSFLD
        SM_LDSFLDA, // CEE_LDSFLDA
        SM_STSFLD, // CEE_STSFLD
        SM_STOBJ, // CEE_STOBJ
        SM_OVF_NOTYPE_UN, // CEE_CONV_OVF_I1_UN
        SM_OVF_NOTYPE_UN, // CEE_CONV_OVF_I2_UN
        SM_OVF_NOTYPE_UN, // CEE_CONV_OVF_I4_UN
        SM_OVF_NOTYPE_UN, // CEE_CONV_OVF_I8_UN
        SM_OVF_NOTYPE_UN, // CEE_CONV_OVF_U1_UN
        SM_OVF_NOTYPE_UN, // CEE_CONV_OVF_U2_UN
        SM_OVF_NOTYPE_UN, // CEE_CONV_OVF_U4_UN
        SM_OVF_NOTYPE_UN, // CEE_CONV_OVF_U8_UN
        SM_OVF_NOTYPE_UN, // CEE_CONV_OVF_I_UN
        SM_OVF_NOTYPE_UN, // CEE_CONV_OVF_U_UN
        SM_BOX, // CEE_BOX
        SM_NEWARR, // CEE_NEWARR
        SM_LDLEN, // CEE_LDLEN
        SM_LDELEMA, // CEE_LDELEMA
        SM_LDELEM_I1, // CEE_LDELEM_I1
        SM_LDELEM_U1, // CEE_LDELEM_U1
        SM_LDELEM_I2, // CEE_LDELEM_I2
        SM_LDELEM_U2, // CEE_LDELEM_U2
        SM_LDELEM_I4, // CEE_LDELEM_I4
        SM_LDELEM_U4, // CEE_LDELEM_U4
        SM_LDELEM_I8, // CEE_LDELEM_I8
        SM_LDELEM_I, // CEE_LDELEM_I
        SM_LDELEM_R4, // CEE_LDELEM_R4
        SM_LDELEM_R8, // CEE_LDELEM_R8
        SM_LDELEM_REF, // CEE_LDELEM_REF
        SM_STELEM_I, // CEE_STELEM_I
        SM_STELEM_I1, // CEE_STELEM_I1
        SM_STELEM_I2, // CEE_STELEM_I2
        SM_STELEM_I4, // CEE_STELEM_I4
        SM_STELEM_I8, // CEE_STELEM_I8
        SM_STELEM_R4, // CEE_STELEM_R4
        SM_STELEM_R8, // CEE_STELEM_R8
        SM_STELEM_REF, // CEE_STELEM_REF
        SM_LDELEM, // CEE_LDELEM
        SM_STELEM, // CEE_STELEM
        SM_UNBOX_ANY, // CEE_UNBOX_ANY
        SM_UNUSED, // CEE_UNUSED5
        SM_UNUSED, // CEE_UNUSED6
        SM_UNUSED, // CEE_UNUSED7
        SM_UNUSED, // CEE_UNUSED8
        SM_UNUSED, // CEE_UNUSED9
        SM_UNUSED, // CEE_UNUSED10
        SM_UNUSED, // CEE_UNUSED11
        SM_UNUSED, // CEE_UNUSED12
        SM_UNUSED, // CEE_UNUSED13
        SM_UNUSED, // CEE_UNUSED14
        SM_UNUSED, // CEE_UNUSED15
        SM_UNUSED, // CEE_UNUSED16
        SM_UNUSED, // CEE_UNUSED17
        SM_CONV_OVF_I1, // CEE_CONV_OVF_I1
        SM_CONV_OVF_U1, // CEE_CONV_OVF_U1
        SM_CONV_OVF_I2, // CEE_CONV_OVF_I2
        SM_CONV_OVF_U2, // CEE_CONV_OVF_U2
        SM_CONV_OVF_I4, // CEE_CONV_OVF_I4
        SM_CONV_OVF_U4, // CEE_CONV_OVF_U4
        SM_CONV_OVF_I8, // CEE_CONV_OVF_I8
        SM_CONV_OVF_U8, // CEE_CONV_OVF_U8
        SM_UNUSED, // CEE_UNUSED50
        SM_UNUSED, // CEE_UNUSED18
        SM_UNUSED, // CEE_UNUSED19
        SM_UNUSED, // CEE_UNUSED20
        SM_UNUSED, // CEE_UNUSED21
        SM_UNUSED, // CEE_UNUSED22
        SM_UNUSED, // CEE_UNUSED23
        SM_REFANYVAL, // CEE_REFANYVAL
        SM_CKFINITE, // CEE_CKFINITE
        SM_UNUSED, // CEE_UNUSED24
        SM_UNUSED, // CEE_UNUSED25
        SM_MKREFANY, // CEE_MKREFANY
        SM_UNUSED, // CEE_UNUSED59
        SM_UNUSED, // CEE_UNUSED60
        SM_UNUSED, // CEE_UNUSED61
        SM_UNUSED, // CEE_UNUSED62
        SM_UNUSED, // CEE_UNUSED63
        SM_UNUSED, // CEE_UNUSED64
        SM_UNUSED, // CEE_UNUSED65
        SM_UNUSED, // CEE_UNUSED66
        SM_UNUSED, // CEE_UNUSED67
        SM_LDTOKEN, // CEE_LDTOKEN
        SM_CONV_U2, // CEE_CONV_U2
        SM_CONV_U1, // CEE_CONV_U1
        SM_CONV_I, // CEE_CONV_I
        SM_CONV_OVF_I, // CEE_CONV_OVF_I
        SM_CONV_OVF_U, // CEE_CONV_OVF_U
        SM_ADD_OVF, // CEE_ADD_OVF
        SM_OVF_NOTYPE_UN, // CEE_ADD_OVF_UN
        SM_MUL_OVF, // CEE_MUL_OVF
        SM_OVF_NOTYPE_UN, // CEE_MUL_OVF_UN
        SM_SUB_OVF, // CEE_SUB_OVF
        SM_OVF_NOTYPE_UN, // CEE_SUB_OVF_UN
        SM_NOSHOW, // CEE_ENDFINALLY
        SM_NOSHOW, // CEE_LEAVE
        SM_LEAVE_S, // CEE_LEAVE_S
        SM_STIND_I, // CEE_STIND_I
        SM_CONV_U, // CEE_CONV_U
        SM_UNUSED, // CEE_UNUSED26
        SM_UNUSED, // CEE_UNUSED27
        SM_UNUSED, // CEE_UNUSED28
        SM_UNUSED, // CEE_UNUSED29
        SM_UNUSED, // CEE_UNUSED30
        SM_UNUSED, // CEE_UNUSED31
        SM_UNUSED, // CEE_UNUSED32
        SM_UNUSED, // CEE_UNUSED33
        SM_UNUSED, // CEE_UNUSED34
        SM_UNUSED, // CEE_UNUSED35
        SM_UNUSED, // CEE_UNUSED36
        SM_UNUSED, // CEE_UNUSED37
        SM_UNUSED, // CEE_UNUSED38
        SM_UNUSED, // CEE_UNUSED39
        SM_UNUSED, // CEE_UNUSED40
        SM_UNUSED, // CEE_UNUSED41
        SM_UNUSED, // CEE_UNUSED42
        SM_UNUSED, // CEE_UNUSED43
        SM_UNUSED, // CEE_UNUSED44
        SM_UNUSED, // CEE_UNUSED45
        SM_UNUSED, // CEE_UNUSED46
        SM_UNUSED, // CEE_UNUSED47
        SM_UNUSED, // CEE_UNUSED48
        SM_PREFIX_N, // CEE_PREFIX7
        SM_PREFIX_N, // CEE_PREFIX6
        SM_PREFIX_N, // CEE_PREFIX5
        SM_PREFIX_N, // CEE_PREFIX4
        SM_PREFIX_N, // CEE_PREFIX3
        SM_PREFIX_N, // CEE_PREFIX2
        SM_PREFIX_N, // CEE_PREFIX1
        SM_PREFIX_N, // CEE_PREFIXREF
        SM_ARGLIST, // CEE_ARGLIST
        SM_CEQ, // CEE_CEQ
        SM_CGT, // CEE_CGT
        SM_CGT_UN, // CEE_CGT_UN
        SM_CLT, // CEE_CLT
        SM_CLT_UN, // CEE_CLT_UN
        SM_LDFTN, // CEE_LDFTN
        SM_LDVIRTFTN, // CEE_LDVIRTFTN
        SM_UNUSED, // CEE_UNUSED56
        SM_LONG_LOC_ARG, // CEE_LDARG
        SM_LONG_LOC_ARG, // CEE_LDARGA
        SM_LONG_LOC_ARG, // CEE_STARG
        SM_LONG_LOC_ARG, // CEE_LDLOC
        SM_LONG_LOC_ARG, // CEE_LDLOCA
        SM_LONG_LOC_ARG, // CEE_STLOC
        SM_LOCALLOC, // CEE_LOCALLOC
        SM_UNUSED, // CEE_UNUSED57
        SM_NOSHOW, // CEE_ENDFILTER
        SM_UNALIGNED, // CEE_UNALIGNED
        SM_VOLATILE, // CEE_VOLATILE
        SM_TAILCALL, // CEE_TAILCALL
        SM_INITOBJ, // CEE_INITOBJ
        SM_CONSTRAINED, // CEE_CONSTRAINED
        SM_CPBLK, // CEE_CPBLK
        SM_INITBLK, // CEE_INITBLK
        SM_UNUSED, // CEE_UNUSED69
        SM_RETHROW, // CEE_RETHROW
        SM_UNUSED, // CEE_UNUSED51
        SM_SIZEOF, // CEE_SIZEOF
        SM_REFANYTYPE, // CEE_REFANYTYPE
        SM_READONLY, // CEE_READONLY
        SM_UNUSED, // CEE_UNUSED53
        SM_UNUSED, // CEE_UNUSED54
        SM_UNUSED, // CEE_UNUSED55
        SM_UNUSED, // CEE_UNUSED70
        SM_UNUSED, // CEE_ILLEGAL
        SM_UNUSED, // CEE_MACRO_END
        SM_UNUSED, // CEE_CODE_LABEL
    ];
}