<?xml version="1.0" encoding="utf-8"?>
<!-- Copyright © Tanner Gooding and Contributors. Licensed under the MIT License (MIT). See License.md in the repository root for more information. -->
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net11.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\sources\Core\RyuJitSharp.csproj" />
  </ItemGroup>

  <Target Name="GetRyuJitCompileConstants" BeforeTargets="CoreCompile">
    <MSBuild Projects="@(ProjectReference)" Targets="GetRyuJitCompileConstants" Properties="Configuration=$(Configuration)">
      <Output TaskParameter="TargetOutputs" ItemName="_RyuJitCompileConstants" />
    </MSBuild>
    <PropertyGroup>
      <DefineConstants>$(DefineConstants);@(_RyuJitCompileConstants)</DefineConstants>
    </PropertyGroup>
  </Target>

</Project>
