// Copyright © Tanner Gooding and Contributors. Licensed under the MIT License (MIT). See License.md in the repository root for more information.
//
// Based on the RyuJIT compiler from dotnet/runtime.
// Original source is Copyright (c) .NET Foundation and Contributors. Licensed under the MIT License (MIT).

namespace RyuJitSharp;

public partial struct JitMetrics
{
    public int ActualCodeBytes;
    public int AllocatedHotCodeBytes;
    public int AllocatedColdCodeBytes;
    public int ReadOnlyDataBytes;
    public int GCInfoBytes;
    public int EHClauseCount;
    public int PhysicallyPromotedFields;
    public int LoopsFoundDuringOpts;
    public int LoopsInverted;
    public int LoopsCloned;
    public int LoopsRejectedForInsufficientBenefit;
    public int LoopsUnrolled;
    public int LoopAlignmentCandidates;
    public int LoopsAligned;
    public int LoopsIVWidened;
    public int WidenedIVs;
    public int UnusedIVsRemoved;
    public int LoopsMadeDownwardsCounted;
    public int LoopsStrengthReduced;
    public int VarsInSsa;
    public int HoistedExpressions;
    public int RedundantBranchesEliminated;
    public int JumpThreadingsPerformed;
    public int CseCount;
    public int BasicBlocksAtCodegen;
    public double PerfScore;
    public long BytesAllocated;
    public int ImporterBranchFold;
    public int ImporterSwitchFold;
    public int DevirtualizedCall;
    public int DevirtualizedCallUnboxedEntry;
    public int GDV;
    public int ClassGDV;
    public int MethodGDV;
    public int MultiGuessGDV;
    public int ChainedGDV;
    public int EnumeratorGDV;
    public int InlinerBranchFold;
    public int InlineAttempt;
    public int InlineCount;
    public int ProfileConsistentBeforeInline;
    public int ProfileConsistentAfterInline;
    public int ProfileConsistentBeforeMorph;
    public int ProfileConsistentAfterMorph;
    public int ProfileSynthesizedBlendedOrRepaired;
    public int ProfileInconsistentInitially;
    public int ProfileInconsistentResetLeave;
    public int ProfileInconsistentImporterBranchFold;
    public int ProfileInconsistentImporterSwitchFold;
    public int ProfileInconsistentChainedGDV;
    public int ProfileInconsistentScratchBB;
    public int ProfileInconsistentInlinerBranchFold;
    public int ProfileInconsistentInlineeScale;
    public int ProfileInconsistentInlinee;
    public int ProfileInconsistentNoReturnInlinee;
    public int ProfileInconsistentMayThrowInlinee;
    public int NewRefClassHelperCalls;
    public int StackAllocatedRefClasses;
    public int NewBoxedValueClassHelperCalls;
    public int StackAllocatedBoxedValueClasses;
    public int NewArrayHelperCalls;
    public int StackAllocatedArrays;
    public int LocalAssertionCount;
    public int LocalAssertionOverflow;
    public int MorphTrackedLocals;
    public int MorphLocals;
    public int EnumeratorGDVProvisionalNoEscape;
    public int EnumeratorGDVCanCloneToEnsureNoEscape;
    public int SuspensionPointsMerged;

    /// <summary>Report all metrics and their values back to the EE.</summary>
    /// <param name="compiler">Compiler instance</param>
    public readonly void report(Compiler compiler)
    {
        JitMetadata.report(compiler, nameof(ActualCodeBytes), ActualCodeBytes);
        JitMetadata.report(compiler, nameof(AllocatedHotCodeBytes), AllocatedHotCodeBytes);
        JitMetadata.report(compiler, nameof(AllocatedColdCodeBytes), AllocatedColdCodeBytes);
        JitMetadata.report(compiler, nameof(ReadOnlyDataBytes), ReadOnlyDataBytes);
        JitMetadata.report(compiler, nameof(GCInfoBytes), GCInfoBytes);
        JitMetadata.report(compiler, nameof(EHClauseCount), EHClauseCount);
        JitMetadata.report(compiler, nameof(PhysicallyPromotedFields), PhysicallyPromotedFields);
        JitMetadata.report(compiler, nameof(LoopsFoundDuringOpts), LoopsFoundDuringOpts);
        JitMetadata.report(compiler, nameof(LoopsInverted), LoopsInverted);
        JitMetadata.report(compiler, nameof(LoopsCloned), LoopsCloned);
        JitMetadata.report(compiler, nameof(LoopsRejectedForInsufficientBenefit), LoopsRejectedForInsufficientBenefit);
        JitMetadata.report(compiler, nameof(LoopsUnrolled), LoopsUnrolled);
        JitMetadata.report(compiler, nameof(LoopAlignmentCandidates), LoopAlignmentCandidates);
        JitMetadata.report(compiler, nameof(LoopsAligned), LoopsAligned);
        JitMetadata.report(compiler, nameof(LoopsIVWidened), LoopsIVWidened);
        JitMetadata.report(compiler, nameof(WidenedIVs), WidenedIVs);
        JitMetadata.report(compiler, nameof(UnusedIVsRemoved), UnusedIVsRemoved);
        JitMetadata.report(compiler, nameof(LoopsMadeDownwardsCounted), LoopsMadeDownwardsCounted);
        JitMetadata.report(compiler, nameof(LoopsStrengthReduced), LoopsStrengthReduced);
        JitMetadata.report(compiler, nameof(VarsInSsa), VarsInSsa);
        JitMetadata.report(compiler, nameof(HoistedExpressions), HoistedExpressions);
        JitMetadata.report(compiler, nameof(RedundantBranchesEliminated), RedundantBranchesEliminated);
        JitMetadata.report(compiler, nameof(JumpThreadingsPerformed), JumpThreadingsPerformed);
        JitMetadata.report(compiler, nameof(CseCount), CseCount);
        JitMetadata.report(compiler, nameof(BasicBlocksAtCodegen), BasicBlocksAtCodegen);
        JitMetadata.report(compiler, nameof(PerfScore), PerfScore);
        JitMetadata.report(compiler, nameof(BytesAllocated), BytesAllocated);
        JitMetadata.report(compiler, nameof(ImporterBranchFold), ImporterBranchFold);
        JitMetadata.report(compiler, nameof(ImporterSwitchFold), ImporterSwitchFold);
        JitMetadata.report(compiler, nameof(DevirtualizedCall), DevirtualizedCall);
        JitMetadata.report(compiler, nameof(DevirtualizedCallUnboxedEntry), DevirtualizedCallUnboxedEntry);
        JitMetadata.report(compiler, nameof(GDV), GDV);
        JitMetadata.report(compiler, nameof(ClassGDV), ClassGDV);
        JitMetadata.report(compiler, nameof(MethodGDV), MethodGDV);
        JitMetadata.report(compiler, nameof(MultiGuessGDV), MultiGuessGDV);
        JitMetadata.report(compiler, nameof(ChainedGDV), ChainedGDV);
        JitMetadata.report(compiler, nameof(EnumeratorGDV), EnumeratorGDV);
        JitMetadata.report(compiler, nameof(InlinerBranchFold), InlinerBranchFold);
        JitMetadata.report(compiler, nameof(InlineAttempt), InlineAttempt);
        JitMetadata.report(compiler, nameof(InlineCount), InlineCount);
        JitMetadata.report(compiler, nameof(ProfileConsistentBeforeInline), ProfileConsistentBeforeInline);
        JitMetadata.report(compiler, nameof(ProfileConsistentAfterInline), ProfileConsistentAfterInline);
        JitMetadata.report(compiler, nameof(ProfileConsistentBeforeMorph), ProfileConsistentBeforeMorph);
        JitMetadata.report(compiler, nameof(ProfileConsistentAfterMorph), ProfileConsistentAfterMorph);
        JitMetadata.report(compiler, nameof(ProfileSynthesizedBlendedOrRepaired), ProfileSynthesizedBlendedOrRepaired);
        JitMetadata.report(compiler, nameof(ProfileInconsistentInitially), ProfileInconsistentInitially);
        JitMetadata.report(compiler, nameof(ProfileInconsistentResetLeave), ProfileInconsistentResetLeave);
        JitMetadata.report(compiler, nameof(ProfileInconsistentImporterBranchFold), ProfileInconsistentImporterBranchFold);
        JitMetadata.report(compiler, nameof(ProfileInconsistentImporterSwitchFold), ProfileInconsistentImporterSwitchFold);
        JitMetadata.report(compiler, nameof(ProfileInconsistentChainedGDV), ProfileInconsistentChainedGDV);
        JitMetadata.report(compiler, nameof(ProfileInconsistentScratchBB), ProfileInconsistentScratchBB);
        JitMetadata.report(compiler, nameof(ProfileInconsistentInlinerBranchFold), ProfileInconsistentInlinerBranchFold);
        JitMetadata.report(compiler, nameof(ProfileInconsistentInlineeScale), ProfileInconsistentInlineeScale);
        JitMetadata.report(compiler, nameof(ProfileInconsistentInlinee), ProfileInconsistentInlinee);
        JitMetadata.report(compiler, nameof(ProfileInconsistentNoReturnInlinee), ProfileInconsistentNoReturnInlinee);
        JitMetadata.report(compiler, nameof(ProfileInconsistentMayThrowInlinee), ProfileInconsistentMayThrowInlinee);
        JitMetadata.report(compiler, nameof(NewRefClassHelperCalls), NewRefClassHelperCalls);
        JitMetadata.report(compiler, nameof(StackAllocatedRefClasses), StackAllocatedRefClasses);
        JitMetadata.report(compiler, nameof(NewBoxedValueClassHelperCalls), NewBoxedValueClassHelperCalls);
        JitMetadata.report(compiler, nameof(StackAllocatedBoxedValueClasses), StackAllocatedBoxedValueClasses);
        JitMetadata.report(compiler, nameof(NewArrayHelperCalls), NewArrayHelperCalls);
        JitMetadata.report(compiler, nameof(StackAllocatedArrays), StackAllocatedArrays);
        JitMetadata.report(compiler, nameof(LocalAssertionCount), LocalAssertionCount);
        JitMetadata.report(compiler, nameof(LocalAssertionOverflow), LocalAssertionOverflow);
        JitMetadata.report(compiler, nameof(MorphTrackedLocals), MorphTrackedLocals);
        JitMetadata.report(compiler, nameof(MorphLocals), MorphLocals);
        JitMetadata.report(compiler, nameof(EnumeratorGDVProvisionalNoEscape), EnumeratorGDVProvisionalNoEscape);
        JitMetadata.report(compiler, nameof(EnumeratorGDVCanCloneToEnsureNoEscape), EnumeratorGDVCanCloneToEnsureNoEscape);
        JitMetadata.report(compiler, nameof(SuspensionPointsMerged), SuspensionPointsMerged);
    }

#if DEBUG
    public readonly void dump()
    {
        const int NameMaxWidth = 37;

        jitprintf($"{nameof(ActualCodeBytes)}{new string(' ', NameMaxWidth + 5 - 15)}: {ActualCodeBytes}\n");
        jitprintf($"{nameof(AllocatedHotCodeBytes)}{new string(' ', NameMaxWidth + 5 - 21)}: {AllocatedHotCodeBytes}\n");
        jitprintf($"{nameof(AllocatedColdCodeBytes)}{new string(' ', NameMaxWidth + 5 - 22)}: {AllocatedColdCodeBytes}\n");
        jitprintf($"{nameof(ReadOnlyDataBytes)}{new string(' ', NameMaxWidth + 5 - 17)}: {ReadOnlyDataBytes}\n");
        jitprintf($"{nameof(GCInfoBytes)}{new string(' ', NameMaxWidth + 5 - 11)}: {GCInfoBytes}\n");
        jitprintf($"{nameof(EHClauseCount)}{new string(' ', NameMaxWidth + 5 - 13)}: {EHClauseCount}\n");
        jitprintf($"{nameof(PhysicallyPromotedFields)}{new string(' ', NameMaxWidth + 5 - 24)}: {PhysicallyPromotedFields}\n");
        jitprintf($"{nameof(LoopsFoundDuringOpts)}{new string(' ', NameMaxWidth + 5 - 20)}: {LoopsFoundDuringOpts}\n");
        jitprintf($"{nameof(LoopsInverted)}{new string(' ', NameMaxWidth + 5 - 13)}: {LoopsInverted}\n");
        jitprintf($"{nameof(LoopsCloned)}{new string(' ', NameMaxWidth + 5 - 11)}: {LoopsCloned}\n");
        jitprintf($"{nameof(LoopsRejectedForInsufficientBenefit)}{new string(' ', NameMaxWidth + 5 - 35)}: {LoopsRejectedForInsufficientBenefit}\n");
        jitprintf($"{nameof(LoopsUnrolled)}{new string(' ', NameMaxWidth + 5 - 13)}: {LoopsUnrolled}\n");
        jitprintf($"{nameof(LoopAlignmentCandidates)}{new string(' ', NameMaxWidth + 5 - 23)}: {LoopAlignmentCandidates}\n");
        jitprintf($"{nameof(LoopsAligned)}{new string(' ', NameMaxWidth + 5 - 12)}: {LoopsAligned}\n");
        jitprintf($"{nameof(LoopsIVWidened)}{new string(' ', NameMaxWidth + 5 - 14)}: {LoopsIVWidened}\n");
        jitprintf($"{nameof(WidenedIVs)}{new string(' ', NameMaxWidth + 5 - 10)}: {WidenedIVs}\n");
        jitprintf($"{nameof(UnusedIVsRemoved)}{new string(' ', NameMaxWidth + 5 - 16)}: {UnusedIVsRemoved}\n");
        jitprintf($"{nameof(LoopsMadeDownwardsCounted)}{new string(' ', NameMaxWidth + 5 - 25)}: {LoopsMadeDownwardsCounted}\n");
        jitprintf($"{nameof(LoopsStrengthReduced)}{new string(' ', NameMaxWidth + 5 - 20)}: {LoopsStrengthReduced}\n");
        jitprintf($"{nameof(VarsInSsa)}{new string(' ', NameMaxWidth + 5 - 9)}: {VarsInSsa}\n");
        jitprintf($"{nameof(HoistedExpressions)}{new string(' ', NameMaxWidth + 5 - 18)}: {HoistedExpressions}\n");
        jitprintf($"{nameof(RedundantBranchesEliminated)}{new string(' ', NameMaxWidth + 5 - 27)}: {RedundantBranchesEliminated}\n");
        jitprintf($"{nameof(JumpThreadingsPerformed)}{new string(' ', NameMaxWidth + 5 - 23)}: {JumpThreadingsPerformed}\n");
        jitprintf($"{nameof(CseCount)}{new string(' ', NameMaxWidth + 5 - 8)}: {CseCount}\n");
        jitprintf($"{nameof(BasicBlocksAtCodegen)}{new string(' ', NameMaxWidth + 5 - 20)}: {BasicBlocksAtCodegen}\n");
        jitprintf($"{nameof(PerfScore)}{new string(' ', NameMaxWidth + 5 - 9)}: {PerfScore}\n");
        jitprintf($"{nameof(BytesAllocated)}{new string(' ', NameMaxWidth + 5 - 14)}: {BytesAllocated}\n");
        jitprintf($"{nameof(ImporterBranchFold)}{new string(' ', NameMaxWidth + 5 - 18)}: {ImporterBranchFold}\n");
        jitprintf($"{nameof(ImporterSwitchFold)}{new string(' ', NameMaxWidth + 5 - 18)}: {ImporterSwitchFold}\n");
        jitprintf($"{nameof(DevirtualizedCall)}{new string(' ', NameMaxWidth + 5 - 17)}: {DevirtualizedCall}\n");
        jitprintf($"{nameof(DevirtualizedCallUnboxedEntry)}{new string(' ', NameMaxWidth + 5 - 29)}: {DevirtualizedCallUnboxedEntry}\n");
        jitprintf($"{nameof(GDV)}{new string(' ', NameMaxWidth + 5 - 3)}: {GDV}\n");
        jitprintf($"{nameof(ClassGDV)}{new string(' ', NameMaxWidth + 5 - 8)}: {ClassGDV}\n");
        jitprintf($"{nameof(MethodGDV)}{new string(' ', NameMaxWidth + 5 - 9)}: {MethodGDV}\n");
        jitprintf($"{nameof(MultiGuessGDV)}{new string(' ', NameMaxWidth + 5 - 13)}: {MultiGuessGDV}\n");
        jitprintf($"{nameof(ChainedGDV)}{new string(' ', NameMaxWidth + 5 - 10)}: {ChainedGDV}\n");
        jitprintf($"{nameof(EnumeratorGDV)}{new string(' ', NameMaxWidth + 5 - 13)}: {EnumeratorGDV}\n");
        jitprintf($"{nameof(InlinerBranchFold)}{new string(' ', NameMaxWidth + 5 - 17)}: {InlinerBranchFold}\n");
        jitprintf($"{nameof(InlineAttempt)}{new string(' ', NameMaxWidth + 5 - 13)}: {InlineAttempt}\n");
        jitprintf($"{nameof(InlineCount)}{new string(' ', NameMaxWidth + 5 - 11)}: {InlineCount}\n");
        jitprintf($"{nameof(ProfileConsistentBeforeInline)}{new string(' ', NameMaxWidth + 5 - 29)}: {ProfileConsistentBeforeInline}\n");
        jitprintf($"{nameof(ProfileConsistentAfterInline)}{new string(' ', NameMaxWidth + 5 - 28)}: {ProfileConsistentAfterInline}\n");
        jitprintf($"{nameof(ProfileConsistentBeforeMorph)}{new string(' ', NameMaxWidth + 5 - 28)}: {ProfileConsistentBeforeMorph}\n");
        jitprintf($"{nameof(ProfileConsistentAfterMorph)}{new string(' ', NameMaxWidth + 5 - 27)}: {ProfileConsistentAfterMorph}\n");
        jitprintf($"{nameof(ProfileSynthesizedBlendedOrRepaired)}{new string(' ', NameMaxWidth + 5 - 35)}: {ProfileSynthesizedBlendedOrRepaired}\n");
        jitprintf($"{nameof(ProfileInconsistentInitially)}{new string(' ', NameMaxWidth + 5 - 28)}: {ProfileInconsistentInitially}\n");
        jitprintf($"{nameof(ProfileInconsistentResetLeave)}{new string(' ', NameMaxWidth + 5 - 29)}: {ProfileInconsistentResetLeave}\n");
        jitprintf($"{nameof(ProfileInconsistentImporterBranchFold)}{new string(' ', NameMaxWidth + 5 - 37)}: {ProfileInconsistentImporterBranchFold}\n");
        jitprintf($"{nameof(ProfileInconsistentImporterSwitchFold)}{new string(' ', NameMaxWidth + 5 - 37)}: {ProfileInconsistentImporterSwitchFold}\n");
        jitprintf($"{nameof(ProfileInconsistentChainedGDV)}{new string(' ', NameMaxWidth + 5 - 29)}: {ProfileInconsistentChainedGDV}\n");
        jitprintf($"{nameof(ProfileInconsistentScratchBB)}{new string(' ', NameMaxWidth + 5 - 28)}: {ProfileInconsistentScratchBB}\n");
        jitprintf($"{nameof(ProfileInconsistentInlinerBranchFold)}{new string(' ', NameMaxWidth + 5 - 36)}: {ProfileInconsistentInlinerBranchFold}\n");
        jitprintf($"{nameof(ProfileInconsistentInlineeScale)}{new string(' ', NameMaxWidth + 5 - 31)}: {ProfileInconsistentInlineeScale}\n");
        jitprintf($"{nameof(ProfileInconsistentInlinee)}{new string(' ', NameMaxWidth + 5 - 26)}: {ProfileInconsistentInlinee}\n");
        jitprintf($"{nameof(ProfileInconsistentNoReturnInlinee)}{new string(' ', NameMaxWidth + 5 - 34)}: {ProfileInconsistentNoReturnInlinee}\n");
        jitprintf($"{nameof(ProfileInconsistentMayThrowInlinee)}{new string(' ', NameMaxWidth + 5 - 34)}: {ProfileInconsistentMayThrowInlinee}\n");
        jitprintf($"{nameof(NewRefClassHelperCalls)}{new string(' ', NameMaxWidth + 5 - 22)}: {NewRefClassHelperCalls}\n");
        jitprintf($"{nameof(StackAllocatedRefClasses)}{new string(' ', NameMaxWidth + 5 - 24)}: {StackAllocatedRefClasses}\n");
        jitprintf($"{nameof(NewBoxedValueClassHelperCalls)}{new string(' ', NameMaxWidth + 5 - 29)}: {NewBoxedValueClassHelperCalls}\n");
        jitprintf($"{nameof(StackAllocatedBoxedValueClasses)}{new string(' ', NameMaxWidth + 5 - 31)}: {StackAllocatedBoxedValueClasses}\n");
        jitprintf($"{nameof(NewArrayHelperCalls)}{new string(' ', NameMaxWidth + 5 - 19)}: {NewArrayHelperCalls}\n");
        jitprintf($"{nameof(StackAllocatedArrays)}{new string(' ', NameMaxWidth + 5 - 20)}: {StackAllocatedArrays}\n");
        jitprintf($"{nameof(LocalAssertionCount)}{new string(' ', NameMaxWidth + 5 - 19)}: {LocalAssertionCount}\n");
        jitprintf($"{nameof(LocalAssertionOverflow)}{new string(' ', NameMaxWidth + 5 - 22)}: {LocalAssertionOverflow}\n");
        jitprintf($"{nameof(MorphTrackedLocals)}{new string(' ', NameMaxWidth + 5 - 18)}: {MorphTrackedLocals}\n");
        jitprintf($"{nameof(MorphLocals)}{new string(' ', NameMaxWidth + 5 - 11)}: {MorphLocals}\n");
        jitprintf($"{nameof(EnumeratorGDVProvisionalNoEscape)}{new string(' ', NameMaxWidth + 5 - 32)}: {EnumeratorGDVProvisionalNoEscape}\n");
        jitprintf($"{nameof(EnumeratorGDVCanCloneToEnsureNoEscape)}{new string(' ', NameMaxWidth + 5 - 37)}: {EnumeratorGDVCanCloneToEnsureNoEscape}\n");
        jitprintf($"{nameof(SuspensionPointsMerged)}{new string(' ', NameMaxWidth + 5 - 22)}: {SuspensionPointsMerged}\n");
    }

    /// <summary>Merge inlinee compiler metrics to root compiler instance</summary>
    /// <param name="inlineeCompiler">inlinee compiler instance</param>
    public readonly void mergeToRoot(Compiler inlineeCompiler)
    {
        var root = inlineeCompiler.impInlineRoot;

        root.Metrics.ActualCodeBytes += inlineeCompiler.Metrics.ActualCodeBytes;
        root.Metrics.AllocatedHotCodeBytes += inlineeCompiler.Metrics.AllocatedHotCodeBytes;
        root.Metrics.AllocatedColdCodeBytes += inlineeCompiler.Metrics.AllocatedColdCodeBytes;
        root.Metrics.ReadOnlyDataBytes += inlineeCompiler.Metrics.ReadOnlyDataBytes;
        root.Metrics.GCInfoBytes += inlineeCompiler.Metrics.GCInfoBytes;
        root.Metrics.EHClauseCount += inlineeCompiler.Metrics.EHClauseCount;
        root.Metrics.PhysicallyPromotedFields += inlineeCompiler.Metrics.PhysicallyPromotedFields;
        root.Metrics.LoopsFoundDuringOpts += inlineeCompiler.Metrics.LoopsFoundDuringOpts;
        root.Metrics.LoopsInverted += inlineeCompiler.Metrics.LoopsInverted;
        root.Metrics.LoopsCloned += inlineeCompiler.Metrics.LoopsCloned;
        root.Metrics.LoopsRejectedForInsufficientBenefit += inlineeCompiler.Metrics.LoopsRejectedForInsufficientBenefit;
        root.Metrics.LoopsUnrolled += inlineeCompiler.Metrics.LoopsUnrolled;
        root.Metrics.LoopAlignmentCandidates += inlineeCompiler.Metrics.LoopAlignmentCandidates;
        root.Metrics.LoopsAligned += inlineeCompiler.Metrics.LoopsAligned;
        root.Metrics.LoopsIVWidened += inlineeCompiler.Metrics.LoopsIVWidened;
        root.Metrics.WidenedIVs += inlineeCompiler.Metrics.WidenedIVs;
        root.Metrics.UnusedIVsRemoved += inlineeCompiler.Metrics.UnusedIVsRemoved;
        root.Metrics.LoopsMadeDownwardsCounted += inlineeCompiler.Metrics.LoopsMadeDownwardsCounted;
        root.Metrics.LoopsStrengthReduced += inlineeCompiler.Metrics.LoopsStrengthReduced;
        root.Metrics.VarsInSsa += inlineeCompiler.Metrics.VarsInSsa;
        root.Metrics.HoistedExpressions += inlineeCompiler.Metrics.HoistedExpressions;
        root.Metrics.RedundantBranchesEliminated += inlineeCompiler.Metrics.RedundantBranchesEliminated;
        root.Metrics.JumpThreadingsPerformed += inlineeCompiler.Metrics.JumpThreadingsPerformed;
        root.Metrics.CseCount += inlineeCompiler.Metrics.CseCount;
        root.Metrics.BasicBlocksAtCodegen += inlineeCompiler.Metrics.BasicBlocksAtCodegen;
        root.Metrics.PerfScore += inlineeCompiler.Metrics.PerfScore;
        root.Metrics.BytesAllocated += inlineeCompiler.Metrics.BytesAllocated;
        root.Metrics.ImporterBranchFold += inlineeCompiler.Metrics.ImporterBranchFold;
        root.Metrics.ImporterSwitchFold += inlineeCompiler.Metrics.ImporterSwitchFold;
        root.Metrics.DevirtualizedCall += inlineeCompiler.Metrics.DevirtualizedCall;
        root.Metrics.DevirtualizedCallUnboxedEntry += inlineeCompiler.Metrics.DevirtualizedCallUnboxedEntry;
        root.Metrics.GDV += inlineeCompiler.Metrics.GDV;
        root.Metrics.ClassGDV += inlineeCompiler.Metrics.ClassGDV;
        root.Metrics.MethodGDV += inlineeCompiler.Metrics.MethodGDV;
        root.Metrics.MultiGuessGDV += inlineeCompiler.Metrics.MultiGuessGDV;
        root.Metrics.ChainedGDV += inlineeCompiler.Metrics.ChainedGDV;
        root.Metrics.EnumeratorGDV += inlineeCompiler.Metrics.EnumeratorGDV;
        root.Metrics.InlinerBranchFold += inlineeCompiler.Metrics.InlinerBranchFold;
        root.Metrics.InlineAttempt += inlineeCompiler.Metrics.InlineAttempt;
        root.Metrics.InlineCount += inlineeCompiler.Metrics.InlineCount;
        root.Metrics.ProfileConsistentBeforeInline += inlineeCompiler.Metrics.ProfileConsistentBeforeInline;
        root.Metrics.ProfileConsistentAfterInline += inlineeCompiler.Metrics.ProfileConsistentAfterInline;
        root.Metrics.ProfileConsistentBeforeMorph += inlineeCompiler.Metrics.ProfileConsistentBeforeMorph;
        root.Metrics.ProfileConsistentAfterMorph += inlineeCompiler.Metrics.ProfileConsistentAfterMorph;
        root.Metrics.ProfileSynthesizedBlendedOrRepaired += inlineeCompiler.Metrics.ProfileSynthesizedBlendedOrRepaired;
        root.Metrics.ProfileInconsistentInitially += inlineeCompiler.Metrics.ProfileInconsistentInitially;
        root.Metrics.ProfileInconsistentResetLeave += inlineeCompiler.Metrics.ProfileInconsistentResetLeave;
        root.Metrics.ProfileInconsistentImporterBranchFold += inlineeCompiler.Metrics.ProfileInconsistentImporterBranchFold;
        root.Metrics.ProfileInconsistentImporterSwitchFold += inlineeCompiler.Metrics.ProfileInconsistentImporterSwitchFold;
        root.Metrics.ProfileInconsistentChainedGDV += inlineeCompiler.Metrics.ProfileInconsistentChainedGDV;
        root.Metrics.ProfileInconsistentScratchBB += inlineeCompiler.Metrics.ProfileInconsistentScratchBB;
        root.Metrics.ProfileInconsistentInlinerBranchFold += inlineeCompiler.Metrics.ProfileInconsistentInlinerBranchFold;
        root.Metrics.ProfileInconsistentInlineeScale += inlineeCompiler.Metrics.ProfileInconsistentInlineeScale;
        root.Metrics.ProfileInconsistentInlinee += inlineeCompiler.Metrics.ProfileInconsistentInlinee;
        root.Metrics.ProfileInconsistentNoReturnInlinee += inlineeCompiler.Metrics.ProfileInconsistentNoReturnInlinee;
        root.Metrics.ProfileInconsistentMayThrowInlinee += inlineeCompiler.Metrics.ProfileInconsistentMayThrowInlinee;
        root.Metrics.NewRefClassHelperCalls += inlineeCompiler.Metrics.NewRefClassHelperCalls;
        root.Metrics.StackAllocatedRefClasses += inlineeCompiler.Metrics.StackAllocatedRefClasses;
        root.Metrics.NewBoxedValueClassHelperCalls += inlineeCompiler.Metrics.NewBoxedValueClassHelperCalls;
        root.Metrics.StackAllocatedBoxedValueClasses += inlineeCompiler.Metrics.StackAllocatedBoxedValueClasses;
        root.Metrics.NewArrayHelperCalls += inlineeCompiler.Metrics.NewArrayHelperCalls;
        root.Metrics.StackAllocatedArrays += inlineeCompiler.Metrics.StackAllocatedArrays;
        root.Metrics.LocalAssertionCount += inlineeCompiler.Metrics.LocalAssertionCount;
        root.Metrics.LocalAssertionOverflow += inlineeCompiler.Metrics.LocalAssertionOverflow;
        root.Metrics.MorphTrackedLocals += inlineeCompiler.Metrics.MorphTrackedLocals;
        root.Metrics.MorphLocals += inlineeCompiler.Metrics.MorphLocals;
        root.Metrics.EnumeratorGDVProvisionalNoEscape += inlineeCompiler.Metrics.EnumeratorGDVProvisionalNoEscape;
        root.Metrics.EnumeratorGDVCanCloneToEnsureNoEscape += inlineeCompiler.Metrics.EnumeratorGDVCanCloneToEnsureNoEscape;
        root.Metrics.SuspensionPointsMerged += inlineeCompiler.Metrics.SuspensionPointsMerged;
    }
#endif
}