// Copyright © Tanner Gooding and Contributors. Licensed under the MIT License (MIT). See License.md in the repository root for more information.
//
// Based on the RyuJIT compiler from dotnet/runtime.
// Original source is Copyright (c) .NET Foundation and Contributors. Licensed under the MIT License (MIT).

namespace RyuJitSharp;

public struct JitMetrics
{
    public int ActualCodeBytes;
    public int AllocatedHotCodeBytes;
    public int AllocatedColdCodeBytes;
    public int ReadOnlyDataBytes;
    public int GCInfoBytes;
    public int EHClauseCount;
    public int PhysicallyPromotedFields;
    public int LoopsFoundDuringOpts;
    public int LoopsInverted;
    public int LoopsCloned;
    public int LoopsUnrolled;
    public int LoopAlignmentCandidates;
    public int LoopsAligned;
    public int LoopsIVWidened;
    public int WidenedIVs;
    public int UnusedIVsRemoved;
    public int LoopsMadeDownwardsCounted;
    public int LoopsStrengthReduced;
    public int VarsInSsa;
    public int HoistedExpressions;
    public int RedundantBranchesEliminated;
    public int JumpThreadingsPerformed;
    public int CseCount;
    public int BasicBlocksAtCodegen;
    public double PerfScore;
    public long BytesAllocated;
    public int ImporterBranchFold;
    public int ImporterSwitchFold;
    public int DevirtualizedCall;
    public int DevirtualizedCallUnboxedEntry;
    public int GDV;
    public int ClassGDV;
    public int MethodGDV;
    public int MultiGuessGDV;
    public int ChainedGDV;
    public int EnumeratorGDV;
    public int InlinerBranchFold;
    public int InlineAttempt;
    public int InlineCount;
    public int ProfileConsistentBeforeInline;
    public int ProfileConsistentAfterInline;
    public int ProfileConsistentBeforeMorph;
    public int ProfileConsistentAfterMorph;
    public int ProfileSynthesizedBlendedOrRepaired;
    public int ProfileInconsistentInitially;
    public int ProfileInconsistentResetLeave;
    public int ProfileInconsistentImporterBranchFold;
    public int ProfileInconsistentImporterSwitchFold;
    public int ProfileInconsistentChainedGDV;
    public int ProfileInconsistentScratchBB;
    public int ProfileInconsistentInlinerBranchFold;
    public int ProfileInconsistentInlineeScale;
    public int ProfileInconsistentInlinee;
    public int ProfileInconsistentNoReturnInlinee;
    public int ProfileInconsistentMayThrowInlinee;
    public int NewRefClassHelperCalls;
    public int StackAllocatedRefClasses;
    public int NewBoxedValueClassHelperCalls;
    public int StackAllocatedBoxedValueClasses;
    public int NewArrayHelperCalls;
    public int StackAllocatedArrays;
    public int LocalAssertionCount;
    public int LocalAssertionOverflow;
    public int MorphTrackedLocals;
    public int MorphLocals;
    public int EnumeratorGDVProvisionalNoEscape;
    public int EnumeratorGDVCanCloneToEnsureNoEscape;
    public int SuspensionPointsMerged;

    /// <summary>Report all metrics and their values back to the EE.</summary>
    /// <param name="compiler">Compiler instance</param>
    public readonly void report(Compiler compiler)
    {
        JitMetadata.report(compiler, nameof(ActualCodeBytes), ActualCodeBytes);
        JitMetadata.report(compiler, nameof(AllocatedHotCodeBytes), AllocatedHotCodeBytes);
        JitMetadata.report(compiler, nameof(AllocatedColdCodeBytes), AllocatedColdCodeBytes);
        JitMetadata.report(compiler, nameof(ReadOnlyDataBytes), ReadOnlyDataBytes);
        JitMetadata.report(compiler, nameof(GCInfoBytes), GCInfoBytes);
        JitMetadata.report(compiler, nameof(EHClauseCount), EHClauseCount);
        JitMetadata.report(compiler, nameof(PhysicallyPromotedFields), PhysicallyPromotedFields);
        JitMetadata.report(compiler, nameof(LoopsFoundDuringOpts), LoopsFoundDuringOpts);
        JitMetadata.report(compiler, nameof(LoopsInverted), LoopsInverted);
        JitMetadata.report(compiler, nameof(LoopsCloned), LoopsCloned);
        JitMetadata.report(compiler, nameof(LoopsUnrolled), LoopsUnrolled);
        JitMetadata.report(compiler, nameof(LoopAlignmentCandidates), LoopAlignmentCandidates);
        JitMetadata.report(compiler, nameof(LoopsAligned), LoopsAligned);
        JitMetadata.report(compiler, nameof(LoopsIVWidened), LoopsIVWidened);
        JitMetadata.report(compiler, nameof(WidenedIVs), WidenedIVs);
        JitMetadata.report(compiler, nameof(UnusedIVsRemoved), UnusedIVsRemoved);
        JitMetadata.report(compiler, nameof(LoopsMadeDownwardsCounted), LoopsMadeDownwardsCounted);
        JitMetadata.report(compiler, nameof(LoopsStrengthReduced), LoopsStrengthReduced);
        JitMetadata.report(compiler, nameof(VarsInSsa), VarsInSsa);
        JitMetadata.report(compiler, nameof(HoistedExpressions), HoistedExpressions);
        JitMetadata.report(compiler, nameof(RedundantBranchesEliminated), RedundantBranchesEliminated);
        JitMetadata.report(compiler, nameof(JumpThreadingsPerformed), JumpThreadingsPerformed);
        JitMetadata.report(compiler, nameof(CseCount), CseCount);
        JitMetadata.report(compiler, nameof(BasicBlocksAtCodegen), BasicBlocksAtCodegen);
        JitMetadata.report(compiler, nameof(PerfScore), PerfScore);
        JitMetadata.report(compiler, nameof(BytesAllocated), BytesAllocated);
        JitMetadata.report(compiler, nameof(ImporterBranchFold), ImporterBranchFold);
        JitMetadata.report(compiler, nameof(ImporterSwitchFold), ImporterSwitchFold);
        JitMetadata.report(compiler, nameof(DevirtualizedCall), DevirtualizedCall);
        JitMetadata.report(compiler, nameof(DevirtualizedCallUnboxedEntry), DevirtualizedCallUnboxedEntry);
        JitMetadata.report(compiler, nameof(GDV), GDV);
        JitMetadata.report(compiler, nameof(ClassGDV), ClassGDV);
        JitMetadata.report(compiler, nameof(MethodGDV), MethodGDV);
        JitMetadata.report(compiler, nameof(MultiGuessGDV), MultiGuessGDV);
        JitMetadata.report(compiler, nameof(ChainedGDV), ChainedGDV);
        JitMetadata.report(compiler, nameof(EnumeratorGDV), EnumeratorGDV);
        JitMetadata.report(compiler, nameof(InlinerBranchFold), InlinerBranchFold);
        JitMetadata.report(compiler, nameof(InlineAttempt), InlineAttempt);
        JitMetadata.report(compiler, nameof(InlineCount), InlineCount);
        JitMetadata.report(compiler, nameof(ProfileConsistentBeforeInline), ProfileConsistentBeforeInline);
        JitMetadata.report(compiler, nameof(ProfileConsistentAfterInline), ProfileConsistentAfterInline);
        JitMetadata.report(compiler, nameof(ProfileConsistentBeforeMorph), ProfileConsistentBeforeMorph);
        JitMetadata.report(compiler, nameof(ProfileConsistentAfterMorph), ProfileConsistentAfterMorph);
        JitMetadata.report(compiler, nameof(ProfileSynthesizedBlendedOrRepaired), ProfileSynthesizedBlendedOrRepaired);
        JitMetadata.report(compiler, nameof(ProfileInconsistentInitially), ProfileInconsistentInitially);
        JitMetadata.report(compiler, nameof(ProfileInconsistentResetLeave), ProfileInconsistentResetLeave);
        JitMetadata.report(compiler, nameof(ProfileInconsistentImporterBranchFold), ProfileInconsistentImporterBranchFold);
        JitMetadata.report(compiler, nameof(ProfileInconsistentImporterSwitchFold), ProfileInconsistentImporterSwitchFold);
        JitMetadata.report(compiler, nameof(ProfileInconsistentChainedGDV), ProfileInconsistentChainedGDV);
        JitMetadata.report(compiler, nameof(ProfileInconsistentScratchBB), ProfileInconsistentScratchBB);
        JitMetadata.report(compiler, nameof(ProfileInconsistentInlinerBranchFold), ProfileInconsistentInlinerBranchFold);
        JitMetadata.report(compiler, nameof(ProfileInconsistentInlineeScale), ProfileInconsistentInlineeScale);
        JitMetadata.report(compiler, nameof(ProfileInconsistentInlinee), ProfileInconsistentInlinee);
        JitMetadata.report(compiler, nameof(ProfileInconsistentNoReturnInlinee), ProfileInconsistentNoReturnInlinee);
        JitMetadata.report(compiler, nameof(ProfileInconsistentMayThrowInlinee), ProfileInconsistentMayThrowInlinee);
        JitMetadata.report(compiler, nameof(NewRefClassHelperCalls), NewRefClassHelperCalls);
        JitMetadata.report(compiler, nameof(StackAllocatedRefClasses), StackAllocatedRefClasses);
        JitMetadata.report(compiler, nameof(NewBoxedValueClassHelperCalls), NewBoxedValueClassHelperCalls);
        JitMetadata.report(compiler, nameof(StackAllocatedBoxedValueClasses), StackAllocatedBoxedValueClasses);
        JitMetadata.report(compiler, nameof(NewArrayHelperCalls), NewArrayHelperCalls);
        JitMetadata.report(compiler, nameof(StackAllocatedArrays), StackAllocatedArrays);
        JitMetadata.report(compiler, nameof(LocalAssertionCount), LocalAssertionCount);
        JitMetadata.report(compiler, nameof(LocalAssertionOverflow), LocalAssertionOverflow);
        JitMetadata.report(compiler, nameof(MorphTrackedLocals), MorphTrackedLocals);
        JitMetadata.report(compiler, nameof(MorphLocals), MorphLocals);
        JitMetadata.report(compiler, nameof(EnumeratorGDVProvisionalNoEscape), EnumeratorGDVProvisionalNoEscape);
        JitMetadata.report(compiler, nameof(EnumeratorGDVCanCloneToEnsureNoEscape), EnumeratorGDVCanCloneToEnsureNoEscape);
        JitMetadata.report(compiler, nameof(SuspensionPointsMerged), SuspensionPointsMerged);
    }

#if DEBUG
    public readonly void dump()
    {
        jitprintf($"{nameof(ActualCodeBytes)}                      : {ActualCodeBytes}\n");
        jitprintf($"{nameof(AllocatedHotCodeBytes)}                : {AllocatedHotCodeBytes}\n");
        jitprintf($"{nameof(AllocatedColdCodeBytes)}               : {AllocatedColdCodeBytes}\n");
        jitprintf($"{nameof(ReadOnlyDataBytes)}                    : {ReadOnlyDataBytes}\n");
        jitprintf($"{nameof(GCInfoBytes)}                          : {GCInfoBytes}\n");
        jitprintf($"{nameof(EHClauseCount)}                        : {EHClauseCount}\n");
        jitprintf($"{nameof(PhysicallyPromotedFields)}             : {PhysicallyPromotedFields}\n");
        jitprintf($"{nameof(LoopsFoundDuringOpts)}                 : {LoopsFoundDuringOpts}\n");
        jitprintf($"{nameof(LoopsInverted)}                        : {LoopsInverted}\n");
        jitprintf($"{nameof(LoopsCloned)}                          : {LoopsCloned}\n");
        jitprintf($"{nameof(LoopsUnrolled)}                        : {LoopsUnrolled}\n");
        jitprintf($"{nameof(LoopAlignmentCandidates)}              : {LoopAlignmentCandidates}\n");
        jitprintf($"{nameof(LoopsAligned)}                         : {LoopsAligned}\n");
        jitprintf($"{nameof(LoopsIVWidened)}                       : {LoopsIVWidened}\n");
        jitprintf($"{nameof(WidenedIVs)}                           : {WidenedIVs}\n");
        jitprintf($"{nameof(UnusedIVsRemoved)}                     : {UnusedIVsRemoved}\n");
        jitprintf($"{nameof(LoopsMadeDownwardsCounted)}            : {LoopsMadeDownwardsCounted}\n");
        jitprintf($"{nameof(LoopsStrengthReduced)}                 : {LoopsStrengthReduced}\n");
        jitprintf($"{nameof(VarsInSsa)}                            : {VarsInSsa}\n");
        jitprintf($"{nameof(HoistedExpressions)}                   : {HoistedExpressions}\n");
        jitprintf($"{nameof(RedundantBranchesEliminated)}          : {RedundantBranchesEliminated}\n");
        jitprintf($"{nameof(JumpThreadingsPerformed)}              : {JumpThreadingsPerformed}\n");
        jitprintf($"{nameof(CseCount)}                             : {CseCount}\n");
        jitprintf($"{nameof(BasicBlocksAtCodegen)}                 : {BasicBlocksAtCodegen}\n");
        jitprintf($"{nameof(PerfScore)}                            : {PerfScore}\n");
        jitprintf($"{nameof(BytesAllocated)}                       : {BytesAllocated}\n");
        jitprintf($"{nameof(ImporterBranchFold)}                   : {ImporterBranchFold}\n");
        jitprintf($"{nameof(ImporterSwitchFold)}                   : {ImporterSwitchFold}\n");
        jitprintf($"{nameof(DevirtualizedCall)}                    : {DevirtualizedCall}\n");
        jitprintf($"{nameof(DevirtualizedCallUnboxedEntry)}        : {DevirtualizedCallUnboxedEntry}\n");
        jitprintf($"{nameof(GDV)}                                  : {GDV}\n");
        jitprintf($"{nameof(ClassGDV)}                             : {ClassGDV}\n");
        jitprintf($"{nameof(MethodGDV)}                            : {MethodGDV}\n");
        jitprintf($"{nameof(MultiGuessGDV)}                        : {MultiGuessGDV}\n");
        jitprintf($"{nameof(ChainedGDV)}                           : {ChainedGDV}\n");
        jitprintf($"{nameof(EnumeratorGDV)}                        : {EnumeratorGDV}\n");
        jitprintf($"{nameof(InlinerBranchFold)}                    : {InlinerBranchFold}\n");
        jitprintf($"{nameof(InlineAttempt)}                        : {InlineAttempt}\n");
        jitprintf($"{nameof(InlineCount)}                          : {InlineCount}\n");
        jitprintf($"{nameof(ProfileConsistentBeforeInline)}        : {ProfileConsistentBeforeInline}\n");
        jitprintf($"{nameof(ProfileConsistentAfterInline)}         : {ProfileConsistentAfterInline}\n");
        jitprintf($"{nameof(ProfileConsistentBeforeMorph)}         : {ProfileConsistentBeforeMorph}\n");
        jitprintf($"{nameof(ProfileConsistentAfterMorph)}          : {ProfileConsistentAfterMorph}\n");
        jitprintf($"{nameof(ProfileSynthesizedBlendedOrRepaired)}  : {ProfileSynthesizedBlendedOrRepaired}\n");
        jitprintf($"{nameof(ProfileInconsistentInitially)}         : {ProfileInconsistentInitially}\n");
        jitprintf($"{nameof(ProfileInconsistentResetLeave)}        : {ProfileInconsistentResetLeave}\n");
        jitprintf($"{nameof(ProfileInconsistentImporterBranchFold)}: {ProfileInconsistentImporterBranchFold}\n");
        jitprintf($"{nameof(ProfileInconsistentImporterSwitchFold)}: {ProfileInconsistentImporterSwitchFold}\n");
        jitprintf($"{nameof(ProfileInconsistentChainedGDV)}        : {ProfileInconsistentChainedGDV}\n");
        jitprintf($"{nameof(ProfileInconsistentScratchBB)}         : {ProfileInconsistentScratchBB}\n");
        jitprintf($"{nameof(ProfileInconsistentInlinerBranchFold)} : {ProfileInconsistentInlinerBranchFold}\n");
        jitprintf($"{nameof(ProfileInconsistentInlineeScale)}      : {ProfileInconsistentInlineeScale}\n");
        jitprintf($"{nameof(ProfileInconsistentInlinee)}           : {ProfileInconsistentInlinee}\n");
        jitprintf($"{nameof(ProfileInconsistentNoReturnInlinee)}   : {ProfileInconsistentNoReturnInlinee}\n");
        jitprintf($"{nameof(ProfileInconsistentMayThrowInlinee)}   : {ProfileInconsistentMayThrowInlinee}\n");
        jitprintf($"{nameof(NewRefClassHelperCalls)}               : {NewRefClassHelperCalls}\n");
        jitprintf($"{nameof(StackAllocatedRefClasses)}             : {StackAllocatedRefClasses}\n");
        jitprintf($"{nameof(NewBoxedValueClassHelperCalls)}        : {NewBoxedValueClassHelperCalls}\n");
        jitprintf($"{nameof(StackAllocatedBoxedValueClasses)}      : {StackAllocatedBoxedValueClasses}\n");
        jitprintf($"{nameof(NewArrayHelperCalls)}                  : {NewArrayHelperCalls}\n");
        jitprintf($"{nameof(StackAllocatedArrays)}                 : {StackAllocatedArrays}\n");
        jitprintf($"{nameof(LocalAssertionCount)}                  : {LocalAssertionCount}\n");
        jitprintf($"{nameof(LocalAssertionOverflow)}               : {LocalAssertionOverflow}\n");
        jitprintf($"{nameof(MorphTrackedLocals)}                   : {MorphTrackedLocals}\n");
        jitprintf($"{nameof(MorphLocals)}                          : {MorphLocals}\n");
        jitprintf($"{nameof(EnumeratorGDVProvisionalNoEscape)}     : {EnumeratorGDVProvisionalNoEscape}\n");
        jitprintf($"{nameof(EnumeratorGDVCanCloneToEnsureNoEscape)}: {EnumeratorGDVCanCloneToEnsureNoEscape}\n");
        jitprintf($"{nameof(SuspensionPointsMerged)}               : {SuspensionPointsMerged}\n");
    }

    /// <summary>Merge inlinee compiler metrics to root compiler instance</summary>
    /// <param name="inlineeCompiler">inlinee compiler instance</param>
    public readonly void mergeToRoot(Compiler inlineeCompiler)
    {
        var root = inlineeCompiler.impInlineRoot;

        root.Metrics.ActualCodeBytes += inlineeCompiler.Metrics.ActualCodeBytes;
        root.Metrics.AllocatedHotCodeBytes += inlineeCompiler.Metrics.AllocatedHotCodeBytes;
        root.Metrics.AllocatedColdCodeBytes += inlineeCompiler.Metrics.AllocatedColdCodeBytes;
        root.Metrics.ReadOnlyDataBytes += inlineeCompiler.Metrics.ReadOnlyDataBytes;
        root.Metrics.GCInfoBytes += inlineeCompiler.Metrics.GCInfoBytes;
        root.Metrics.EHClauseCount += inlineeCompiler.Metrics.EHClauseCount;
        root.Metrics.PhysicallyPromotedFields += inlineeCompiler.Metrics.PhysicallyPromotedFields;
        root.Metrics.LoopsFoundDuringOpts += inlineeCompiler.Metrics.LoopsFoundDuringOpts;
        root.Metrics.LoopsInverted += inlineeCompiler.Metrics.LoopsInverted;
        root.Metrics.LoopsCloned += inlineeCompiler.Metrics.LoopsCloned;
        root.Metrics.LoopsUnrolled += inlineeCompiler.Metrics.LoopsUnrolled;
        root.Metrics.LoopAlignmentCandidates += inlineeCompiler.Metrics.LoopAlignmentCandidates;
        root.Metrics.LoopsAligned += inlineeCompiler.Metrics.LoopsAligned;
        root.Metrics.LoopsIVWidened += inlineeCompiler.Metrics.LoopsIVWidened;
        root.Metrics.WidenedIVs += inlineeCompiler.Metrics.WidenedIVs;
        root.Metrics.UnusedIVsRemoved += inlineeCompiler.Metrics.UnusedIVsRemoved;
        root.Metrics.LoopsMadeDownwardsCounted += inlineeCompiler.Metrics.LoopsMadeDownwardsCounted;
        root.Metrics.LoopsStrengthReduced += inlineeCompiler.Metrics.LoopsStrengthReduced;
        root.Metrics.VarsInSsa += inlineeCompiler.Metrics.VarsInSsa;
        root.Metrics.HoistedExpressions += inlineeCompiler.Metrics.HoistedExpressions;
        root.Metrics.RedundantBranchesEliminated += inlineeCompiler.Metrics.RedundantBranchesEliminated;
        root.Metrics.JumpThreadingsPerformed += inlineeCompiler.Metrics.JumpThreadingsPerformed;
        root.Metrics.CseCount += inlineeCompiler.Metrics.CseCount;
        root.Metrics.BasicBlocksAtCodegen += inlineeCompiler.Metrics.BasicBlocksAtCodegen;
        root.Metrics.PerfScore += inlineeCompiler.Metrics.PerfScore;
        root.Metrics.BytesAllocated += inlineeCompiler.Metrics.BytesAllocated;
        root.Metrics.ImporterBranchFold += inlineeCompiler.Metrics.ImporterBranchFold;
        root.Metrics.ImporterSwitchFold += inlineeCompiler.Metrics.ImporterSwitchFold;
        root.Metrics.DevirtualizedCall += inlineeCompiler.Metrics.DevirtualizedCall;
        root.Metrics.DevirtualizedCallUnboxedEntry += inlineeCompiler.Metrics.DevirtualizedCallUnboxedEntry;
        root.Metrics.GDV += inlineeCompiler.Metrics.GDV;
        root.Metrics.ClassGDV += inlineeCompiler.Metrics.ClassGDV;
        root.Metrics.MethodGDV += inlineeCompiler.Metrics.MethodGDV;
        root.Metrics.MultiGuessGDV += inlineeCompiler.Metrics.MultiGuessGDV;
        root.Metrics.ChainedGDV += inlineeCompiler.Metrics.ChainedGDV;
        root.Metrics.EnumeratorGDV += inlineeCompiler.Metrics.EnumeratorGDV;
        root.Metrics.InlinerBranchFold += inlineeCompiler.Metrics.InlinerBranchFold;
        root.Metrics.InlineAttempt += inlineeCompiler.Metrics.InlineAttempt;
        root.Metrics.InlineCount += inlineeCompiler.Metrics.InlineCount;
        root.Metrics.ProfileConsistentBeforeInline += inlineeCompiler.Metrics.ProfileConsistentBeforeInline;
        root.Metrics.ProfileConsistentAfterInline += inlineeCompiler.Metrics.ProfileConsistentAfterInline;
        root.Metrics.ProfileConsistentBeforeMorph += inlineeCompiler.Metrics.ProfileConsistentBeforeMorph;
        root.Metrics.ProfileConsistentAfterMorph += inlineeCompiler.Metrics.ProfileConsistentAfterMorph;
        root.Metrics.ProfileSynthesizedBlendedOrRepaired += inlineeCompiler.Metrics.ProfileSynthesizedBlendedOrRepaired;
        root.Metrics.ProfileInconsistentInitially += inlineeCompiler.Metrics.ProfileInconsistentInitially;
        root.Metrics.ProfileInconsistentResetLeave += inlineeCompiler.Metrics.ProfileInconsistentResetLeave;
        root.Metrics.ProfileInconsistentImporterBranchFold += inlineeCompiler.Metrics.ProfileInconsistentImporterBranchFold;
        root.Metrics.ProfileInconsistentImporterSwitchFold += inlineeCompiler.Metrics.ProfileInconsistentImporterSwitchFold;
        root.Metrics.ProfileInconsistentChainedGDV += inlineeCompiler.Metrics.ProfileInconsistentChainedGDV;
        root.Metrics.ProfileInconsistentScratchBB += inlineeCompiler.Metrics.ProfileInconsistentScratchBB;
        root.Metrics.ProfileInconsistentInlinerBranchFold += inlineeCompiler.Metrics.ProfileInconsistentInlinerBranchFold;
        root.Metrics.ProfileInconsistentInlineeScale += inlineeCompiler.Metrics.ProfileInconsistentInlineeScale;
        root.Metrics.ProfileInconsistentInlinee += inlineeCompiler.Metrics.ProfileInconsistentInlinee;
        root.Metrics.ProfileInconsistentNoReturnInlinee += inlineeCompiler.Metrics.ProfileInconsistentNoReturnInlinee;
        root.Metrics.ProfileInconsistentMayThrowInlinee += inlineeCompiler.Metrics.ProfileInconsistentMayThrowInlinee;
        root.Metrics.NewRefClassHelperCalls += inlineeCompiler.Metrics.NewRefClassHelperCalls;
        root.Metrics.StackAllocatedRefClasses += inlineeCompiler.Metrics.StackAllocatedRefClasses;
        root.Metrics.NewBoxedValueClassHelperCalls += inlineeCompiler.Metrics.NewBoxedValueClassHelperCalls;
        root.Metrics.StackAllocatedBoxedValueClasses += inlineeCompiler.Metrics.StackAllocatedBoxedValueClasses;
        root.Metrics.NewArrayHelperCalls += inlineeCompiler.Metrics.NewArrayHelperCalls;
        root.Metrics.StackAllocatedArrays += inlineeCompiler.Metrics.StackAllocatedArrays;
        root.Metrics.LocalAssertionCount += inlineeCompiler.Metrics.LocalAssertionCount;
        root.Metrics.LocalAssertionOverflow += inlineeCompiler.Metrics.LocalAssertionOverflow;
        root.Metrics.MorphTrackedLocals += inlineeCompiler.Metrics.MorphTrackedLocals;
        root.Metrics.MorphLocals += inlineeCompiler.Metrics.MorphLocals;
        root.Metrics.EnumeratorGDVProvisionalNoEscape += inlineeCompiler.Metrics.EnumeratorGDVProvisionalNoEscape;
        root.Metrics.EnumeratorGDVCanCloneToEnsureNoEscape += inlineeCompiler.Metrics.EnumeratorGDVCanCloneToEnsureNoEscape;
        root.Metrics.SuspensionPointsMerged += inlineeCompiler.Metrics.SuspensionPointsMerged;
    }
#endif
}
