// Copyright (c) Tanner Gooding and Contributors. Licensed under the MIT License (MIT). See License.md in the repository root for more information.
//
// Based on the RyuJIT compiler from dotnet/runtime.
// Original source is Copyright (c) .NET Foundation and Contributors. Licensed under the MIT License (MIT).

using System;

namespace RyuJitSharp;

public partial class Emitter
{
#if TARGET_XARCH
    private static ReadOnlySpan<insTupleType> s_tupleTypes => [
#if TARGET_XARCH
#if !TARGET_XARCH
#error Unexpected target type
#endif
        INS_TT_NONE, // INS_invalid
        INS_TT_NONE, // INS_push
        INS_TT_NONE, // INS_pop
        INS_TT_NONE, // INS_push_hide
        INS_TT_NONE, // INS_pop_hide
        INS_TT_NONE, // INS_push2
        INS_TT_NONE, // INS_pop2
        INS_TT_NONE, // INS_inc
        INS_TT_NONE, // INS_inc_l
        INS_TT_NONE, // INS_dec
        INS_TT_NONE, // INS_dec_l
        INS_TT_NONE, // INS_bswap
        INS_TT_NONE, // INS_add
        INS_TT_NONE, // INS_or
        INS_TT_NONE, // INS_adc
        INS_TT_NONE, // INS_sbb
        INS_TT_NONE, // INS_and
        INS_TT_NONE, // INS_sub
        INS_TT_NONE, // INS_sub_hide
        INS_TT_NONE, // INS_xor
        INS_TT_NONE, // INS_cmp
        INS_TT_NONE, // INS_test
        INS_TT_NONE, // INS_mov
        INS_TT_NONE, // INS_lea
        INS_TT_NONE, // INS_bt
        INS_TT_NONE, // INS_bts
        INS_TT_NONE, // INS_btr
        INS_TT_NONE, // INS_btc
        INS_TT_NONE, // INS_bsr
        INS_TT_NONE, // INS_bsf
        INS_TT_NONE, // INS_movsx
#if TARGET_AMD64
        INS_TT_NONE, // INS_movsxd
#endif
        INS_TT_NONE, // INS_movzx
        INS_TT_NONE, // INS_cmovo
        INS_TT_NONE, // INS_cmovno
        INS_TT_NONE, // INS_cmovb
        INS_TT_NONE, // INS_cmovae
        INS_TT_NONE, // INS_cmove
        INS_TT_NONE, // INS_cmovne
        INS_TT_NONE, // INS_cmovbe
        INS_TT_NONE, // INS_cmova
        INS_TT_NONE, // INS_cmovs
        INS_TT_NONE, // INS_cmovns
        INS_TT_NONE, // INS_cmovp
        INS_TT_NONE, // INS_cmovnp
        INS_TT_NONE, // INS_cmovl
        INS_TT_NONE, // INS_cmovge
        INS_TT_NONE, // INS_cmovle
        INS_TT_NONE, // INS_cmovg
        INS_TT_NONE, // INS_xchg
        INS_TT_NONE, // INS_imul
        INS_TT_NONE, // INS_imul_AX
        INS_TT_NONE, // INS_imul_CX
        INS_TT_NONE, // INS_imul_DX
        INS_TT_NONE, // INS_imul_BX
        INS_TT_NONE, // INS_imul_SP
        INS_TT_NONE, // INS_imul_BP
        INS_TT_NONE, // INS_imul_SI
        INS_TT_NONE, // INS_imul_DI
#if TARGET_AMD64
        INS_TT_NONE, // INS_imul_08
        INS_TT_NONE, // INS_imul_09
        INS_TT_NONE, // INS_imul_10
        INS_TT_NONE, // INS_imul_11
        INS_TT_NONE, // INS_imul_12
        INS_TT_NONE, // INS_imul_13
        INS_TT_NONE, // INS_imul_14
        INS_TT_NONE, // INS_imul_15
        INS_TT_NONE, // INS_imul_16
        INS_TT_NONE, // INS_imul_17
        INS_TT_NONE, // INS_imul_18
        INS_TT_NONE, // INS_imul_19
        INS_TT_NONE, // INS_imul_20
        INS_TT_NONE, // INS_imul_21
        INS_TT_NONE, // INS_imul_22
        INS_TT_NONE, // INS_imul_23
        INS_TT_NONE, // INS_imul_24
        INS_TT_NONE, // INS_imul_25
        INS_TT_NONE, // INS_imul_26
        INS_TT_NONE, // INS_imul_27
        INS_TT_NONE, // INS_imul_28
        INS_TT_NONE, // INS_imul_29
        INS_TT_NONE, // INS_imul_30
        INS_TT_NONE, // INS_imul_31
#endif
        INS_TT_FULL, // INS_addpd
        INS_TT_FULL, // INS_addps
        INS_TT_TUPLE1_SCALAR, // INS_addsd
        INS_TT_TUPLE1_SCALAR, // INS_addss
        INS_TT_FULL_MEM, // INS_addsubpd
        INS_TT_FULL_MEM, // INS_addsubps
        INS_TT_FULL, // INS_andnpd
        INS_TT_FULL, // INS_andnps
        INS_TT_FULL, // INS_andpd
        INS_TT_FULL, // INS_andps
        INS_TT_FULL_MEM, // INS_blendpd
        INS_TT_FULL_MEM, // INS_blendps
        INS_TT_FULL_MEM, // INS_blendvpd
        INS_TT_FULL_MEM, // INS_blendvps
        INS_TT_FULL, // INS_cmppd
        INS_TT_FULL, // INS_cmpps
        INS_TT_TUPLE1_SCALAR, // INS_cmpsd
        INS_TT_TUPLE1_SCALAR, // INS_cmpss
        INS_TT_TUPLE1_SCALAR, // INS_comisd
        INS_TT_TUPLE1_SCALAR, // INS_comiss
        INS_TT_HALF, // INS_cvtdq2pd
        INS_TT_FULL, // INS_cvtdq2ps
        INS_TT_FULL, // INS_cvtpd2dq
        INS_TT_FULL, // INS_cvtpd2ps
        INS_TT_FULL, // INS_cvtps2dq
        INS_TT_HALF, // INS_cvtps2pd
        INS_TT_TUPLE1_FIXED, // INS_cvtsd2si32
        INS_TT_TUPLE1_FIXED, // INS_cvtsd2si64
        INS_TT_TUPLE1_SCALAR, // INS_cvtsd2ss
        INS_TT_TUPLE1_SCALAR, // INS_cvtsi2sd32
        INS_TT_TUPLE1_SCALAR, // INS_cvtsi2sd64
        INS_TT_TUPLE1_SCALAR, // INS_cvtsi2ss32
        INS_TT_TUPLE1_SCALAR, // INS_cvtsi2ss64
        INS_TT_TUPLE1_SCALAR, // INS_cvtss2sd
        INS_TT_TUPLE1_FIXED, // INS_cvtss2si32
        INS_TT_TUPLE1_FIXED, // INS_cvtss2si64
        INS_TT_FULL, // INS_cvttpd2dq
        INS_TT_FULL, // INS_cvttps2dq
        INS_TT_TUPLE1_FIXED, // INS_cvttsd2si32
        INS_TT_TUPLE1_FIXED, // INS_cvttsd2si64
        INS_TT_TUPLE1_FIXED, // INS_cvttss2si32
        INS_TT_TUPLE1_FIXED, // INS_cvttss2si64
        INS_TT_FULL, // INS_divpd
        INS_TT_FULL, // INS_divps
        INS_TT_TUPLE1_SCALAR, // INS_divsd
        INS_TT_TUPLE1_SCALAR, // INS_divss
        INS_TT_FULL_MEM, // INS_dppd
        INS_TT_FULL_MEM, // INS_dpps
        INS_TT_TUPLE1_SCALAR, // INS_extractps
        INS_TT_FULL_MEM, // INS_haddpd
        INS_TT_FULL_MEM, // INS_haddps
        INS_TT_FULL_MEM, // INS_hsubpd
        INS_TT_FULL_MEM, // INS_hsubps
        INS_TT_TUPLE1_SCALAR, // INS_insertps
        INS_TT_FULL_MEM, // INS_lddqu
        INS_TT_NONE, // INS_lfence
        INS_TT_NONE, // INS_maskmovdqu
        INS_TT_FULL, // INS_maxpd
        INS_TT_FULL, // INS_maxps
        INS_TT_TUPLE1_SCALAR, // INS_maxsd
        INS_TT_TUPLE1_SCALAR, // INS_maxss
        INS_TT_NONE, // INS_mfence
        INS_TT_FULL, // INS_minpd
        INS_TT_FULL, // INS_minps
        INS_TT_TUPLE1_SCALAR, // INS_minsd
        INS_TT_TUPLE1_SCALAR, // INS_minss
        INS_TT_FULL_MEM, // INS_movapd
        INS_TT_FULL_MEM, // INS_movaps
        INS_TT_TUPLE1_SCALAR, // INS_movd32
        INS_TT_TUPLE1_SCALAR, // INS_movd64
        INS_TT_MOVDDUP, // INS_movddup
        INS_TT_FULL_MEM, // INS_movdqa32
        INS_TT_FULL_MEM, // INS_movdqu32
        INS_TT_NONE, // INS_movhlps
        INS_TT_TUPLE1_SCALAR, // INS_movhpd
        INS_TT_TUPLE2, // INS_movhps
        INS_TT_NONE, // INS_movlhps
        INS_TT_TUPLE1_SCALAR, // INS_movlpd
        INS_TT_TUPLE2, // INS_movlps
        INS_TT_NONE, // INS_movmskpd
        INS_TT_NONE, // INS_movmskps
        INS_TT_FULL_MEM, // INS_movntdq
        INS_TT_FULL_MEM, // INS_movntdqa
        INS_TT_TUPLE1_SCALAR, // INS_movnti32
        INS_TT_TUPLE1_SCALAR, // INS_movnti64
        INS_TT_FULL_MEM, // INS_movntpd
        INS_TT_FULL_MEM, // INS_movntps
        INS_TT_TUPLE1_SCALAR, // INS_movq
        INS_TT_TUPLE1_SCALAR, // INS_movsd_simd
        INS_TT_FULL_MEM, // INS_movshdup
        INS_TT_FULL_MEM, // INS_movsldup
        INS_TT_TUPLE1_SCALAR, // INS_movss
        INS_TT_FULL_MEM, // INS_movupd
        INS_TT_FULL_MEM, // INS_movups
        INS_TT_FULL_MEM, // INS_mpsadbw
        INS_TT_FULL, // INS_mulpd
        INS_TT_FULL, // INS_mulps
        INS_TT_TUPLE1_SCALAR, // INS_mulsd
        INS_TT_TUPLE1_SCALAR, // INS_mulss
        INS_TT_FULL, // INS_orpd
        INS_TT_FULL, // INS_orps
        INS_TT_FULL_MEM, // INS_pabsb
        INS_TT_FULL, // INS_pabsd
        INS_TT_FULL_MEM, // INS_pabsw
        INS_TT_FULL, // INS_packssdw
        INS_TT_FULL_MEM, // INS_packsswb
        INS_TT_FULL, // INS_packusdw
        INS_TT_FULL_MEM, // INS_packuswb
        INS_TT_FULL_MEM, // INS_paddb
        INS_TT_FULL, // INS_paddd
        INS_TT_FULL, // INS_paddq
        INS_TT_FULL_MEM, // INS_paddsb
        INS_TT_FULL_MEM, // INS_paddsw
        INS_TT_FULL_MEM, // INS_paddusb
        INS_TT_FULL_MEM, // INS_paddusw
        INS_TT_FULL_MEM, // INS_paddw
        INS_TT_FULL_MEM, // INS_palignr
        INS_TT_FULL, // INS_pandd
        INS_TT_FULL, // INS_pandnd
        INS_TT_FULL_MEM, // INS_pavgb
        INS_TT_FULL_MEM, // INS_pavgw
        INS_TT_FULL_MEM, // INS_pblendvb
        INS_TT_FULL_MEM, // INS_pblendw
        INS_TT_FULL_MEM, // INS_pcmpeqb
        INS_TT_FULL, // INS_pcmpeqd
        INS_TT_FULL, // INS_pcmpeqq
        INS_TT_FULL_MEM, // INS_pcmpeqw
        INS_TT_FULL_MEM, // INS_pcmpgtb
        INS_TT_FULL, // INS_pcmpgtd
        INS_TT_FULL, // INS_pcmpgtq
        INS_TT_FULL_MEM, // INS_pcmpgtw
        INS_TT_TUPLE1_SCALAR, // INS_pextrb
        INS_TT_TUPLE1_SCALAR, // INS_pextrd
        INS_TT_TUPLE1_SCALAR, // INS_pextrq
        INS_TT_FULL_MEM, // INS_phaddd
        INS_TT_TUPLE1_SCALAR, // INS_pextrw
        INS_TT_FULL_MEM, // INS_phaddsw
        INS_TT_FULL_MEM, // INS_phaddw
        INS_TT_FULL_MEM, // INS_phminposuw
        INS_TT_FULL_MEM, // INS_phsubd
        INS_TT_FULL_MEM, // INS_phsubsw
        INS_TT_FULL_MEM, // INS_phsubw
        INS_TT_TUPLE1_SCALAR, // INS_pinsrb
        INS_TT_TUPLE1_SCALAR, // INS_pinsrd
        INS_TT_TUPLE1_SCALAR, // INS_pinsrq
        INS_TT_TUPLE1_SCALAR, // INS_pinsrw
        INS_TT_FULL_MEM, // INS_pmaddubsw
        INS_TT_FULL_MEM, // INS_pmaddwd
        INS_TT_FULL_MEM, // INS_pmaxsb
        INS_TT_FULL, // INS_pmaxsd
        INS_TT_FULL_MEM, // INS_pmaxsw
        INS_TT_FULL_MEM, // INS_pmaxub
        INS_TT_FULL, // INS_pmaxud
        INS_TT_FULL_MEM, // INS_pmaxuw
        INS_TT_FULL_MEM, // INS_pminsb
        INS_TT_FULL, // INS_pminsd
        INS_TT_FULL_MEM, // INS_pminsw
        INS_TT_FULL_MEM, // INS_pminub
        INS_TT_FULL, // INS_pminud
        INS_TT_FULL_MEM, // INS_pminuw
        INS_TT_NONE, // INS_pmovmskb
        INS_TT_QUARTER_MEM, // INS_pmovsxbd
        INS_TT_EIGHTH_MEM, // INS_pmovsxbq
        INS_TT_HALF_MEM, // INS_pmovsxbw
        INS_TT_HALF_MEM, // INS_pmovsxdq
        INS_TT_HALF_MEM, // INS_pmovsxwd
        INS_TT_QUARTER_MEM, // INS_pmovsxwq
        INS_TT_QUARTER_MEM, // INS_pmovzxbd
        INS_TT_EIGHTH_MEM, // INS_pmovzxbq
        INS_TT_HALF_MEM, // INS_pmovzxbw
        INS_TT_HALF_MEM, // INS_pmovzxdq
        INS_TT_HALF_MEM, // INS_pmovzxwd
        INS_TT_QUARTER_MEM, // INS_pmovzxwq
        INS_TT_FULL, // INS_pmuldq
        INS_TT_FULL_MEM, // INS_pmulhrsw
        INS_TT_FULL_MEM, // INS_pmulhuw
        INS_TT_FULL_MEM, // INS_pmulhw
        INS_TT_FULL, // INS_pmulld
        INS_TT_FULL, // INS_pmuludq
        INS_TT_FULL_MEM, // INS_pmullw
        INS_TT_FULL, // INS_pord
        INS_TT_TUPLE1_FIXED, // INS_prefetchnta
        INS_TT_TUPLE1_FIXED, // INS_prefetcht0
        INS_TT_TUPLE1_FIXED, // INS_prefetcht1
        INS_TT_TUPLE1_FIXED, // INS_prefetcht2
        INS_TT_FULL_MEM, // INS_psadbw
        INS_TT_FULL_MEM, // INS_pshufb
        INS_TT_FULL, // INS_pshufd
        INS_TT_FULL_MEM, // INS_pshufhw
        INS_TT_FULL_MEM, // INS_pshuflw
        INS_TT_FULL_MEM, // INS_psignb
        INS_TT_FULL_MEM, // INS_psignd
        INS_TT_FULL_MEM, // INS_psignw
        INS_TT_FULL     | INS_TT_MEM128, // INS_pslld
        INS_TT_FULL_MEM, // INS_pslldq
        INS_TT_FULL     | INS_TT_MEM128, // INS_psllq
        INS_TT_FULL_MEM | INS_TT_MEM128, // INS_psllw
        INS_TT_FULL     | INS_TT_MEM128, // INS_psrad
        INS_TT_FULL_MEM | INS_TT_MEM128, // INS_psraw
        INS_TT_FULL     | INS_TT_MEM128, // INS_psrld
        INS_TT_FULL_MEM, // INS_psrldq
        INS_TT_FULL     | INS_TT_MEM128, // INS_psrlq
        INS_TT_FULL_MEM | INS_TT_MEM128, // INS_psrlw
        INS_TT_FULL_MEM, // INS_psubb
        INS_TT_FULL, // INS_psubd
        INS_TT_FULL, // INS_psubq
        INS_TT_FULL_MEM, // INS_psubsb
        INS_TT_FULL_MEM, // INS_psubsw
        INS_TT_FULL_MEM, // INS_psubusb
        INS_TT_FULL_MEM, // INS_psubusw
        INS_TT_FULL_MEM, // INS_psubw
        INS_TT_FULL_MEM, // INS_ptest
        INS_TT_FULL_MEM, // INS_punpckhbw
        INS_TT_FULL, // INS_punpckhdq
        INS_TT_FULL, // INS_punpckhqdq
        INS_TT_FULL_MEM, // INS_punpckhwd
        INS_TT_FULL_MEM, // INS_punpcklbw
        INS_TT_FULL, // INS_punpckldq
        INS_TT_FULL, // INS_punpcklqdq
        INS_TT_FULL_MEM, // INS_punpcklwd
        INS_TT_FULL, // INS_pxord
        INS_TT_FULL_MEM, // INS_rcpps
        INS_TT_TUPLE1_SCALAR, // INS_rcpss
        INS_TT_FULL, // INS_roundpd
        INS_TT_FULL, // INS_roundps
        INS_TT_TUPLE1_SCALAR, // INS_roundsd
        INS_TT_TUPLE1_SCALAR, // INS_roundss
        INS_TT_FULL_MEM, // INS_rsqrtps
        INS_TT_TUPLE1_SCALAR, // INS_rsqrtss
        INS_TT_NONE, // INS_sfence
        INS_TT_FULL, // INS_shufpd
        INS_TT_FULL, // INS_shufps
        INS_TT_FULL, // INS_sqrtpd
        INS_TT_FULL, // INS_sqrtps
        INS_TT_TUPLE1_SCALAR, // INS_sqrtsd
        INS_TT_TUPLE1_SCALAR, // INS_sqrtss
        INS_TT_FULL, // INS_subpd
        INS_TT_FULL, // INS_subps
        INS_TT_TUPLE1_SCALAR, // INS_subsd
        INS_TT_TUPLE1_SCALAR, // INS_subss
        INS_TT_TUPLE1_SCALAR, // INS_ucomisd
        INS_TT_TUPLE1_SCALAR, // INS_ucomiss
        INS_TT_FULL, // INS_unpckhpd
        INS_TT_FULL, // INS_unpckhps
        INS_TT_FULL, // INS_unpcklpd
        INS_TT_FULL, // INS_unpcklps
        INS_TT_FULL, // INS_xorpd
        INS_TT_FULL, // INS_xorps
        INS_TT_FULL_MEM, // INS_aesdec
        INS_TT_FULL_MEM, // INS_aesdeclast
        INS_TT_FULL_MEM, // INS_aesenc
        INS_TT_FULL_MEM, // INS_aesenclast
        INS_TT_FULL_MEM, // INS_aesimc
        INS_TT_FULL_MEM, // INS_aeskeygenassist
        INS_TT_FULL_MEM, // INS_pclmulqdq
        INS_TT_FULL_MEM, // INS_sha1msg1
        INS_TT_FULL_MEM, // INS_sha1msg2
        INS_TT_FULL_MEM, // INS_sha1nexte
        INS_TT_FULL_MEM, // INS_sha1rnds4
        INS_TT_FULL_MEM, // INS_sha256msg1
        INS_TT_FULL_MEM, // INS_sha256msg2
        INS_TT_FULL_MEM, // INS_sha256rnds2
        INS_TT_FULL, // INS_gf2p8affineinvqb
        INS_TT_FULL, // INS_gf2p8affineqb
        INS_TT_FULL_MEM, // INS_gf2p8mulb
        INS_TT_FULL_MEM, // INS_vblendvpd
        INS_TT_FULL_MEM, // INS_vblendvps
        INS_TT_TUPLE4, // INS_vbroadcastf32x4
        INS_TT_TUPLE1_SCALAR, // INS_vbroadcastsd
        INS_TT_TUPLE1_SCALAR, // INS_vbroadcastss
        INS_TT_TUPLE4, // INS_vextractf32x4
        INS_TT_TUPLE4, // INS_vinsertf32x4
        INS_TT_FULL_MEM, // INS_vmaskmovpd
        INS_TT_FULL_MEM, // INS_vmaskmovps
        INS_TT_FULL_MEM, // INS_vpblendvb
        INS_TT_FULL_MEM, // INS_vperm2f128
        INS_TT_FULL, // INS_vpermilpd
        INS_TT_FULL, // INS_vpermilpdvar
        INS_TT_FULL, // INS_vpermilps
        INS_TT_FULL, // INS_vpermilpsvar
        INS_TT_FULL_MEM, // INS_vtestpd
        INS_TT_FULL_MEM, // INS_vtestps
        INS_TT_NONE, // INS_vzeroupper
        INS_TT_TUPLE4, // INS_vbroadcasti32x4
        INS_TT_HALF_MEM, // INS_vcvtph2ps
        INS_TT_HALF_MEM, // INS_vcvtps2ph
        INS_TT_TUPLE4, // INS_vextracti32x4
        INS_TT_TUPLE1_SCALAR, // INS_vgatherdpd
        INS_TT_TUPLE1_SCALAR, // INS_vgatherdps
        INS_TT_TUPLE1_SCALAR, // INS_vgatherqpd
        INS_TT_TUPLE1_SCALAR, // INS_vgatherqps
        INS_TT_TUPLE4, // INS_vinserti32x4
        INS_TT_FULL_MEM, // INS_vpblendd
        INS_TT_TUPLE1_SCALAR, // INS_vpbroadcastb
        INS_TT_TUPLE1_SCALAR, // INS_vpbroadcastd
        INS_TT_TUPLE1_SCALAR, // INS_vpbroadcastq
        INS_TT_TUPLE1_SCALAR, // INS_vpbroadcastw
        INS_TT_FULL_MEM, // INS_vperm2i128
        INS_TT_FULL, // INS_vpermd
        INS_TT_FULL, // INS_vpermpd
        INS_TT_FULL, // INS_vpermps
        INS_TT_FULL, // INS_vpermq
        INS_TT_TUPLE1_SCALAR, // INS_vpgatherdd
        INS_TT_TUPLE1_SCALAR, // INS_vpgatherdq
        INS_TT_TUPLE1_SCALAR, // INS_vpgatherqd
        INS_TT_TUPLE1_SCALAR, // INS_vpgatherqq
        INS_TT_FULL_MEM, // INS_vpmaskmovd
        INS_TT_FULL_MEM, // INS_vpmaskmovq
        INS_TT_FULL, // INS_vpsllvd
        INS_TT_FULL, // INS_vpsllvq
        INS_TT_FULL, // INS_vpsravd
        INS_TT_FULL, // INS_vpsrlvd
        INS_TT_FULL, // INS_vpsrlvq
        INS_TT_FULL, // INS_vfmadd132pd
        INS_TT_FULL, // INS_vfmadd213pd
        INS_TT_FULL, // INS_vfmadd231pd
        INS_TT_FULL, // INS_vfmadd132ps
        INS_TT_FULL, // INS_vfmadd213ps
        INS_TT_FULL, // INS_vfmadd231ps
        INS_TT_TUPLE1_SCALAR, // INS_vfmadd132sd
        INS_TT_TUPLE1_SCALAR, // INS_vfmadd213sd
        INS_TT_TUPLE1_SCALAR, // INS_vfmadd231sd
        INS_TT_TUPLE1_SCALAR, // INS_vfmadd132ss
        INS_TT_TUPLE1_SCALAR, // INS_vfmadd213ss
        INS_TT_TUPLE1_SCALAR, // INS_vfmadd231ss
        INS_TT_FULL, // INS_vfmaddsub132pd
        INS_TT_FULL, // INS_vfmaddsub213pd
        INS_TT_FULL, // INS_vfmaddsub231pd
        INS_TT_FULL, // INS_vfmaddsub132ps
        INS_TT_FULL, // INS_vfmaddsub213ps
        INS_TT_FULL, // INS_vfmaddsub231ps
        INS_TT_FULL, // INS_vfmsubadd132pd
        INS_TT_FULL, // INS_vfmsubadd213pd
        INS_TT_FULL, // INS_vfmsubadd231pd
        INS_TT_FULL, // INS_vfmsubadd132ps
        INS_TT_FULL, // INS_vfmsubadd213ps
        INS_TT_FULL, // INS_vfmsubadd231ps
        INS_TT_FULL, // INS_vfmsub132pd
        INS_TT_FULL, // INS_vfmsub213pd
        INS_TT_FULL, // INS_vfmsub231pd
        INS_TT_FULL, // INS_vfmsub132ps
        INS_TT_FULL, // INS_vfmsub213ps
        INS_TT_FULL, // INS_vfmsub231ps
        INS_TT_TUPLE1_SCALAR, // INS_vfmsub132sd
        INS_TT_TUPLE1_SCALAR, // INS_vfmsub213sd
        INS_TT_TUPLE1_SCALAR, // INS_vfmsub231sd
        INS_TT_TUPLE1_SCALAR, // INS_vfmsub132ss
        INS_TT_TUPLE1_SCALAR, // INS_vfmsub213ss
        INS_TT_TUPLE1_SCALAR, // INS_vfmsub231ss
        INS_TT_FULL, // INS_vfnmadd132pd
        INS_TT_FULL, // INS_vfnmadd213pd
        INS_TT_FULL, // INS_vfnmadd231pd
        INS_TT_FULL, // INS_vfnmadd132ps
        INS_TT_FULL, // INS_vfnmadd213ps
        INS_TT_FULL, // INS_vfnmadd231ps
        INS_TT_TUPLE1_SCALAR, // INS_vfnmadd132sd
        INS_TT_TUPLE1_SCALAR, // INS_vfnmadd213sd
        INS_TT_TUPLE1_SCALAR, // INS_vfnmadd231sd
        INS_TT_TUPLE1_SCALAR, // INS_vfnmadd132ss
        INS_TT_TUPLE1_SCALAR, // INS_vfnmadd213ss
        INS_TT_TUPLE1_SCALAR, // INS_vfnmadd231ss
        INS_TT_FULL, // INS_vfnmsub132pd
        INS_TT_FULL, // INS_vfnmsub213pd
        INS_TT_FULL, // INS_vfnmsub231pd
        INS_TT_FULL, // INS_vfnmsub132ps
        INS_TT_FULL, // INS_vfnmsub213ps
        INS_TT_FULL, // INS_vfnmsub231ps
        INS_TT_TUPLE1_SCALAR, // INS_vfnmsub132sd
        INS_TT_TUPLE1_SCALAR, // INS_vfnmsub213sd
        INS_TT_TUPLE1_SCALAR, // INS_vfnmsub231sd
        INS_TT_TUPLE1_SCALAR, // INS_vfnmsub132ss
        INS_TT_TUPLE1_SCALAR, // INS_vfnmsub213ss
        INS_TT_TUPLE1_SCALAR, // INS_vfnmsub231ss
        INS_TT_NONE, // INS_andn
        INS_TT_NONE, // INS_bextr
        INS_TT_NONE, // INS_blsi
        INS_TT_NONE, // INS_blsmsk
        INS_TT_NONE, // INS_blsr
        INS_TT_NONE, // INS_bzhi
        INS_TT_NONE, // INS_mulx
        INS_TT_NONE, // INS_pdep
        INS_TT_NONE, // INS_pext
        INS_TT_NONE, // INS_rorx
        INS_TT_NONE, // INS_sarx
        INS_TT_NONE, // INS_shlx
        INS_TT_NONE, // INS_shrx
        INS_TT_FULL, // INS_vpdpbusd
        INS_TT_FULL, // INS_vpdpbusds
        INS_TT_FULL, // INS_vpdpwssd
        INS_TT_FULL, // INS_vpdpwssds
        INS_TT_FULL, // INS_vpdpwsud
        INS_TT_FULL, // INS_vpdpwsuds
        INS_TT_FULL, // INS_vpdpwusd
        INS_TT_FULL, // INS_vpdpwusds
        INS_TT_FULL, // INS_vpdpwuud
        INS_TT_FULL, // INS_vpdpwuuds
        INS_TT_FULL, // INS_vpdpbssd
        INS_TT_FULL, // INS_vpdpbssds
        INS_TT_FULL, // INS_vpdpbsud
        INS_TT_FULL, // INS_vpdpbsuds
        INS_TT_FULL, // INS_vpdpbuud
        INS_TT_FULL, // INS_vpdpbuuds
        INS_TT_FULL_MEM, // INS_vbmacor16x16x16
        INS_TT_FULL_MEM, // INS_vbmacxor16x16x16
        INS_TT_FULL_MEM, // INS_vbitrev
        INS_TT_FULL, // INS_vpmadd52huq
        INS_TT_FULL, // INS_vpmadd52luq
        INS_TT_NONE, // INS_kaddb
        INS_TT_NONE, // INS_kaddd
        INS_TT_NONE, // INS_kaddq
        INS_TT_NONE, // INS_kaddw
        INS_TT_NONE, // INS_kandb
        INS_TT_NONE, // INS_kandd
        INS_TT_NONE, // INS_kandnb
        INS_TT_NONE, // INS_kandnd
        INS_TT_NONE, // INS_kandnq
        INS_TT_NONE, // INS_kandnw
        INS_TT_NONE, // INS_kandq
        INS_TT_NONE, // INS_kandw
        INS_TT_NONE, // INS_kmovb_gpr
        INS_TT_NONE, // INS_kmovb_msk
        INS_TT_NONE, // INS_kmovd_gpr
        INS_TT_NONE, // INS_kmovd_msk
        INS_TT_NONE, // INS_kmovq_gpr
        INS_TT_NONE, // INS_kmovq_msk
        INS_TT_NONE, // INS_kmovw_gpr
        INS_TT_NONE, // INS_kmovw_msk
        INS_TT_NONE, // INS_knotb
        INS_TT_NONE, // INS_knotd
        INS_TT_NONE, // INS_knotq
        INS_TT_NONE, // INS_knotw
        INS_TT_NONE, // INS_korb
        INS_TT_NONE, // INS_kord
        INS_TT_NONE, // INS_korq
        INS_TT_NONE, // INS_kortestb
        INS_TT_NONE, // INS_kortestd
        INS_TT_NONE, // INS_kortestq
        INS_TT_NONE, // INS_kortestw
        INS_TT_NONE, // INS_korw
        INS_TT_NONE, // INS_kshiftlb
        INS_TT_NONE, // INS_kshiftld
        INS_TT_NONE, // INS_kshiftlq
        INS_TT_NONE, // INS_kshiftlw
        INS_TT_NONE, // INS_kshiftrb
        INS_TT_NONE, // INS_kshiftrd
        INS_TT_NONE, // INS_kshiftrq
        INS_TT_NONE, // INS_kshiftrw
        INS_TT_NONE, // INS_ktestb
        INS_TT_NONE, // INS_ktestd
        INS_TT_NONE, // INS_ktestq
        INS_TT_NONE, // INS_ktestw
        INS_TT_NONE, // INS_kunpckbw
        INS_TT_NONE, // INS_kunpckdq
        INS_TT_NONE, // INS_kunpckwd
        INS_TT_NONE, // INS_kxnorb
        INS_TT_NONE, // INS_kxnord
        INS_TT_NONE, // INS_kxnorq
        INS_TT_NONE, // INS_kxnorw
        INS_TT_NONE, // INS_kxorb
        INS_TT_NONE, // INS_kxord
        INS_TT_NONE, // INS_kxorq
        INS_TT_NONE, // INS_kxorw
        INS_TT_FULL, // INS_valignd
        INS_TT_FULL, // INS_valignq
        INS_TT_FULL, // INS_vblendmpd
        INS_TT_FULL, // INS_vblendmps
        INS_TT_TUPLE2, // INS_vbroadcastf32x2
        INS_TT_TUPLE8, // INS_vbroadcastf32x8
        INS_TT_TUPLE2, // INS_vbroadcastf64x2
        INS_TT_TUPLE2, // INS_vbroadcastf64x4
        INS_TT_TUPLE2, // INS_vbroadcasti32x2
        INS_TT_TUPLE8, // INS_vbroadcasti32x8
        INS_TT_TUPLE2, // INS_vbroadcasti64x2
        INS_TT_TUPLE2, // INS_vbroadcasti64x4
        INS_TT_FULL, // INS_vcmppd
        INS_TT_FULL, // INS_vcmpps
        INS_TT_TUPLE1_SCALAR, // INS_vcmpsd
        INS_TT_TUPLE1_SCALAR, // INS_vcmpss
        INS_TT_FULL_MEM, // INS_vcompresspd
        INS_TT_FULL_MEM, // INS_vcompressps
        INS_TT_FULL, // INS_vcvtpd2qq
        INS_TT_FULL, // INS_vcvtpd2udq
        INS_TT_FULL, // INS_vcvtpd2uqq
        INS_TT_HALF, // INS_vcvtps2qq
        INS_TT_FULL, // INS_vcvtps2udq
        INS_TT_HALF, // INS_vcvtps2uqq
        INS_TT_FULL, // INS_vcvtqq2pd
        INS_TT_FULL, // INS_vcvtqq2ps
        INS_TT_TUPLE1_FIXED, // INS_vcvtsd2usi32
        INS_TT_TUPLE1_FIXED, // INS_vcvtsd2usi64
        INS_TT_TUPLE1_FIXED, // INS_vcvtss2usi32
        INS_TT_TUPLE1_FIXED, // INS_vcvtss2usi64
        INS_TT_FULL, // INS_vcvttpd2qq
        INS_TT_FULL, // INS_vcvttpd2udq
        INS_TT_FULL, // INS_vcvttpd2uqq
        INS_TT_HALF, // INS_vcvttps2qq
        INS_TT_FULL, // INS_vcvttps2udq
        INS_TT_HALF, // INS_vcvttps2uqq
        INS_TT_TUPLE1_FIXED, // INS_vcvttsd2usi32
        INS_TT_TUPLE1_FIXED, // INS_vcvttsd2usi64
        INS_TT_TUPLE1_FIXED, // INS_vcvttss2usi32
        INS_TT_TUPLE1_FIXED, // INS_vcvttss2usi64
        INS_TT_HALF, // INS_vcvtudq2pd
        INS_TT_FULL, // INS_vcvtudq2ps
        INS_TT_FULL, // INS_vcvtuqq2pd
        INS_TT_FULL, // INS_vcvtuqq2ps
        INS_TT_TUPLE1_SCALAR, // INS_vcvtusi2sd32
        INS_TT_TUPLE1_SCALAR, // INS_vcvtusi2sd64
        INS_TT_TUPLE1_SCALAR, // INS_vcvtusi2ss32
        INS_TT_TUPLE1_SCALAR, // INS_vcvtusi2ss64
        INS_TT_FULL_MEM, // INS_vdbpsadbw
        INS_TT_FULL_MEM, // INS_vexpandpd
        INS_TT_FULL_MEM, // INS_vexpandps
        INS_TT_TUPLE8, // INS_vextractf32x8
        INS_TT_TUPLE2, // INS_vextractf64x2
        INS_TT_TUPLE4, // INS_vextractf64x4
        INS_TT_TUPLE8, // INS_vextracti32x8
        INS_TT_TUPLE2, // INS_vextracti64x2
        INS_TT_TUPLE4, // INS_vextracti64x4
        INS_TT_FULL, // INS_vfixupimmpd
        INS_TT_FULL, // INS_vfixupimmps
        INS_TT_TUPLE1_SCALAR, // INS_vfixupimmsd
        INS_TT_TUPLE1_SCALAR, // INS_vfixupimmss
        INS_TT_FULL, // INS_vfpclasspd
        INS_TT_FULL, // INS_vfpclassps
        INS_TT_TUPLE1_SCALAR, // INS_vfpclasssd
        INS_TT_TUPLE1_SCALAR, // INS_vfpclassss
        INS_TT_TUPLE1_SCALAR, // INS_vgatherdpd_msk
        INS_TT_TUPLE1_SCALAR, // INS_vgatherdps_msk
        INS_TT_TUPLE1_SCALAR, // INS_vgatherqpd_msk
        INS_TT_TUPLE1_SCALAR, // INS_vgatherqps_msk
        INS_TT_FULL, // INS_vgetexppd
        INS_TT_FULL, // INS_vgetexpps
        INS_TT_TUPLE1_SCALAR, // INS_vgetexpsd
        INS_TT_TUPLE1_SCALAR, // INS_vgetexpss
        INS_TT_FULL, // INS_vgetmantpd
        INS_TT_FULL, // INS_vgetmantps
        INS_TT_TUPLE1_SCALAR, // INS_vgetmantsd
        INS_TT_TUPLE1_SCALAR, // INS_vgetmantss
        INS_TT_TUPLE8, // INS_vinsertf32x8
        INS_TT_TUPLE2, // INS_vinsertf64x2
        INS_TT_TUPLE4, // INS_vinsertf64x4
        INS_TT_TUPLE8, // INS_vinserti32x8
        INS_TT_TUPLE2, // INS_vinserti64x2
        INS_TT_TUPLE4, // INS_vinserti64x4
        INS_TT_FULL_MEM, // INS_vmovdqa64
        INS_TT_FULL_MEM, // INS_vmovdqu16
        INS_TT_FULL_MEM, // INS_vmovdqu64
        INS_TT_FULL_MEM, // INS_vmovdqu8
        INS_TT_FULL, // INS_vpabsq
        INS_TT_FULL, // INS_vpandnq
        INS_TT_FULL, // INS_vpandq
        INS_TT_FULL_MEM, // INS_vpblendmb
        INS_TT_FULL, // INS_vpblendmd
        INS_TT_FULL, // INS_vpblendmq
        INS_TT_FULL_MEM, // INS_vpblendmw
        INS_TT_TUPLE1_SCALAR, // INS_vpbroadcastb_gpr
        INS_TT_TUPLE1_SCALAR, // INS_vpbroadcastd_gpr
        INS_TT_TUPLE1_SCALAR, // INS_vpbroadcastq_gpr
        INS_TT_TUPLE1_SCALAR, // INS_vpbroadcastw_gpr
        INS_TT_FULL_MEM, // INS_vpcmpb
        INS_TT_FULL, // INS_vpcmpd
        INS_TT_FULL_MEM, // INS_vpcmpeqb
        INS_TT_FULL, // INS_vpcmpeqd
        INS_TT_FULL, // INS_vpcmpeqq
        INS_TT_FULL_MEM, // INS_vpcmpeqw
        INS_TT_FULL_MEM, // INS_vpcmpgtb
        INS_TT_FULL, // INS_vpcmpgtd
        INS_TT_FULL, // INS_vpcmpgtq
        INS_TT_FULL_MEM, // INS_vpcmpgtw
        INS_TT_FULL, // INS_vpcmpq
        INS_TT_FULL_MEM, // INS_vpcmpub
        INS_TT_FULL, // INS_vpcmpud
        INS_TT_FULL, // INS_vpcmpuq
        INS_TT_FULL_MEM, // INS_vpcmpuw
        INS_TT_FULL_MEM, // INS_vpcmpw
        INS_TT_FULL_MEM, // INS_vpcompressd
        INS_TT_FULL_MEM, // INS_vpcompressq
        INS_TT_FULL, // INS_vpconflictd
        INS_TT_FULL, // INS_vpconflictq
        INS_TT_FULL, // INS_vpermi2d
        INS_TT_FULL, // INS_vpermi2pd
        INS_TT_FULL, // INS_vpermi2ps
        INS_TT_FULL, // INS_vpermi2q
        INS_TT_FULL_MEM, // INS_vpermi2w
        INS_TT_FULL, // INS_vpermpd_reg
        INS_TT_FULL, // INS_vpermq_reg
        INS_TT_FULL, // INS_vpermt2d
        INS_TT_FULL, // INS_vpermt2pd
        INS_TT_FULL, // INS_vpermt2ps
        INS_TT_FULL, // INS_vpermt2q
        INS_TT_FULL_MEM, // INS_vpermt2w
        INS_TT_FULL_MEM, // INS_vpermw
        INS_TT_FULL_MEM, // INS_vpexpandd
        INS_TT_FULL_MEM, // INS_vpexpandq
        INS_TT_TUPLE1_SCALAR, // INS_vpgatherdd_msk
        INS_TT_TUPLE1_SCALAR, // INS_vpgatherdq_msk
        INS_TT_TUPLE1_SCALAR, // INS_vpgatherqd_msk
        INS_TT_TUPLE1_SCALAR, // INS_vpgatherqq_msk
        INS_TT_FULL, // INS_vplzcntd
        INS_TT_FULL, // INS_vplzcntq
        INS_TT_FULL, // INS_vpmaxsq
        INS_TT_FULL, // INS_vpmaxuq
        INS_TT_FULL, // INS_vpminsq
        INS_TT_FULL, // INS_vpminuq
        INS_TT_NONE, // INS_vpmovb2m
        INS_TT_NONE, // INS_vpmovd2m
        INS_TT_QUARTER_MEM, // INS_vpmovdb
        INS_TT_HALF_MEM, // INS_vpmovdw
        INS_TT_NONE, // INS_vpmovm2b
        INS_TT_NONE, // INS_vpmovm2d
        INS_TT_NONE, // INS_vpmovm2q
        INS_TT_NONE, // INS_vpmovm2w
        INS_TT_NONE, // INS_vpmovq2m
        INS_TT_EIGHTH_MEM, // INS_vpmovqb
        INS_TT_HALF_MEM, // INS_vpmovqd
        INS_TT_QUARTER_MEM, // INS_vpmovqw
        INS_TT_QUARTER_MEM, // INS_vpmovsdb
        INS_TT_HALF_MEM, // INS_vpmovsdw
        INS_TT_EIGHTH_MEM, // INS_vpmovsqb
        INS_TT_HALF_MEM, // INS_vpmovsqd
        INS_TT_QUARTER_MEM, // INS_vpmovsqw
        INS_TT_HALF_MEM, // INS_vpmovswb
        INS_TT_QUARTER_MEM, // INS_vpmovusdb
        INS_TT_HALF_MEM, // INS_vpmovusdw
        INS_TT_EIGHTH_MEM, // INS_vpmovusqb
        INS_TT_HALF_MEM, // INS_vpmovusqd
        INS_TT_QUARTER_MEM, // INS_vpmovusqw
        INS_TT_HALF_MEM, // INS_vpmovuswb
        INS_TT_NONE, // INS_vpmovw2m
        INS_TT_HALF_MEM, // INS_vpmovwb
        INS_TT_FULL, // INS_vpmullq
        INS_TT_FULL, // INS_vporq
        INS_TT_FULL, // INS_vprold
        INS_TT_FULL, // INS_vprolq
        INS_TT_FULL, // INS_vprolvd
        INS_TT_FULL, // INS_vprolvq
        INS_TT_FULL, // INS_vprord
        INS_TT_FULL, // INS_vprorq
        INS_TT_FULL, // INS_vprorvd
        INS_TT_FULL, // INS_vprorvq
        INS_TT_TUPLE1_SCALAR, // INS_vpscatterdd_msk
        INS_TT_TUPLE1_SCALAR, // INS_vpscatterdq_msk
        INS_TT_TUPLE1_SCALAR, // INS_vpscatterqd_msk
        INS_TT_TUPLE1_SCALAR, // INS_vpscatterqq_msk
        INS_TT_FULL_MEM, // INS_vpsllvw
        INS_TT_FULL     | INS_TT_MEM128, // INS_vpsraq
        INS_TT_FULL, // INS_vpsravq
        INS_TT_FULL_MEM, // INS_vpsravw
        INS_TT_FULL_MEM, // INS_vpsrlvw
        INS_TT_FULL, // INS_vpternlogd
        INS_TT_FULL, // INS_vpternlogq
        INS_TT_FULL_MEM, // INS_vptestmb
        INS_TT_FULL, // INS_vptestmd
        INS_TT_FULL, // INS_vptestmq
        INS_TT_FULL_MEM, // INS_vptestmw
        INS_TT_FULL_MEM, // INS_vptestnmb
        INS_TT_FULL, // INS_vptestnmd
        INS_TT_FULL, // INS_vptestnmq
        INS_TT_FULL_MEM, // INS_vptestnmw
        INS_TT_FULL, // INS_vpxorq
        INS_TT_FULL, // INS_vrangepd
        INS_TT_FULL, // INS_vrangeps
        INS_TT_TUPLE1_SCALAR, // INS_vrangesd
        INS_TT_TUPLE1_SCALAR, // INS_vrangess
        INS_TT_FULL, // INS_vrcp14pd
        INS_TT_FULL, // INS_vrcp14ps
        INS_TT_TUPLE1_SCALAR, // INS_vrcp14sd
        INS_TT_TUPLE1_SCALAR, // INS_vrcp14ss
        INS_TT_FULL, // INS_vreducepd
        INS_TT_FULL, // INS_vreduceps
        INS_TT_TUPLE1_SCALAR, // INS_vreducesd
        INS_TT_TUPLE1_SCALAR, // INS_vreducess
        INS_TT_FULL, // INS_vrndscalepd
        INS_TT_FULL, // INS_vrndscaleps
        INS_TT_TUPLE1_SCALAR, // INS_vrndscalesd
        INS_TT_TUPLE1_SCALAR, // INS_vrndscaless
        INS_TT_FULL, // INS_vrsqrt14pd
        INS_TT_FULL, // INS_vrsqrt14ps
        INS_TT_TUPLE1_SCALAR, // INS_vrsqrt14sd
        INS_TT_TUPLE1_SCALAR, // INS_vrsqrt14ss
        INS_TT_FULL, // INS_vscalefpd
        INS_TT_FULL, // INS_vscalefps
        INS_TT_TUPLE1_SCALAR, // INS_vscalefsd
        INS_TT_TUPLE1_SCALAR, // INS_vscalefss
        INS_TT_TUPLE1_SCALAR, // INS_vscatterdpd_msk
        INS_TT_TUPLE1_SCALAR, // INS_vscatterdps_msk
        INS_TT_TUPLE1_SCALAR, // INS_vscatterqpd_msk
        INS_TT_TUPLE1_SCALAR, // INS_vscatterqps_msk
        INS_TT_FULL, // INS_vshuff32x4
        INS_TT_FULL, // INS_vshuff64x2
        INS_TT_FULL, // INS_vshufi32x4
        INS_TT_FULL, // INS_vshufi64x2
        INS_TT_FULL_MEM, // INS_vpermb
        INS_TT_FULL_MEM, // INS_vpermi2b
        INS_TT_FULL_MEM, // INS_vpermt2b
        INS_TT_FULL, // INS_vpmultishiftqb
        INS_TT_FULL_MEM, // INS_vpcompressb
        INS_TT_FULL_MEM, // INS_vpcompressw
        INS_TT_FULL_MEM, // INS_vpexpandb
        INS_TT_FULL_MEM, // INS_vpexpandw
        INS_TT_FULL_MEM, // INS_vpopcntb
        INS_TT_FULL, // INS_vpopcntd
        INS_TT_FULL, // INS_vpopcntq
        INS_TT_FULL_MEM, // INS_vpopcntw
        INS_TT_FULL, // INS_vpshldd
        INS_TT_FULL, // INS_vpshldq
        INS_TT_FULL, // INS_vpshldvd
        INS_TT_FULL, // INS_vpshldvq
        INS_TT_FULL_MEM, // INS_vpshldvw
        INS_TT_FULL_MEM, // INS_vpshldw
        INS_TT_FULL, // INS_vpshrdd
        INS_TT_FULL, // INS_vpshrdq
        INS_TT_FULL, // INS_vpshrdvd
        INS_TT_FULL, // INS_vpshrdvq
        INS_TT_FULL_MEM, // INS_vpshrdvw
        INS_TT_FULL_MEM, // INS_vpshrdw
        INS_TT_FULL_MEM, // INS_vpshufbitqmb
        INS_TT_FULL_MEM, // INS_vaddph
        INS_TT_TUPLE1_SCALAR, // INS_vaddsh
        INS_TT_FULL_MEM, // INS_vcmpph
        INS_TT_TUPLE1_SCALAR, // INS_vcmpsh
        INS_TT_TUPLE1_SCALAR, // INS_vcomish
        INS_TT_FULL, // INS_vcvtdq2ph
        INS_TT_FULL, // INS_vcvtne2ps2bf16
        INS_TT_FULL, // INS_vcvtneps2bf16
        INS_TT_FULL, // INS_vcvtpd2ph
        INS_TT_HALF_MEM, // INS_vcvtph2dq
        INS_TT_QUARTER_MEM, // INS_vcvtph2pd
        INS_TT_HALF_MEM, // INS_vcvtph2psx
        INS_TT_QUARTER_MEM, // INS_vcvtph2qq
        INS_TT_HALF_MEM, // INS_vcvtph2udq
        INS_TT_QUARTER_MEM, // INS_vcvtph2uqq
        INS_TT_FULL_MEM, // INS_vcvtph2uw
        INS_TT_FULL_MEM, // INS_vcvtph2w
        INS_TT_FULL, // INS_vcvtps2phx
        INS_TT_FULL, // INS_vcvtqq2ph
        INS_TT_TUPLE1_SCALAR, // INS_vcvtsd2sh
        INS_TT_TUPLE1_SCALAR, // INS_vcvtsh2sd
        INS_TT_TUPLE1_SCALAR, // INS_vcvtsh2si32
        INS_TT_TUPLE1_SCALAR, // INS_vcvtsh2si64
        INS_TT_TUPLE1_SCALAR, // INS_vcvtsh2ss
        INS_TT_TUPLE1_SCALAR, // INS_vcvtsh2usi32
        INS_TT_TUPLE1_SCALAR, // INS_vcvtsh2usi64
        INS_TT_TUPLE1_SCALAR, // INS_vcvtsi2sh32
        INS_TT_TUPLE1_SCALAR, // INS_vcvtsi2sh64
        INS_TT_TUPLE1_SCALAR, // INS_vcvtss2sh
        INS_TT_HALF_MEM, // INS_vcvttph2dq
        INS_TT_QUARTER_MEM, // INS_vcvttph2qq
        INS_TT_HALF_MEM, // INS_vcvttph2udq
        INS_TT_QUARTER_MEM, // INS_vcvttph2uqq
        INS_TT_FULL_MEM, // INS_vcvttph2uw
        INS_TT_FULL_MEM, // INS_vcvttph2w
        INS_TT_TUPLE1_SCALAR, // INS_vcvttsh2si32
        INS_TT_TUPLE1_SCALAR, // INS_vcvttsh2si64
        INS_TT_TUPLE1_SCALAR, // INS_vcvttsh2usi32
        INS_TT_TUPLE1_SCALAR, // INS_vcvttsh2usi64
        INS_TT_FULL, // INS_vcvtudq2ph
        INS_TT_FULL, // INS_vcvtuqq2ph
        INS_TT_TUPLE1_SCALAR, // INS_vcvtusi2sh32
        INS_TT_TUPLE1_SCALAR, // INS_vcvtusi2sh64
        INS_TT_FULL_MEM, // INS_vcvtuw2ph
        INS_TT_FULL_MEM, // INS_vcvtw2ph
        INS_TT_FULL_MEM, // INS_vdivph
        INS_TT_TUPLE1_SCALAR, // INS_vdivsh
        INS_TT_FULL, // INS_vdpbf16ps
        INS_TT_FULL, // INS_vfcmaddcph
        INS_TT_TUPLE1_SCALAR, // INS_vfcmaddcsh
        INS_TT_FULL, // INS_vfcmulcph
        INS_TT_TUPLE1_SCALAR, // INS_vfcmulcsh
        INS_TT_FULL, // INS_vfmulcph
        INS_TT_TUPLE1_SCALAR, // INS_vfmulcsh
        INS_TT_FULL_MEM, // INS_vfmadd132ph
        INS_TT_FULL_MEM, // INS_vfmadd213ph
        INS_TT_FULL_MEM, // INS_vfmadd231ph
        INS_TT_TUPLE1_SCALAR, // INS_vfmadd132sh
        INS_TT_TUPLE1_SCALAR, // INS_vfmadd213sh
        INS_TT_TUPLE1_SCALAR, // INS_vfmadd231sh
        INS_TT_FULL, // INS_vfmaddcph
        INS_TT_TUPLE1_SCALAR, // INS_vfmaddcsh
        INS_TT_FULL_MEM, // INS_vfmaddsub132ph
        INS_TT_FULL_MEM, // INS_vfmaddsub213ph
        INS_TT_FULL_MEM, // INS_vfmaddsub231ph
        INS_TT_FULL_MEM, // INS_vfmsub132ph
        INS_TT_FULL_MEM, // INS_vfmsub213ph
        INS_TT_FULL_MEM, // INS_vfmsub231ph
        INS_TT_TUPLE1_SCALAR, // INS_vfmsub132sh
        INS_TT_TUPLE1_SCALAR, // INS_vfmsub213sh
        INS_TT_TUPLE1_SCALAR, // INS_vfmsub231sh
        INS_TT_FULL_MEM, // INS_vfmsubadd132ph
        INS_TT_FULL_MEM, // INS_vfmsubadd213ph
        INS_TT_FULL_MEM, // INS_vfmsubadd231ph
        INS_TT_FULL_MEM, // INS_vfnmadd132ph
        INS_TT_FULL_MEM, // INS_vfnmadd213ph
        INS_TT_FULL_MEM, // INS_vfnmadd231ph
        INS_TT_TUPLE1_SCALAR, // INS_vfnmadd132sh
        INS_TT_TUPLE1_SCALAR, // INS_vfnmadd213sh
        INS_TT_TUPLE1_SCALAR, // INS_vfnmadd231sh
        INS_TT_FULL_MEM, // INS_vfnmsub132ph
        INS_TT_FULL_MEM, // INS_vfnmsub213ph
        INS_TT_FULL_MEM, // INS_vfnmsub231ph
        INS_TT_TUPLE1_SCALAR, // INS_vfnmsub132sh
        INS_TT_TUPLE1_SCALAR, // INS_vfnmsub213sh
        INS_TT_TUPLE1_SCALAR, // INS_vfnmsub231sh
        INS_TT_FULL_MEM, // INS_vfpclassph
        INS_TT_TUPLE1_SCALAR, // INS_vfpclasssh
        INS_TT_FULL_MEM, // INS_vgetexpph
        INS_TT_TUPLE1_SCALAR, // INS_vgetexpsh
        INS_TT_FULL_MEM, // INS_vgetmantph
        INS_TT_TUPLE1_SCALAR, // INS_vgetmantsh
        INS_TT_FULL_MEM, // INS_vmaxph
        INS_TT_TUPLE1_SCALAR, // INS_vmaxsh
        INS_TT_TUPLE1_SCALAR, // INS_vminsh
        INS_TT_FULL_MEM, // INS_vminph
        INS_TT_TUPLE1_SCALAR, // INS_vmovsh
        INS_TT_TUPLE1_SCALAR, // INS_vmovw
        INS_TT_FULL_MEM, // INS_vmulph
        INS_TT_TUPLE1_SCALAR, // INS_vmulsh
        INS_TT_FULL_MEM, // INS_vrcpph
        INS_TT_TUPLE1_SCALAR, // INS_vrcpsh
        INS_TT_FULL_MEM, // INS_vreduceph
        INS_TT_TUPLE1_SCALAR, // INS_vreducesh
        INS_TT_FULL_MEM, // INS_vrndscaleph
        INS_TT_TUPLE1_SCALAR, // INS_vrndscalesh
        INS_TT_FULL_MEM, // INS_vrsqrtph
        INS_TT_TUPLE1_SCALAR, // INS_vrsqrtsh
        INS_TT_FULL_MEM, // INS_vscalefph
        INS_TT_TUPLE1_SCALAR, // INS_vscalefsh
        INS_TT_FULL_MEM, // INS_vsqrtph
        INS_TT_TUPLE1_SCALAR, // INS_vsqrtsh
        INS_TT_FULL_MEM, // INS_vsubph
        INS_TT_TUPLE1_SCALAR, // INS_vsubsh
        INS_TT_TUPLE1_SCALAR, // INS_vucomish
        INS_TT_FULL, // INS_vp2intersectd
        INS_TT_FULL, // INS_vp2intersectq
        INS_TT_TUPLE1_SCALAR, // INS_vcomxsd
        INS_TT_TUPLE1_SCALAR, // INS_vcomxss
        INS_TT_FULL, // INS_vcvtps2ibs
        INS_TT_FULL, // INS_vcvtps2iubs
        INS_TT_FULL, // INS_vcvttpd2dqs
        INS_TT_FULL, // INS_vcvttpd2qqs
        INS_TT_FULL, // INS_vcvttpd2udqs
        INS_TT_FULL, // INS_vcvttpd2uqqs
        INS_TT_FULL, // INS_vcvttps2dqs
        INS_TT_FULL, // INS_vcvttps2ibs
        INS_TT_FULL, // INS_vcvttps2iubs
        INS_TT_HALF, // INS_vcvttps2qqs
        INS_TT_FULL, // INS_vcvttps2udqs
        INS_TT_HALF, // INS_vcvttps2uqqs
        INS_TT_TUPLE1_SCALAR, // INS_vcvttsd2sis32
        INS_TT_TUPLE1_SCALAR, // INS_vcvttsd2sis64
        INS_TT_TUPLE1_SCALAR, // INS_vcvttsd2usis32
        INS_TT_TUPLE1_SCALAR, // INS_vcvttsd2usis64
        INS_TT_TUPLE1_SCALAR, // INS_vcvttss2sis32
        INS_TT_TUPLE1_SCALAR, // INS_vcvttss2sis64
        INS_TT_TUPLE1_SCALAR, // INS_vcvttss2usis32
        INS_TT_TUPLE1_SCALAR, // INS_vcvttss2usis64
        INS_TT_FULL, // INS_vminmaxpd
        INS_TT_FULL, // INS_vminmaxps
        INS_TT_TUPLE1_SCALAR, // INS_vminmaxsd
        INS_TT_TUPLE1_SCALAR, // INS_vminmaxss
        INS_TT_TUPLE1_SCALAR, // INS_vmovd_simd
        INS_TT_TUPLE1_SCALAR, // INS_vmovw_simd
        INS_TT_FULL_MEM, // INS_vmpsadbw
        INS_TT_TUPLE1_SCALAR, // INS_vucomxsd
        INS_TT_TUPLE1_SCALAR, // INS_vucomxss
#if TARGET_AMD64
        INS_TT_NONE, // INS_ccmpo
        INS_TT_NONE, // INS_ccmpno
        INS_TT_NONE, // INS_ccmpb
        INS_TT_NONE, // INS_ccmpae
        INS_TT_NONE, // INS_ccmpe
        INS_TT_NONE, // INS_ccmpne
        INS_TT_NONE, // INS_ccmpbe
        INS_TT_NONE, // INS_ccmpa
        INS_TT_NONE, // INS_ccmps
        INS_TT_NONE, // INS_ccmpns
        INS_TT_NONE, // INS_ccmpt
        INS_TT_NONE, // INS_ccmpf
        INS_TT_NONE, // INS_ccmpl
        INS_TT_NONE, // INS_ccmpge
        INS_TT_NONE, // INS_ccmple
        INS_TT_NONE, // INS_ccmpg
        INS_TT_NONE, // INS_cfcmovo
        INS_TT_NONE, // INS_cfcmovno
        INS_TT_NONE, // INS_cfcmovb
        INS_TT_NONE, // INS_cfcmovae
        INS_TT_NONE, // INS_cfcmove
        INS_TT_NONE, // INS_cfcmovne
        INS_TT_NONE, // INS_cfcmovbe
        INS_TT_NONE, // INS_cfcmova
        INS_TT_NONE, // INS_cfcmovs
        INS_TT_NONE, // INS_cfcmovns
        INS_TT_NONE, // INS_cfcmovp
        INS_TT_NONE, // INS_cfcmovnp
        INS_TT_NONE, // INS_cfcmovl
        INS_TT_NONE, // INS_cfcmovge
        INS_TT_NONE, // INS_cfcmovle
        INS_TT_NONE, // INS_cfcmovg
        INS_TT_NONE, // INS_ctesto
        INS_TT_NONE, // INS_ctestno
        INS_TT_NONE, // INS_ctestb
        INS_TT_NONE, // INS_ctestae
        INS_TT_NONE, // INS_cteste
        INS_TT_NONE, // INS_ctestne
        INS_TT_NONE, // INS_ctestbe
        INS_TT_NONE, // INS_ctesta
        INS_TT_NONE, // INS_ctests
        INS_TT_NONE, // INS_ctestns
        INS_TT_NONE, // INS_ctestt
        INS_TT_NONE, // INS_ctestf
        INS_TT_NONE, // INS_ctestl
        INS_TT_NONE, // INS_ctestge
        INS_TT_NONE, // INS_ctestle
        INS_TT_NONE, // INS_ctestg
        INS_TT_NONE, // INS_crc32_apx
        INS_TT_NONE, // INS_movbe_apx
        INS_TT_NONE, // INS_seto_apx
        INS_TT_NONE, // INS_setno_apx
        INS_TT_NONE, // INS_setb_apx
        INS_TT_NONE, // INS_setae_apx
        INS_TT_NONE, // INS_sete_apx
        INS_TT_NONE, // INS_setne_apx
        INS_TT_NONE, // INS_setbe_apx
        INS_TT_NONE, // INS_seta_apx
        INS_TT_NONE, // INS_sets_apx
        INS_TT_NONE, // INS_setns_apx
        INS_TT_NONE, // INS_setp_apx
        INS_TT_NONE, // INS_setnp_apx
        INS_TT_NONE, // INS_setl_apx
        INS_TT_NONE, // INS_setge_apx
        INS_TT_NONE, // INS_setle_apx
        INS_TT_NONE, // INS_setg_apx
#endif
        INS_TT_NONE, // INS_crc32
        INS_TT_NONE, // INS_tzcnt
#if TARGET_AMD64
        INS_TT_NONE, // INS_tzcnt_apx
#endif
        INS_TT_NONE, // INS_lzcnt
#if TARGET_AMD64
        INS_TT_NONE, // INS_lzcnt_apx
#endif
        INS_TT_NONE, // INS_movbe
        INS_TT_NONE, // INS_popcnt
#if TARGET_AMD64
        INS_TT_NONE, // INS_popcnt_apx
#endif
        INS_TT_NONE, // INS_tpause
        INS_TT_NONE, // INS_umonitor
        INS_TT_NONE, // INS_umwait
        INS_TT_NONE, // INS_neg
        INS_TT_NONE, // INS_not
        INS_TT_NONE, // INS_rol
        INS_TT_NONE, // INS_rol_1
        INS_TT_NONE, // INS_rol_N
        INS_TT_NONE, // INS_ror
        INS_TT_NONE, // INS_ror_1
        INS_TT_NONE, // INS_ror_N
        INS_TT_NONE, // INS_rcl
        INS_TT_NONE, // INS_rcl_1
        INS_TT_NONE, // INS_rcl_N
        INS_TT_NONE, // INS_rcr
        INS_TT_NONE, // INS_rcr_1
        INS_TT_NONE, // INS_rcr_N
        INS_TT_NONE, // INS_shl
        INS_TT_NONE, // INS_shl_1
        INS_TT_NONE, // INS_shl_N
        INS_TT_NONE, // INS_shr
        INS_TT_NONE, // INS_shr_1
        INS_TT_NONE, // INS_shr_N
        INS_TT_NONE, // INS_sar
        INS_TT_NONE, // INS_sar_1
        INS_TT_NONE, // INS_sar_N
        INS_TT_NONE, // INS_ret
        INS_TT_NONE, // INS_loop
        INS_TT_NONE, // INS_call
        INS_TT_NONE, // INS_r_movsb
        INS_TT_NONE, // INS_r_movsd
#if TARGET_AMD64
        INS_TT_NONE, // INS_r_movsq
#endif
        INS_TT_NONE, // INS_movsb
        INS_TT_NONE, // INS_movsd
#if TARGET_AMD64
        INS_TT_NONE, // INS_movsq
#endif
        INS_TT_NONE, // INS_r_stosb
        INS_TT_NONE, // INS_r_stosd
#if TARGET_AMD64
        INS_TT_NONE, // INS_r_stosq
#endif
        INS_TT_NONE, // INS_stosb
        INS_TT_NONE, // INS_stosd
#if TARGET_AMD64
        INS_TT_NONE, // INS_stosq
#endif
        INS_TT_NONE, // INS_int3
        INS_TT_NONE, // INS_nop
        INS_TT_NONE, // INS_pause
        INS_TT_NONE, // INS_lock
        INS_TT_NONE, // INS_leave
        INS_TT_NONE, // INS_serialize
        INS_TT_NONE, // INS_cwde
        INS_TT_NONE, // INS_cdq
        INS_TT_NONE, // INS_idiv
        INS_TT_NONE, // INS_imulEAX
        INS_TT_NONE, // INS_div
        INS_TT_NONE, // INS_mulEAX
        INS_TT_NONE, // INS_sahf
        INS_TT_NONE, // INS_xadd
        INS_TT_NONE, // INS_cmpxchg
        INS_TT_NONE, // INS_shld
        INS_TT_NONE, // INS_shrd
#if TARGET_X86
        INS_TT_NONE, // INS_fld
        INS_TT_NONE, // INS_fstp
#endif
        INS_TT_NONE, // INS_seto
        INS_TT_NONE, // INS_setno
        INS_TT_NONE, // INS_setb
        INS_TT_NONE, // INS_setae
        INS_TT_NONE, // INS_sete
        INS_TT_NONE, // INS_setne
        INS_TT_NONE, // INS_setbe
        INS_TT_NONE, // INS_seta
        INS_TT_NONE, // INS_sets
        INS_TT_NONE, // INS_setns
        INS_TT_NONE, // INS_setp
        INS_TT_NONE, // INS_setnp
        INS_TT_NONE, // INS_setl
        INS_TT_NONE, // INS_setge
        INS_TT_NONE, // INS_setle
        INS_TT_NONE, // INS_setg
        INS_TT_NONE, // INS_tail_i_jmp
        INS_TT_NONE, // INS_i_jmp
        INS_TT_NONE, // INS_jmp
        INS_TT_NONE, // INS_jo
        INS_TT_NONE, // INS_jno
        INS_TT_NONE, // INS_jb
        INS_TT_NONE, // INS_jae
        INS_TT_NONE, // INS_je
        INS_TT_NONE, // INS_jne
        INS_TT_NONE, // INS_jbe
        INS_TT_NONE, // INS_ja
        INS_TT_NONE, // INS_js
        INS_TT_NONE, // INS_jns
        INS_TT_NONE, // INS_jp
        INS_TT_NONE, // INS_jnp
        INS_TT_NONE, // INS_jl
        INS_TT_NONE, // INS_jge
        INS_TT_NONE, // INS_jle
        INS_TT_NONE, // INS_jg
        INS_TT_NONE, // INS_l_jmp
        INS_TT_NONE, // INS_l_jo
        INS_TT_NONE, // INS_l_jno
        INS_TT_NONE, // INS_l_jb
        INS_TT_NONE, // INS_l_jae
        INS_TT_NONE, // INS_l_je
        INS_TT_NONE, // INS_l_jne
        INS_TT_NONE, // INS_l_jbe
        INS_TT_NONE, // INS_l_ja
        INS_TT_NONE, // INS_l_js
        INS_TT_NONE, // INS_l_jns
        INS_TT_NONE, // INS_l_jp
        INS_TT_NONE, // INS_l_jnp
        INS_TT_NONE, // INS_l_jl
        INS_TT_NONE, // INS_l_jge
        INS_TT_NONE, // INS_l_jle
        INS_TT_NONE, // INS_l_jg
        INS_TT_NONE, // INS_align
        INS_TT_NONE, // INS_data16
#elif TARGET_ARM
#if !TARGET_ARM
#error Unexpected target type
#endif
#if FEATURE_PLI_INSTRUCTION
#endif
#if FEATURE_ITINSTRUCTION
#endif
#elif TARGET_ARM64
#if !TARGET_ARM64
#error Unexpected target type
#endif
#if FEATURE_LOOP_ALIGN
#endif
#if !TARGET_ARM64
#error Unexpected target type
#endif
#elif TARGET_LOONGARCH64
#if !TARGET_LOONGARCH64
#error Unexpected target type
#endif
#if FEATURE_SIMD
#endif
#elif TARGET_RISCV64
#if !TARGET_RISCV64
#error Unexpected target type
#endif
#elif TARGET_WASM
#if !TARGET_WASM
#error Unexpected target type
#endif
#else
#error Unsupported or unset target architecture
#endif

    ];
#endif
}