// Copyright (c) Tanner Gooding and Contributors. Licensed under the MIT License (MIT). See License.md in the repository root for more information.
//
// Based on the RyuJIT compiler from dotnet/runtime.
// Original source is Copyright (c) .NET Foundation and Contributors. Licensed under the MIT License (MIT).

using System;

namespace RyuJitSharp;

public sealed partial class CodeGen
{
#if TARGET_XARCH
    private static readonly string[] s_insNames = [
#if TARGET_XARCH
#if !TARGET_XARCH
#error Unexpected target type
#endif
        "INVALID", // INS_invalid
        "push", // INS_push
        "pop", // INS_pop
        "push", // INS_push_hide
        "pop", // INS_pop_hide
        "push2", // INS_push2
        "pop2", // INS_pop2
        "inc", // INS_inc
        "inc", // INS_inc_l
        "dec", // INS_dec
        "dec", // INS_dec_l
        "bswap", // INS_bswap
        "add", // INS_add
        "or", // INS_or
        "adc", // INS_adc
        "sbb", // INS_sbb
        "and", // INS_and
        "sub", // INS_sub
        "sub", // INS_sub_hide
        "xor", // INS_xor
        "cmp", // INS_cmp
        "test", // INS_test
        "mov", // INS_mov
        "lea", // INS_lea
        "bt", // INS_bt
        "bts", // INS_bts
        "btr", // INS_btr
        "btc", // INS_btc
        "bsr", // INS_bsr
        "bsf", // INS_bsf
        "movsx", // INS_movsx
#if TARGET_AMD64
        "movsxd", // INS_movsxd
#endif
        "movzx", // INS_movzx
        "cmovo", // INS_cmovo
        "cmovno", // INS_cmovno
        "cmovb", // INS_cmovb
        "cmovae", // INS_cmovae
        "cmove", // INS_cmove
        "cmovne", // INS_cmovne
        "cmovbe", // INS_cmovbe
        "cmova", // INS_cmova
        "cmovs", // INS_cmovs
        "cmovns", // INS_cmovns
        "cmovp", // INS_cmovp
        "cmovnp", // INS_cmovnp
        "cmovl", // INS_cmovl
        "cmovge", // INS_cmovge
        "cmovle", // INS_cmovle
        "cmovg", // INS_cmovg
        "xchg", // INS_xchg
        "imul", // INS_imul
        "imul", // INS_imul_AX
        "imul", // INS_imul_CX
        "imul", // INS_imul_DX
        "imul", // INS_imul_BX
        "imul", // INS_imul_SP
        "imul", // INS_imul_BP
        "imul", // INS_imul_SI
        "imul", // INS_imul_DI
#if TARGET_AMD64
        "imul", // INS_imul_08
        "imul", // INS_imul_09
        "imul", // INS_imul_10
        "imul", // INS_imul_11
        "imul", // INS_imul_12
        "imul", // INS_imul_13
        "imul", // INS_imul_14
        "imul", // INS_imul_15
        "imul", // INS_imul_16
        "imul", // INS_imul_17
        "imul", // INS_imul_18
        "imul", // INS_imul_19
        "imul", // INS_imul_20
        "imul", // INS_imul_21
        "imul", // INS_imul_22
        "imul", // INS_imul_23
        "imul", // INS_imul_24
        "imul", // INS_imul_25
        "imul", // INS_imul_26
        "imul", // INS_imul_27
        "imul", // INS_imul_28
        "imul", // INS_imul_29
        "imul", // INS_imul_30
        "imul", // INS_imul_31
#endif
        "vaddpd", // INS_addpd
        "vaddps", // INS_addps
        "vaddsd", // INS_addsd
        "vaddss", // INS_addss
        "vaddsubpd", // INS_addsubpd
        "vaddsubps", // INS_addsubps
        "vandnpd", // INS_andnpd
        "vandnps", // INS_andnps
        "vandpd", // INS_andpd
        "vandps", // INS_andps
        "vblendpd", // INS_blendpd
        "vblendps", // INS_blendps
        "blendvpd", // INS_blendvpd
        "blendvps", // INS_blendvps
        "vcmppd", // INS_cmppd
        "vcmpps", // INS_cmpps
        "vcmpsd", // INS_cmpsd
        "vcmpss", // INS_cmpss
        "vcomisd", // INS_comisd
        "vcomiss", // INS_comiss
        "vcvtdq2pd", // INS_cvtdq2pd
        "vcvtdq2ps", // INS_cvtdq2ps
        "vcvtpd2dq", // INS_cvtpd2dq
        "vcvtpd2ps", // INS_cvtpd2ps
        "vcvtps2dq", // INS_cvtps2dq
        "vcvtps2pd", // INS_cvtps2pd
        "vcvtsd2si", // INS_cvtsd2si32
        "vcvtsd2si", // INS_cvtsd2si64
        "vcvtsd2ss", // INS_cvtsd2ss
        "vcvtsi2sd", // INS_cvtsi2sd32
        "vcvtsi2sd", // INS_cvtsi2sd64
        "vcvtsi2ss", // INS_cvtsi2ss32
        "vcvtsi2ss", // INS_cvtsi2ss64
        "vcvtss2sd", // INS_cvtss2sd
        "vcvtss2si", // INS_cvtss2si32
        "vcvtss2si", // INS_cvtss2si64
        "vcvttpd2dq", // INS_cvttpd2dq
        "vcvttps2dq", // INS_cvttps2dq
        "vcvttsd2si", // INS_cvttsd2si32
        "vcvttsd2si", // INS_cvttsd2si64
        "vcvttss2si", // INS_cvttss2si32
        "vcvttss2si", // INS_cvttss2si64
        "vdivpd", // INS_divpd
        "vdivps", // INS_divps
        "vdivsd", // INS_divsd
        "vdivss", // INS_divss
        "vdppd", // INS_dppd
        "vdpps", // INS_dpps
        "vextractps", // INS_extractps
        "vhaddpd", // INS_haddpd
        "vhaddps", // INS_haddps
        "vhsubpd", // INS_hsubpd
        "vhsubps", // INS_hsubps
        "vinsertps", // INS_insertps
        "vlddqu", // INS_lddqu
        "lfence", // INS_lfence
        "vmaskmovdqu", // INS_maskmovdqu
        "vmaxpd", // INS_maxpd
        "vmaxps", // INS_maxps
        "vmaxsd", // INS_maxsd
        "vmaxss", // INS_maxss
        "mfence", // INS_mfence
        "vminpd", // INS_minpd
        "vminps", // INS_minps
        "vminsd", // INS_minsd
        "vminss", // INS_minss
        "vmovapd", // INS_movapd
        "vmovaps", // INS_movaps
        "vmovd", // INS_movd32
        "vmovq", // INS_movd64
        "vmovddup", // INS_movddup
        "vmovdqa", // INS_movdqa32
        "vmovdqu", // INS_movdqu32
        "vmovhlps", // INS_movhlps
        "vmovhpd", // INS_movhpd
        "vmovhps", // INS_movhps
        "vmovlhps", // INS_movlhps
        "vmovlpd", // INS_movlpd
        "vmovlps", // INS_movlps
        "vmovmskpd", // INS_movmskpd
        "vmovmskps", // INS_movmskps
        "vmovntdq", // INS_movntdq
        "vmovntdqa", // INS_movntdqa
        "movnti", // INS_movnti32
        "movnti", // INS_movnti64
        "vmovntpd", // INS_movntpd
        "vmovntps", // INS_movntps
        "vmovq", // INS_movq
        "vmovsd", // INS_movsd_simd
        "vmovshdup", // INS_movshdup
        "vmovsldup", // INS_movsldup
        "vmovss", // INS_movss
        "vmovupd", // INS_movupd
        "vmovups", // INS_movups
        "vmpsadbw", // INS_mpsadbw
        "vmulpd", // INS_mulpd
        "vmulps", // INS_mulps
        "vmulsd", // INS_mulsd
        "vmulss", // INS_mulss
        "vorpd", // INS_orpd
        "vorps", // INS_orps
        "vpabsb", // INS_pabsb
        "vpabsd", // INS_pabsd
        "vpabsw", // INS_pabsw
        "vpackssdw", // INS_packssdw
        "vpacksswb", // INS_packsswb
        "vpackusdw", // INS_packusdw
        "vpackuswb", // INS_packuswb
        "vpaddb", // INS_paddb
        "vpaddd", // INS_paddd
        "vpaddq", // INS_paddq
        "vpaddsb", // INS_paddsb
        "vpaddsw", // INS_paddsw
        "vpaddusb", // INS_paddusb
        "vpaddusw", // INS_paddusw
        "vpaddw", // INS_paddw
        "vpalignr", // INS_palignr
        "vpand", // INS_pandd
        "vpandn", // INS_pandnd
        "vpavgb", // INS_pavgb
        "vpavgw", // INS_pavgw
        "pblendvb", // INS_pblendvb
        "vpblendw", // INS_pblendw
        "vpcmpeqb", // INS_pcmpeqb
        "vpcmpeqd", // INS_pcmpeqd
        "vpcmpeqq", // INS_pcmpeqq
        "vpcmpeqw", // INS_pcmpeqw
        "vpcmpgtb", // INS_pcmpgtb
        "vpcmpgtd", // INS_pcmpgtd
        "vpcmpgtq", // INS_pcmpgtq
        "vpcmpgtw", // INS_pcmpgtw
        "vpextrb", // INS_pextrb
        "vpextrd", // INS_pextrd
        "vpextrq", // INS_pextrq
        "vphaddd", // INS_phaddd
        "vpextrw", // INS_pextrw
        "vphaddsw", // INS_phaddsw
        "vphaddw", // INS_phaddw
        "vphminposuw", // INS_phminposuw
        "vphsubd", // INS_phsubd
        "vphsubsw", // INS_phsubsw
        "vphsubw", // INS_phsubw
        "vpinsrb", // INS_pinsrb
        "vpinsrd", // INS_pinsrd
        "vpinsrq", // INS_pinsrq
        "vpinsrw", // INS_pinsrw
        "vpmaddubsw", // INS_pmaddubsw
        "vpmaddwd", // INS_pmaddwd
        "vpmaxsb", // INS_pmaxsb
        "vpmaxsd", // INS_pmaxsd
        "vpmaxsw", // INS_pmaxsw
        "vpmaxub", // INS_pmaxub
        "vpmaxud", // INS_pmaxud
        "vpmaxuw", // INS_pmaxuw
        "vpminsb", // INS_pminsb
        "vpminsd", // INS_pminsd
        "vpminsw", // INS_pminsw
        "vpminub", // INS_pminub
        "vpminud", // INS_pminud
        "vpminuw", // INS_pminuw
        "vpmovmskb", // INS_pmovmskb
        "vpmovsxbd", // INS_pmovsxbd
        "vpmovsxbq", // INS_pmovsxbq
        "vpmovsxbw", // INS_pmovsxbw
        "vpmovsxdq", // INS_pmovsxdq
        "vpmovsxwd", // INS_pmovsxwd
        "vpmovsxwq", // INS_pmovsxwq
        "vpmovzxbd", // INS_pmovzxbd
        "vpmovzxbq", // INS_pmovzxbq
        "vpmovzxbw", // INS_pmovzxbw
        "vpmovzxdq", // INS_pmovzxdq
        "vpmovzxwd", // INS_pmovzxwd
        "vpmovzxwq", // INS_pmovzxwq
        "vpmuldq", // INS_pmuldq
        "vpmulhrsw", // INS_pmulhrsw
        "vpmulhuw", // INS_pmulhuw
        "vpmulhw", // INS_pmulhw
        "vpmulld", // INS_pmulld
        "vpmuludq", // INS_pmuludq
        "vpmullw", // INS_pmullw
        "vpor", // INS_pord
        "prefetchnta", // INS_prefetchnta
        "prefetcht0", // INS_prefetcht0
        "prefetcht1", // INS_prefetcht1
        "prefetcht2", // INS_prefetcht2
        "vpsadbw", // INS_psadbw
        "vpshufb", // INS_pshufb
        "vpshufd", // INS_pshufd
        "vpshufhw", // INS_pshufhw
        "vpshuflw", // INS_pshuflw
        "vpsignb", // INS_psignb
        "vpsignd", // INS_psignd
        "vpsignw", // INS_psignw
        "vpslld", // INS_pslld
        "vpslldq", // INS_pslldq
        "vpsllq", // INS_psllq
        "vpsllw", // INS_psllw
        "vpsrad", // INS_psrad
        "vpsraw", // INS_psraw
        "vpsrld", // INS_psrld
        "vpsrldq", // INS_psrldq
        "vpsrlq", // INS_psrlq
        "vpsrlw", // INS_psrlw
        "vpsubb", // INS_psubb
        "vpsubd", // INS_psubd
        "vpsubq", // INS_psubq
        "vpsubsb", // INS_psubsb
        "vpsubsw", // INS_psubsw
        "vpsubusb", // INS_psubusb
        "vpsubusw", // INS_psubusw
        "vpsubw", // INS_psubw
        "vptest", // INS_ptest
        "vpunpckhbw", // INS_punpckhbw
        "vpunpckhdq", // INS_punpckhdq
        "vpunpckhqdq", // INS_punpckhqdq
        "vpunpckhwd", // INS_punpckhwd
        "vpunpcklbw", // INS_punpcklbw
        "vpunpckldq", // INS_punpckldq
        "vpunpcklqdq", // INS_punpcklqdq
        "vpunpcklwd", // INS_punpcklwd
        "vpxor", // INS_pxord
        "vrcpps", // INS_rcpps
        "vrcpss", // INS_rcpss
        "vroundpd", // INS_roundpd
        "vroundps", // INS_roundps
        "vroundsd", // INS_roundsd
        "vroundss", // INS_roundss
        "vrsqrtps", // INS_rsqrtps
        "vrsqrtss", // INS_rsqrtss
        "sfence", // INS_sfence
        "vshufpd", // INS_shufpd
        "vshufps", // INS_shufps
        "vsqrtpd", // INS_sqrtpd
        "vsqrtps", // INS_sqrtps
        "vsqrtsd", // INS_sqrtsd
        "vsqrtss", // INS_sqrtss
        "vsubpd", // INS_subpd
        "vsubps", // INS_subps
        "vsubsd", // INS_subsd
        "vsubss", // INS_subss
        "vucomisd", // INS_ucomisd
        "vucomiss", // INS_ucomiss
        "vunpckhpd", // INS_unpckhpd
        "vunpckhps", // INS_unpckhps
        "vunpcklpd", // INS_unpcklpd
        "vunpcklps", // INS_unpcklps
        "vxorpd", // INS_xorpd
        "vxorps", // INS_xorps
        "vaesdec", // INS_aesdec
        "vaesdeclast", // INS_aesdeclast
        "vaesenc", // INS_aesenc
        "vaesenclast", // INS_aesenclast
        "vaesimc", // INS_aesimc
        "vaeskeygenassist", // INS_aeskeygenassist
        "vpclmulqdq", // INS_pclmulqdq
        "sha1msg1", // INS_sha1msg1
        "sha1msg2", // INS_sha1msg2
        "sha1nexte", // INS_sha1nexte
        "sha1rnds4", // INS_sha1rnds4
        "sha256msg1", // INS_sha256msg1
        "sha256msg2", // INS_sha256msg2
        "sha256rnds2", // INS_sha256rnds2
        "vgf2p8affineinvqb", // INS_gf2p8affineinvqb
        "vgf2p8affineqb", // INS_gf2p8affineqb
        "vgf2p8mulb", // INS_gf2p8mulb
        "vblendvpd", // INS_vblendvpd
        "vblendvps", // INS_vblendvps
        "vbroadcastf128", // INS_vbroadcastf32x4
        "vbroadcastsd", // INS_vbroadcastsd
        "vbroadcastss", // INS_vbroadcastss
        "vextractf128", // INS_vextractf32x4
        "vinsertf128", // INS_vinsertf32x4
        "vmaskmovpd", // INS_vmaskmovpd
        "vmaskmovps", // INS_vmaskmovps
        "vpblendvb", // INS_vpblendvb
        "vperm2f128", // INS_vperm2f128
        "vpermilpd", // INS_vpermilpd
        "vpermilpd", // INS_vpermilpdvar
        "vpermilps", // INS_vpermilps
        "vpermilps", // INS_vpermilpsvar
        "vtestpd", // INS_vtestpd
        "vtestps", // INS_vtestps
        "vzeroupper", // INS_vzeroupper
        "vbroadcasti128", // INS_vbroadcasti32x4
        "vcvtph2ps", // INS_vcvtph2ps
        "vcvtps2ph", // INS_vcvtps2ph
        "vextracti128", // INS_vextracti32x4
        "vgatherdpd", // INS_vgatherdpd
        "vgatherdps", // INS_vgatherdps
        "vgatherqpd", // INS_vgatherqpd
        "vgatherqps", // INS_vgatherqps
        "vinserti128", // INS_vinserti32x4
        "vpblendd", // INS_vpblendd
        "vpbroadcastb", // INS_vpbroadcastb
        "vpbroadcastd", // INS_vpbroadcastd
        "vpbroadcastq", // INS_vpbroadcastq
        "vpbroadcastw", // INS_vpbroadcastw
        "vperm2i128", // INS_vperm2i128
        "vpermd", // INS_vpermd
        "vpermpd", // INS_vpermpd
        "vpermps", // INS_vpermps
        "vpermq", // INS_vpermq
        "vpgatherdd", // INS_vpgatherdd
        "vpgatherdq", // INS_vpgatherdq
        "vpgatherqd", // INS_vpgatherqd
        "vpgatherqq", // INS_vpgatherqq
        "vpmaskmovd", // INS_vpmaskmovd
        "vpmaskmovq", // INS_vpmaskmovq
        "vpsllvd", // INS_vpsllvd
        "vpsllvq", // INS_vpsllvq
        "vpsravd", // INS_vpsravd
        "vpsrlvd", // INS_vpsrlvd
        "vpsrlvq", // INS_vpsrlvq
        "vfmadd132pd", // INS_vfmadd132pd
        "vfmadd213pd", // INS_vfmadd213pd
        "vfmadd231pd", // INS_vfmadd231pd
        "vfmadd132ps", // INS_vfmadd132ps
        "vfmadd213ps", // INS_vfmadd213ps
        "vfmadd231ps", // INS_vfmadd231ps
        "vfmadd132sd", // INS_vfmadd132sd
        "vfmadd213sd", // INS_vfmadd213sd
        "vfmadd231sd", // INS_vfmadd231sd
        "vfmadd132ss", // INS_vfmadd132ss
        "vfmadd213ss", // INS_vfmadd213ss
        "vfmadd231ss", // INS_vfmadd231ss
        "vfmaddsub132pd", // INS_vfmaddsub132pd
        "vfmaddsub213pd", // INS_vfmaddsub213pd
        "vfmaddsub231pd", // INS_vfmaddsub231pd
        "vfmaddsub132ps", // INS_vfmaddsub132ps
        "vfmaddsub213ps", // INS_vfmaddsub213ps
        "vfmaddsub231ps", // INS_vfmaddsub231ps
        "vfmsubadd132pd", // INS_vfmsubadd132pd
        "vfmsubadd213pd", // INS_vfmsubadd213pd
        "vfmsubadd231pd", // INS_vfmsubadd231pd
        "vfmsubadd132ps", // INS_vfmsubadd132ps
        "vfmsubadd213ps", // INS_vfmsubadd213ps
        "vfmsubadd231ps", // INS_vfmsubadd231ps
        "vfmsub132pd", // INS_vfmsub132pd
        "vfmsub213pd", // INS_vfmsub213pd
        "vfmsub231pd", // INS_vfmsub231pd
        "vfmsub132ps", // INS_vfmsub132ps
        "vfmsub213ps", // INS_vfmsub213ps
        "vfmsub231ps", // INS_vfmsub231ps
        "vfmsub132sd", // INS_vfmsub132sd
        "vfmsub213sd", // INS_vfmsub213sd
        "vfmsub231sd", // INS_vfmsub231sd
        "vfmsub132ss", // INS_vfmsub132ss
        "vfmsub213ss", // INS_vfmsub213ss
        "vfmsub231ss", // INS_vfmsub231ss
        "vfnmadd132pd", // INS_vfnmadd132pd
        "vfnmadd213pd", // INS_vfnmadd213pd
        "vfnmadd231pd", // INS_vfnmadd231pd
        "vfnmadd132ps", // INS_vfnmadd132ps
        "vfnmadd213ps", // INS_vfnmadd213ps
        "vfnmadd231ps", // INS_vfnmadd231ps
        "vfnmadd132sd", // INS_vfnmadd132sd
        "vfnmadd213sd", // INS_vfnmadd213sd
        "vfnmadd231sd", // INS_vfnmadd231sd
        "vfnmadd132ss", // INS_vfnmadd132ss
        "vfnmadd213ss", // INS_vfnmadd213ss
        "vfnmadd231ss", // INS_vfnmadd231ss
        "vfnmsub132pd", // INS_vfnmsub132pd
        "vfnmsub213pd", // INS_vfnmsub213pd
        "vfnmsub231pd", // INS_vfnmsub231pd
        "vfnmsub132ps", // INS_vfnmsub132ps
        "vfnmsub213ps", // INS_vfnmsub213ps
        "vfnmsub231ps", // INS_vfnmsub231ps
        "vfnmsub132sd", // INS_vfnmsub132sd
        "vfnmsub213sd", // INS_vfnmsub213sd
        "vfnmsub231sd", // INS_vfnmsub231sd
        "vfnmsub132ss", // INS_vfnmsub132ss
        "vfnmsub213ss", // INS_vfnmsub213ss
        "vfnmsub231ss", // INS_vfnmsub231ss
        "andn", // INS_andn
        "bextr", // INS_bextr
        "blsi", // INS_blsi
        "blsmsk", // INS_blsmsk
        "blsr", // INS_blsr
        "bzhi", // INS_bzhi
        "mulx", // INS_mulx
        "pdep", // INS_pdep
        "pext", // INS_pext
        "rorx", // INS_rorx
        "sarx", // INS_sarx
        "shlx", // INS_shlx
        "shrx", // INS_shrx
        "vpdpbusd", // INS_vpdpbusd
        "vpdpbusds", // INS_vpdpbusds
        "vpdpwssd", // INS_vpdpwssd
        "vpdpwssds", // INS_vpdpwssds
        "vpdpwsud", // INS_vpdpwsud
        "vpdpwsuds", // INS_vpdpwsuds
        "vpdpwusd", // INS_vpdpwusd
        "vpdpwusds", // INS_vpdpwusds
        "vpdpwuud", // INS_vpdpwuud
        "vpdpwuuds", // INS_vpdpwuuds
        "vpdpbssd", // INS_vpdpbssd
        "vpdpbssds", // INS_vpdpbssds
        "vpdpbsud", // INS_vpdpbsud
        "vpdpbsuds", // INS_vpdpbsuds
        "vpdpbuud", // INS_vpdpbuud
        "vpdpbuuds", // INS_vpdpbuuds
        "vbmacor16x16x16", // INS_vbmacor16x16x16
        "vbmacxor16x16x16", // INS_vbmacxor16x16x16
        "vbitrev", // INS_vbitrev
        "vpmadd52huq", // INS_vpmadd52huq
        "vpmadd52luq", // INS_vpmadd52luq
        "kaddb", // INS_kaddb
        "kaddd", // INS_kaddd
        "kaddq", // INS_kaddq
        "kaddw", // INS_kaddw
        "kandb", // INS_kandb
        "kandd", // INS_kandd
        "kandnb", // INS_kandnb
        "kandnd", // INS_kandnd
        "kandnq", // INS_kandnq
        "kandnw", // INS_kandnw
        "kandq", // INS_kandq
        "kandw", // INS_kandw
        "kmovb", // INS_kmovb_gpr
        "kmovb", // INS_kmovb_msk
        "kmovd", // INS_kmovd_gpr
        "kmovd", // INS_kmovd_msk
        "kmovq", // INS_kmovq_gpr
        "kmovq", // INS_kmovq_msk
        "kmovw", // INS_kmovw_gpr
        "kmovw", // INS_kmovw_msk
        "knotb", // INS_knotb
        "knotd", // INS_knotd
        "knotq", // INS_knotq
        "knotw", // INS_knotw
        "korb", // INS_korb
        "kord", // INS_kord
        "korq", // INS_korq
        "kortestb", // INS_kortestb
        "kortestd", // INS_kortestd
        "kortestq", // INS_kortestq
        "kortestw", // INS_kortestw
        "korw", // INS_korw
        "kshiftlb", // INS_kshiftlb
        "kshiftld", // INS_kshiftld
        "kshiftlq", // INS_kshiftlq
        "kshiftlw", // INS_kshiftlw
        "kshiftrb", // INS_kshiftrb
        "kshiftrd", // INS_kshiftrd
        "kshiftrq", // INS_kshiftrq
        "kshiftrw", // INS_kshiftrw
        "ktestb", // INS_ktestb
        "ktestd", // INS_ktestd
        "ktestq", // INS_ktestq
        "ktestw", // INS_ktestw
        "kunpckbw", // INS_kunpckbw
        "kunpckdq", // INS_kunpckdq
        "kunpckwd", // INS_kunpckwd
        "kxnorb", // INS_kxnorb
        "kxnord", // INS_kxnord
        "kxnorq", // INS_kxnorq
        "kxnorw", // INS_kxnorw
        "kxorb", // INS_kxorb
        "kxord", // INS_kxord
        "kxorq", // INS_kxorq
        "kxorw", // INS_kxorw
        "valignd", // INS_valignd
        "valignq", // INS_valignq
        "vblendmpd", // INS_vblendmpd
        "vblendmps", // INS_vblendmps
        "vbroadcastf32x2", // INS_vbroadcastf32x2
        "vbroadcastf32x8", // INS_vbroadcastf32x8
        "vbroadcastf64x2", // INS_vbroadcastf64x2
        "vbroadcastf64x4", // INS_vbroadcastf64x4
        "vbroadcasti32x2", // INS_vbroadcasti32x2
        "vbroadcasti32x8", // INS_vbroadcasti32x8
        "vbroadcasti64x2", // INS_vbroadcasti64x2
        "vbroadcasti64x4", // INS_vbroadcasti64x4
        "vcmppd", // INS_vcmppd
        "vcmpps", // INS_vcmpps
        "vcmpsd", // INS_vcmpsd
        "vcmpss", // INS_vcmpss
        "vcompresspd", // INS_vcompresspd
        "vcompressps", // INS_vcompressps
        "vcvtpd2qq", // INS_vcvtpd2qq
        "vcvtpd2udq", // INS_vcvtpd2udq
        "vcvtpd2uqq", // INS_vcvtpd2uqq
        "vcvtps2qq", // INS_vcvtps2qq
        "vcvtps2udq", // INS_vcvtps2udq
        "vcvtps2uqq", // INS_vcvtps2uqq
        "vcvtqq2pd", // INS_vcvtqq2pd
        "vcvtqq2ps", // INS_vcvtqq2ps
        "vcvtsd2usi", // INS_vcvtsd2usi32
        "vcvtsd2usi", // INS_vcvtsd2usi64
        "vcvtss2usi", // INS_vcvtss2usi32
        "vcvtss2usi", // INS_vcvtss2usi64
        "vcvttpd2qq", // INS_vcvttpd2qq
        "vcvttpd2udq", // INS_vcvttpd2udq
        "vcvttpd2uqq", // INS_vcvttpd2uqq
        "vcvttps2qq", // INS_vcvttps2qq
        "vcvttps2udq", // INS_vcvttps2udq
        "vcvttps2uqq", // INS_vcvttps2uqq
        "vcvttsd2usi", // INS_vcvttsd2usi32
        "vcvttsd2usi", // INS_vcvttsd2usi64
        "vcvttss2usi", // INS_vcvttss2usi32
        "vcvttss2usi", // INS_vcvttss2usi64
        "vcvtudq2pd", // INS_vcvtudq2pd
        "vcvtudq2ps", // INS_vcvtudq2ps
        "vcvtuqq2pd", // INS_vcvtuqq2pd
        "vcvtuqq2ps", // INS_vcvtuqq2ps
        "vcvtusi2sd", // INS_vcvtusi2sd32
        "vcvtusi2sd", // INS_vcvtusi2sd64
        "vcvtusi2ss", // INS_vcvtusi2ss32
        "vcvtusi2ss", // INS_vcvtusi2ss64
        "vdbpsadbw", // INS_vdbpsadbw
        "vexpandpd", // INS_vexpandpd
        "vexpandps", // INS_vexpandps
        "vextractf32x8", // INS_vextractf32x8
        "vextractf64x2", // INS_vextractf64x2
        "vextractf64x4", // INS_vextractf64x4
        "vextracti32x8", // INS_vextracti32x8
        "vextracti64x2", // INS_vextracti64x2
        "vextracti64x4", // INS_vextracti64x4
        "vfixupimmpd", // INS_vfixupimmpd
        "vfixupimmps", // INS_vfixupimmps
        "vfixupimmsd", // INS_vfixupimmsd
        "vfixupimmss", // INS_vfixupimmss
        "vfpclasspd", // INS_vfpclasspd
        "vfpclassps", // INS_vfpclassps
        "vfpclasssd", // INS_vfpclasssd
        "vfpclassss", // INS_vfpclassss
        "vgatherdpd", // INS_vgatherdpd_msk
        "vgatherdps", // INS_vgatherdps_msk
        "vgatherqpd", // INS_vgatherqpd_msk
        "vgatherqps", // INS_vgatherqps_msk
        "vgetexppd", // INS_vgetexppd
        "vgetexpps", // INS_vgetexpps
        "vgetexpsd", // INS_vgetexpsd
        "vgetexpss", // INS_vgetexpss
        "vgetmantpd", // INS_vgetmantpd
        "vgetmantps", // INS_vgetmantps
        "vgetmantsd", // INS_vgetmantsd
        "vgetmantss", // INS_vgetmantss
        "vinsertf32x8", // INS_vinsertf32x8
        "vinsertf64x2", // INS_vinsertf64x2
        "vinsertf64x4", // INS_vinsertf64x4
        "vinserti32x8", // INS_vinserti32x8
        "vinserti64x2", // INS_vinserti64x2
        "vinserti64x4", // INS_vinserti64x4
        "vmovdqa64", // INS_vmovdqa64
        "vmovdqu16", // INS_vmovdqu16
        "vmovdqu64", // INS_vmovdqu64
        "vmovdqu8", // INS_vmovdqu8
        "vpabsq", // INS_vpabsq
        "vpandnq", // INS_vpandnq
        "vpandq", // INS_vpandq
        "vpblendmb", // INS_vpblendmb
        "vpblendmd", // INS_vpblendmd
        "vpblendmq", // INS_vpblendmq
        "vpblendmw", // INS_vpblendmw
        "vpbroadcastb", // INS_vpbroadcastb_gpr
        "vpbroadcastd", // INS_vpbroadcastd_gpr
        "vpbroadcastq", // INS_vpbroadcastq_gpr
        "vpbroadcastw", // INS_vpbroadcastw_gpr
        "vpcmpb", // INS_vpcmpb
        "vpcmpd", // INS_vpcmpd
        "vpcmpeqb", // INS_vpcmpeqb
        "vpcmpeqd", // INS_vpcmpeqd
        "vpcmpeqq", // INS_vpcmpeqq
        "vpcmpeqw", // INS_vpcmpeqw
        "vpcmpgtb", // INS_vpcmpgtb
        "vpcmpgtd", // INS_vpcmpgtd
        "vpcmpgtq", // INS_vpcmpgtq
        "vpcmpgtw", // INS_vpcmpgtw
        "vpcmpq", // INS_vpcmpq
        "vpcmpub", // INS_vpcmpub
        "vpcmpud", // INS_vpcmpud
        "vpcmpuq", // INS_vpcmpuq
        "vpcmpuw", // INS_vpcmpuw
        "vpcmpw", // INS_vpcmpw
        "vpcompressd", // INS_vpcompressd
        "vpcompressq", // INS_vpcompressq
        "vpconflictd", // INS_vpconflictd
        "vpconflictq", // INS_vpconflictq
        "vpermi2d", // INS_vpermi2d
        "vpermi2pd", // INS_vpermi2pd
        "vpermi2ps", // INS_vpermi2ps
        "vpermi2q", // INS_vpermi2q
        "vpermi2w", // INS_vpermi2w
        "vpermpd", // INS_vpermpd_reg
        "vpermq", // INS_vpermq_reg
        "vpermt2d", // INS_vpermt2d
        "vpermt2pd", // INS_vpermt2pd
        "vpermt2ps", // INS_vpermt2ps
        "vpermt2q", // INS_vpermt2q
        "vpermt2w", // INS_vpermt2w
        "vpermw", // INS_vpermw
        "vpexpandd", // INS_vpexpandd
        "vpexpandq", // INS_vpexpandq
        "vpgatherdd", // INS_vpgatherdd_msk
        "vpgatherdq", // INS_vpgatherdq_msk
        "vpgatherqd", // INS_vpgatherqd_msk
        "vpgatherqq", // INS_vpgatherqq_msk
        "vplzcntd", // INS_vplzcntd
        "vplzcntq", // INS_vplzcntq
        "vpmaxsq", // INS_vpmaxsq
        "vpmaxuq", // INS_vpmaxuq
        "vpminsq", // INS_vpminsq
        "vpminuq", // INS_vpminuq
        "vpmovb2m", // INS_vpmovb2m
        "vpmovd2m", // INS_vpmovd2m
        "vpmovdb", // INS_vpmovdb
        "vpmovdw", // INS_vpmovdw
        "vpmovm2b", // INS_vpmovm2b
        "vpmovm2d", // INS_vpmovm2d
        "vpmovm2q", // INS_vpmovm2q
        "vpmovm2w", // INS_vpmovm2w
        "vpmovq2m", // INS_vpmovq2m
        "vpmovqb", // INS_vpmovqb
        "vpmovqd", // INS_vpmovqd
        "vpmovqw", // INS_vpmovqw
        "vpmovsdb", // INS_vpmovsdb
        "vpmovsdw", // INS_vpmovsdw
        "vpmovsqb", // INS_vpmovsqb
        "vpmovsqd", // INS_vpmovsqd
        "vpmovsqw", // INS_vpmovsqw
        "vpmovswb", // INS_vpmovswb
        "vpmovusdb", // INS_vpmovusdb
        "vpmovusdw", // INS_vpmovusdw
        "vpmovusqb", // INS_vpmovusqb
        "vpmovusqd", // INS_vpmovusqd
        "vpmovusqw", // INS_vpmovusqw
        "vpmovuswb", // INS_vpmovuswb
        "vpmovw2m", // INS_vpmovw2m
        "vpmovwb", // INS_vpmovwb
        "vpmullq", // INS_vpmullq
        "vporq", // INS_vporq
        "vprold", // INS_vprold
        "vprolq", // INS_vprolq
        "vprolvd", // INS_vprolvd
        "vprolvq", // INS_vprolvq
        "vprord", // INS_vprord
        "vprorq", // INS_vprorq
        "vprorvd", // INS_vprorvd
        "vprorvq", // INS_vprorvq
        "vpscatterdd", // INS_vpscatterdd_msk
        "vpscatterdq", // INS_vpscatterdq_msk
        "vpscatterqd", // INS_vpscatterqd_msk
        "vpscatterqq", // INS_vpscatterqq_msk
        "vpsllvw", // INS_vpsllvw
        "vpsraq", // INS_vpsraq
        "vpsravq", // INS_vpsravq
        "vpsravw", // INS_vpsravw
        "vpsrlvw", // INS_vpsrlvw
        "vpternlogd", // INS_vpternlogd
        "vpternlogq", // INS_vpternlogq
        "vptestmb", // INS_vptestmb
        "vptestmd", // INS_vptestmd
        "vptestmq", // INS_vptestmq
        "vptestmw", // INS_vptestmw
        "vptestnmb", // INS_vptestnmb
        "vptestnmd", // INS_vptestnmd
        "vptestnmq", // INS_vptestnmq
        "vptestnmw", // INS_vptestnmw
        "vpxorq", // INS_vpxorq
        "vrangepd", // INS_vrangepd
        "vrangeps", // INS_vrangeps
        "vrangesd", // INS_vrangesd
        "vrangess", // INS_vrangess
        "vrcp14pd", // INS_vrcp14pd
        "vrcp14ps", // INS_vrcp14ps
        "vrcp14sd", // INS_vrcp14sd
        "vrcp14ss", // INS_vrcp14ss
        "vreducepd", // INS_vreducepd
        "vreduceps", // INS_vreduceps
        "vreducesd", // INS_vreducesd
        "vreducess", // INS_vreducess
        "vrndscalepd", // INS_vrndscalepd
        "vrndscaleps", // INS_vrndscaleps
        "vrndscalesd", // INS_vrndscalesd
        "vrndscaless", // INS_vrndscaless
        "vrsqrt14pd", // INS_vrsqrt14pd
        "vrsqrt14ps", // INS_vrsqrt14ps
        "vrsqrt14sd", // INS_vrsqrt14sd
        "vrsqrt14ss", // INS_vrsqrt14ss
        "vscalefpd", // INS_vscalefpd
        "vscalefps", // INS_vscalefps
        "vscalefsd", // INS_vscalefsd
        "vscalefss", // INS_vscalefss
        "vscatterdpd", // INS_vscatterdpd_msk
        "vscatterdps", // INS_vscatterdps_msk
        "vscatterqpd", // INS_vscatterqpd_msk
        "vscatterqps", // INS_vscatterqps_msk
        "vshuff32x4", // INS_vshuff32x4
        "vshuff64x2", // INS_vshuff64x2
        "vshufi32x4", // INS_vshufi32x4
        "vshufi64x2", // INS_vshufi64x2
        "vpermb", // INS_vpermb
        "vpermi2b", // INS_vpermi2b
        "vpermt2b", // INS_vpermt2b
        "vpmultishiftqb", // INS_vpmultishiftqb
        "vpcompressb", // INS_vpcompressb
        "vpcompressw", // INS_vpcompressw
        "vpexpandb", // INS_vpexpandb
        "vpexpandw", // INS_vpexpandw
        "vpopcntb", // INS_vpopcntb
        "vpopcntd", // INS_vpopcntd
        "vpopcntq", // INS_vpopcntq
        "vpopcntw", // INS_vpopcntw
        "vpshldd", // INS_vpshldd
        "vpshldq", // INS_vpshldq
        "vpshldvd", // INS_vpshldvd
        "vpshldvq", // INS_vpshldvq
        "vpshldvw", // INS_vpshldvw
        "vpshldw", // INS_vpshldw
        "vpshrdd", // INS_vpshrdd
        "vpshrdq", // INS_vpshrdq
        "vpshrdvd", // INS_vpshrdvd
        "vpshrdvq", // INS_vpshrdvq
        "vpshrdvw", // INS_vpshrdvw
        "vpshrdw", // INS_vpshrdw
        "vpshufbitqmb", // INS_vpshufbitqmb
        "vaddph", // INS_vaddph
        "vaddsh", // INS_vaddsh
        "vcmpph", // INS_vcmpph
        "vcmpsh", // INS_vcmpsh
        "vcomish", // INS_vcomish
        "vcvtdq2ph", // INS_vcvtdq2ph
        "vcvtne2ps2bf16", // INS_vcvtne2ps2bf16
        "vcvtneps2bf16", // INS_vcvtneps2bf16
        "vcvtpd2ph", // INS_vcvtpd2ph
        "vcvtph2dq", // INS_vcvtph2dq
        "vcvtph2pd", // INS_vcvtph2pd
        "vcvtph2psx", // INS_vcvtph2psx
        "vcvtph2qq", // INS_vcvtph2qq
        "vcvtph2udq", // INS_vcvtph2udq
        "vcvtph2uqq", // INS_vcvtph2uqq
        "vcvtph2uw", // INS_vcvtph2uw
        "vcvtph2w", // INS_vcvtph2w
        "vcvtps2phx", // INS_vcvtps2phx
        "vcvtqq2ph", // INS_vcvtqq2ph
        "vcvtsd2sh", // INS_vcvtsd2sh
        "vcvtsh2sd", // INS_vcvtsh2sd
        "vcvtsh2si", // INS_vcvtsh2si32
        "vcvtsh2si", // INS_vcvtsh2si64
        "vcvtsh2ss", // INS_vcvtsh2ss
        "vcvtsh2usi", // INS_vcvtsh2usi32
        "vcvtsh2usi", // INS_vcvtsh2usi64
        "vcvtsi2sh", // INS_vcvtsi2sh32
        "vcvtsi2sh", // INS_vcvtsi2sh64
        "vcvtss2sh", // INS_vcvtss2sh
        "vcvttph2dq", // INS_vcvttph2dq
        "vcvttph2qq", // INS_vcvttph2qq
        "vcvttph2udq", // INS_vcvttph2udq
        "vcvttph2uqq", // INS_vcvttph2uqq
        "vcvttph2uw", // INS_vcvttph2uw
        "vcvttph2w", // INS_vcvttph2w
        "vcvttsh2si", // INS_vcvttsh2si32
        "vcvttsh2si", // INS_vcvttsh2si64
        "vcvttsh2usi", // INS_vcvttsh2usi32
        "vcvttsh2usi", // INS_vcvttsh2usi64
        "vcvtudq2ph", // INS_vcvtudq2ph
        "vcvtuqq2ph", // INS_vcvtuqq2ph
        "vcvtusi2sh", // INS_vcvtusi2sh32
        "vcvtusi2sh", // INS_vcvtusi2sh64
        "vcvtuw2ph", // INS_vcvtuw2ph
        "vcvtw2ph", // INS_vcvtw2ph
        "vdivph", // INS_vdivph
        "vdivsh", // INS_vdivsh
        "vdpbf16ps", // INS_vdpbf16ps
        "vfcmaddcph", // INS_vfcmaddcph
        "vfcmaddcsh", // INS_vfcmaddcsh
        "vfcmulcph", // INS_vfcmulcph
        "vfcmulcsh", // INS_vfcmulcsh
        "vfmulcph", // INS_vfmulcph
        "vfmulcsh", // INS_vfmulcsh
        "vfmadd132ph", // INS_vfmadd132ph
        "vfmadd213ph", // INS_vfmadd213ph
        "vfmadd231ph", // INS_vfmadd231ph
        "vfmadd132sh", // INS_vfmadd132sh
        "vfmadd213sh", // INS_vfmadd213sh
        "vfmadd231sh", // INS_vfmadd231sh
        "vfmaddcph", // INS_vfmaddcph
        "vfmaddcsh", // INS_vfmaddcsh
        "vfmaddsub132ph", // INS_vfmaddsub132ph
        "vfmaddsub213ph", // INS_vfmaddsub213ph
        "vfmaddsub231ph", // INS_vfmaddsub231ph
        "vfmsub132ph", // INS_vfmsub132ph
        "vfmsub213ph", // INS_vfmsub213ph
        "vfmsub231ph", // INS_vfmsub231ph
        "vfmsub132sh", // INS_vfmsub132sh
        "vfmsub213sh", // INS_vfmsub213sh
        "vfmsub231sh", // INS_vfmsub231sh
        "vfmsubadd132ph", // INS_vfmsubadd132ph
        "vfmsubadd213ph", // INS_vfmsubadd213ph
        "vfmsubadd231ph", // INS_vfmsubadd231ph
        "vfnmadd132ph", // INS_vfnmadd132ph
        "vfnmadd213ph", // INS_vfnmadd213ph
        "vfnmadd231ph", // INS_vfnmadd231ph
        "vfnmadd132sh", // INS_vfnmadd132sh
        "vfnmadd213sh", // INS_vfnmadd213sh
        "vfnmadd231sh", // INS_vfnmadd231sh
        "vfnmsub132ph", // INS_vfnmsub132ph
        "vfnmsub213ph", // INS_vfnmsub213ph
        "vfnmsub231ph", // INS_vfnmsub231ph
        "vfnmsub132sh", // INS_vfnmsub132sh
        "vfnmsub213sh", // INS_vfnmsub213sh
        "vfnmsub231sh", // INS_vfnmsub231sh
        "vfpclassph", // INS_vfpclassph
        "vfpclasssh", // INS_vfpclasssh
        "vgetexpph", // INS_vgetexpph
        "vgetexpsh", // INS_vgetexpsh
        "vgetmantph", // INS_vgetmantph
        "vgetmantsh", // INS_vgetmantsh
        "vmaxph", // INS_vmaxph
        "vmaxsh", // INS_vmaxsh
        "vminsh", // INS_vminsh
        "vminph", // INS_vminph
        "vmovsh", // INS_vmovsh
        "vmovw", // INS_vmovw
        "vmulph", // INS_vmulph
        "vmulsh", // INS_vmulsh
        "vrcpph", // INS_vrcpph
        "vrcpsh", // INS_vrcpsh
        "vreduceph", // INS_vreduceph
        "vreducesh", // INS_vreducesh
        "vrndscaleph", // INS_vrndscaleph
        "vrndscalesh", // INS_vrndscalesh
        "vrsqrtph", // INS_vrsqrtph
        "vrsqrtsh", // INS_vrsqrtsh
        "vscalefph", // INS_vscalefph
        "vscalefsh", // INS_vscalefsh
        "vsqrtph", // INS_vsqrtph
        "vsqrtsh", // INS_vsqrtsh
        "vsubph", // INS_vsubph
        "vsubsh", // INS_vsubsh
        "vucomish", // INS_vucomish
        "vp2intersectd", // INS_vp2intersectd
        "vp2intersectq", // INS_vp2intersectq
        "vcomxsd", // INS_vcomxsd
        "vcomxss", // INS_vcomxss
        "vcvtps2ibs", // INS_vcvtps2ibs
        "vcvtps2iubs", // INS_vcvtps2iubs
        "vcvttpd2dqs", // INS_vcvttpd2dqs
        "vcvttpd2qqs", // INS_vcvttpd2qqs
        "vcvttpd2udqs", // INS_vcvttpd2udqs
        "vcvttpd2uqqs", // INS_vcvttpd2uqqs
        "vcvttps2dqs", // INS_vcvttps2dqs
        "vcvttps2ibs", // INS_vcvttps2ibs
        "vcvttps2iubs", // INS_vcvttps2iubs
        "vcvttps2qqs", // INS_vcvttps2qqs
        "vcvttps2udqs", // INS_vcvttps2udqs
        "vcvttps2uqqs", // INS_vcvttps2uqqs
        "vcvttsd2sis", // INS_vcvttsd2sis32
        "vcvttsd2sis", // INS_vcvttsd2sis64
        "vcvttsd2usis", // INS_vcvttsd2usis32
        "vcvttsd2usis", // INS_vcvttsd2usis64
        "vcvttss2sis", // INS_vcvttss2sis32
        "vcvttss2sis", // INS_vcvttss2sis64
        "vcvttss2usis", // INS_vcvttss2usis32
        "vcvttss2usis", // INS_vcvttss2usis64
        "vminmaxpd", // INS_vminmaxpd
        "vminmaxps", // INS_vminmaxps
        "vminmaxsd", // INS_vminmaxsd
        "vminmaxss", // INS_vminmaxss
        "vmovd", // INS_vmovd_simd
        "vmovw", // INS_vmovw_simd
        "vmpsadbw", // INS_vmpsadbw
        "vucomxsd", // INS_vucomxsd
        "vucomxss", // INS_vucomxss
#if TARGET_AMD64
        "ccmpo", // INS_ccmpo
        "ccmpno", // INS_ccmpno
        "ccmpb", // INS_ccmpb
        "ccmpae", // INS_ccmpae
        "ccmpe", // INS_ccmpe
        "ccmpne", // INS_ccmpne
        "ccmpbe", // INS_ccmpbe
        "ccmpa", // INS_ccmpa
        "ccmps", // INS_ccmps
        "ccmpns", // INS_ccmpns
        "ccmpt", // INS_ccmpt
        "ccmpf", // INS_ccmpf
        "ccmpl", // INS_ccmpl
        "ccmpge", // INS_ccmpge
        "ccmple", // INS_ccmple
        "ccmpg", // INS_ccmpg
        "cfcmovo", // INS_cfcmovo
        "cfcmovno", // INS_cfcmovno
        "cfcmovb", // INS_cfcmovb
        "cfcmovae", // INS_cfcmovae
        "cfcmove", // INS_cfcmove
        "cfcmovne", // INS_cfcmovne
        "cfcmovbe", // INS_cfcmovbe
        "cfcmova", // INS_cfcmova
        "cfcmovs", // INS_cfcmovs
        "cfcmovns", // INS_cfcmovns
        "cfcmovp", // INS_cfcmovp
        "cfcmovnp", // INS_cfcmovnp
        "cfcmovl", // INS_cfcmovl
        "cfcmovge", // INS_cfcmovge
        "cfcmovle", // INS_cfcmovle
        "cfcmovg", // INS_cfcmovg
        "ctesto", // INS_ctesto
        "ctestno", // INS_ctestno
        "ctestb", // INS_ctestb
        "ctestae", // INS_ctestae
        "cteste", // INS_cteste
        "ctestne", // INS_ctestne
        "ctestbe", // INS_ctestbe
        "ctesta", // INS_ctesta
        "ctests", // INS_ctests
        "ctestns", // INS_ctestns
        "ctestt", // INS_ctestt
        "ctestf", // INS_ctestf
        "ctestl", // INS_ctestl
        "ctestge", // INS_ctestge
        "ctestle", // INS_ctestle
        "ctestg", // INS_ctestg
        "crc32", // INS_crc32_apx
        "movbe", // INS_movbe_apx
        "setzuo", // INS_seto_apx
        "setzuno", // INS_setno_apx
        "setzub", // INS_setb_apx
        "setzuae", // INS_setae_apx
        "setzue", // INS_sete_apx
        "setzune", // INS_setne_apx
        "setzube", // INS_setbe_apx
        "setzua", // INS_seta_apx
        "setzus", // INS_sets_apx
        "setzuns", // INS_setns_apx
        "setzup", // INS_setp_apx
        "setzunp", // INS_setnp_apx
        "setzul", // INS_setl_apx
        "setzuge", // INS_setge_apx
        "setzule", // INS_setle_apx
        "setzug", // INS_setg_apx
#endif
        "crc32", // INS_crc32
        "tzcnt", // INS_tzcnt
#if TARGET_AMD64
        "tzcnt", // INS_tzcnt_apx
#endif
        "lzcnt", // INS_lzcnt
#if TARGET_AMD64
        "lzcnt", // INS_lzcnt_apx
#endif
        "movbe", // INS_movbe
        "popcnt", // INS_popcnt
#if TARGET_AMD64
        "popcnt", // INS_popcnt_apx
#endif
        "tpause", // INS_tpause
        "umonitor", // INS_umonitor
        "umwait", // INS_umwait
        "neg", // INS_neg
        "not", // INS_not
        "rol", // INS_rol
        "rol", // INS_rol_1
        "rol", // INS_rol_N
        "ror", // INS_ror
        "ror", // INS_ror_1
        "ror", // INS_ror_N
        "rcl", // INS_rcl
        "rcl", // INS_rcl_1
        "rcl", // INS_rcl_N
        "rcr", // INS_rcr
        "rcr", // INS_rcr_1
        "rcr", // INS_rcr_N
        "shl", // INS_shl
        "shl", // INS_shl_1
        "shl", // INS_shl_N
        "shr", // INS_shr
        "shr", // INS_shr_1
        "shr", // INS_shr_N
        "sar", // INS_sar
        "sar", // INS_sar_1
        "sar", // INS_sar_N
        "ret", // INS_ret
        "loop", // INS_loop
        "call", // INS_call
        "rep movsb", // INS_r_movsb
        "rep movsd", // INS_r_movsd
#if TARGET_AMD64
        "rep movsq", // INS_r_movsq
#endif
        "movsb", // INS_movsb
        "movsd", // INS_movsd
#if TARGET_AMD64
        "movsq", // INS_movsq
#endif
        "rep stosb", // INS_r_stosb
        "rep stosd", // INS_r_stosd
#if TARGET_AMD64
        "rep stosq", // INS_r_stosq
#endif
        "stosb", // INS_stosb
        "stosd", // INS_stosd
#if TARGET_AMD64
        "stosq", // INS_stosq
#endif
        "int3", // INS_int3
        "nop", // INS_nop
        "pause", // INS_pause
        "lock", // INS_lock
        "leave", // INS_leave
        "serialize", // INS_serialize
        "cwde", // INS_cwde
        "cdq", // INS_cdq
        "idiv", // INS_idiv
        "imul", // INS_imulEAX
        "div", // INS_div
        "mul", // INS_mulEAX
        "sahf", // INS_sahf
        "xadd", // INS_xadd
        "cmpxchg", // INS_cmpxchg
        "shld", // INS_shld
        "shrd", // INS_shrd
#if TARGET_X86
        "fld", // INS_fld
        "fstp", // INS_fstp
#endif
        "seto", // INS_seto
        "setno", // INS_setno
        "setb", // INS_setb
        "setae", // INS_setae
        "sete", // INS_sete
        "setne", // INS_setne
        "setbe", // INS_setbe
        "seta", // INS_seta
        "sets", // INS_sets
        "setns", // INS_setns
        "setp", // INS_setp
        "setnp", // INS_setnp
        "setl", // INS_setl
        "setge", // INS_setge
        "setle", // INS_setle
        "setg", // INS_setg
        "tail.jmp", // INS_tail_i_jmp
        "jmp", // INS_i_jmp
        "jmp", // INS_jmp
        "jo", // INS_jo
        "jno", // INS_jno
        "jb", // INS_jb
        "jae", // INS_jae
        "je", // INS_je
        "jne", // INS_jne
        "jbe", // INS_jbe
        "ja", // INS_ja
        "js", // INS_js
        "jns", // INS_jns
        "jp", // INS_jp
        "jnp", // INS_jnp
        "jl", // INS_jl
        "jge", // INS_jge
        "jle", // INS_jle
        "jg", // INS_jg
        "jmp", // INS_l_jmp
        "jo", // INS_l_jo
        "jno", // INS_l_jno
        "jb", // INS_l_jb
        "jae", // INS_l_jae
        "je", // INS_l_je
        "jne", // INS_l_jne
        "jbe", // INS_l_jbe
        "ja", // INS_l_ja
        "js", // INS_l_js
        "jns", // INS_l_jns
        "jp", // INS_l_jp
        "jnp", // INS_l_jnp
        "jl", // INS_l_jl
        "jge", // INS_l_jge
        "jle", // INS_l_jle
        "jg", // INS_l_jg
        "align", // INS_align
        "data16", // INS_data16
#elif TARGET_ARM
#if !TARGET_ARM
#error Unexpected target type
#endif
#if FEATURE_PLI_INSTRUCTION
#endif
#if FEATURE_ITINSTRUCTION
#endif
#elif TARGET_ARM64
#if !TARGET_ARM64
#error Unexpected target type
#endif
#if FEATURE_LOOP_ALIGN
#endif
#if !TARGET_ARM64
#error Unexpected target type
#endif
#elif TARGET_LOONGARCH64
#if !TARGET_LOONGARCH64
#error Unexpected target type
#endif
#if FEATURE_SIMD
#endif
#elif TARGET_RISCV64
#if !TARGET_RISCV64
#error Unexpected target type
#endif
#elif TARGET_WASM
#if !TARGET_WASM
#error Unexpected target type
#endif
#else
#error Unsupported or unset target architecture
#endif
    ];
#endif
}