// Copyright (c) Tanner Gooding and Contributors. Licensed under the MIT License (MIT). See License.md in the repository root for more information.
//
// Based on the RyuJIT compiler from dotnet/runtime.
// Original source is Copyright (c) .NET Foundation and Contributors. Licensed under the MIT License (MIT).

using System;

namespace RyuJitSharp;

public partial class Emitter
{
#if TARGET_WASM
    private static ReadOnlySpan<uint> s_wasmOpcodes => [
        unchecked((uint)(Globals.BAD_CODE)), // INS_invalid
        unchecked((uint)(0x00)), // INS_unreachable
        unchecked((uint)(0x00)), // INS_label
        unchecked((uint)(0x00)), // INS_catch_ref
        unchecked((uint)(0x00)), // INS_local_cnt
        unchecked((uint)(0x00)), // INS_local_decl
        unchecked((uint)(0x00)), // INS_code_size
        unchecked((uint)(0x01)), // INS_nop
        unchecked((uint)(0x02)), // INS_block
        unchecked((uint)(0x03)), // INS_loop
        unchecked((uint)(0x04)), // INS_if
        unchecked((uint)(0x05)), // INS_else
        unchecked((uint)(0x0A)), // INS_throw_ref
        unchecked((uint)(0x0B)), // INS_end
        unchecked((uint)(0x0C)), // INS_br
        unchecked((uint)(0x0D)), // INS_br_if
        unchecked((uint)(0x0E)), // INS_br_table
        unchecked((uint)(0x0F)), // INS_return
        unchecked((uint)(0x10)), // INS_call
        unchecked((uint)(0x11)), // INS_call_indirect
        unchecked((uint)(0x12)), // INS_return_call
        unchecked((uint)(0x13)), // INS_return_call_indirect
        unchecked((uint)(0x10)), // INS_call_funclet
        unchecked((uint)(0x1A)), // INS_drop
        unchecked((uint)(0x1F)), // INS_try_table
        unchecked((uint)(0x20)), // INS_local_get
        unchecked((uint)(0x21)), // INS_local_set
        unchecked((uint)(0x22)), // INS_local_tee
        unchecked((uint)(0x23)), // INS_global_get
        unchecked((uint)(0x24)), // INS_global_set
        unchecked((uint)(0x28)), // INS_i32_load
        unchecked((uint)(0x29)), // INS_i64_load
        unchecked((uint)(0x2A)), // INS_f32_load
        unchecked((uint)(0x2B)), // INS_f64_load
        unchecked((uint)(0x2C)), // INS_i32_load8_s
        unchecked((uint)(0x2D)), // INS_i32_load8_u
        unchecked((uint)(0x2E)), // INS_i32_load16_s
        unchecked((uint)(0x2F)), // INS_i32_load16_u
        unchecked((uint)(0x30)), // INS_i64_load8_s
        unchecked((uint)(0x31)), // INS_i64_load8_u
        unchecked((uint)(0x32)), // INS_i64_load16_s
        unchecked((uint)(0x33)), // INS_i64_load16_u
        unchecked((uint)(0x34)), // INS_i64_load32_s
        unchecked((uint)(0x35)), // INS_i64_load32_u
        unchecked((uint)(0x36)), // INS_i32_store
        unchecked((uint)(0x37)), // INS_i64_store
        unchecked((uint)(0x38)), // INS_f32_store
        unchecked((uint)(0x39)), // INS_f64_store
        unchecked((uint)(0x3A)), // INS_i32_store8
        unchecked((uint)(0x3B)), // INS_i32_store16
        unchecked((uint)(0x41)), // INS_i32_const
        unchecked((uint)(0x41)), // INS_i32_const_address
        unchecked((uint)(0x41)), // INS_i32_const_funcptr
        unchecked((uint)(0x41)), // INS_i32_const_funcletptr
        unchecked((uint)(0x41)), // INS_i32_const_dataoffs
        unchecked((uint)(0x42)), // INS_i64_const
        unchecked((uint)(0x43)), // INS_f32_const
        unchecked((uint)(0x44)), // INS_f64_const
        unchecked((uint)(0x45)), // INS_i32_eqz
        unchecked((uint)(0x46)), // INS_i32_eq
        unchecked((uint)(0x47)), // INS_i32_ne
        unchecked((uint)(0x48)), // INS_i32_lt_s
        unchecked((uint)(0x49)), // INS_i32_lt_u
        unchecked((uint)(0x4A)), // INS_i32_gt_s
        unchecked((uint)(0x4B)), // INS_i32_gt_u
        unchecked((uint)(0x4C)), // INS_i32_le_s
        unchecked((uint)(0x4D)), // INS_i32_le_u
        unchecked((uint)(0x4E)), // INS_i32_ge_s
        unchecked((uint)(0x4F)), // INS_i32_ge_u
        unchecked((uint)(0x50)), // INS_i64_eqz
        unchecked((uint)(0x51)), // INS_i64_eq
        unchecked((uint)(0x52)), // INS_i64_ne
        unchecked((uint)(0x53)), // INS_i64_lt_s
        unchecked((uint)(0x54)), // INS_i64_lt_u
        unchecked((uint)(0x55)), // INS_i64_gt_s
        unchecked((uint)(0x56)), // INS_i64_gt_u
        unchecked((uint)(0x57)), // INS_i64_le_s
        unchecked((uint)(0x58)), // INS_i64_le_u
        unchecked((uint)(0x59)), // INS_i64_ge_s
        unchecked((uint)(0x5A)), // INS_i64_ge_u
        unchecked((uint)(0x5B)), // INS_f32_eq
        unchecked((uint)(0x5C)), // INS_f32_ne
        unchecked((uint)(0x5D)), // INS_f32_lt
        unchecked((uint)(0x5E)), // INS_f32_gt
        unchecked((uint)(0x5F)), // INS_f32_le
        unchecked((uint)(0x60)), // INS_f32_ge
        unchecked((uint)(0x61)), // INS_f64_eq
        unchecked((uint)(0x62)), // INS_f64_ne
        unchecked((uint)(0x63)), // INS_f64_lt
        unchecked((uint)(0x64)), // INS_f64_gt
        unchecked((uint)(0x65)), // INS_f64_le
        unchecked((uint)(0x66)), // INS_f64_ge
        unchecked((uint)(0x67)), // INS_i32_clz
        unchecked((uint)(0x68)), // INS_i32_ctz
        unchecked((uint)(0x69)), // INS_i32_popcnt
        unchecked((uint)(0x6A)), // INS_i32_add
        unchecked((uint)(0x6B)), // INS_i32_sub
        unchecked((uint)(0x6C)), // INS_i32_mul
        unchecked((uint)(0x6D)), // INS_i32_div_s
        unchecked((uint)(0x6E)), // INS_i32_div_u
        unchecked((uint)(0x6F)), // INS_i32_rem_s
        unchecked((uint)(0x70)), // INS_i32_rem_u
        unchecked((uint)(0x71)), // INS_i32_and
        unchecked((uint)(0x72)), // INS_i32_or
        unchecked((uint)(0x73)), // INS_i32_xor
        unchecked((uint)(0x74)), // INS_i32_shl
        unchecked((uint)(0x75)), // INS_i32_shr_s
        unchecked((uint)(0x76)), // INS_i32_shr_u
        unchecked((uint)(0x77)), // INS_i32_rotl
        unchecked((uint)(0x78)), // INS_i32_rotr
        unchecked((uint)(0x79)), // INS_i64_clz
        unchecked((uint)(0x7A)), // INS_i64_ctz
        unchecked((uint)(0x7B)), // INS_i64_popcnt
        unchecked((uint)(0x7C)), // INS_i64_add
        unchecked((uint)(0x7D)), // INS_i64_sub
        unchecked((uint)(0x7E)), // INS_i64_mul
        unchecked((uint)(0x7F)), // INS_i64_div_s
        unchecked((uint)(0x80)), // INS_i64_div_u
        unchecked((uint)(0x81)), // INS_i64_rem_s
        unchecked((uint)(0x82)), // INS_i64_rem_u
        unchecked((uint)(0x83)), // INS_i64_and
        unchecked((uint)(0x84)), // INS_i64_or
        unchecked((uint)(0x85)), // INS_i64_xor
        unchecked((uint)(0x86)), // INS_i64_shl
        unchecked((uint)(0x87)), // INS_i64_shr_s
        unchecked((uint)(0x88)), // INS_i64_shr_u
        unchecked((uint)(0x89)), // INS_i64_rotl
        unchecked((uint)(0x8A)), // INS_i64_rotr
        unchecked((uint)(0x8B)), // INS_f32_abs
        unchecked((uint)(0x8C)), // INS_f32_neg
        unchecked((uint)(0x8D)), // INS_f32_ceil
        unchecked((uint)(0x8E)), // INS_f32_floor
        unchecked((uint)(0x8F)), // INS_f32_trunc
        unchecked((uint)(0x90)), // INS_f32_nearest
        unchecked((uint)(0x91)), // INS_f32_sqrt
        unchecked((uint)(0x92)), // INS_f32_add
        unchecked((uint)(0x93)), // INS_f32_sub
        unchecked((uint)(0x94)), // INS_f32_mul
        unchecked((uint)(0x95)), // INS_f32_div
        unchecked((uint)(0x96)), // INS_f32_min
        unchecked((uint)(0x97)), // INS_f32_max
        unchecked((uint)(0x98)), // INS_f32_copysign
        unchecked((uint)(0x99)), // INS_f64_abs
        unchecked((uint)(0x9A)), // INS_f64_neg
        unchecked((uint)(0x9B)), // INS_f64_ceil
        unchecked((uint)(0x9C)), // INS_f64_floor
        unchecked((uint)(0x9D)), // INS_f64_trunc
        unchecked((uint)(0x9E)), // INS_f64_nearest
        unchecked((uint)(0x9F)), // INS_f64_sqrt
        unchecked((uint)(0xA0)), // INS_f64_add
        unchecked((uint)(0xA1)), // INS_f64_sub
        unchecked((uint)(0xA2)), // INS_f64_mul
        unchecked((uint)(0xA3)), // INS_f64_div
        unchecked((uint)(0xA4)), // INS_f64_min
        unchecked((uint)(0xA5)), // INS_f64_max
        unchecked((uint)(0xA6)), // INS_f64_copysign
        unchecked((uint)(0xA7)), // INS_i32_wrap_i64
        unchecked((uint)(0xA8)), // INS_i32_trunc_s_f32
        unchecked((uint)(0xA9)), // INS_i32_trunc_u_f32
        unchecked((uint)(0xAA)), // INS_i32_trunc_s_f64
        unchecked((uint)(0xAB)), // INS_i32_trunc_u_f64
        unchecked((uint)(0xAC)), // INS_i64_extend_s_i32
        unchecked((uint)(0xAD)), // INS_i64_extend_u_i32
        unchecked((uint)(0xAE)), // INS_i64_trunc_s_f32
        unchecked((uint)(0xAF)), // INS_i64_trunc_u_f32
        unchecked((uint)(0xB0)), // INS_i64_trunc_s_f64
        unchecked((uint)(0xB1)), // INS_i64_trunc_u_f64
        unchecked((uint)(0xB2)), // INS_f32_convert_s_i32
        unchecked((uint)(0xB3)), // INS_f32_convert_u_i32
        unchecked((uint)(0xB4)), // INS_f32_convert_s_i64
        unchecked((uint)(0xB5)), // INS_f32_convert_u_i64
        unchecked((uint)(0xB6)), // INS_f32_demote_f64
        unchecked((uint)(0xB7)), // INS_f64_convert_s_i32
        unchecked((uint)(0xB8)), // INS_f64_convert_u_i32
        unchecked((uint)(0xB9)), // INS_f64_convert_s_i64
        unchecked((uint)(0xBA)), // INS_f64_convert_u_i64
        unchecked((uint)(0xBB)), // INS_f64_promote_f32
        unchecked((uint)(0xBC)), // INS_i32_reinterpret_f32
        unchecked((uint)(0xBD)), // INS_i64_reinterpret_f64
        unchecked((uint)(0xBE)), // INS_f32_reinterpret_i32
        unchecked((uint)(0xBF)), // INS_f64_reinterpret_i64
        unchecked((uint)(0xC0)), // INS_i32_extend8_s
        unchecked((uint)(0xC1)), // INS_i32_extend16_s
        unchecked((uint)(0xC2)), // INS_i64_extend8_s
        unchecked((uint)(0xC3)), // INS_i64_extend16_s
        unchecked((uint)(0xC4)), // INS_i64_extend32_s
        unchecked((uint)(0)), // INS_i32_trunc_sat_f32_s
        unchecked((uint)(1)), // INS_i32_trunc_sat_f32_u
        unchecked((uint)(2)), // INS_i32_trunc_sat_f64_s
        unchecked((uint)(3)), // INS_i32_trunc_sat_f64_u
        unchecked((uint)(4)), // INS_i64_trunc_sat_f32_s
        unchecked((uint)(5)), // INS_i64_trunc_sat_f32_u
        unchecked((uint)(6)), // INS_i64_trunc_sat_f64_s
        unchecked((uint)(7)), // INS_i64_trunc_sat_f64_u
        unchecked((uint)(10)), // INS_memory_copy
        unchecked((uint)(11)), // INS_memory_fill
        unchecked((uint)(0)), // INS_v128_load
        unchecked((uint)(1)), // INS_v128_load8x8_s
        unchecked((uint)(2)), // INS_v128_load8x8_u
        unchecked((uint)(3)), // INS_v128_load16x4_s
        unchecked((uint)(4)), // INS_v128_load16x4_u
        unchecked((uint)(5)), // INS_v128_load32x2_s
        unchecked((uint)(6)), // INS_v128_load32x2_u
        unchecked((uint)(7)), // INS_v128_load8_splat
        unchecked((uint)(8)), // INS_v128_load16_splat
        unchecked((uint)(9)), // INS_v128_load32_splat
        unchecked((uint)(10)), // INS_v128_load64_splat
        unchecked((uint)(11)), // INS_v128_store
        unchecked((uint)(12)), // INS_v128_const
        unchecked((uint)(13)), // INS_i8x16_shuffle
        unchecked((uint)(14)), // INS_i8x16_swizzle
        unchecked((uint)(15)), // INS_i8x16_splat
        unchecked((uint)(16)), // INS_i16x8_splat
        unchecked((uint)(17)), // INS_i32x4_splat
        unchecked((uint)(18)), // INS_i64x2_splat
        unchecked((uint)(19)), // INS_f32x4_splat
        unchecked((uint)(20)), // INS_f64x2_splat
        unchecked((uint)(21)), // INS_i8x16_extract_lane_s
        unchecked((uint)(22)), // INS_i8x16_extract_lane_u
        unchecked((uint)(23)), // INS_i8x16_replace_lane
        unchecked((uint)(24)), // INS_i16x8_extract_lane_s
        unchecked((uint)(25)), // INS_i16x8_extract_lane_u
        unchecked((uint)(26)), // INS_i16x8_replace_lane
        unchecked((uint)(27)), // INS_i32x4_extract_lane
        unchecked((uint)(28)), // INS_i32x4_replace_lane
        unchecked((uint)(29)), // INS_i64x2_extract_lane
        unchecked((uint)(30)), // INS_i64x2_replace_lane
        unchecked((uint)(31)), // INS_f32x4_extract_lane
        unchecked((uint)(32)), // INS_f32x4_replace_lane
        unchecked((uint)(33)), // INS_f64x2_extract_lane
        unchecked((uint)(34)), // INS_f64x2_replace_lane
        unchecked((uint)(35)), // INS_i8x16_eq
        unchecked((uint)(36)), // INS_i8x16_ne
        unchecked((uint)(37)), // INS_i8x16_lt_s
        unchecked((uint)(38)), // INS_i8x16_lt_u
        unchecked((uint)(39)), // INS_i8x16_gt_s
        unchecked((uint)(40)), // INS_i8x16_gt_u
        unchecked((uint)(41)), // INS_i8x16_le_s
        unchecked((uint)(42)), // INS_i8x16_le_u
        unchecked((uint)(43)), // INS_i8x16_ge_s
        unchecked((uint)(44)), // INS_i8x16_ge_u
        unchecked((uint)(45)), // INS_i16x8_eq
        unchecked((uint)(46)), // INS_i16x8_ne
        unchecked((uint)(47)), // INS_i16x8_lt_s
        unchecked((uint)(48)), // INS_i16x8_lt_u
        unchecked((uint)(49)), // INS_i16x8_gt_s
        unchecked((uint)(50)), // INS_i16x8_gt_u
        unchecked((uint)(51)), // INS_i16x8_le_s
        unchecked((uint)(52)), // INS_i16x8_le_u
        unchecked((uint)(53)), // INS_i16x8_ge_s
        unchecked((uint)(54)), // INS_i16x8_ge_u
        unchecked((uint)(55)), // INS_i32x4_eq
        unchecked((uint)(56)), // INS_i32x4_ne
        unchecked((uint)(57)), // INS_i32x4_lt_s
        unchecked((uint)(58)), // INS_i32x4_lt_u
        unchecked((uint)(59)), // INS_i32x4_gt_s
        unchecked((uint)(60)), // INS_i32x4_gt_u
        unchecked((uint)(61)), // INS_i32x4_le_s
        unchecked((uint)(62)), // INS_i32x4_le_u
        unchecked((uint)(63)), // INS_i32x4_ge_s
        unchecked((uint)(64)), // INS_i32x4_ge_u
        unchecked((uint)(214)), // INS_i64x2_eq
        unchecked((uint)(215)), // INS_i64x2_ne
        unchecked((uint)(216)), // INS_i64x2_lt_s
        unchecked((uint)(217)), // INS_i64x2_gt_s
        unchecked((uint)(218)), // INS_i64x2_le_s
        unchecked((uint)(219)), // INS_i64x2_ge_s
        unchecked((uint)(65)), // INS_f32x4_eq
        unchecked((uint)(66)), // INS_f32x4_ne
        unchecked((uint)(67)), // INS_f32x4_lt
        unchecked((uint)(68)), // INS_f32x4_gt
        unchecked((uint)(69)), // INS_f32x4_le
        unchecked((uint)(70)), // INS_f32x4_ge
        unchecked((uint)(71)), // INS_f64x2_eq
        unchecked((uint)(72)), // INS_f64x2_ne
        unchecked((uint)(73)), // INS_f64x2_lt
        unchecked((uint)(74)), // INS_f64x2_gt
        unchecked((uint)(75)), // INS_f64x2_le
        unchecked((uint)(76)), // INS_f64x2_ge
        unchecked((uint)(77)), // INS_v128_not
        unchecked((uint)(78)), // INS_v128_and
        unchecked((uint)(79)), // INS_v128_andnot
        unchecked((uint)(80)), // INS_v128_or
        unchecked((uint)(81)), // INS_v128_xor
        unchecked((uint)(82)), // INS_v128_bitselect
        unchecked((uint)(83)), // INS_v128_any_true
        unchecked((uint)(84)), // INS_v128_load8_lane
        unchecked((uint)(85)), // INS_v128_load16_lane
        unchecked((uint)(86)), // INS_v128_load32_lane
        unchecked((uint)(87)), // INS_v128_load64_lane
        unchecked((uint)(88)), // INS_v128_store8_lane
        unchecked((uint)(89)), // INS_v128_store16_lane
        unchecked((uint)(90)), // INS_v128_store32_lane
        unchecked((uint)(91)), // INS_v128_store64_lane
        unchecked((uint)(92)), // INS_v128_load32_zero
        unchecked((uint)(93)), // INS_v128_load64_zero
        unchecked((uint)(94)), // INS_f32x4_demote_f64x2_zero
        unchecked((uint)(95)), // INS_f64x2_promote_low_f32x4
        unchecked((uint)(96)), // INS_i8x16_abs
        unchecked((uint)(97)), // INS_i8x16_neg
        unchecked((uint)(98)), // INS_i8x16_popcnt
        unchecked((uint)(99)), // INS_i8x16_all_true
        unchecked((uint)(100)), // INS_i8x16_bitmask
        unchecked((uint)(101)), // INS_i8x16_narrow_i16x8_s
        unchecked((uint)(102)), // INS_i8x16_narrow_i16x8_u
        unchecked((uint)(103)), // INS_f32x4_ceil
        unchecked((uint)(104)), // INS_f32x4_floor
        unchecked((uint)(105)), // INS_f32x4_trunc
        unchecked((uint)(106)), // INS_f32x4_nearest
        unchecked((uint)(107)), // INS_i8x16_shl
        unchecked((uint)(108)), // INS_i8x16_shr_s
        unchecked((uint)(109)), // INS_i8x16_shr_u
        unchecked((uint)(110)), // INS_i8x16_add
        unchecked((uint)(111)), // INS_i8x16_add_sat_s
        unchecked((uint)(112)), // INS_i8x16_add_sat_u
        unchecked((uint)(113)), // INS_i8x16_sub
        unchecked((uint)(114)), // INS_i8x16_sub_sat_s
        unchecked((uint)(115)), // INS_i8x16_sub_sat_u
        unchecked((uint)(116)), // INS_f64x2_ceil
        unchecked((uint)(117)), // INS_f64x2_floor
        unchecked((uint)(118)), // INS_i8x16_min_s
        unchecked((uint)(119)), // INS_i8x16_min_u
        unchecked((uint)(120)), // INS_i8x16_max_s
        unchecked((uint)(121)), // INS_i8x16_max_u
        unchecked((uint)(122)), // INS_f64x2_trunc
        unchecked((uint)(123)), // INS_i8x16_avgr_u
        unchecked((uint)(124)), // INS_i16x8_extadd_pairwise_s_i8x16
        unchecked((uint)(125)), // INS_i16x8_extadd_pairwise_u_i8x16
        unchecked((uint)(126)), // INS_i32x4_extadd_pairwise_s_i16x8
        unchecked((uint)(127)), // INS_i32x4_extadd_pairwise_u_i16x8
        unchecked((uint)(128)), // INS_i16x8_abs
        unchecked((uint)(129)), // INS_i16x8_neg
        unchecked((uint)(130)), // INS_i16x8_q15mulr_sat_s
        unchecked((uint)(131)), // INS_i16x8_all_true
        unchecked((uint)(132)), // INS_i16x8_bitmask
        unchecked((uint)(133)), // INS_i16x8_narrow_i32x4_s
        unchecked((uint)(134)), // INS_i16x8_narrow_i32x4_u
        unchecked((uint)(135)), // INS_i16x8_extend_low_s_i8x16
        unchecked((uint)(136)), // INS_i16x8_extend_high_s_i8x16
        unchecked((uint)(137)), // INS_i16x8_extend_low_u_i8x16
        unchecked((uint)(138)), // INS_i16x8_extend_high_u_i8x16
        unchecked((uint)(139)), // INS_i16x8_shl
        unchecked((uint)(140)), // INS_i16x8_shr_s
        unchecked((uint)(141)), // INS_i16x8_shr_u
        unchecked((uint)(142)), // INS_i16x8_add
        unchecked((uint)(143)), // INS_i16x8_add_sat_s
        unchecked((uint)(144)), // INS_i16x8_add_sat_u
        unchecked((uint)(145)), // INS_i16x8_sub
        unchecked((uint)(146)), // INS_i16x8_sub_sat_s
        unchecked((uint)(147)), // INS_i16x8_sub_sat_u
        unchecked((uint)(148)), // INS_f64x2_nearest
        unchecked((uint)(149)), // INS_i16x8_mul
        unchecked((uint)(150)), // INS_i16x8_min_s
        unchecked((uint)(151)), // INS_i16x8_min_u
        unchecked((uint)(152)), // INS_i16x8_max_s
        unchecked((uint)(153)), // INS_i16x8_max_u
        unchecked((uint)(155)), // INS_i16x8_avgr_u
        unchecked((uint)(156)), // INS_i16x8_extmul_low_s_i8x16
        unchecked((uint)(157)), // INS_i16x8_extmul_high_s_i8x16
        unchecked((uint)(158)), // INS_i16x8_extmul_low_u_i8x16
        unchecked((uint)(159)), // INS_i16x8_extmul_high_u_i8x16
        unchecked((uint)(160)), // INS_i32x4_abs
        unchecked((uint)(161)), // INS_i32x4_neg
        unchecked((uint)(163)), // INS_i32x4_all_true
        unchecked((uint)(164)), // INS_i32x4_bitmask
        unchecked((uint)(167)), // INS_i32x4_extend_low_s_i16x8
        unchecked((uint)(168)), // INS_i32x4_extend_high_s_i16x8
        unchecked((uint)(169)), // INS_i32x4_extend_low_u_i16x8
        unchecked((uint)(170)), // INS_i32x4_extend_high_u_i16x8
        unchecked((uint)(171)), // INS_i32x4_shl
        unchecked((uint)(172)), // INS_i32x4_shr_s
        unchecked((uint)(173)), // INS_i32x4_shr_u
        unchecked((uint)(174)), // INS_i32x4_add
        unchecked((uint)(177)), // INS_i32x4_sub
        unchecked((uint)(181)), // INS_i32x4_mul
        unchecked((uint)(182)), // INS_i32x4_min_s
        unchecked((uint)(183)), // INS_i32x4_min_u
        unchecked((uint)(184)), // INS_i32x4_max_s
        unchecked((uint)(185)), // INS_i32x4_max_u
        unchecked((uint)(186)), // INS_i32x4_dot_i16x8_s
        unchecked((uint)(188)), // INS_i32x4_extmul_low_s_i16x8
        unchecked((uint)(189)), // INS_i32x4_extmul_high_s_i16x8
        unchecked((uint)(190)), // INS_i32x4_extmul_low_u_i16x8
        unchecked((uint)(191)), // INS_i32x4_extmul_high_u_i16x8
        unchecked((uint)(192)), // INS_i64x2_abs
        unchecked((uint)(193)), // INS_i64x2_neg
        unchecked((uint)(195)), // INS_i64x2_all_true
        unchecked((uint)(196)), // INS_i64x2_bitmask
        unchecked((uint)(199)), // INS_i64x2_extend_low_s_i32x4
        unchecked((uint)(200)), // INS_i64x2_extend_high_s_i32x4
        unchecked((uint)(201)), // INS_i64x2_extend_low_u_i32x4
        unchecked((uint)(202)), // INS_i64x2_extend_high_u_i32x4
        unchecked((uint)(203)), // INS_i64x2_shl
        unchecked((uint)(204)), // INS_i64x2_shr_s
        unchecked((uint)(205)), // INS_i64x2_shr_u
        unchecked((uint)(206)), // INS_i64x2_add
        unchecked((uint)(209)), // INS_i64x2_sub
        unchecked((uint)(213)), // INS_i64x2_mul
        unchecked((uint)(220)), // INS_i64x2_extmul_low_s_i32x4
        unchecked((uint)(221)), // INS_i64x2_extmul_high_s_i32x4
        unchecked((uint)(222)), // INS_i64x2_extmul_low_u_i32x4
        unchecked((uint)(223)), // INS_i64x2_extmul_high_u_i32x4
        unchecked((uint)(224)), // INS_f32x4_abs
        unchecked((uint)(225)), // INS_f32x4_neg
        unchecked((uint)(227)), // INS_f32x4_sqrt
        unchecked((uint)(228)), // INS_f32x4_add
        unchecked((uint)(229)), // INS_f32x4_sub
        unchecked((uint)(230)), // INS_f32x4_mul
        unchecked((uint)(231)), // INS_f32x4_div
        unchecked((uint)(232)), // INS_f32x4_min
        unchecked((uint)(233)), // INS_f32x4_max
        unchecked((uint)(234)), // INS_f32x4_pmin
        unchecked((uint)(235)), // INS_f32x4_pmax
        unchecked((uint)(236)), // INS_f64x2_abs
        unchecked((uint)(237)), // INS_f64x2_neg
        unchecked((uint)(239)), // INS_f64x2_sqrt
        unchecked((uint)(240)), // INS_f64x2_add
        unchecked((uint)(241)), // INS_f64x2_sub
        unchecked((uint)(242)), // INS_f64x2_mul
        unchecked((uint)(243)), // INS_f64x2_div
        unchecked((uint)(244)), // INS_f64x2_min
        unchecked((uint)(245)), // INS_f64x2_max
        unchecked((uint)(246)), // INS_f64x2_pmin
        unchecked((uint)(247)), // INS_f64x2_pmax
        unchecked((uint)(248)), // INS_i32x4_trunc_sat_s_f32x4
        unchecked((uint)(249)), // INS_i32x4_trunc_sat_u_f32x4
        unchecked((uint)(250)), // INS_f32x4_convert_s_i32x4
        unchecked((uint)(251)), // INS_f32x4_convert_u_i32x4
        unchecked((uint)(252)), // INS_i32x4_trunc_sat_s_f64x2_zero
        unchecked((uint)(253)), // INS_i32x4_trunc_sat_u_f64x2_zero
        unchecked((uint)(254)), // INS_f64x2_convert_low_s_i32x4
        unchecked((uint)(255)), // INS_f64x2_convert_low_u_i32x4
    ];

    private static ReadOnlySpan<byte> s_wasmOpcodePrefixes => [
        unchecked((byte)(0xFC)), // INS_invalid
        unchecked((byte)(0)), // INS_unreachable
        unchecked((byte)(0)), // INS_label
        unchecked((byte)(0)), // INS_catch_ref
        unchecked((byte)(0)), // INS_local_cnt
        unchecked((byte)(0)), // INS_local_decl
        unchecked((byte)(0)), // INS_code_size
        unchecked((byte)(0)), // INS_nop
        unchecked((byte)(0)), // INS_block
        unchecked((byte)(0)), // INS_loop
        unchecked((byte)(0)), // INS_if
        unchecked((byte)(0)), // INS_else
        unchecked((byte)(0)), // INS_throw_ref
        unchecked((byte)(0)), // INS_end
        unchecked((byte)(0)), // INS_br
        unchecked((byte)(0)), // INS_br_if
        unchecked((byte)(0)), // INS_br_table
        unchecked((byte)(0)), // INS_return
        unchecked((byte)(0)), // INS_call
        unchecked((byte)(0)), // INS_call_indirect
        unchecked((byte)(0)), // INS_return_call
        unchecked((byte)(0)), // INS_return_call_indirect
        unchecked((byte)(0)), // INS_call_funclet
        unchecked((byte)(0)), // INS_drop
        unchecked((byte)(0)), // INS_try_table
        unchecked((byte)(0)), // INS_local_get
        unchecked((byte)(0)), // INS_local_set
        unchecked((byte)(0)), // INS_local_tee
        unchecked((byte)(0)), // INS_global_get
        unchecked((byte)(0)), // INS_global_set
        unchecked((byte)(0)), // INS_i32_load
        unchecked((byte)(0)), // INS_i64_load
        unchecked((byte)(0)), // INS_f32_load
        unchecked((byte)(0)), // INS_f64_load
        unchecked((byte)(0)), // INS_i32_load8_s
        unchecked((byte)(0)), // INS_i32_load8_u
        unchecked((byte)(0)), // INS_i32_load16_s
        unchecked((byte)(0)), // INS_i32_load16_u
        unchecked((byte)(0)), // INS_i64_load8_s
        unchecked((byte)(0)), // INS_i64_load8_u
        unchecked((byte)(0)), // INS_i64_load16_s
        unchecked((byte)(0)), // INS_i64_load16_u
        unchecked((byte)(0)), // INS_i64_load32_s
        unchecked((byte)(0)), // INS_i64_load32_u
        unchecked((byte)(0)), // INS_i32_store
        unchecked((byte)(0)), // INS_i64_store
        unchecked((byte)(0)), // INS_f32_store
        unchecked((byte)(0)), // INS_f64_store
        unchecked((byte)(0)), // INS_i32_store8
        unchecked((byte)(0)), // INS_i32_store16
        unchecked((byte)(0)), // INS_i32_const
        unchecked((byte)(0)), // INS_i32_const_address
        unchecked((byte)(0)), // INS_i32_const_funcptr
        unchecked((byte)(0)), // INS_i32_const_funcletptr
        unchecked((byte)(0)), // INS_i32_const_dataoffs
        unchecked((byte)(0)), // INS_i64_const
        unchecked((byte)(0)), // INS_f32_const
        unchecked((byte)(0)), // INS_f64_const
        unchecked((byte)(0)), // INS_i32_eqz
        unchecked((byte)(0)), // INS_i32_eq
        unchecked((byte)(0)), // INS_i32_ne
        unchecked((byte)(0)), // INS_i32_lt_s
        unchecked((byte)(0)), // INS_i32_lt_u
        unchecked((byte)(0)), // INS_i32_gt_s
        unchecked((byte)(0)), // INS_i32_gt_u
        unchecked((byte)(0)), // INS_i32_le_s
        unchecked((byte)(0)), // INS_i32_le_u
        unchecked((byte)(0)), // INS_i32_ge_s
        unchecked((byte)(0)), // INS_i32_ge_u
        unchecked((byte)(0)), // INS_i64_eqz
        unchecked((byte)(0)), // INS_i64_eq
        unchecked((byte)(0)), // INS_i64_ne
        unchecked((byte)(0)), // INS_i64_lt_s
        unchecked((byte)(0)), // INS_i64_lt_u
        unchecked((byte)(0)), // INS_i64_gt_s
        unchecked((byte)(0)), // INS_i64_gt_u
        unchecked((byte)(0)), // INS_i64_le_s
        unchecked((byte)(0)), // INS_i64_le_u
        unchecked((byte)(0)), // INS_i64_ge_s
        unchecked((byte)(0)), // INS_i64_ge_u
        unchecked((byte)(0)), // INS_f32_eq
        unchecked((byte)(0)), // INS_f32_ne
        unchecked((byte)(0)), // INS_f32_lt
        unchecked((byte)(0)), // INS_f32_gt
        unchecked((byte)(0)), // INS_f32_le
        unchecked((byte)(0)), // INS_f32_ge
        unchecked((byte)(0)), // INS_f64_eq
        unchecked((byte)(0)), // INS_f64_ne
        unchecked((byte)(0)), // INS_f64_lt
        unchecked((byte)(0)), // INS_f64_gt
        unchecked((byte)(0)), // INS_f64_le
        unchecked((byte)(0)), // INS_f64_ge
        unchecked((byte)(0)), // INS_i32_clz
        unchecked((byte)(0)), // INS_i32_ctz
        unchecked((byte)(0)), // INS_i32_popcnt
        unchecked((byte)(0)), // INS_i32_add
        unchecked((byte)(0)), // INS_i32_sub
        unchecked((byte)(0)), // INS_i32_mul
        unchecked((byte)(0)), // INS_i32_div_s
        unchecked((byte)(0)), // INS_i32_div_u
        unchecked((byte)(0)), // INS_i32_rem_s
        unchecked((byte)(0)), // INS_i32_rem_u
        unchecked((byte)(0)), // INS_i32_and
        unchecked((byte)(0)), // INS_i32_or
        unchecked((byte)(0)), // INS_i32_xor
        unchecked((byte)(0)), // INS_i32_shl
        unchecked((byte)(0)), // INS_i32_shr_s
        unchecked((byte)(0)), // INS_i32_shr_u
        unchecked((byte)(0)), // INS_i32_rotl
        unchecked((byte)(0)), // INS_i32_rotr
        unchecked((byte)(0)), // INS_i64_clz
        unchecked((byte)(0)), // INS_i64_ctz
        unchecked((byte)(0)), // INS_i64_popcnt
        unchecked((byte)(0)), // INS_i64_add
        unchecked((byte)(0)), // INS_i64_sub
        unchecked((byte)(0)), // INS_i64_mul
        unchecked((byte)(0)), // INS_i64_div_s
        unchecked((byte)(0)), // INS_i64_div_u
        unchecked((byte)(0)), // INS_i64_rem_s
        unchecked((byte)(0)), // INS_i64_rem_u
        unchecked((byte)(0)), // INS_i64_and
        unchecked((byte)(0)), // INS_i64_or
        unchecked((byte)(0)), // INS_i64_xor
        unchecked((byte)(0)), // INS_i64_shl
        unchecked((byte)(0)), // INS_i64_shr_s
        unchecked((byte)(0)), // INS_i64_shr_u
        unchecked((byte)(0)), // INS_i64_rotl
        unchecked((byte)(0)), // INS_i64_rotr
        unchecked((byte)(0)), // INS_f32_abs
        unchecked((byte)(0)), // INS_f32_neg
        unchecked((byte)(0)), // INS_f32_ceil
        unchecked((byte)(0)), // INS_f32_floor
        unchecked((byte)(0)), // INS_f32_trunc
        unchecked((byte)(0)), // INS_f32_nearest
        unchecked((byte)(0)), // INS_f32_sqrt
        unchecked((byte)(0)), // INS_f32_add
        unchecked((byte)(0)), // INS_f32_sub
        unchecked((byte)(0)), // INS_f32_mul
        unchecked((byte)(0)), // INS_f32_div
        unchecked((byte)(0)), // INS_f32_min
        unchecked((byte)(0)), // INS_f32_max
        unchecked((byte)(0)), // INS_f32_copysign
        unchecked((byte)(0)), // INS_f64_abs
        unchecked((byte)(0)), // INS_f64_neg
        unchecked((byte)(0)), // INS_f64_ceil
        unchecked((byte)(0)), // INS_f64_floor
        unchecked((byte)(0)), // INS_f64_trunc
        unchecked((byte)(0)), // INS_f64_nearest
        unchecked((byte)(0)), // INS_f64_sqrt
        unchecked((byte)(0)), // INS_f64_add
        unchecked((byte)(0)), // INS_f64_sub
        unchecked((byte)(0)), // INS_f64_mul
        unchecked((byte)(0)), // INS_f64_div
        unchecked((byte)(0)), // INS_f64_min
        unchecked((byte)(0)), // INS_f64_max
        unchecked((byte)(0)), // INS_f64_copysign
        unchecked((byte)(0)), // INS_i32_wrap_i64
        unchecked((byte)(0)), // INS_i32_trunc_s_f32
        unchecked((byte)(0)), // INS_i32_trunc_u_f32
        unchecked((byte)(0)), // INS_i32_trunc_s_f64
        unchecked((byte)(0)), // INS_i32_trunc_u_f64
        unchecked((byte)(0)), // INS_i64_extend_s_i32
        unchecked((byte)(0)), // INS_i64_extend_u_i32
        unchecked((byte)(0)), // INS_i64_trunc_s_f32
        unchecked((byte)(0)), // INS_i64_trunc_u_f32
        unchecked((byte)(0)), // INS_i64_trunc_s_f64
        unchecked((byte)(0)), // INS_i64_trunc_u_f64
        unchecked((byte)(0)), // INS_f32_convert_s_i32
        unchecked((byte)(0)), // INS_f32_convert_u_i32
        unchecked((byte)(0)), // INS_f32_convert_s_i64
        unchecked((byte)(0)), // INS_f32_convert_u_i64
        unchecked((byte)(0)), // INS_f32_demote_f64
        unchecked((byte)(0)), // INS_f64_convert_s_i32
        unchecked((byte)(0)), // INS_f64_convert_u_i32
        unchecked((byte)(0)), // INS_f64_convert_s_i64
        unchecked((byte)(0)), // INS_f64_convert_u_i64
        unchecked((byte)(0)), // INS_f64_promote_f32
        unchecked((byte)(0)), // INS_i32_reinterpret_f32
        unchecked((byte)(0)), // INS_i64_reinterpret_f64
        unchecked((byte)(0)), // INS_f32_reinterpret_i32
        unchecked((byte)(0)), // INS_f64_reinterpret_i64
        unchecked((byte)(0)), // INS_i32_extend8_s
        unchecked((byte)(0)), // INS_i32_extend16_s
        unchecked((byte)(0)), // INS_i64_extend8_s
        unchecked((byte)(0)), // INS_i64_extend16_s
        unchecked((byte)(0)), // INS_i64_extend32_s
        unchecked((byte)(0xFC)), // INS_i32_trunc_sat_f32_s
        unchecked((byte)(0xFC)), // INS_i32_trunc_sat_f32_u
        unchecked((byte)(0xFC)), // INS_i32_trunc_sat_f64_s
        unchecked((byte)(0xFC)), // INS_i32_trunc_sat_f64_u
        unchecked((byte)(0xFC)), // INS_i64_trunc_sat_f32_s
        unchecked((byte)(0xFC)), // INS_i64_trunc_sat_f32_u
        unchecked((byte)(0xFC)), // INS_i64_trunc_sat_f64_s
        unchecked((byte)(0xFC)), // INS_i64_trunc_sat_f64_u
        unchecked((byte)(0xFC)), // INS_memory_copy
        unchecked((byte)(0xFC)), // INS_memory_fill
        unchecked((byte)(0xFD)), // INS_v128_load
        unchecked((byte)(0xFD)), // INS_v128_load8x8_s
        unchecked((byte)(0xFD)), // INS_v128_load8x8_u
        unchecked((byte)(0xFD)), // INS_v128_load16x4_s
        unchecked((byte)(0xFD)), // INS_v128_load16x4_u
        unchecked((byte)(0xFD)), // INS_v128_load32x2_s
        unchecked((byte)(0xFD)), // INS_v128_load32x2_u
        unchecked((byte)(0xFD)), // INS_v128_load8_splat
        unchecked((byte)(0xFD)), // INS_v128_load16_splat
        unchecked((byte)(0xFD)), // INS_v128_load32_splat
        unchecked((byte)(0xFD)), // INS_v128_load64_splat
        unchecked((byte)(0xFD)), // INS_v128_store
        unchecked((byte)(0xFD)), // INS_v128_const
        unchecked((byte)(0xFD)), // INS_i8x16_shuffle
        unchecked((byte)(0xFD)), // INS_i8x16_swizzle
        unchecked((byte)(0xFD)), // INS_i8x16_splat
        unchecked((byte)(0xFD)), // INS_i16x8_splat
        unchecked((byte)(0xFD)), // INS_i32x4_splat
        unchecked((byte)(0xFD)), // INS_i64x2_splat
        unchecked((byte)(0xFD)), // INS_f32x4_splat
        unchecked((byte)(0xFD)), // INS_f64x2_splat
        unchecked((byte)(0xFD)), // INS_i8x16_extract_lane_s
        unchecked((byte)(0xFD)), // INS_i8x16_extract_lane_u
        unchecked((byte)(0xFD)), // INS_i8x16_replace_lane
        unchecked((byte)(0xFD)), // INS_i16x8_extract_lane_s
        unchecked((byte)(0xFD)), // INS_i16x8_extract_lane_u
        unchecked((byte)(0xFD)), // INS_i16x8_replace_lane
        unchecked((byte)(0xFD)), // INS_i32x4_extract_lane
        unchecked((byte)(0xFD)), // INS_i32x4_replace_lane
        unchecked((byte)(0xFD)), // INS_i64x2_extract_lane
        unchecked((byte)(0xFD)), // INS_i64x2_replace_lane
        unchecked((byte)(0xFD)), // INS_f32x4_extract_lane
        unchecked((byte)(0xFD)), // INS_f32x4_replace_lane
        unchecked((byte)(0xFD)), // INS_f64x2_extract_lane
        unchecked((byte)(0xFD)), // INS_f64x2_replace_lane
        unchecked((byte)(0xFD)), // INS_i8x16_eq
        unchecked((byte)(0xFD)), // INS_i8x16_ne
        unchecked((byte)(0xFD)), // INS_i8x16_lt_s
        unchecked((byte)(0xFD)), // INS_i8x16_lt_u
        unchecked((byte)(0xFD)), // INS_i8x16_gt_s
        unchecked((byte)(0xFD)), // INS_i8x16_gt_u
        unchecked((byte)(0xFD)), // INS_i8x16_le_s
        unchecked((byte)(0xFD)), // INS_i8x16_le_u
        unchecked((byte)(0xFD)), // INS_i8x16_ge_s
        unchecked((byte)(0xFD)), // INS_i8x16_ge_u
        unchecked((byte)(0xFD)), // INS_i16x8_eq
        unchecked((byte)(0xFD)), // INS_i16x8_ne
        unchecked((byte)(0xFD)), // INS_i16x8_lt_s
        unchecked((byte)(0xFD)), // INS_i16x8_lt_u
        unchecked((byte)(0xFD)), // INS_i16x8_gt_s
        unchecked((byte)(0xFD)), // INS_i16x8_gt_u
        unchecked((byte)(0xFD)), // INS_i16x8_le_s
        unchecked((byte)(0xFD)), // INS_i16x8_le_u
        unchecked((byte)(0xFD)), // INS_i16x8_ge_s
        unchecked((byte)(0xFD)), // INS_i16x8_ge_u
        unchecked((byte)(0xFD)), // INS_i32x4_eq
        unchecked((byte)(0xFD)), // INS_i32x4_ne
        unchecked((byte)(0xFD)), // INS_i32x4_lt_s
        unchecked((byte)(0xFD)), // INS_i32x4_lt_u
        unchecked((byte)(0xFD)), // INS_i32x4_gt_s
        unchecked((byte)(0xFD)), // INS_i32x4_gt_u
        unchecked((byte)(0xFD)), // INS_i32x4_le_s
        unchecked((byte)(0xFD)), // INS_i32x4_le_u
        unchecked((byte)(0xFD)), // INS_i32x4_ge_s
        unchecked((byte)(0xFD)), // INS_i32x4_ge_u
        unchecked((byte)(0xFD)), // INS_i64x2_eq
        unchecked((byte)(0xFD)), // INS_i64x2_ne
        unchecked((byte)(0xFD)), // INS_i64x2_lt_s
        unchecked((byte)(0xFD)), // INS_i64x2_gt_s
        unchecked((byte)(0xFD)), // INS_i64x2_le_s
        unchecked((byte)(0xFD)), // INS_i64x2_ge_s
        unchecked((byte)(0xFD)), // INS_f32x4_eq
        unchecked((byte)(0xFD)), // INS_f32x4_ne
        unchecked((byte)(0xFD)), // INS_f32x4_lt
        unchecked((byte)(0xFD)), // INS_f32x4_gt
        unchecked((byte)(0xFD)), // INS_f32x4_le
        unchecked((byte)(0xFD)), // INS_f32x4_ge
        unchecked((byte)(0xFD)), // INS_f64x2_eq
        unchecked((byte)(0xFD)), // INS_f64x2_ne
        unchecked((byte)(0xFD)), // INS_f64x2_lt
        unchecked((byte)(0xFD)), // INS_f64x2_gt
        unchecked((byte)(0xFD)), // INS_f64x2_le
        unchecked((byte)(0xFD)), // INS_f64x2_ge
        unchecked((byte)(0xFD)), // INS_v128_not
        unchecked((byte)(0xFD)), // INS_v128_and
        unchecked((byte)(0xFD)), // INS_v128_andnot
        unchecked((byte)(0xFD)), // INS_v128_or
        unchecked((byte)(0xFD)), // INS_v128_xor
        unchecked((byte)(0xFD)), // INS_v128_bitselect
        unchecked((byte)(0xFD)), // INS_v128_any_true
        unchecked((byte)(0xFD)), // INS_v128_load8_lane
        unchecked((byte)(0xFD)), // INS_v128_load16_lane
        unchecked((byte)(0xFD)), // INS_v128_load32_lane
        unchecked((byte)(0xFD)), // INS_v128_load64_lane
        unchecked((byte)(0xFD)), // INS_v128_store8_lane
        unchecked((byte)(0xFD)), // INS_v128_store16_lane
        unchecked((byte)(0xFD)), // INS_v128_store32_lane
        unchecked((byte)(0xFD)), // INS_v128_store64_lane
        unchecked((byte)(0xFD)), // INS_v128_load32_zero
        unchecked((byte)(0xFD)), // INS_v128_load64_zero
        unchecked((byte)(0xFD)), // INS_f32x4_demote_f64x2_zero
        unchecked((byte)(0xFD)), // INS_f64x2_promote_low_f32x4
        unchecked((byte)(0xFD)), // INS_i8x16_abs
        unchecked((byte)(0xFD)), // INS_i8x16_neg
        unchecked((byte)(0xFD)), // INS_i8x16_popcnt
        unchecked((byte)(0xFD)), // INS_i8x16_all_true
        unchecked((byte)(0xFD)), // INS_i8x16_bitmask
        unchecked((byte)(0xFD)), // INS_i8x16_narrow_i16x8_s
        unchecked((byte)(0xFD)), // INS_i8x16_narrow_i16x8_u
        unchecked((byte)(0xFD)), // INS_f32x4_ceil
        unchecked((byte)(0xFD)), // INS_f32x4_floor
        unchecked((byte)(0xFD)), // INS_f32x4_trunc
        unchecked((byte)(0xFD)), // INS_f32x4_nearest
        unchecked((byte)(0xFD)), // INS_i8x16_shl
        unchecked((byte)(0xFD)), // INS_i8x16_shr_s
        unchecked((byte)(0xFD)), // INS_i8x16_shr_u
        unchecked((byte)(0xFD)), // INS_i8x16_add
        unchecked((byte)(0xFD)), // INS_i8x16_add_sat_s
        unchecked((byte)(0xFD)), // INS_i8x16_add_sat_u
        unchecked((byte)(0xFD)), // INS_i8x16_sub
        unchecked((byte)(0xFD)), // INS_i8x16_sub_sat_s
        unchecked((byte)(0xFD)), // INS_i8x16_sub_sat_u
        unchecked((byte)(0xFD)), // INS_f64x2_ceil
        unchecked((byte)(0xFD)), // INS_f64x2_floor
        unchecked((byte)(0xFD)), // INS_i8x16_min_s
        unchecked((byte)(0xFD)), // INS_i8x16_min_u
        unchecked((byte)(0xFD)), // INS_i8x16_max_s
        unchecked((byte)(0xFD)), // INS_i8x16_max_u
        unchecked((byte)(0xFD)), // INS_f64x2_trunc
        unchecked((byte)(0xFD)), // INS_i8x16_avgr_u
        unchecked((byte)(0xFD)), // INS_i16x8_extadd_pairwise_s_i8x16
        unchecked((byte)(0xFD)), // INS_i16x8_extadd_pairwise_u_i8x16
        unchecked((byte)(0xFD)), // INS_i32x4_extadd_pairwise_s_i16x8
        unchecked((byte)(0xFD)), // INS_i32x4_extadd_pairwise_u_i16x8
        unchecked((byte)(0xFD)), // INS_i16x8_abs
        unchecked((byte)(0xFD)), // INS_i16x8_neg
        unchecked((byte)(0xFD)), // INS_i16x8_q15mulr_sat_s
        unchecked((byte)(0xFD)), // INS_i16x8_all_true
        unchecked((byte)(0xFD)), // INS_i16x8_bitmask
        unchecked((byte)(0xFD)), // INS_i16x8_narrow_i32x4_s
        unchecked((byte)(0xFD)), // INS_i16x8_narrow_i32x4_u
        unchecked((byte)(0xFD)), // INS_i16x8_extend_low_s_i8x16
        unchecked((byte)(0xFD)), // INS_i16x8_extend_high_s_i8x16
        unchecked((byte)(0xFD)), // INS_i16x8_extend_low_u_i8x16
        unchecked((byte)(0xFD)), // INS_i16x8_extend_high_u_i8x16
        unchecked((byte)(0xFD)), // INS_i16x8_shl
        unchecked((byte)(0xFD)), // INS_i16x8_shr_s
        unchecked((byte)(0xFD)), // INS_i16x8_shr_u
        unchecked((byte)(0xFD)), // INS_i16x8_add
        unchecked((byte)(0xFD)), // INS_i16x8_add_sat_s
        unchecked((byte)(0xFD)), // INS_i16x8_add_sat_u
        unchecked((byte)(0xFD)), // INS_i16x8_sub
        unchecked((byte)(0xFD)), // INS_i16x8_sub_sat_s
        unchecked((byte)(0xFD)), // INS_i16x8_sub_sat_u
        unchecked((byte)(0xFD)), // INS_f64x2_nearest
        unchecked((byte)(0xFD)), // INS_i16x8_mul
        unchecked((byte)(0xFD)), // INS_i16x8_min_s
        unchecked((byte)(0xFD)), // INS_i16x8_min_u
        unchecked((byte)(0xFD)), // INS_i16x8_max_s
        unchecked((byte)(0xFD)), // INS_i16x8_max_u
        unchecked((byte)(0xFD)), // INS_i16x8_avgr_u
        unchecked((byte)(0xFD)), // INS_i16x8_extmul_low_s_i8x16
        unchecked((byte)(0xFD)), // INS_i16x8_extmul_high_s_i8x16
        unchecked((byte)(0xFD)), // INS_i16x8_extmul_low_u_i8x16
        unchecked((byte)(0xFD)), // INS_i16x8_extmul_high_u_i8x16
        unchecked((byte)(0xFD)), // INS_i32x4_abs
        unchecked((byte)(0xFD)), // INS_i32x4_neg
        unchecked((byte)(0xFD)), // INS_i32x4_all_true
        unchecked((byte)(0xFD)), // INS_i32x4_bitmask
        unchecked((byte)(0xFD)), // INS_i32x4_extend_low_s_i16x8
        unchecked((byte)(0xFD)), // INS_i32x4_extend_high_s_i16x8
        unchecked((byte)(0xFD)), // INS_i32x4_extend_low_u_i16x8
        unchecked((byte)(0xFD)), // INS_i32x4_extend_high_u_i16x8
        unchecked((byte)(0xFD)), // INS_i32x4_shl
        unchecked((byte)(0xFD)), // INS_i32x4_shr_s
        unchecked((byte)(0xFD)), // INS_i32x4_shr_u
        unchecked((byte)(0xFD)), // INS_i32x4_add
        unchecked((byte)(0xFD)), // INS_i32x4_sub
        unchecked((byte)(0xFD)), // INS_i32x4_mul
        unchecked((byte)(0xFD)), // INS_i32x4_min_s
        unchecked((byte)(0xFD)), // INS_i32x4_min_u
        unchecked((byte)(0xFD)), // INS_i32x4_max_s
        unchecked((byte)(0xFD)), // INS_i32x4_max_u
        unchecked((byte)(0xFD)), // INS_i32x4_dot_i16x8_s
        unchecked((byte)(0xFD)), // INS_i32x4_extmul_low_s_i16x8
        unchecked((byte)(0xFD)), // INS_i32x4_extmul_high_s_i16x8
        unchecked((byte)(0xFD)), // INS_i32x4_extmul_low_u_i16x8
        unchecked((byte)(0xFD)), // INS_i32x4_extmul_high_u_i16x8
        unchecked((byte)(0xFD)), // INS_i64x2_abs
        unchecked((byte)(0xFD)), // INS_i64x2_neg
        unchecked((byte)(0xFD)), // INS_i64x2_all_true
        unchecked((byte)(0xFD)), // INS_i64x2_bitmask
        unchecked((byte)(0xFD)), // INS_i64x2_extend_low_s_i32x4
        unchecked((byte)(0xFD)), // INS_i64x2_extend_high_s_i32x4
        unchecked((byte)(0xFD)), // INS_i64x2_extend_low_u_i32x4
        unchecked((byte)(0xFD)), // INS_i64x2_extend_high_u_i32x4
        unchecked((byte)(0xFD)), // INS_i64x2_shl
        unchecked((byte)(0xFD)), // INS_i64x2_shr_s
        unchecked((byte)(0xFD)), // INS_i64x2_shr_u
        unchecked((byte)(0xFD)), // INS_i64x2_add
        unchecked((byte)(0xFD)), // INS_i64x2_sub
        unchecked((byte)(0xFD)), // INS_i64x2_mul
        unchecked((byte)(0xFD)), // INS_i64x2_extmul_low_s_i32x4
        unchecked((byte)(0xFD)), // INS_i64x2_extmul_high_s_i32x4
        unchecked((byte)(0xFD)), // INS_i64x2_extmul_low_u_i32x4
        unchecked((byte)(0xFD)), // INS_i64x2_extmul_high_u_i32x4
        unchecked((byte)(0xFD)), // INS_f32x4_abs
        unchecked((byte)(0xFD)), // INS_f32x4_neg
        unchecked((byte)(0xFD)), // INS_f32x4_sqrt
        unchecked((byte)(0xFD)), // INS_f32x4_add
        unchecked((byte)(0xFD)), // INS_f32x4_sub
        unchecked((byte)(0xFD)), // INS_f32x4_mul
        unchecked((byte)(0xFD)), // INS_f32x4_div
        unchecked((byte)(0xFD)), // INS_f32x4_min
        unchecked((byte)(0xFD)), // INS_f32x4_max
        unchecked((byte)(0xFD)), // INS_f32x4_pmin
        unchecked((byte)(0xFD)), // INS_f32x4_pmax
        unchecked((byte)(0xFD)), // INS_f64x2_abs
        unchecked((byte)(0xFD)), // INS_f64x2_neg
        unchecked((byte)(0xFD)), // INS_f64x2_sqrt
        unchecked((byte)(0xFD)), // INS_f64x2_add
        unchecked((byte)(0xFD)), // INS_f64x2_sub
        unchecked((byte)(0xFD)), // INS_f64x2_mul
        unchecked((byte)(0xFD)), // INS_f64x2_div
        unchecked((byte)(0xFD)), // INS_f64x2_min
        unchecked((byte)(0xFD)), // INS_f64x2_max
        unchecked((byte)(0xFD)), // INS_f64x2_pmin
        unchecked((byte)(0xFD)), // INS_f64x2_pmax
        unchecked((byte)(0xFD)), // INS_i32x4_trunc_sat_s_f32x4
        unchecked((byte)(0xFD)), // INS_i32x4_trunc_sat_u_f32x4
        unchecked((byte)(0xFD)), // INS_f32x4_convert_s_i32x4
        unchecked((byte)(0xFD)), // INS_f32x4_convert_u_i32x4
        unchecked((byte)(0xFD)), // INS_i32x4_trunc_sat_s_f64x2_zero
        unchecked((byte)(0xFD)), // INS_i32x4_trunc_sat_u_f64x2_zero
        unchecked((byte)(0xFD)), // INS_f64x2_convert_low_s_i32x4
        unchecked((byte)(0xFD)), // INS_f64x2_convert_low_u_i32x4
    ];

    private static ReadOnlySpan<insFormat> s_wasmInstructionFormats => [
        insFormat.IF_NONE, // INS_invalid
        insFormat.IF_OPCODE, // INS_unreachable
        insFormat.IF_RAW_ULEB128, // INS_label
        insFormat.IF_CATCH_DECL, // INS_catch_ref
        insFormat.IF_RAW_ULEB128, // INS_local_cnt
        insFormat.IF_LOCAL_DECL, // INS_local_decl
        insFormat.IF_CODE_SIZE, // INS_code_size
        insFormat.IF_OPCODE, // INS_nop
        insFormat.IF_BLOCK, // INS_block
        insFormat.IF_BLOCK, // INS_loop
        insFormat.IF_BLOCK, // INS_if
        insFormat.IF_OPCODE, // INS_else
        insFormat.IF_OPCODE, // INS_throw_ref
        insFormat.IF_OPCODE, // INS_end
        insFormat.IF_ULEB128, // INS_br
        insFormat.IF_ULEB128, // INS_br_if
        insFormat.IF_ULEB128, // INS_br_table
        insFormat.IF_OPCODE, // INS_return
        insFormat.IF_FUNCIDX, // INS_call
        insFormat.IF_CALL_INDIRECT, // INS_call_indirect
        insFormat.IF_FUNCIDX, // INS_return_call
        insFormat.IF_CALL_INDIRECT, // INS_return_call_indirect
        insFormat.IF_FUNCLETIDX, // INS_call_funclet
        insFormat.IF_OPCODE, // INS_drop
        insFormat.IF_TRY_TABLE, // INS_try_table
        insFormat.IF_ULEB128, // INS_local_get
        insFormat.IF_ULEB128, // INS_local_set
        insFormat.IF_ULEB128, // INS_local_tee
        insFormat.IF_GLOBALIDX, // INS_global_get
        insFormat.IF_GLOBALIDX, // INS_global_set
        insFormat.IF_MEMARG, // INS_i32_load
        insFormat.IF_MEMARG, // INS_i64_load
        insFormat.IF_MEMARG, // INS_f32_load
        insFormat.IF_MEMARG, // INS_f64_load
        insFormat.IF_MEMARG, // INS_i32_load8_s
        insFormat.IF_MEMARG, // INS_i32_load8_u
        insFormat.IF_MEMARG, // INS_i32_load16_s
        insFormat.IF_MEMARG, // INS_i32_load16_u
        insFormat.IF_MEMARG, // INS_i64_load8_s
        insFormat.IF_MEMARG, // INS_i64_load8_u
        insFormat.IF_MEMARG, // INS_i64_load16_s
        insFormat.IF_MEMARG, // INS_i64_load16_u
        insFormat.IF_MEMARG, // INS_i64_load32_s
        insFormat.IF_MEMARG, // INS_i64_load32_u
        insFormat.IF_MEMARG, // INS_i32_store
        insFormat.IF_MEMARG, // INS_i64_store
        insFormat.IF_MEMARG, // INS_f32_store
        insFormat.IF_MEMARG, // INS_f64_store
        insFormat.IF_MEMARG, // INS_i32_store8
        insFormat.IF_MEMARG, // INS_i32_store16
        insFormat.IF_SLEB128, // INS_i32_const
        insFormat.IF_MEMADDR, // INS_i32_const_address
        insFormat.IF_FUNCPTR, // INS_i32_const_funcptr
        insFormat.IF_FUNCLETPTR, // INS_i32_const_funcletptr
        insFormat.IF_DATAOFFS, // INS_i32_const_dataoffs
        insFormat.IF_SLEB128, // INS_i64_const
        insFormat.IF_F32, // INS_f32_const
        insFormat.IF_F64, // INS_f64_const
        insFormat.IF_OPCODE, // INS_i32_eqz
        insFormat.IF_OPCODE, // INS_i32_eq
        insFormat.IF_OPCODE, // INS_i32_ne
        insFormat.IF_OPCODE, // INS_i32_lt_s
        insFormat.IF_OPCODE, // INS_i32_lt_u
        insFormat.IF_OPCODE, // INS_i32_gt_s
        insFormat.IF_OPCODE, // INS_i32_gt_u
        insFormat.IF_OPCODE, // INS_i32_le_s
        insFormat.IF_OPCODE, // INS_i32_le_u
        insFormat.IF_OPCODE, // INS_i32_ge_s
        insFormat.IF_OPCODE, // INS_i32_ge_u
        insFormat.IF_OPCODE, // INS_i64_eqz
        insFormat.IF_OPCODE, // INS_i64_eq
        insFormat.IF_OPCODE, // INS_i64_ne
        insFormat.IF_OPCODE, // INS_i64_lt_s
        insFormat.IF_OPCODE, // INS_i64_lt_u
        insFormat.IF_OPCODE, // INS_i64_gt_s
        insFormat.IF_OPCODE, // INS_i64_gt_u
        insFormat.IF_OPCODE, // INS_i64_le_s
        insFormat.IF_OPCODE, // INS_i64_le_u
        insFormat.IF_OPCODE, // INS_i64_ge_s
        insFormat.IF_OPCODE, // INS_i64_ge_u
        insFormat.IF_OPCODE, // INS_f32_eq
        insFormat.IF_OPCODE, // INS_f32_ne
        insFormat.IF_OPCODE, // INS_f32_lt
        insFormat.IF_OPCODE, // INS_f32_gt
        insFormat.IF_OPCODE, // INS_f32_le
        insFormat.IF_OPCODE, // INS_f32_ge
        insFormat.IF_OPCODE, // INS_f64_eq
        insFormat.IF_OPCODE, // INS_f64_ne
        insFormat.IF_OPCODE, // INS_f64_lt
        insFormat.IF_OPCODE, // INS_f64_gt
        insFormat.IF_OPCODE, // INS_f64_le
        insFormat.IF_OPCODE, // INS_f64_ge
        insFormat.IF_OPCODE, // INS_i32_clz
        insFormat.IF_OPCODE, // INS_i32_ctz
        insFormat.IF_OPCODE, // INS_i32_popcnt
        insFormat.IF_OPCODE, // INS_i32_add
        insFormat.IF_OPCODE, // INS_i32_sub
        insFormat.IF_OPCODE, // INS_i32_mul
        insFormat.IF_OPCODE, // INS_i32_div_s
        insFormat.IF_OPCODE, // INS_i32_div_u
        insFormat.IF_OPCODE, // INS_i32_rem_s
        insFormat.IF_OPCODE, // INS_i32_rem_u
        insFormat.IF_OPCODE, // INS_i32_and
        insFormat.IF_OPCODE, // INS_i32_or
        insFormat.IF_OPCODE, // INS_i32_xor
        insFormat.IF_OPCODE, // INS_i32_shl
        insFormat.IF_OPCODE, // INS_i32_shr_s
        insFormat.IF_OPCODE, // INS_i32_shr_u
        insFormat.IF_OPCODE, // INS_i32_rotl
        insFormat.IF_OPCODE, // INS_i32_rotr
        insFormat.IF_OPCODE, // INS_i64_clz
        insFormat.IF_OPCODE, // INS_i64_ctz
        insFormat.IF_OPCODE, // INS_i64_popcnt
        insFormat.IF_OPCODE, // INS_i64_add
        insFormat.IF_OPCODE, // INS_i64_sub
        insFormat.IF_OPCODE, // INS_i64_mul
        insFormat.IF_OPCODE, // INS_i64_div_s
        insFormat.IF_OPCODE, // INS_i64_div_u
        insFormat.IF_OPCODE, // INS_i64_rem_s
        insFormat.IF_OPCODE, // INS_i64_rem_u
        insFormat.IF_OPCODE, // INS_i64_and
        insFormat.IF_OPCODE, // INS_i64_or
        insFormat.IF_OPCODE, // INS_i64_xor
        insFormat.IF_OPCODE, // INS_i64_shl
        insFormat.IF_OPCODE, // INS_i64_shr_s
        insFormat.IF_OPCODE, // INS_i64_shr_u
        insFormat.IF_OPCODE, // INS_i64_rotl
        insFormat.IF_OPCODE, // INS_i64_rotr
        insFormat.IF_OPCODE, // INS_f32_abs
        insFormat.IF_OPCODE, // INS_f32_neg
        insFormat.IF_OPCODE, // INS_f32_ceil
        insFormat.IF_OPCODE, // INS_f32_floor
        insFormat.IF_OPCODE, // INS_f32_trunc
        insFormat.IF_OPCODE, // INS_f32_nearest
        insFormat.IF_OPCODE, // INS_f32_sqrt
        insFormat.IF_OPCODE, // INS_f32_add
        insFormat.IF_OPCODE, // INS_f32_sub
        insFormat.IF_OPCODE, // INS_f32_mul
        insFormat.IF_OPCODE, // INS_f32_div
        insFormat.IF_OPCODE, // INS_f32_min
        insFormat.IF_OPCODE, // INS_f32_max
        insFormat.IF_OPCODE, // INS_f32_copysign
        insFormat.IF_OPCODE, // INS_f64_abs
        insFormat.IF_OPCODE, // INS_f64_neg
        insFormat.IF_OPCODE, // INS_f64_ceil
        insFormat.IF_OPCODE, // INS_f64_floor
        insFormat.IF_OPCODE, // INS_f64_trunc
        insFormat.IF_OPCODE, // INS_f64_nearest
        insFormat.IF_OPCODE, // INS_f64_sqrt
        insFormat.IF_OPCODE, // INS_f64_add
        insFormat.IF_OPCODE, // INS_f64_sub
        insFormat.IF_OPCODE, // INS_f64_mul
        insFormat.IF_OPCODE, // INS_f64_div
        insFormat.IF_OPCODE, // INS_f64_min
        insFormat.IF_OPCODE, // INS_f64_max
        insFormat.IF_OPCODE, // INS_f64_copysign
        insFormat.IF_OPCODE, // INS_i32_wrap_i64
        insFormat.IF_OPCODE, // INS_i32_trunc_s_f32
        insFormat.IF_OPCODE, // INS_i32_trunc_u_f32
        insFormat.IF_OPCODE, // INS_i32_trunc_s_f64
        insFormat.IF_OPCODE, // INS_i32_trunc_u_f64
        insFormat.IF_OPCODE, // INS_i64_extend_s_i32
        insFormat.IF_OPCODE, // INS_i64_extend_u_i32
        insFormat.IF_OPCODE, // INS_i64_trunc_s_f32
        insFormat.IF_OPCODE, // INS_i64_trunc_u_f32
        insFormat.IF_OPCODE, // INS_i64_trunc_s_f64
        insFormat.IF_OPCODE, // INS_i64_trunc_u_f64
        insFormat.IF_OPCODE, // INS_f32_convert_s_i32
        insFormat.IF_OPCODE, // INS_f32_convert_u_i32
        insFormat.IF_OPCODE, // INS_f32_convert_s_i64
        insFormat.IF_OPCODE, // INS_f32_convert_u_i64
        insFormat.IF_OPCODE, // INS_f32_demote_f64
        insFormat.IF_OPCODE, // INS_f64_convert_s_i32
        insFormat.IF_OPCODE, // INS_f64_convert_u_i32
        insFormat.IF_OPCODE, // INS_f64_convert_s_i64
        insFormat.IF_OPCODE, // INS_f64_convert_u_i64
        insFormat.IF_OPCODE, // INS_f64_promote_f32
        insFormat.IF_OPCODE, // INS_i32_reinterpret_f32
        insFormat.IF_OPCODE, // INS_i64_reinterpret_f64
        insFormat.IF_OPCODE, // INS_f32_reinterpret_i32
        insFormat.IF_OPCODE, // INS_f64_reinterpret_i64
        insFormat.IF_OPCODE, // INS_i32_extend8_s
        insFormat.IF_OPCODE, // INS_i32_extend16_s
        insFormat.IF_OPCODE, // INS_i64_extend8_s
        insFormat.IF_OPCODE, // INS_i64_extend16_s
        insFormat.IF_OPCODE, // INS_i64_extend32_s
        insFormat.IF_OPCODE, // INS_i32_trunc_sat_f32_s
        insFormat.IF_OPCODE, // INS_i32_trunc_sat_f32_u
        insFormat.IF_OPCODE, // INS_i32_trunc_sat_f64_s
        insFormat.IF_OPCODE, // INS_i32_trunc_sat_f64_u
        insFormat.IF_OPCODE, // INS_i64_trunc_sat_f32_s
        insFormat.IF_OPCODE, // INS_i64_trunc_sat_f32_u
        insFormat.IF_OPCODE, // INS_i64_trunc_sat_f64_s
        insFormat.IF_OPCODE, // INS_i64_trunc_sat_f64_u
        insFormat.IF_MEMIDX_MEMIDX, // INS_memory_copy
        insFormat.IF_ULEB128, // INS_memory_fill
        insFormat.IF_MEMARG, // INS_v128_load
        insFormat.IF_MEMARG, // INS_v128_load8x8_s
        insFormat.IF_MEMARG, // INS_v128_load8x8_u
        insFormat.IF_MEMARG, // INS_v128_load16x4_s
        insFormat.IF_MEMARG, // INS_v128_load16x4_u
        insFormat.IF_MEMARG, // INS_v128_load32x2_s
        insFormat.IF_MEMARG, // INS_v128_load32x2_u
        insFormat.IF_MEMARG, // INS_v128_load8_splat
        insFormat.IF_MEMARG, // INS_v128_load16_splat
        insFormat.IF_MEMARG, // INS_v128_load32_splat
        insFormat.IF_MEMARG, // INS_v128_load64_splat
        insFormat.IF_MEMARG, // INS_v128_store
        insFormat.IF_V128, // INS_v128_const
        insFormat.IF_V128, // INS_i8x16_shuffle
        insFormat.IF_OPCODE, // INS_i8x16_swizzle
        insFormat.IF_OPCODE, // INS_i8x16_splat
        insFormat.IF_OPCODE, // INS_i16x8_splat
        insFormat.IF_OPCODE, // INS_i32x4_splat
        insFormat.IF_OPCODE, // INS_i64x2_splat
        insFormat.IF_OPCODE, // INS_f32x4_splat
        insFormat.IF_OPCODE, // INS_f64x2_splat
        insFormat.IF_LANE, // INS_i8x16_extract_lane_s
        insFormat.IF_LANE, // INS_i8x16_extract_lane_u
        insFormat.IF_LANE, // INS_i8x16_replace_lane
        insFormat.IF_LANE, // INS_i16x8_extract_lane_s
        insFormat.IF_LANE, // INS_i16x8_extract_lane_u
        insFormat.IF_LANE, // INS_i16x8_replace_lane
        insFormat.IF_LANE, // INS_i32x4_extract_lane
        insFormat.IF_LANE, // INS_i32x4_replace_lane
        insFormat.IF_LANE, // INS_i64x2_extract_lane
        insFormat.IF_LANE, // INS_i64x2_replace_lane
        insFormat.IF_LANE, // INS_f32x4_extract_lane
        insFormat.IF_LANE, // INS_f32x4_replace_lane
        insFormat.IF_LANE, // INS_f64x2_extract_lane
        insFormat.IF_LANE, // INS_f64x2_replace_lane
        insFormat.IF_OPCODE, // INS_i8x16_eq
        insFormat.IF_OPCODE, // INS_i8x16_ne
        insFormat.IF_OPCODE, // INS_i8x16_lt_s
        insFormat.IF_OPCODE, // INS_i8x16_lt_u
        insFormat.IF_OPCODE, // INS_i8x16_gt_s
        insFormat.IF_OPCODE, // INS_i8x16_gt_u
        insFormat.IF_OPCODE, // INS_i8x16_le_s
        insFormat.IF_OPCODE, // INS_i8x16_le_u
        insFormat.IF_OPCODE, // INS_i8x16_ge_s
        insFormat.IF_OPCODE, // INS_i8x16_ge_u
        insFormat.IF_OPCODE, // INS_i16x8_eq
        insFormat.IF_OPCODE, // INS_i16x8_ne
        insFormat.IF_OPCODE, // INS_i16x8_lt_s
        insFormat.IF_OPCODE, // INS_i16x8_lt_u
        insFormat.IF_OPCODE, // INS_i16x8_gt_s
        insFormat.IF_OPCODE, // INS_i16x8_gt_u
        insFormat.IF_OPCODE, // INS_i16x8_le_s
        insFormat.IF_OPCODE, // INS_i16x8_le_u
        insFormat.IF_OPCODE, // INS_i16x8_ge_s
        insFormat.IF_OPCODE, // INS_i16x8_ge_u
        insFormat.IF_OPCODE, // INS_i32x4_eq
        insFormat.IF_OPCODE, // INS_i32x4_ne
        insFormat.IF_OPCODE, // INS_i32x4_lt_s
        insFormat.IF_OPCODE, // INS_i32x4_lt_u
        insFormat.IF_OPCODE, // INS_i32x4_gt_s
        insFormat.IF_OPCODE, // INS_i32x4_gt_u
        insFormat.IF_OPCODE, // INS_i32x4_le_s
        insFormat.IF_OPCODE, // INS_i32x4_le_u
        insFormat.IF_OPCODE, // INS_i32x4_ge_s
        insFormat.IF_OPCODE, // INS_i32x4_ge_u
        insFormat.IF_OPCODE, // INS_i64x2_eq
        insFormat.IF_OPCODE, // INS_i64x2_ne
        insFormat.IF_OPCODE, // INS_i64x2_lt_s
        insFormat.IF_OPCODE, // INS_i64x2_gt_s
        insFormat.IF_OPCODE, // INS_i64x2_le_s
        insFormat.IF_OPCODE, // INS_i64x2_ge_s
        insFormat.IF_OPCODE, // INS_f32x4_eq
        insFormat.IF_OPCODE, // INS_f32x4_ne
        insFormat.IF_OPCODE, // INS_f32x4_lt
        insFormat.IF_OPCODE, // INS_f32x4_gt
        insFormat.IF_OPCODE, // INS_f32x4_le
        insFormat.IF_OPCODE, // INS_f32x4_ge
        insFormat.IF_OPCODE, // INS_f64x2_eq
        insFormat.IF_OPCODE, // INS_f64x2_ne
        insFormat.IF_OPCODE, // INS_f64x2_lt
        insFormat.IF_OPCODE, // INS_f64x2_gt
        insFormat.IF_OPCODE, // INS_f64x2_le
        insFormat.IF_OPCODE, // INS_f64x2_ge
        insFormat.IF_OPCODE, // INS_v128_not
        insFormat.IF_OPCODE, // INS_v128_and
        insFormat.IF_OPCODE, // INS_v128_andnot
        insFormat.IF_OPCODE, // INS_v128_or
        insFormat.IF_OPCODE, // INS_v128_xor
        insFormat.IF_OPCODE, // INS_v128_bitselect
        insFormat.IF_OPCODE, // INS_v128_any_true
        insFormat.IF_MEMARG_LANE, // INS_v128_load8_lane
        insFormat.IF_MEMARG_LANE, // INS_v128_load16_lane
        insFormat.IF_MEMARG_LANE, // INS_v128_load32_lane
        insFormat.IF_MEMARG_LANE, // INS_v128_load64_lane
        insFormat.IF_MEMARG_LANE, // INS_v128_store8_lane
        insFormat.IF_MEMARG_LANE, // INS_v128_store16_lane
        insFormat.IF_MEMARG_LANE, // INS_v128_store32_lane
        insFormat.IF_MEMARG_LANE, // INS_v128_store64_lane
        insFormat.IF_MEMARG, // INS_v128_load32_zero
        insFormat.IF_MEMARG, // INS_v128_load64_zero
        insFormat.IF_OPCODE, // INS_f32x4_demote_f64x2_zero
        insFormat.IF_OPCODE, // INS_f64x2_promote_low_f32x4
        insFormat.IF_OPCODE, // INS_i8x16_abs
        insFormat.IF_OPCODE, // INS_i8x16_neg
        insFormat.IF_OPCODE, // INS_i8x16_popcnt
        insFormat.IF_OPCODE, // INS_i8x16_all_true
        insFormat.IF_OPCODE, // INS_i8x16_bitmask
        insFormat.IF_OPCODE, // INS_i8x16_narrow_i16x8_s
        insFormat.IF_OPCODE, // INS_i8x16_narrow_i16x8_u
        insFormat.IF_OPCODE, // INS_f32x4_ceil
        insFormat.IF_OPCODE, // INS_f32x4_floor
        insFormat.IF_OPCODE, // INS_f32x4_trunc
        insFormat.IF_OPCODE, // INS_f32x4_nearest
        insFormat.IF_OPCODE, // INS_i8x16_shl
        insFormat.IF_OPCODE, // INS_i8x16_shr_s
        insFormat.IF_OPCODE, // INS_i8x16_shr_u
        insFormat.IF_OPCODE, // INS_i8x16_add
        insFormat.IF_OPCODE, // INS_i8x16_add_sat_s
        insFormat.IF_OPCODE, // INS_i8x16_add_sat_u
        insFormat.IF_OPCODE, // INS_i8x16_sub
        insFormat.IF_OPCODE, // INS_i8x16_sub_sat_s
        insFormat.IF_OPCODE, // INS_i8x16_sub_sat_u
        insFormat.IF_OPCODE, // INS_f64x2_ceil
        insFormat.IF_OPCODE, // INS_f64x2_floor
        insFormat.IF_OPCODE, // INS_i8x16_min_s
        insFormat.IF_OPCODE, // INS_i8x16_min_u
        insFormat.IF_OPCODE, // INS_i8x16_max_s
        insFormat.IF_OPCODE, // INS_i8x16_max_u
        insFormat.IF_OPCODE, // INS_f64x2_trunc
        insFormat.IF_OPCODE, // INS_i8x16_avgr_u
        insFormat.IF_OPCODE, // INS_i16x8_extadd_pairwise_s_i8x16
        insFormat.IF_OPCODE, // INS_i16x8_extadd_pairwise_u_i8x16
        insFormat.IF_OPCODE, // INS_i32x4_extadd_pairwise_s_i16x8
        insFormat.IF_OPCODE, // INS_i32x4_extadd_pairwise_u_i16x8
        insFormat.IF_OPCODE, // INS_i16x8_abs
        insFormat.IF_OPCODE, // INS_i16x8_neg
        insFormat.IF_OPCODE, // INS_i16x8_q15mulr_sat_s
        insFormat.IF_OPCODE, // INS_i16x8_all_true
        insFormat.IF_OPCODE, // INS_i16x8_bitmask
        insFormat.IF_OPCODE, // INS_i16x8_narrow_i32x4_s
        insFormat.IF_OPCODE, // INS_i16x8_narrow_i32x4_u
        insFormat.IF_OPCODE, // INS_i16x8_extend_low_s_i8x16
        insFormat.IF_OPCODE, // INS_i16x8_extend_high_s_i8x16
        insFormat.IF_OPCODE, // INS_i16x8_extend_low_u_i8x16
        insFormat.IF_OPCODE, // INS_i16x8_extend_high_u_i8x16
        insFormat.IF_OPCODE, // INS_i16x8_shl
        insFormat.IF_OPCODE, // INS_i16x8_shr_s
        insFormat.IF_OPCODE, // INS_i16x8_shr_u
        insFormat.IF_OPCODE, // INS_i16x8_add
        insFormat.IF_OPCODE, // INS_i16x8_add_sat_s
        insFormat.IF_OPCODE, // INS_i16x8_add_sat_u
        insFormat.IF_OPCODE, // INS_i16x8_sub
        insFormat.IF_OPCODE, // INS_i16x8_sub_sat_s
        insFormat.IF_OPCODE, // INS_i16x8_sub_sat_u
        insFormat.IF_OPCODE, // INS_f64x2_nearest
        insFormat.IF_OPCODE, // INS_i16x8_mul
        insFormat.IF_OPCODE, // INS_i16x8_min_s
        insFormat.IF_OPCODE, // INS_i16x8_min_u
        insFormat.IF_OPCODE, // INS_i16x8_max_s
        insFormat.IF_OPCODE, // INS_i16x8_max_u
        insFormat.IF_OPCODE, // INS_i16x8_avgr_u
        insFormat.IF_OPCODE, // INS_i16x8_extmul_low_s_i8x16
        insFormat.IF_OPCODE, // INS_i16x8_extmul_high_s_i8x16
        insFormat.IF_OPCODE, // INS_i16x8_extmul_low_u_i8x16
        insFormat.IF_OPCODE, // INS_i16x8_extmul_high_u_i8x16
        insFormat.IF_OPCODE, // INS_i32x4_abs
        insFormat.IF_OPCODE, // INS_i32x4_neg
        insFormat.IF_OPCODE, // INS_i32x4_all_true
        insFormat.IF_OPCODE, // INS_i32x4_bitmask
        insFormat.IF_OPCODE, // INS_i32x4_extend_low_s_i16x8
        insFormat.IF_OPCODE, // INS_i32x4_extend_high_s_i16x8
        insFormat.IF_OPCODE, // INS_i32x4_extend_low_u_i16x8
        insFormat.IF_OPCODE, // INS_i32x4_extend_high_u_i16x8
        insFormat.IF_OPCODE, // INS_i32x4_shl
        insFormat.IF_OPCODE, // INS_i32x4_shr_s
        insFormat.IF_OPCODE, // INS_i32x4_shr_u
        insFormat.IF_OPCODE, // INS_i32x4_add
        insFormat.IF_OPCODE, // INS_i32x4_sub
        insFormat.IF_OPCODE, // INS_i32x4_mul
        insFormat.IF_OPCODE, // INS_i32x4_min_s
        insFormat.IF_OPCODE, // INS_i32x4_min_u
        insFormat.IF_OPCODE, // INS_i32x4_max_s
        insFormat.IF_OPCODE, // INS_i32x4_max_u
        insFormat.IF_OPCODE, // INS_i32x4_dot_i16x8_s
        insFormat.IF_OPCODE, // INS_i32x4_extmul_low_s_i16x8
        insFormat.IF_OPCODE, // INS_i32x4_extmul_high_s_i16x8
        insFormat.IF_OPCODE, // INS_i32x4_extmul_low_u_i16x8
        insFormat.IF_OPCODE, // INS_i32x4_extmul_high_u_i16x8
        insFormat.IF_OPCODE, // INS_i64x2_abs
        insFormat.IF_OPCODE, // INS_i64x2_neg
        insFormat.IF_OPCODE, // INS_i64x2_all_true
        insFormat.IF_OPCODE, // INS_i64x2_bitmask
        insFormat.IF_OPCODE, // INS_i64x2_extend_low_s_i32x4
        insFormat.IF_OPCODE, // INS_i64x2_extend_high_s_i32x4
        insFormat.IF_OPCODE, // INS_i64x2_extend_low_u_i32x4
        insFormat.IF_OPCODE, // INS_i64x2_extend_high_u_i32x4
        insFormat.IF_OPCODE, // INS_i64x2_shl
        insFormat.IF_OPCODE, // INS_i64x2_shr_s
        insFormat.IF_OPCODE, // INS_i64x2_shr_u
        insFormat.IF_OPCODE, // INS_i64x2_add
        insFormat.IF_OPCODE, // INS_i64x2_sub
        insFormat.IF_OPCODE, // INS_i64x2_mul
        insFormat.IF_OPCODE, // INS_i64x2_extmul_low_s_i32x4
        insFormat.IF_OPCODE, // INS_i64x2_extmul_high_s_i32x4
        insFormat.IF_OPCODE, // INS_i64x2_extmul_low_u_i32x4
        insFormat.IF_OPCODE, // INS_i64x2_extmul_high_u_i32x4
        insFormat.IF_OPCODE, // INS_f32x4_abs
        insFormat.IF_OPCODE, // INS_f32x4_neg
        insFormat.IF_OPCODE, // INS_f32x4_sqrt
        insFormat.IF_OPCODE, // INS_f32x4_add
        insFormat.IF_OPCODE, // INS_f32x4_sub
        insFormat.IF_OPCODE, // INS_f32x4_mul
        insFormat.IF_OPCODE, // INS_f32x4_div
        insFormat.IF_OPCODE, // INS_f32x4_min
        insFormat.IF_OPCODE, // INS_f32x4_max
        insFormat.IF_OPCODE, // INS_f32x4_pmin
        insFormat.IF_OPCODE, // INS_f32x4_pmax
        insFormat.IF_OPCODE, // INS_f64x2_abs
        insFormat.IF_OPCODE, // INS_f64x2_neg
        insFormat.IF_OPCODE, // INS_f64x2_sqrt
        insFormat.IF_OPCODE, // INS_f64x2_add
        insFormat.IF_OPCODE, // INS_f64x2_sub
        insFormat.IF_OPCODE, // INS_f64x2_mul
        insFormat.IF_OPCODE, // INS_f64x2_div
        insFormat.IF_OPCODE, // INS_f64x2_min
        insFormat.IF_OPCODE, // INS_f64x2_max
        insFormat.IF_OPCODE, // INS_f64x2_pmin
        insFormat.IF_OPCODE, // INS_f64x2_pmax
        insFormat.IF_OPCODE, // INS_i32x4_trunc_sat_s_f32x4
        insFormat.IF_OPCODE, // INS_i32x4_trunc_sat_u_f32x4
        insFormat.IF_OPCODE, // INS_f32x4_convert_s_i32x4
        insFormat.IF_OPCODE, // INS_f32x4_convert_u_i32x4
        insFormat.IF_OPCODE, // INS_i32x4_trunc_sat_s_f64x2_zero
        insFormat.IF_OPCODE, // INS_i32x4_trunc_sat_u_f64x2_zero
        insFormat.IF_OPCODE, // INS_f64x2_convert_low_s_i32x4
        insFormat.IF_OPCODE, // INS_f64x2_convert_low_u_i32x4
    ];

#endif
}
